import { get, patch, post, remove } from './training-api';
import type { PssrTrainingAssignment, PssrTrainingBlocker, PssrTrainingDashboard, PssrTrainingRegister, PssrTrainingReadiness, PssrTrainingReadinessDetail, PssrTrainingWaiver } from '../types/pssr-training.types';

const base = '/training-competency/pssr-training-readiness';

export const pssrTrainingService = {
  dashboard: (params?: Record<string, unknown>) => get<PssrTrainingDashboard>(base, params),
  dashboardSummary: (params?: Record<string, unknown>) => get<Record<string, number>>(`${base}/dashboard/summary`, params),
  register: (params?: Record<string, unknown>) => get<PssrTrainingRegister<PssrTrainingReadiness>>(`${base}/register`, params),
  context: (params?: Record<string, unknown>) => get<Record<string, unknown>>(`${base}/new/context`, params),
  create: (payload: Record<string, unknown>) => post<PssrTrainingReadinessDetail>(base, payload),
  detail: (readinessId: string) => get<PssrTrainingReadinessDetail>(`${base}/${readinessId}`),
  update: (readinessId: string, payload: Record<string, unknown>) => patch<PssrTrainingReadinessDetail>(`${base}/${readinessId}`, payload),
  archive: (readinessId: string, payload?: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/${readinessId}/archive`, payload),
  reactivate: (readinessId: string, payload?: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/${readinessId}/reactivate`, payload),
  activate: (readinessId: string, payload?: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/${readinessId}/activate`, payload),
  impactChecks: (params?: Record<string, unknown>) => get<PssrTrainingRegister>(`${base}/impact-checks`, params),
  runImpactCheck: (readinessId: string, payload?: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/${readinessId}/readiness-check/run`, payload),
  previewRequiredWorkers: (readinessId: string, params?: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/${readinessId}/preview-required-workers`, params),
  requiredWorkers: (readinessId: string, params?: Record<string, unknown>) => get<PssrTrainingRegister>(`${base}/${readinessId}/required-workers`, params),
  addRequiredWorker: (readinessId: string, payload: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/${readinessId}/required-workers`, payload),
  removeRequiredWorker: (readinessId: string, requiredWorkerId: string, payload?: Record<string, unknown>) => remove<Record<string, unknown>>(`${base}/${readinessId}/required-workers/${requiredWorkerId}`, payload),
  generateAssignments: (readinessId: string, payload?: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/${readinessId}/generate-assignments`, payload),
  assignments: (params?: Record<string, unknown>) => get<PssrTrainingRegister<PssrTrainingAssignment>>(`${base}/assignments`, params),
  readinessAssignments: (readinessId: string, params?: Record<string, unknown>) => get<PssrTrainingRegister<PssrTrainingAssignment>>(`${base}/${readinessId}/assignments`, params),
  assignmentDetail: (assignmentId: string) => get<Record<string, unknown>>(`${base}/assignments/${assignmentId}`),
  cancelAssignment: (assignmentId: string, payload?: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/assignments/${assignmentId}/cancel`, payload),
  recalculateAssignment: (assignmentId: string) => post<Record<string, unknown>>(`${base}/assignments/${assignmentId}/recalculate`),
  readiness: (readinessId: string) => get<Record<string, unknown>>(`${base}/${readinessId}/readiness-check`),
  runReadiness: (readinessId: string, payload?: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/${readinessId}/readiness/run`, payload),
  blockers: (params?: Record<string, unknown>) => get<PssrTrainingRegister<PssrTrainingBlocker>>(`${base}/blockers`, params),
  approvalBlockers: (params?: Record<string, unknown>) => get<PssrTrainingRegister<PssrTrainingBlocker>>(`${base}/approval-blockers`, params),
  handoverBlockers: (params?: Record<string, unknown>) => get<PssrTrainingRegister<PssrTrainingBlocker>>(`${base}/handover-blockers`, params),
  startupBlockers: (params?: Record<string, unknown>) => get<PssrTrainingRegister<PssrTrainingBlocker>>(`${base}/startup-blockers`, params),
  blockerDetail: (blockerId: string) => get<Record<string, unknown>>(`${base}/blockers/${blockerId}`),
  createBlockerAction: (blockerId: string, payload?: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/blockers/${blockerId}/create-action`, payload),
  resolveBlocker: (blockerId: string, payload?: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/blockers/${blockerId}/mark-resolved`, payload),
  verifyBlocker: (blockerId: string, payload?: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/blockers/${blockerId}/verify`, payload),
  reopenBlocker: (blockerId: string, payload?: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/blockers/${blockerId}/reopen`, payload),
  waivers: (params?: Record<string, unknown>) => get<PssrTrainingRegister<PssrTrainingWaiver>>(`${base}/waivers`, params),
  requestWaiver: (blockerId: string, payload: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/blockers/${blockerId}/waiver-request`, payload),
  decideWaiver: (waiverId: string, decision: 'approve' | 'reject' | 'revoke', payload?: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/waivers/${waiverId}/${decision}`, payload),
  pending: (params?: Record<string, unknown>) => get<PssrTrainingRegister<PssrTrainingAssignment>>(`${base}/pending`, params),
  overdue: (params?: Record<string, unknown>) => get<PssrTrainingRegister<PssrTrainingAssignment>>(`${base}/overdue`, params),
  ready: (params?: Record<string, unknown>) => get<PssrTrainingRegister<PssrTrainingReadiness>>(`${base}/ready`, params),
  history: (params?: Record<string, unknown>) => get<PssrTrainingRegister>(`${base}/history`, params),
  settings: (params?: Record<string, unknown>) => get<Record<string, unknown>>(`${base}/settings`, params),
  updateSettings: (payload: Record<string, unknown>) => patch<Record<string, unknown>>(`${base}/settings`, payload),
  importTemplate: () => get<Record<string, unknown>>(`${base}/import-template`),
  importRows: (payload: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/import`, payload),
  exportRows: (params?: Record<string, unknown>) => get<Record<string, unknown>>(`${base}/export`, params),
  workerReadiness: (workerId: string, params?: Record<string, unknown>) => get<PssrTrainingRegister<PssrTrainingAssignment>>(`/training-competency/workforce/${workerId}/pssr-training-readiness`, params),
  workerAssignments: (workerId: string, params?: Record<string, unknown>) => get<PssrTrainingRegister<PssrTrainingAssignment>>(`/training-competency/workforce/${workerId}/pssr-training-assignments`, params),
  workerHistory: (workerId: string, params?: Record<string, unknown>) => get<PssrTrainingRegister>(`/training-competency/workforce/${workerId}/pssr-training-history`, params),
  scoped: (scope: 'sites' | 'units' | 'areas', id: string, params?: Record<string, unknown>) => get<PssrTrainingRegister<PssrTrainingReadiness>>(`/training-competency/${scope}/${id}/pssr-training-readiness`, params),
  pssrReadinessRecords: (pssrId: string, params?: Record<string, unknown>) => get<PssrTrainingRegister<PssrTrainingReadiness>>(`/pssr/${pssrId}/training-requirements`, params),
  pssrReadiness: (pssrId: string) => get<Record<string, unknown>>(`/pssr/${pssrId}/training-readiness`),
  runPssrReadiness: (pssrId: string, payload?: Record<string, unknown>) => post<Record<string, unknown>>(`/pssr/${pssrId}/training-readiness/run`, payload),
  pssrBlockers: (pssrId: string, params?: Record<string, unknown>) => get<PssrTrainingRegister<PssrTrainingBlocker>>(`/pssr/${pssrId}/training-blockers`, params),
  pssrEvidence: (pssrId: string, params?: Record<string, unknown>) => get<PssrTrainingRegister<PssrTrainingAssignment>>(`/pssr/${pssrId}/training-evidence`, params),
  pssrImpactCheck: (pssrId: string, params?: Record<string, unknown>) => get<Record<string, unknown>>(`/pssr/${pssrId}/training-impact-check`, params),
  runPssrImpactCheck: (pssrId: string, payload?: Record<string, unknown>) => post<Record<string, unknown>>(`/pssr/${pssrId}/training-impact-check/run`, payload)
};

