import type { RequiredTrainingContext, RequiredTrainingDashboardResponse, RequiredTrainingDetailResponse, RequiredTrainingRegistryResponse, RequiredTrainingSummary } from '../types/required-training.types';
import { get, patch, post, remove } from './training-api';

const base = '/training-competency/required-training';

export const requiredTrainingService = {
  dashboard: (params: Record<string, unknown> = {}) => get<RequiredTrainingDashboardResponse>(`${base}/dashboard`, params),
  dashboardSummary: (params: Record<string, unknown> = {}) => get<RequiredTrainingSummary>(`${base}/dashboard/summary`, params),
  byCategory: (params: Record<string, unknown> = {}) => get<Array<{ label: string; count: number }>>(`${base}/dashboard/by-category`, params),
  byStatus: (params: Record<string, unknown> = {}) => get<Array<{ label: string; count: number }>>(`${base}/dashboard/by-status`, params),
  reviewOverduePreview: (params: Record<string, unknown> = {}) => get<Array<Record<string, any>>>(`${base}/dashboard/review-overdue-preview`, params),
  matrixUnlinkedPreview: (params: Record<string, unknown> = {}) => get<Array<Record<string, any>>>(`${base}/dashboard/matrix-unlinked-preview`, params),
  library: (params: Record<string, unknown> = {}) => get<RequiredTrainingRegistryResponse>(`${base}/library`, params),
  librarySummary: (params: Record<string, unknown> = {}) => get<RequiredTrainingSummary>(`${base}/library/summary`, params),
  create: (data: Record<string, unknown>) => post<RequiredTrainingDetailResponse>(`${base}/library`, data),
  detail: (trainingId: string) => get<RequiredTrainingDetailResponse>(`${base}/library/${trainingId}`),
  update: (trainingId: string, data: Record<string, unknown>) => patch<RequiredTrainingDetailResponse>(`${base}/library/${trainingId}`, data),
  archive: (trainingId: string, data: Record<string, unknown>) => post<RequiredTrainingDetailResponse>(`${base}/library/${trainingId}/archive`, data),
  reactivate: (trainingId: string, data: Record<string, unknown> = {}) => post<RequiredTrainingDetailResponse>(`${base}/library/${trainingId}/reactivate`, data),
  activate: (trainingId: string) => post<RequiredTrainingDetailResponse>(`${base}/library/${trainingId}/activate`),
  newVersion: (trainingId: string, data: Record<string, unknown>) => post<RequiredTrainingDetailResponse>(`${base}/library/${trainingId}/new-version`, data),
  content: (trainingId: string) => get<Array<Record<string, any>>>(`${base}/library/${trainingId}/content`),
  addContent: (trainingId: string, data: Record<string, unknown>) => post<Record<string, any>>(`${base}/library/${trainingId}/content`, data),
  updateContent: (trainingId: string, sectionId: string, data: Record<string, unknown>) => patch<Record<string, any>>(`${base}/library/${trainingId}/content/${sectionId}`, data),
  removeContent: (trainingId: string, sectionId: string, data: Record<string, unknown>) => remove<Record<string, any>>(`${base}/library/${trainingId}/content/${sectionId}`, data),
  deliveryRules: (trainingId: string) => get<Record<string, any> | null>(`${base}/library/${trainingId}/delivery-rules`),
  updateDeliveryRules: (trainingId: string, data: Record<string, unknown>) => patch<Record<string, any>>(`${base}/library/${trainingId}/delivery-rules`, data),
  evidenceRules: (trainingId: string) => get<Record<string, any> | null>(`${base}/library/${trainingId}/evidence-rules`),
  updateEvidenceRules: (trainingId: string, data: Record<string, unknown>) => patch<Record<string, any>>(`${base}/library/${trainingId}/evidence-rules`, data),
  applicability: (trainingId: string) => get<Array<Record<string, any>>>(`${base}/library/${trainingId}/applicability`),
  addApplicability: (trainingId: string, data: Record<string, unknown>) => post<Record<string, any>>(`${base}/library/${trainingId}/applicability`, data),
  updateApplicability: (trainingId: string, scopeId: string, data: Record<string, unknown>) => patch<Record<string, any>>(`${base}/library/${trainingId}/applicability/${scopeId}`, data),
  removeApplicability: (trainingId: string, scopeId: string, data: Record<string, unknown>) => remove<Record<string, any>>(`${base}/library/${trainingId}/applicability/${scopeId}`, data),
  links: (trainingId: string) => get<Array<Record<string, any>>>(`${base}/library/${trainingId}/links`),
  addLink: (trainingId: string, data: Record<string, unknown>) => post<Record<string, any>>(`${base}/library/${trainingId}/links`, data),
  removeLink: (trainingId: string, linkId: string, data: Record<string, unknown>) => remove<Record<string, any>>(`${base}/library/${trainingId}/links/${linkId}`, data),
  documents: (trainingId: string) => get<Array<Record<string, any>>>(`${base}/library/${trainingId}/documents`),
  linkDocument: (trainingId: string, data: Record<string, unknown>) => post<Record<string, any>>(`${base}/library/${trainingId}/documents/link`, data),
  removeDocument: (trainingId: string, linkId: string, data: Record<string, unknown>) => remove<Record<string, any>>(`${base}/library/${trainingId}/documents/${linkId}`, data),
  matrixLinks: (trainingId: string) => get<Array<Record<string, any>>>(`${base}/library/${trainingId}/matrix-links`),
  addMatrixLink: (trainingId: string, data: Record<string, unknown>) => post<Record<string, any>>(`${base}/library/${trainingId}/matrix-links`, data),
  previewMatrixImpact: (trainingId: string) => get<Record<string, any>>(`${base}/library/${trainingId}/preview-matrix-impact`),
  syncToMatrix: (trainingId: string) => post<Record<string, any>>(`${base}/library/${trainingId}/sync-to-matrix`),
  matrixUnlinked: (params: Record<string, unknown> = {}) => get<RequiredTrainingRegistryResponse>(`${base}/matrix-unlinked`, params),
  linkTempRef: (data: Record<string, unknown>) => post<Record<string, any>>(`${base}/link-temp-ref`, data),
  competencyLinks: (trainingId: string) => get<Array<Record<string, any>>>(`${base}/library/${trainingId}/competency-links`),
  addCompetencyLink: (trainingId: string, data: Record<string, unknown>) => post<Record<string, any>>(`${base}/library/${trainingId}/competency-links`, data),
  syncToCompetencyProfiles: (trainingId: string) => post<Record<string, any>>(`${base}/library/${trainingId}/sync-to-competency-profiles`),
  submitReview: (trainingId: string, data: Record<string, unknown>) => post<RequiredTrainingDetailResponse>(`${base}/library/${trainingId}/submit-review`, data),
  approve: (trainingId: string, data: Record<string, unknown>) => post<RequiredTrainingDetailResponse>(`${base}/library/${trainingId}/approve`, data),
  versionHistory: (trainingId: string) => get<Array<Record<string, any>>>(`${base}/library/${trainingId}/version-history`),
  history: (params: Record<string, unknown> = {}) => get<{ rows: Array<Record<string, any>>; total: number }>(`${base}/history`, params),
  itemHistory: (trainingId: string, params: Record<string, unknown> = {}) => get<{ rows: Array<Record<string, any>>; total: number }>(`${base}/library/${trainingId}/history`, params),
  export: (params: Record<string, unknown> = {}) => get<Record<string, any>>(`${base}/export`, params),
  importTemplate: () => get<Record<string, any>>(`${base}/import/template`),
  importJob: (data: Record<string, unknown>) => post<Record<string, any>>(`${base}/import`, data),
  settings: (params: Record<string, unknown> = {}) => get<Record<string, any>>(`${base}/settings`, params),
  updateSettings: (data: Record<string, unknown>) => patch<Record<string, any>>(`${base}/settings`, data),
  context: (params: Record<string, unknown> = {}) => get<RequiredTrainingContext>(`${base}/context`, params),
  lookups: () => get<Record<string, string[]>>(`${base}/lookups`),
  safetyCritical: (params: Record<string, unknown> = {}) => get<RequiredTrainingRegistryResponse>(`${base}/safety-critical`, params),
  ptwCritical: (params: Record<string, unknown> = {}) => get<RequiredTrainingRegistryResponse>(`${base}/ptw-critical`, params),
  psmCritical: (params: Record<string, unknown> = {}) => get<RequiredTrainingRegistryResponse>(`${base}/psm-critical`, params),
  reviewOverdue: (params: Record<string, unknown> = {}) => get<RequiredTrainingRegistryResponse>(`${base}/review-overdue`, params),
  pendingApproval: (params: Record<string, unknown> = {}) => get<RequiredTrainingRegistryResponse>(`${base}/pending-approval`, params)
};
