import type { TrainingCompletionRecord, TrainingRecordDetailResponse, TrainingRecordsContext, TrainingRecordsDashboardResponse, TrainingRecordsRegistry, TrainingSession, TrainingSessionDetailResponse } from '../types/training-records.types';
import { get, patch, post, remove } from './training-api';

const base = '/training-competency/training-records';

export const trainingRecordsService = {
  dashboard: (params: Record<string, unknown> = {}) => get<TrainingRecordsDashboardResponse>(`${base}/dashboard`, params),
  dashboardSummary: (params: Record<string, unknown> = {}) => get<Record<string, number>>(`${base}/dashboard/summary`, params),
  bySite: (params: Record<string, unknown> = {}) => get<Array<{ label: string; count: number }>>(`${base}/dashboard/by-site`, params),
  byUnit: (params: Record<string, unknown> = {}) => get<Array<{ label: string; count: number }>>(`${base}/dashboard/by-unit`, params),
  sessions: (params: Record<string, unknown> = {}) => get<TrainingRecordsRegistry<TrainingSession>>(`${base}/sessions`, params),
  sessionsSummary: (params: Record<string, unknown> = {}) => get<Record<string, number>>(`${base}/sessions/summary`, params),
  createSession: (data: Record<string, unknown>) => post<TrainingSessionDetailResponse>(`${base}/sessions`, data),
  sessionDetail: (sessionId: string) => get<TrainingSessionDetailResponse>(`${base}/sessions/${sessionId}`),
  updateSession: (sessionId: string, data: Record<string, unknown>) => patch<TrainingSessionDetailResponse>(`${base}/sessions/${sessionId}`, data),
  cancelSession: (sessionId: string, data: Record<string, unknown>) => post<TrainingSessionDetailResponse>(`${base}/sessions/${sessionId}/cancel`, data),
  archiveSession: (sessionId: string, data: Record<string, unknown>) => post<TrainingSessionDetailResponse>(`${base}/sessions/${sessionId}/archive`, data),
  completeSession: (sessionId: string, data: Record<string, unknown> = {}) => post<TrainingSessionDetailResponse>(`${base}/sessions/${sessionId}/complete`, data),
  roster: (sessionId: string) => get<Array<Record<string, any>>>(`${base}/sessions/${sessionId}/roster`),
  addRoster: (sessionId: string, data: Record<string, unknown>) => post<Record<string, any>>(`${base}/sessions/${sessionId}/roster`, data),
  rosterFromMatrixGaps: (sessionId: string, data: Record<string, unknown> = {}) => post<Record<string, any>>(`${base}/sessions/${sessionId}/roster/from-matrix-gaps`, data),
  rosterFromRequiredTraining: (sessionId: string, data: Record<string, unknown> = {}) => post<Record<string, any>>(`${base}/sessions/${sessionId}/roster/from-required-training`, data),
  rosterFromRole: (sessionId: string, data: Record<string, unknown>) => post<Record<string, any>>(`${base}/sessions/${sessionId}/roster/from-role`, data),
  removeRoster: (sessionId: string, rosterId: string, data: Record<string, unknown>) => remove<Record<string, any>>(`${base}/sessions/${sessionId}/roster/${rosterId}`, data),
  attendance: (sessionId: string) => get<Array<Record<string, any>>>(`${base}/sessions/${sessionId}/attendance`),
  sessionEvidence: (sessionId: string) => get<Array<Record<string, any>>>(`${base}/sessions/${sessionId}/evidence`),
  sessionLinks: (sessionId: string) => get<Array<Record<string, any>>>(`${base}/sessions/${sessionId}/links`),
  addSessionLink: (sessionId: string, data: Record<string, unknown>) => post<Record<string, any>>(`${base}/sessions/${sessionId}/links`, data),
  removeSessionLink: (sessionId: string, linkId: string, data: Record<string, unknown>) => remove<Record<string, any>>(`${base}/sessions/${sessionId}/links/${linkId}`, data),
  saveAttendance: (sessionId: string, data: Record<string, unknown>) => post<Record<string, any>>(`${base}/sessions/${sessionId}/attendance`, data),
  updateAttendance: (sessionId: string, attendanceId: string, data: Record<string, unknown>) => patch<Record<string, any>>(`${base}/sessions/${sessionId}/attendance/${attendanceId}`, data),
  markAllPresent: (sessionId: string) => post<Record<string, any>>(`${base}/sessions/${sessionId}/attendance/mark-all-present`, { confirmed: true }),
  submitAttendance: (sessionId: string) => post<Array<Record<string, any>>>(`${base}/sessions/${sessionId}/attendance/submit`),
  lockAttendance: (sessionId: string) => post<Array<Record<string, any>>>(`${base}/sessions/${sessionId}/attendance/lock`),
  correctAttendance: (sessionId: string, attendanceId: string, data: Record<string, unknown>) => post<Record<string, any>>(`${base}/sessions/${sessionId}/attendance/${attendanceId}/correct`, data),
  records: (params: Record<string, unknown> = {}) => get<TrainingRecordsRegistry<TrainingCompletionRecord>>(`${base}/records`, params),
  createRecord: (data: Record<string, unknown>) => post<TrainingRecordDetailResponse>(`${base}/records`, data),
  recordDetail: (recordId: string) => get<TrainingRecordDetailResponse>(`${base}/records/${recordId}`),
  updateRecord: (recordId: string, data: Record<string, unknown>) => patch<TrainingRecordDetailResponse>(`${base}/records/${recordId}`, data),
  verifyRecord: (recordId: string, data: Record<string, unknown> = {}) => post<TrainingRecordDetailResponse>(`${base}/records/${recordId}/verify`, data),
  rejectRecord: (recordId: string, data: Record<string, unknown>) => post<TrainingRecordDetailResponse>(`${base}/records/${recordId}/reject`, data),
  approveRecord: (recordId: string, data: Record<string, unknown> = {}) => post<TrainingRecordDetailResponse>(`${base}/records/${recordId}/approve`, data),
  reopenRecord: (recordId: string, data: Record<string, unknown>) => post<TrainingRecordDetailResponse>(`${base}/records/${recordId}/reopen`, data),
  recalculateRecord: (recordId: string) => post<TrainingRecordDetailResponse>(`${base}/records/${recordId}/recalculate-status`),
  evidence: (recordId: string) => get<Array<Record<string, any>>>(`${base}/records/${recordId}/evidence`),
  linkEvidence: (recordId: string, data: Record<string, unknown>) => post<Record<string, any>>(`${base}/records/${recordId}/evidence/link`, data),
  removeEvidence: (recordId: string, evidenceId: string, data: Record<string, unknown>) => remove<Record<string, any>>(`${base}/records/${recordId}/evidence/${evidenceId}`, data),
  verifyEvidence: (recordId: string, evidenceId: string) => post<Record<string, any>>(`${base}/records/${recordId}/evidence/${evidenceId}/verify`),
  rejectEvidence: (recordId: string, evidenceId: string, data: Record<string, unknown>) => post<Record<string, any>>(`${base}/records/${recordId}/evidence/${evidenceId}/reject`, data),
  attendanceView: (params: Record<string, unknown> = {}) => get<TrainingRecordsRegistry<TrainingCompletionRecord>>(`${base}/attendance`, params),
  completions: (params: Record<string, unknown> = {}) => get<TrainingRecordsRegistry<TrainingCompletionRecord>>(`${base}/completions`, params),
  pendingVerification: (params: Record<string, unknown> = {}) => get<TrainingRecordsRegistry<TrainingCompletionRecord>>(`${base}/pending-verification`, params),
  pendingApproval: (params: Record<string, unknown> = {}) => get<TrainingRecordsRegistry<TrainingCompletionRecord>>(`${base}/pending-approval`, params),
  failedIncomplete: (params: Record<string, unknown> = {}) => get<TrainingRecordsRegistry<TrainingCompletionRecord>>(`${base}/failed-incomplete`, params),
  missingAttendance: (params: Record<string, unknown> = {}) => get<TrainingRecordsRegistry<TrainingSession>>(`${base}/missing-attendance`, params),
  manualCorrections: (params: Record<string, unknown> = {}) => get<Array<Record<string, any>>>(`${base}/manual-corrections`, params),
  importTemplate: () => get<Record<string, any>>(`${base}/import-template`),
  importJob: (data: Record<string, unknown>) => post<Record<string, any>>(`${base}/import`, data),
  export: (params: Record<string, unknown> = {}) => get<Record<string, any>>(`${base}/export`, params),
  history: (params: Record<string, unknown> = {}) => get<{ rows: Array<Record<string, any>>; total: number }>(`${base}/history`, params),
  settings: (params: Record<string, unknown> = {}) => get<Record<string, any>>(`${base}/settings`, params),
  updateSettings: (data: Record<string, unknown>) => patch<Record<string, any>>(`${base}/settings`, data),
  context: (params: Record<string, unknown> = {}) => get<TrainingRecordsContext>(`${base}/context`, params)
};
