import type { TrainingReportList, TrainingReportLookups, TrainingReportMutationPayload, TrainingReportRow, TrainingReportsDashboard } from '../types/training-reports.types';
import { get, patch, post, remove } from './training-api';

const base = '/training-competency/reports';

export const trainingReportsService = {
  dashboard: (params: Record<string, unknown> = {}) => get<TrainingReportsDashboard>(base, params),
  dashboardSummary: (params: Record<string, unknown> = {}) => get<Record<string, any>>(`${base}/dashboard/summary`, params),
  templates: (params: Record<string, unknown> = {}) => get<TrainingReportList>(`${base}/templates`, params),
  template: (templateId: string) => get<Record<string, any>>(`${base}/templates/${templateId}`),
  createTemplate: (data: TrainingReportMutationPayload) => post<TrainingReportRow>(`${base}/templates`, data),
  updateTemplate: (templateId: string, data: TrainingReportMutationPayload) => patch<TrainingReportRow>(`${base}/templates/${templateId}`, data),
  archiveTemplate: (templateId: string, reason?: string) => post<TrainingReportRow>(`${base}/templates/${templateId}/archive`, { reason }),
  reactivateTemplate: (templateId: string) => post<TrainingReportRow>(`${base}/templates/${templateId}/reactivate`),
  activateTemplate: (templateId: string) => post<TrainingReportRow>(`${base}/templates/${templateId}/activate`),
  newTemplateVersion: (templateId: string, data: TrainingReportMutationPayload = {}) => post<TrainingReportRow>(`${base}/templates/${templateId}/new-version`, data),
  preview: (data: TrainingReportMutationPayload) => post<Record<string, any>>(`${base}/preview`, data),
  generate: (data: TrainingReportMutationPayload) => post<Record<string, any>>(`${base}/generate`, data),
  exportReport: (data: TrainingReportMutationPayload) => post<Record<string, any>>(`${base}/export`, data),
  generated: (params: Record<string, unknown> = {}) => get<TrainingReportList>(`${base}/generated`, params),
  generatedDetail: (reportId: string) => get<Record<string, any>>(`${base}/generated/${reportId}`),
  files: (reportId: string) => get<TrainingReportRow[]>(`${base}/generated/${reportId}/files`),
  archiveGenerated: (reportId: string, reason?: string) => post<TrainingReportRow>(`${base}/generated/${reportId}/archive`, { reason }),
  deleteGenerated: (reportId: string, reason?: string) => remove<TrainingReportRow>(`${base}/generated/${reportId}`, { reason }),
  exportJobs: (params: Record<string, unknown> = {}) => get<TrainingReportList>(`${base}/export/jobs`, params),
  exportJob: (jobId: string) => get<Record<string, any>>(`${base}/export/jobs/${jobId}`),
  retryJob: (jobId: string) => post<Record<string, any>>(`${base}/export/jobs/${jobId}/retry`),
  cancelJob: (jobId: string, reason?: string) => post<Record<string, any>>(`${base}/export/jobs/${jobId}/cancel`, { reason }),
  deleteJob: (jobId: string, reason?: string) => remove<Record<string, any>>(`${base}/export/jobs/${jobId}`, { reason }),
  downloadFile: (fileId: string) => get<Record<string, any>>(`${base}/files/${fileId}/download`),
  packages: (params: Record<string, unknown> = {}) => get<TrainingReportList>(`${base}/packages`, params),
  createPackage: (data: TrainingReportMutationPayload) => post<Record<string, any>>(`${base}/packages`, data),
  packageDetail: (packageId: string) => get<Record<string, any>>(`${base}/packages/${packageId}`),
  regeneratePackage: (packageId: string) => post<Record<string, any>>(`${base}/packages/${packageId}/regenerate`),
  downloadPackage: (packageId: string) => get<Record<string, any>>(`${base}/packages/${packageId}/download`),
  scheduled: (params: Record<string, unknown> = {}) => get<TrainingReportList>(`${base}/scheduled`, params),
  createScheduled: (data: TrainingReportMutationPayload) => post<Record<string, any>>(`${base}/scheduled`, data),
  scheduledDetail: (scheduledReportId: string) => get<Record<string, any>>(`${base}/scheduled/${scheduledReportId}`),
  updateScheduled: (scheduledReportId: string, data: TrainingReportMutationPayload) => patch<Record<string, any>>(`${base}/scheduled/${scheduledReportId}`, data),
  runScheduledNow: (scheduledReportId: string) => post<Record<string, any>>(`${base}/scheduled/${scheduledReportId}/run-now`),
  pauseScheduled: (scheduledReportId: string) => post<Record<string, any>>(`${base}/scheduled/${scheduledReportId}/pause`),
  resumeScheduled: (scheduledReportId: string) => post<Record<string, any>>(`${base}/scheduled/${scheduledReportId}/resume`),
  archiveScheduled: (scheduledReportId: string) => post<Record<string, any>>(`${base}/scheduled/${scheduledReportId}/archive`),
  downloads: (params: Record<string, unknown> = {}) => get<TrainingReportList>(`${base}/downloads`, params),
  auditEvidence: (params: Record<string, unknown> = {}) => get<TrainingReportList>(`${base}/audit-evidence`, params),
  history: (params: Record<string, unknown> = {}) => get<TrainingReportList>(`${base}/history`, params),
  settings: (params: Record<string, unknown> = {}) => get<Record<string, any>>(`${base}/settings`, params),
  updateSettings: (data: TrainingReportMutationPayload) => patch<Record<string, any>>(`${base}/settings`, data),
  lookups: () => get<TrainingReportLookups>(`${base}/lookups`),
  reportView: (reportType: string, params: Record<string, unknown> = {}) => get<Record<string, any>>(`${base}/${encodeURIComponent(reportType)}`, params),
  scopedReports: (scope: 'sites' | 'units' | 'areas', id: string) => get<TrainingReportList>(`/training-competency/${scope}/${id}/training-reports`),
  workerReports: (workerId: string) => get<TrainingReportList>(`/training-competency/workforce/${workerId}/reports`),
  workerEvidencePackage: (workerId: string) => post<Record<string, any>>(`/training-competency/workforce/${workerId}/evidence-package`),
  mocEvidencePackage: (mocId: string) => post<Record<string, any>>(`/moc/${mocId}/training-evidence-package`),
  pssrEvidencePackage: (pssrId: string) => post<Record<string, any>>(`/pssr/${pssrId}/training-evidence-package`),
  ptwEvidencePackage: (permitId: string) => post<Record<string, any>>(`/ptw/permits/${permitId}/training-authorization-evidence`)
};
