import { PssrTrainingBlockerBadge } from '../../shared/PSSRTrainingBlockerBadge';
import { RowsPanel, SimpleTable, valueText } from '../PssrTrainingPanelPrimitives';

export function PssrTrainingBlockersTab({ rows = [] }: { rows?: any[] | undefined }) {
  return <RowsPanel title="PSSR Training Blockers" subtitle="Approval, handover and PSSR startup blockers generated by backend readiness." rows={rows} emptyTitle="No blockers" emptyMessage="No blocker rows were returned for this readiness.">{(items) => <SimpleTable rows={items} columns={[{ key: 'blocker_title', label: 'Blocker', render: (row) => <div><p className="font-semibold">{valueText(row.blocker_title)}</p><p className="text-xs text-[var(--psm-muted)]">{valueText(row.blocker_description)}</p></div> }, { key: 'blocker_type', label: 'Type' }, { key: 'blocker_status', label: 'Status', render: (row) => <PssrTrainingBlockerBadge status={row.blocker_status} /> }, { key: 'severity', label: 'Severity' }, { key: 'approval_blocker', label: 'Approval', render: (row) => valueText(row.approval_blocker) }, { key: 'handover_blocker', label: 'Handover', render: (row) => valueText(row.handover_blocker) }, { key: 'startup_blocker', label: 'Startup', render: (row) => valueText(row.startup_blocker) }]} />}</RowsPanel>;
}

