export type AuditProgram = {
  id: string;
  company_id: string;
  site_id?: string | null;
  program_code: string;
  program_title: string;
  description?: string | null;
  audit_type: string;
  program_category: string;
  criticality: string;
  program_status: string;
  configuration_health: string;
  effective_date?: string | null;
  program_objective?: string | null;
  notes?: string | null;
  owner_user_id?: string | null;
  reviewer_user_id?: string | null;
  approval_owner_user_id?: string | null;
  audit_lead_role?: string | null;
  responsible_department_id?: string | null;
  escalation_owner_user_id?: string | null;
  next_review_due?: string | null;
  ready_for_scheduling: boolean;
  archived_at?: string | null;
  archive_reason?: string | null;
  created_at?: string;
  updated_at?: string;
  scopes?: AuditProgramScope[];
  standards?: AuditProgramStandard[];
  modules?: AuditProgramModule[];
  frequency?: AuditProgramFrequency | null;
  owner?: AuditUser | null;
  reviewer?: AuditUser | null;
};

export type AuditUser = { id: string; displayName?: string | null; email?: string | null; title?: string | null; department?: string | null; status?: string | null };
export type AuditSite = { id: string; name: string; code?: string | null };
export type AuditUnit = { id: string; name: string; code?: string | null; siteId?: string | null };
export type AuditArea = { id: string; name: string; code?: string | null; siteId?: string | null; unitId?: string | null };
export type AuditDepartment = { id: string; name: string; code?: string | null; siteId?: string | null };
export type AuditProgramScope = { id?: string; scope_type?: string; site_scope_id?: string | null; unit_id?: string | null; area_id?: string | null; department_id?: string | null; process_system?: string | null; scope_description?: string | null; exclusions?: string | null; scope_justification?: string | null };
export type AuditProgramStandard = { id?: string; standard_name?: string; jurisdiction?: string | null; clause_reference?: string | null; requirement_category?: string | null; applicability?: string | null; mandatory?: boolean; evidence_expectation?: string | null; notes?: string | null };
export type AuditProgramModule = { id?: string; module_key?: string; module_name?: string; coverage_level?: string; coverage_reason?: string | null; evidence_source?: string | null; required?: boolean; integration_enabled?: boolean; notes?: string | null };
export type AuditProgramFrequency = { id?: string; audit_frequency?: string; frequency_interval?: string | null; planned_start_month?: string | null; next_planned_audit_date?: string | null; review_frequency?: string | null; next_program_review_due?: string | null; audit_duration_estimate_days?: number | null; grace_period_days?: number | null; notes?: string | null };
export type AuditIntegrationSettings = Record<string, unknown>;
export type AuditHistoryEvent = { id: string; event_type: string; event_title: string; event_description?: string | null; created_at: string; actor_user_id?: string | null; program_id?: string | null };
export type AuditDashboard = Record<string, any>;
export type AuditRegister = { rows: AuditProgram[]; page: number; limit: number; total: number; summary: Record<string, number>; savedViews?: string[]; lastUpdated?: string };
export type AuditDetail = { program: AuditProgram; header: Record<string, any>; overview: Array<{ label: string; value: unknown }>; scopes: AuditProgramScope[]; standards: AuditProgramStandard[]; modules: AuditProgramModule[]; frequency: AuditProgramFrequency | null; integrationSettings: AuditIntegrationSettings | null; history: AuditHistoryEvent[]; tabs: string[] };
export type AuditLookups = { auditTypes: string[]; programCategories: string[]; programStatuses: string[]; configurationHealthStatuses: string[]; criticalityLevels: string[]; scopeTypes: string[]; auditFrequencies: string[]; coverageLevels: string[]; auditableModules: Array<{ key: string; name: string }>; standardOptions: string[] };
export type AuditContext = { sites: AuditSite[]; units: AuditUnit[]; areas: AuditArea[]; departments: AuditDepartment[]; users: AuditUser[]; settings: Record<string, any> };
