import type { AuditProgram, AuditUser } from './audit.types';

export type AuditPlan = { id: string; company_id: string; site_id?: string | null; program_id?: string | null; plan_code: string; plan_title: string; description?: string | null; audit_type: string; plan_category: string; criticality: string; plan_status: string; schedule_status: string; readiness_health: string; conflict_status: string; standalone_audit: boolean; standalone_reason?: string | null; audit_objective?: string | null; audit_criteria?: string | null; planned_start_at?: string | null; planned_end_at?: string | null; timezone: string; audit_location?: string | null; audit_mode?: string | null; lead_auditor_user_id?: string | null; owner_user_id?: string | null; reviewer_user_id?: string | null; ready_for_checklist: boolean; program?: Pick<AuditProgram, 'id' | 'program_code' | 'program_title' | 'program_status'> | null; leadAuditor?: AuditUser | null; scopes?: AuditPlanScope[]; standards?: AuditPlanStandard[]; modules?: AuditPlanModule[]; team?: AuditPlanTeamMember[]; durationDays?: number | null; daysUntilAudit?: number | null; updated_at?: string };
export type AuditPlanScope = { id?: string; scope_type: string; site_scope_id?: string | null; unit_id?: string | null; area_id?: string | null; department_id?: string | null; equipment_id?: string | null; process_system?: string | null; contractor_company_id?: string | null; worker_role_scope?: string | null; scope_description?: string | null; exclusions?: string | null; scope_justification?: string | null; source_from_program?: boolean };
export type AuditPlanStandard = { id?: string; standard_name: string; jurisdiction?: string | null; clause_reference?: string | null; requirement_category?: string | null; applicability?: string | null; mandatory?: boolean; evidence_expectation?: string | null; source_from_program?: boolean; notes?: string | null };
export type AuditPlanModule = { id?: string; module_key: string; module_name: string; coverage_level: string; coverage_reason?: string | null; evidence_source?: string | null; required?: boolean; source_from_program?: boolean; notes?: string | null };
export type AuditPlanTeamMember = { id?: string; user_id: string; team_role: string; responsibility?: string | null; required?: boolean; qualification_status?: string | null; availability_status?: string | null; notes?: string | null; user?: AuditUser | null };
export type AuditPlanCheck = { id: string; check_key: string; check_label: string; check_status: string; blocking: boolean; reason?: string | null };
export type AuditPlanConflict = { id: string; conflict_type: string; conflict_status: string; severity: string; title: string; description?: string | null; related_record_id?: string | null; resolution_reason?: string | null };
export type AuditPlanRegister = { rows: AuditPlan[]; total: number; page: number; limit: number; summary: Record<string, number> };
export type AuditPlanDetail = { plan: AuditPlan; scheduleEvents: Record<string, unknown>[]; readinessChecks: AuditPlanCheck[]; conflicts: AuditPlanConflict[]; reviews: Record<string, unknown>[]; history: Record<string, any>[] };
export type AuditPlanDashboard = { summary: Record<string, number>; upcoming: AuditPlan[]; overdue: AuditPlan[]; conflicts: AuditPlan[]; readinessGaps: AuditPlan[]; byStatus: Array<{ label: string; value: number }>; bySite: Array<{ label: string; value: number }>; byAuditType: Array<{ label: string; value: number }>; byCriticality: Array<{ label: string; value: number }>; auditorWorkload: Array<{ label: string; value: number }>; recent: AuditPlan[] };
export type AuditPlanLookups = { planStatuses: string[]; scheduleStatuses: string[]; readinessStatuses: string[]; conflictStatuses: string[]; auditModes: string[]; planCategories: string[]; teamRoles: string[] };
