"use client";

import type { ReactNode } from "react";

export function HazopNodeCoreIdentityTab({ form, errors, onChange }: any) {
  return (
    <div className="grid gap-4 lg:grid-cols-2">
      <Field label="Node Number" required error={errors.nodeNumber}>
        <input className="input" value={form.nodeNumber ?? ""} onChange={(event) => onChange("nodeNumber", event.target.value)} placeholder="Auto-generated by unit/area" />
      </Field>
      <Field label="Node Title" required error={errors.title}>
        <input className="input" value={form.title ?? ""} onChange={(event) => onChange("title", event.target.value)} placeholder="Crude Pump P-101 A/B Discharge to Preheater E-102" />
      </Field>
      <Field label="Node Description">
        <textarea className="input min-h-[110px]" value={form.description ?? ""} onChange={(event) => onChange("description", event.target.value)} />
      </Field>
      <Field label="Design Intent" required error={errors.designIntent}>
        <textarea className="input min-h-[110px]" value={form.designIntent ?? ""} onChange={(event) => onChange("designIntent", event.target.value)} />
      </Field>
      <Field label="Boundary / Battery Limits" required error={errors.boundaryLimits}>
        <textarea className="input min-h-[90px]" value={form.boundaryLimits ?? ""} onChange={(event) => onChange("boundaryLimits", event.target.value)} placeholder="Starts at valve V-1001 and ends at inlet flange of vessel V-2002" />
      </Field>
      <Field label="Assumptions">
        <textarea className="input min-h-[90px]" value={form.assumptions ?? ""} onChange={(event) => onChange("assumptions", event.target.value)} placeholder="- Normal operation at design rate" />
      </Field>
      <Field label="Exclusions">
        <textarea className="input min-h-[90px]" value={form.exclusions ?? ""} onChange={(event) => onChange("exclusions", event.target.value)} placeholder="- Downstream package outside node battery limit" />
      </Field>
    </div>
  );
}

function Field({ label, required, error, children }: { label: string; required?: boolean; error?: string; children: ReactNode }) {
  return (
    <label className="block">
      <span className="mb-1 block text-xs font-semibold uppercase text-slate-400">{label}{required ? <span className="text-red-300"> *</span> : null}</span>
      {children}
      {error ? <span className="mt-1 block text-xs text-red-300">{error}</span> : null}
    </label>
  );
}
