export type ElectricalClassification = {
  id: string;
  company_id: string;
  site_id: string;
  unit_id: string;
  area_id?: string | null;
  classification_title: string;
  classification_record_number?: string | null;
  building_location?: string | null;
  system_service?: string | null;
  classification_system: string;
  applicable_standard?: string | null;
  classification_status: string;
  critical_area: boolean;
  psm_critical: boolean;
  hot_work_restricted: boolean;
  completeness_status: string;
  completeness_score?: number | null;
  conflict_status: string;
  review_status: string;
  rating_compliance_status?: string | null;
  moc_update_required: boolean;
  pssr_blocker: boolean;
  owner_user_id?: string | null;
  electrical_engineer_id?: string | null;
  instrument_engineer_id?: string | null;
  process_engineer_id?: string | null;
  operations_owner_id?: string | null;
  hse_reviewer_id?: string | null;
  last_review_date?: string | null;
  next_review_due?: string | null;
  notes?: string | null;
  hazardous_material_name?: string | null;
  release_source_type?: string | null;
  zone_classification?: string | null;
  nec_class_division?: string | null;
  gas_group?: string | null;
  dust_group?: string | null;
  temperature_class?: string | null;
  required_protection_method?: string | null;
  drawing_status?: string | null;
  hazardSource?: ElectricalHazardSource | null;
  areaDetails?: ElectricalAreaDetails | null;
  ventilationBasis?: ElectricalVentilationBasis | null;
  protectionRequirements?: ElectricalProtectionRequirements | null;
  installedEquipment?: InstalledEquipmentRating[];
  documents?: ElectricalDocumentLink[];
  ptwControls?: ElectricalPtwControls | null;
};

export type ElectricalSummary = {
  totalClassifiedAreas: number;
  zoneAreas: number;
  classDivisionAreas: number;
  dustClassifiedAreas: number;
  unclassifiedAreasWithReview: number;
  missingClassificationStudies: number;
  missingAreaDrawings: number;
  equipmentRatingMismatches: number;
  instrumentsMissingExRating: number;
  hotWorkRestrictedAreas: number;
  ventilationBasisMissing: number;
  releaseSourceMissing: number;
  reviewOverdue: number;
  pendingApproval: number;
  mocRequired: number;
  pssrBlockers: number;
  auditGaps: number;
  lastUpdated: string;
};

export type ElectricalRegistry = { rows: ElectricalClassification[]; page: number; limit: number; total: number; summary: ElectricalSummary; savedViews: string[]; lastUpdated: string };

export type ElectricalHazardSource = Record<string, any> & { hazardous_material_name?: string | null; material_type?: string | null; source_of_release?: string | null; release_source_type?: string | null; release_grade?: string | null };
export type ElectricalAreaDetails = Record<string, any> & { zone_classification?: string | null; nec_class_division?: string | null; gas_group?: string | null; dust_group?: string | null; temperature_class?: string | null };
export type ElectricalVentilationBasis = Record<string, any> & { ventilation_type?: string | null; ventilation_availability?: string | null; ventilation_effectiveness?: string | null };
export type ElectricalProtectionRequirements = Record<string, any> & { required_protection_method?: string | null; required_ex_marking?: string | null; required_epl?: string | null };
export type ElectricalPtwControls = Record<string, any> & { hot_work_restricted?: boolean; hot_work_permit_required?: boolean; gas_test_required?: boolean; non_ex_equipment_prohibited?: boolean };
export type ElectricalDocumentLink = Record<string, any> & { id: string; document_id: string; document_type: string; document_status?: string | null; revision_number?: string | null; required: boolean };
export type InstalledEquipmentRating = Record<string, any> & { id: string; tag_number: string; item_type: string; installed_ex_marking?: string | null; installed_gas_dust_group?: string | null; installed_temperature_class?: string | null; suitability_result: string; mismatch_reason?: string | null; action_required: boolean };
export type ElectricalCheck = Record<string, any> & { id: string; check_key: string; check_title: string; status: string; severity: string; message?: string | null; pssr_blocker: boolean; action_required: boolean };
export type ElectricalConflict = Record<string, any> & { id: string; conflict_type: string; conflict_status: string; severity: string; message: string; override_required: boolean; override_approved: boolean };
export type ElectricalHistoryEvent = Record<string, any> & { id: string; event_type: string; event_title: string; event_description?: string | null; actor_user_id?: string | null; created_at: string };

export type ElectricalDetail = {
  classification: ElectricalClassification;
  unit?: Record<string, unknown> | null;
  hazardSource?: ElectricalHazardSource | null;
  areaDetails?: ElectricalAreaDetails | null;
  ventilationBasis?: ElectricalVentilationBasis | null;
  protectionRequirements?: ElectricalProtectionRequirements | null;
  installedEquipment: InstalledEquipmentRating[];
  documents: ElectricalDocumentLink[];
  ptwControls?: ElectricalPtwControls | null;
  completeness: ElectricalCheck[];
  conflicts: ElectricalConflict[];
  history: ElectricalHistoryEvent[];
  overview: { cards: Array<{ label: string; value: unknown; tone?: 'neutral' | 'good' | 'warn' | 'danger' }>; blockers: Array<Record<string, unknown>> };
  tabs: Array<{ label: string; href: string; enabled: boolean }>;
  actions: Array<{ key: string; label: string; enabled: boolean; disabledReason?: string | null }>;
};

export type ElectricalLookups = {
  classificationSystems: string[];
  hazardousAreaStandards: string[];
  zones: string[];
  classDivisions: string[];
  gasGroups: string[];
  dustGroups: string[];
  temperatureClasses: string[];
  protectionMethods: string[];
  releaseSourceTypes: string[];
  releaseGrades: string[];
  ventilationTypes: string[];
  electricalDocumentTypes: string[];
  electricalConflictStatuses: string[];
  suitabilityResults: string[];
  materialTypes: string[];
};
