export type PsiUnit = {
  id: string;
  company_id: string;
  site_id: string;
  department_id?: string | null;
  area_id?: string | null;
  unit_name: string;
  unit_code: string;
  unit_type: string;
  description?: string | null;
  operating_status: string;
  commissioning_date?: string | null;
  building_location?: string | null;
  battery_limits?: string | null;
  upstream_units_json?: string[] | null;
  downstream_units_json?: string[] | null;
  utilities_connected_json?: string[] | null;
  interfaces_json?: string[] | null;
  process_purpose?: string | null;
  normal_operation_summary?: string | null;
  process_flow_summary?: string | null;
  main_feed_streams_json?: string[] | null;
  main_product_streams_json?: string[] | null;
  waste_streams_json?: string[] | null;
  utilities_used_json?: string[] | null;
  operating_mode?: string | null;
  startup_shutdown_notes?: string | null;
  major_process_hazards?: string | null;
  major_chemical_hazards?: string | null;
  fire_explosion_hazards?: string | null;
  toxicity_hazards?: string | null;
  reactivity_hazards?: string | null;
  pressure_temperature_hazards?: string | null;
  environmental_hazards?: string | null;
  critical_safeguards_summary?: string | null;
  emergency_response_notes?: string | null;
  psi_owner_id?: string | null;
  process_engineer_id?: string | null;
  operations_owner_id?: string | null;
  hse_owner_id?: string | null;
  document_controller_id?: string | null;
  mechanical_mi_contact_id?: string | null;
  electrical_instrument_contact_id?: string | null;
  relief_specialist_id?: string | null;
  review_frequency_value?: number | null;
  review_frequency_unit?: string | null;
  last_review_date?: string | null;
  next_review_due?: string | null;
  review_status: string;
  psi_status: string;
  completeness_score?: number | null;
  completeness_status: string;
  critical_gap_count: number;
  moc_update_required: boolean;
  pssr_blocker: boolean;
  archived_at?: string | null;
  site?: { id: string; name: string; code?: string | null } | null;
  area?: { id: string; name: string; code?: string | null } | null;
  owner?: { id: string; displayName?: string; email?: string; title?: string; department?: string } | null;
  processEngineer?: { id: string; displayName?: string; email?: string; title?: string; department?: string } | null;
  operationsOwner?: { id: string; displayName?: string; email?: string; title?: string; department?: string } | null;
  hseOwner?: { id: string; displayName?: string; email?: string; title?: string; department?: string } | null;
  documentController?: { id: string; displayName?: string; email?: string; title?: string; department?: string } | null;
  mechanicalMiContact?: { id: string; displayName?: string; email?: string; title?: string; department?: string } | null;
  electricalInstrumentContact?: { id: string; displayName?: string; email?: string; title?: string; department?: string } | null;
  reliefSpecialist?: { id: string; displayName?: string; email?: string; title?: string; department?: string } | null;
};

export type PsiUnitRegistryResponse = {
  rows: PsiUnit[];
  page: number;
  limit: number;
  total: number;
  lastUpdated: string;
  savedViews: string[];
  summary: Record<string, number>;
};

export type PsiUnitDetailResponse = {
  unit: PsiUnit;
  overview: {
    cards: Record<string, string | number | boolean | null>;
    blockers: Array<Record<string, unknown>>;
    readOnly: boolean;
  };
  equipment: Array<Record<string, any>>;
  completeness: import('./psi-completeness.types').PsiCompletenessResponse;
  linkedRecords: Array<Record<string, any>>;
  documents: Array<Record<string, any>>;
  reviews: Array<Record<string, any>>;
  history: Array<Record<string, any>>;
  tabs: Array<{ label: string; href: string; enabled: boolean }>;
};
