export type ReliefSystem = {
  id: string;
  unit_id: string;
  site_id: string;
  area_id?: string | null;
  protected_equipment_id: string;
  protected_equipment_tag: string;
  protected_equipment_name: string;
  equipment_type?: string | null;
  equipment_criticality: string;
  safety_critical: boolean;
  psm_critical: boolean;
  relief_basis_number?: string | null;
  relief_basis_title: string;
  relief_system_type: string;
  protection_type?: string | null;
  service_fluid?: string | null;
  fluid_phase?: string | null;
  governing_scenario_type?: string | null;
  governing_scenario_description?: string | null;
  required_relief_rate?: number | null;
  required_relief_rate_unit?: string | null;
  rated_capacity?: number | null;
  rated_capacity_unit?: string | null;
  capacity_margin_percent?: number | null;
  set_pressure?: number | null;
  set_pressure_unit?: string | null;
  mawp?: number | null;
  mawp_unit?: string | null;
  relieving_pressure?: number | null;
  relief_destination?: string | null;
  destination_detail?: string | null;
  relief_device_tag?: string | null;
  mi_relief_device_id?: string | null;
  relief_device_status?: string | null;
  calculation_status: string;
  completeness_status: string;
  completeness_score?: number | null;
  conflict_status: string;
  review_status: string;
  status: string;
  moc_update_required: boolean;
  pssr_blocker: boolean;
  mi_readiness_impact: boolean;
  next_review_due?: string | null;
  updated_at?: string | null;
  missingCalculation?: boolean;
  missingDestination?: boolean;
  missingGoverningCase?: boolean;
};

export type ReliefSystemSummary = {
  totalReliefBasisRecords: number;
  protectedEquipmentCount: number;
  equipmentMissingReliefBasis: number;
  safetyCriticalEquipmentMissingReliefBasis: number;
  reliefDevicesLinked: number;
  reliefDevicesNotLinked: number;
  governingCasesDefined: number;
  missingGoverningCase: number;
  missingReliefCalculation: number;
  missingReliefDestination: number;
  missingPidOrDatasheet: number;
  reliefBasisConflicts: number;
  solConflicts: number;
  equipmentDesignBasisConflicts: number;
  miReliefDeviceConflicts: number;
  reviewOverdue: number;
  pendingApproval: number;
  mocRequired: number;
  pssrBlockers: number;
  miReadinessImpact: number;
  lastUpdated: string;
};

export type ReliefSystemRegistry = {
  rows: ReliefSystem[];
  page: number;
  limit: number;
  total: number;
  summary: ReliefSystemSummary;
  savedViews: string[];
  lastUpdated: string;
};

export type ReliefSystemDetail = {
  reliefBasis: ReliefSystem;
  unit?: Record<string, unknown>;
  protectedEquipment: Array<Record<string, unknown>>;
  deviceLinks: Array<Record<string, unknown>>;
  scenarios: Array<Record<string, unknown>>;
  sizingBasis?: Record<string, unknown> | null;
  dischargeDestination?: Record<string, unknown> | null;
  documents: Array<Record<string, unknown>>;
  conflicts: Array<Record<string, unknown>>;
  completeness: Array<Record<string, unknown>>;
  syncEvents: Array<Record<string, unknown>>;
  history: Array<Record<string, unknown>>;
  overview: { cards: Array<{ label: string; value: unknown; tone?: 'neutral' | 'good' | 'warn' | 'danger' }> };
  tabs: Array<{ label: string; href: string; enabled: boolean }>;
  actions: Array<{ key: string; label: string; enabled: boolean; disabledReason?: string | null }>;
};

export type ReliefSystemLookups = {
  reliefSystemTypes: string[];
  reliefDeviceTypes: string[];
  reliefScenarioTypes: string[];
  reliefDestinationTypes: string[];
  calculationStatuses: string[];
  conflictStatuses: string[];
  documentTypes: string[];
};
