'use client';

import { useState } from 'react';
import type { HazopSession } from '../../types/hazop-session.types';

export function HazopSessionDecisionPanel({ session, context, readonly, canManage, onAdd, onDelete }: { session: HazopSession; context?: any; readonly?: boolean | undefined; canManage?: boolean | undefined; onAdd: (values: Record<string, any>) => void; onDelete: (decisionId: string) => void }) {
  const [form, setForm] = useState<Record<string, any>>({ decisionType: 'Other' });
  const set = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return (
    <section className="rounded-xl border border-[var(--psm-line)] p-4">
      <h4 className="mb-3 font-semibold">Decisions</h4>
      <div className="space-y-2">{(session.decisions ?? []).map((decision: any) => <div key={decision.id} className="rounded-lg border border-[var(--psm-line)] p-3 text-sm"><div className="flex justify-between gap-3"><div><div className="font-semibold">{decision.decision_title}</div><div className="text-xs text-[var(--psm-muted)]">{decision.decision_type} · {decision.decision_date} · Owner: {decision.owner?.displayName ?? decision.owner_id ?? '-'}</div><div className="mt-1 text-xs text-[var(--psm-muted)]">Node: {decision.node?.node_number ?? '-'} · Scenario: {decision.scenario?.scenario_number ?? '-'} · Recommendation: {decision.recommendation?.recommendation_number ?? '-'}</div><p className="mt-2 text-[var(--psm-muted)]">{decision.decision_description}</p></div>{canManage && !readonly ? <button onClick={() => onDelete(decision.id)} className="text-red-300">Delete</button> : null}</div></div>)}</div>
      {canManage && !readonly ? <div className="mt-4 grid gap-2 md:grid-cols-2"><input className="input" placeholder="Decision title" value={form.decisionTitle ?? ''} onChange={(e) => set('decisionTitle', e.target.value)} /><select className="input" value={form.decisionType} onChange={(e) => set('decisionType', e.target.value)}>{['Risk acceptance', 'Recommendation required', 'LOPA required', 'Safeguard accepted', 'Node complete', 'Study scope change', 'Other'].map((x) => <option key={x}>{x}</option>)}</select><select className="input" value={form.nodeId ?? ''} onChange={(e) => set('nodeId', e.target.value)}><option value="">Linked node</option>{(context?.nodes ?? []).map((n: any) => <option key={n.id} value={n.id}>{n.node_number} {n.title}</option>)}</select><select className="input" value={form.scenarioId ?? ''} onChange={(e) => set('scenarioId', e.target.value)}><option value="">Linked scenario</option>{(context?.scenarios ?? []).map((s: any) => <option key={s.id} value={s.id}>{s.scenario_number} {s.deviation_text}</option>)}</select><select className="input" value={form.recommendationId ?? ''} onChange={(e) => set('recommendationId', e.target.value)}><option value="">Linked recommendation</option>{(context?.recommendations ?? []).map((r: any) => <option key={r.id} value={r.id}>{r.recommendation_number} {r.title ?? r.recommendation_text}</option>)}</select><select className="input" value={form.ownerId ?? ''} onChange={(e) => set('ownerId', e.target.value)}><option value="">Decision owner</option>{(context?.users ?? []).map((u: any) => <option key={u.id} value={u.id}>{u.displayName}</option>)}</select><input type="date" className="input" value={form.decisionDate ?? ''} onChange={(e) => set('decisionDate', e.target.value)} /><textarea className="input min-h-20 md:col-span-2" placeholder="Decision description" value={form.decisionDescription ?? ''} onChange={(e) => set('decisionDescription', e.target.value)} /><button onClick={() => onAdd(form)} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white md:col-span-2">Add Decision</button></div> : null}
    </section>
  );
}
