'use client';

import { AlertTriangle, CheckCircle2, Lock, ShieldAlert } from 'lucide-react';
import { Badge, DetailCard, Metric, ProgressBar, riskTone } from '../moc-detail-ui';

export function RiskSummaryCard({ risk, summary, readOnly }: { risk: any; summary?: any; readOnly?: boolean }) {
  const score = Number(risk?.total_score ?? 0);
  const level = risk?.risk_level ?? 'Low';
  return (
    <DetailCard title="Risk Summary" action={<Badge tone={readOnly ? 'slate' : riskTone(level)}>{readOnly ? 'Read only' : risk?.status ?? 'Draft'}</Badge>}>
      <div className="grid gap-3 md:grid-cols-4">
        <Metric label="Total Risk Score" value={`${score} / 9`} tone={riskTone(level)} sub={level} />
        <Metric label="Required Reviews" value={summary?.requiredReviews ?? 0} tone="blue" sub="Generated by risk engine" />
        <Metric label="Approval Blockers" value={summary?.approvalBlockingReviews ?? 0} tone={summary?.approvalBlockingReviews ? 'amber' : 'green'} sub="Before approval" />
        <Metric label="Startup Blockers" value={summary?.startupBlockingReviews ?? 0} tone={summary?.startupBlockingReviews ? 'red' : 'green'} sub="Before startup" />
      </div>
      <div className="mt-4 grid gap-3 lg:grid-cols-[1fr_320px]">
        <div className="rounded-lg border border-white/10 bg-slate-950/35 p-4">
          <div className="mb-2 flex items-center justify-between text-xs font-bold uppercase tracking-wide text-slate-400"><span>Risk position</span><span>{Math.round(score * 11.11)}%</span></div>
          <ProgressBar value={score * 11.11} tone={level === 'Critical' || level === 'High' ? 'red' : level === 'Medium' ? 'amber' : 'green'} />
          <div className="mt-3 grid gap-2 text-sm text-slate-300 md:grid-cols-3">
            <span>Safety: <b className="text-white">{risk?.safety_label ?? '-'}</b></span>
            <span>Environmental: <b className="text-white">{risk?.environmental_label ?? '-'}</b></span>
            <span>Production: <b className="text-white">{risk?.production_label ?? '-'}</b></span>
          </div>
        </div>
        <div className="rounded-lg border border-white/10 bg-slate-950/35 p-4">
          <p className="flex items-center gap-2 text-sm font-black text-white">{level === 'Critical' ? <ShieldAlert className="h-4 w-4 text-red-300" /> : readOnly ? <Lock className="h-4 w-4 text-slate-300" /> : <CheckCircle2 className="h-4 w-4 text-emerald-300" />} Risk controls status</p>
          <p className="mt-2 text-sm text-slate-400">{level === 'Critical' ? 'Critical risk requires management acceptance, HAZOP review, PSSR, and startup controls.' : readOnly ? 'This risk assessment is locked or the MOC state is read-only.' : 'Risk assessment can be saved, recalculated, completed, and locked from this tab.'}</p>
          {(summary?.validationErrors ?? []).length ? <p className="mt-2 flex items-center gap-2 text-xs font-bold text-red-200"><AlertTriangle className="h-4 w-4" />{summary.validationErrors.length} validation issue(s)</p> : null}
        </div>
      </div>
    </DetailCard>
  );
}
