import { PsiCard } from '../../shared/PsiUi';
import type { ElectricalDetail } from '../../types/electrical-classification.types';

export function ElectricalChangeHistoryTab({ detail }: { detail: ElectricalDetail }) {
  return <PsiCard title="Change History" subtitle="Immutable PSI electrical classification history/audit events generated by backend mutations."><div className="grid gap-2">{detail.history.length ? detail.history.map((event) => <div key={event.id} className="rounded-lg border border-[var(--psm-line)] bg-[var(--psm-surface-2)] p-3"><p className="font-semibold">{event.event_title}</p><p className="text-sm text-[var(--psm-muted)]">{new Date(event.created_at).toLocaleString()} - {event.event_type}</p><p className="text-sm">{event.event_description}</p></div>) : <p className="text-sm text-[var(--psm-muted)]">No history events recorded yet.</p>}</div></PsiCard>;
}
