import { PsiCard, PsiMetricCard } from '../../shared/PsiUi';
import type { ElectricalDetail } from '../../types/electrical-classification.types';
import { HazardousAreaMapPlaceholder } from '../HazardousAreaMapPlaceholder';
import { ElectricalCompletenessPanel } from '../ElectricalCompletenessPanel';
import { ElectricalConflictPanel } from '../ElectricalConflictPanel';
import { ElectricalRatingCheckPanel } from '../ElectricalRatingCheckPanel';

export function ElectricalOverviewTab({ detail }: { detail: ElectricalDetail }) {
  return <div className="space-y-5"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{detail.overview.cards.map((card) => <PsiMetricCard key={card.label} label={card.label} value={String(card.value ?? 'N/A')} tone={card.tone ?? 'neutral'} />)}</div><PsiCard title="Electrical Classification Snapshot" subtitle="Backend source of truth for hazardous material, area classification, ventilation, protection, PTW controls, linked evidence, readiness, and blockers."><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><p><strong>Material:</strong> {detail.hazardSource?.hazardous_material_name || 'Missing'}</p><p><strong>Release source:</strong> {detail.hazardSource?.release_source_type || 'Missing'}</p><p><strong>Zone / Division:</strong> {detail.areaDetails?.zone_classification || detail.areaDetails?.nec_class_division || 'Missing'}</p><p><strong>Group:</strong> {detail.areaDetails?.gas_group || detail.areaDetails?.dust_group || 'Missing'}</p><p><strong>Temperature class:</strong> {detail.areaDetails?.temperature_class || 'Missing'}</p><p><strong>Protection:</strong> {detail.protectionRequirements?.required_protection_method || 'Missing'}</p></div>{detail.overview.blockers.length ? <div className="mt-4 rounded-lg border border-danger/30 bg-danger/10 p-3 text-sm text-danger">{detail.overview.blockers.map((blocker, index) => <p key={index}>{String(blocker.title ?? blocker.message ?? 'Open blocker')}</p>)}</div> : null}</PsiCard><HazardousAreaMapPlaceholder /><ElectricalRatingCheckPanel items={detail.installedEquipment} /><ElectricalCompletenessPanel checks={detail.completeness} score={detail.classification.completeness_score} /><ElectricalConflictPanel conflicts={detail.conflicts} /></div>;
}
