'use client';

import { useState } from 'react';

export function CalibrationPlanForm({ initial, saving, onSubmit }: { initial?: Record<string, any>; saving?: boolean; onSubmit: (input: Record<string, unknown>) => void }) {
  const [form, setForm] = useState<Record<string, any>>({ equipmentId: initial?.equipment_id ?? '', planTitle: initial?.plan_title ?? '', instrumentType: initial?.instrument_type ?? '', calibrationType: initial?.calibration_type ?? '', toleranceType: initial?.tolerance_type ?? 'Absolute value', toleranceValue: initial?.tolerance_value ?? '', tolerancePercent: initial?.tolerance_percent ?? '', frequencyValue: initial?.frequency_value ?? '', frequencyUnit: initial?.frequency_unit ?? 'Months' });
  const set = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <form className="space-y-4 rounded-xl border border-[var(--psm-line)] bg-[var(--psm-surface)] p-5" onSubmit={(event) => { event.preventDefault(); onSubmit(form); }}><div className="grid gap-4 md:grid-cols-2"><input className="rounded-lg border border-[var(--psm-line)] bg-[var(--psm-bg)] px-3 py-2" placeholder="Equipment ID" value={form.equipmentId} onChange={(event) => set('equipmentId', event.target.value)} required /><input className="rounded-lg border border-[var(--psm-line)] bg-[var(--psm-bg)] px-3 py-2" placeholder="Plan title" value={form.planTitle} onChange={(event) => set('planTitle', event.target.value)} required /><input className="rounded-lg border border-[var(--psm-line)] bg-[var(--psm-bg)] px-3 py-2" placeholder="Instrument type" value={form.instrumentType} onChange={(event) => set('instrumentType', event.target.value)} required /><input className="rounded-lg border border-[var(--psm-line)] bg-[var(--psm-bg)] px-3 py-2" placeholder="Calibration type" value={form.calibrationType} onChange={(event) => set('calibrationType', event.target.value)} required /><select className="rounded-lg border border-[var(--psm-line)] bg-[var(--psm-bg)] px-3 py-2" value={form.toleranceType} onChange={(event) => set('toleranceType', event.target.value)}>{['Absolute value', 'Percent of span', 'Percent of reading'].map((item) => <option key={item}>{item}</option>)}</select><input className="rounded-lg border border-[var(--psm-line)] bg-[var(--psm-bg)] px-3 py-2" placeholder="Tolerance value" value={form.toleranceValue} onChange={(event) => set('toleranceValue', event.target.value)} /><input type="number" className="rounded-lg border border-[var(--psm-line)] bg-[var(--psm-bg)] px-3 py-2" placeholder="Frequency value" value={form.frequencyValue} onChange={(event) => set('frequencyValue', event.target.value)} /><select className="rounded-lg border border-[var(--psm-line)] bg-[var(--psm-bg)] px-3 py-2" value={form.frequencyUnit} onChange={(event) => set('frequencyUnit', event.target.value)}>{['Days', 'Weeks', 'Months', 'Years'].map((item) => <option key={item}>{item}</option>)}</select></div><button className="rounded-lg bg-info px-4 py-2 text-sm font-semibold text-white" disabled={saving}>{saving ? 'Saving...' : 'Save Calibration Plan'}</button></form>;
}

