'use client';

import { ExternalLink, Plus, RefreshCcw, ShieldAlert, TrafficCone } from 'lucide-react';
import { useState } from 'react';
import { Badge, DetailCard, EmptyState, Field, Metric, ProgressBar, detailInput, detailTextarea } from '../moc-detail-ui';
import type { MOCActionValues } from '../../schemas/moc-actions.schema';

export function ClosedLoopSummaryCard({ summary }: { summary: any }) {
  const readiness = summary?.readinessStatus;
  return <DetailCard title="Closed-Loop Summary Card" action={<Badge tone={readiness === 'Green' ? 'green' : readiness === 'Red' ? 'red' : 'amber'}>{readiness ?? 'Amber'}</Badge>}><div className="grid gap-3 md:grid-cols-4 xl:grid-cols-8"><Metric label="Total" value={summary?.totalRequiredActions ?? 0} tone="blue" /><Metric label="Completed" value={summary?.completedActions ?? 0} tone="green" /><Metric label="Open" value={summary?.openActions ?? 0} tone="amber" /><Metric label="Overdue" value={summary?.overdueActions ?? 0} tone="red" /><Metric label="Startup Blockers" value={summary?.startupBlockingActions ?? 0} tone={summary?.startupBlockingActions ? 'red' : 'green'} /><Metric label="Closure Blockers" value={summary?.closureBlockingActions ?? 0} tone={summary?.closureBlockingActions ? 'red' : 'green'} /><Metric label="Missing Evidence" value={summary?.actionsMissingEvidence ?? 0} tone={summary?.actionsMissingEvidence ? 'amber' : 'green'} /><Metric label="Pending Verification" value={summary?.actionsPendingVerification ?? 0} tone={summary?.actionsPendingVerification ? 'amber' : 'green'} /></div><div className="mt-4"><ProgressBar value={summary?.completionPercentage ?? 0} tone={readiness === 'Red' ? 'red' : readiness === 'Green' ? 'green' : 'amber'} /></div></DetailCard>;
}

export function StartupBlockersPanel({ blockers }: { blockers: any[] }) {
  return <BlockerPanel title="Startup Blockers Panel" blockers={blockers} empty="No startup blockers. MOC can proceed to startup readiness when workflow allows." />;
}

export function ClosureBlockersPanel({ blockers }: { blockers: any[] }) {
  return <BlockerPanel title="Closure Blockers Panel" blockers={blockers} empty="No closure blockers. Required actions are complete, evidenced, and verified." />;
}

function BlockerPanel({ title, blockers, empty }: { title: string; blockers: any[]; empty: string }) {
  return <DetailCard title={title} action={<Badge tone={blockers.length ? 'red' : 'green'}>{blockers.length} Blocking</Badge>}>{!blockers.length ? <EmptyState title={empty} /> : <div className="space-y-2">{blockers.map((item) => <div key={item.id} className="rounded-lg border border-red-300/15 bg-red-500/10 p-3"><p className="flex items-center gap-2 font-bold text-red-100"><ShieldAlert size={15} />{item.title}</p><p className="mt-1 text-xs text-red-200/80">{item.reason ?? item.description ?? item.source_type}</p></div>)}</div>}</DetailCard>;
}

export function RequiredActionsTable({ actions, onSelect, onUpdate }: { actions: any[]; onSelect: (action: any) => void; onUpdate: (actionId: string, values: Record<string, any>) => void }) {
  return <DetailCard title="Required Actions Table">{!actions.length ? <EmptyState title="No closed-loop actions generated yet. Generate actions from impact and risk assessment." /> : <div className="overflow-x-auto"><table className="w-full min-w-[1350px] text-left text-sm"><thead className="sticky top-0 bg-[#07182a] text-xs uppercase text-slate-500"><tr>{['Action', 'Source', 'Linked Module', 'Owner', 'Priority', 'Due', 'Status', 'Evidence', 'Verification', 'Approval', 'Startup', 'Closure', 'Open'].map((h) => <th key={h} className="border-b border-white/10 px-3 py-2">{h}</th>)}</tr></thead><tbody>{actions.map((action) => <tr key={action.id} className="border-b border-white/5 hover:bg-white/[0.03]"><td className="px-3 py-3"><p className="font-black text-white">{action.action_title ?? action.title}</p><p className="text-xs text-slate-500">{action.description}</p></td><td className="px-3 py-3 text-slate-300">{action.source_type ?? action.source_impact_answer ?? 'Manual'}</td><td className="px-3 py-3 text-slate-300">{action.linked_module ?? action.action_type}</td><td className="px-3 py-3 text-slate-300">{action.owner_id ?? '-'}</td><td className="px-3 py-3"><Badge tone={action.priority === 'SAFETY_CRITICAL' || action.priority === 'HIGH' ? 'red' : action.priority === 'MEDIUM' ? 'amber' : 'green'}>{action.priority}</Badge></td><td className="px-3 py-3 text-slate-300">{action.due_date ?? '-'}</td><td className="px-3 py-3"><select className={detailInput} value={action.status} onChange={(e) => onUpdate(action.id, { status: e.target.value })}><option>Preview</option><option>Created</option><option>In Progress</option><option>Pending Verification</option><option>Completed</option><option>Closed</option><option>No Longer Required</option></select></td><td className="px-3 py-3">{action.evidence_required ? <Badge tone={['Uploaded', 'Accepted', 'Approved'].includes(action.evidence_status) ? 'green' : 'amber'}>{action.evidence_status}</Badge> : <Badge>Not Required</Badge>}</td><td className="px-3 py-3">{action.verification_required ? <Badge tone={action.verification_status === 'Verified' ? 'green' : 'amber'}>{action.verification_status}</Badge> : <Badge>Not Required</Badge>}</td><td className="px-3 py-3 text-slate-300">{action.required_before_approval ? 'Yes' : 'No'}</td><td className="px-3 py-3 text-slate-300">{action.required_before_startup ? 'Yes' : 'No'}</td><td className="px-3 py-3 text-slate-300">{action.required_before_closure ? 'Yes' : 'No'}</td><td className="px-3 py-3"><button type="button" onClick={() => onSelect(action)} className="rounded-md border border-blue-300/20 px-2 py-1 text-xs font-black text-blue-200">Details</button></td></tr>)}</tbody></table></div>}</DetailCard>;
}

export function ActionGroupPanels({ actions }: { actions: any[] }) {
  const groups = ['Documents / PSI', 'Engineering', 'HAZOP / LOPA / PSSR', 'Training', 'Equipment Registry', 'Operations / Procedures', 'Environmental / Compliance', 'Quality / Production', 'Temporary / Emergency', 'Manual'];
  return <DetailCard title="Action Group Panels"><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-5">{groups.map((group) => { const rows = actions.filter((row) => groupFor(row) === group); return <div key={group} className="rounded-lg border border-white/10 bg-slate-950/35 p-3"><p className="font-bold text-white">{group}</p><div className="mt-2 grid grid-cols-4 gap-1 text-xs text-slate-400"><span>Total<br /><b className="text-white">{rows.length}</b></span><span>Done<br /><b className="text-emerald-300">{rows.filter((r) => ['Completed', 'Closed'].includes(r.status)).length}</b></span><span>Open<br /><b className="text-amber-300">{rows.filter((r) => !['Completed', 'Closed'].includes(r.status)).length}</b></span><span>Block<br /><b className="text-red-300">{rows.filter((r) => r.required_before_startup || r.required_before_closure).length}</b></span></div></div>; })}</div></DetailCard>;
}

export function MOCActionDetailDrawer({ action, onClose, onNoLongerRequired }: { action: any; onClose: () => void; onNoLongerRequired: (reason: string) => void }) {
  if (!action) return null;
  return <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm"><aside className="ml-auto h-full w-full max-w-xl overflow-y-auto border-l border-cyan-300/10 bg-[#07182a] p-5 shadow-2xl"><div className="mb-4 flex justify-between gap-3"><div><p className="text-xs font-bold uppercase text-slate-500">Action Detail Drawer</p><h3 className="text-xl font-black text-white">{action.title}</h3></div><button type="button" onClick={onClose} className="rounded-md border border-white/10 px-3 py-2 text-sm text-slate-200">Close</button></div><div className="space-y-3 text-sm text-slate-300"><Info label="Owner" value={action.owner_id ?? '-'} /><Info label="Source" value={action.source_type ?? '-'} /><Info label="Linked MOC" value={action.moc_id ?? '-'} /><Info label="Due date" value={action.due_date ?? '-'} /><Info label="Evidence" value={`${action.evidence_required ? 'Required' : 'Not required'} · ${action.evidence_status ?? '-'}`} /><Info label="Verification" value={`${action.verification_required ? 'Required' : 'Not required'} · ${action.verification_status ?? '-'}`} /><p className="rounded-lg border border-white/10 bg-slate-950/35 p-3">{action.description}</p><div className="flex flex-wrap gap-2"><a href={action.action_id ? `/actions/${action.action_id}` : '#'} className="inline-flex items-center gap-2 rounded-md bg-blue-600 px-3 py-2 text-xs font-black text-white">Open full Action Engine page <ExternalLink size={14} /></a><button type="button" onClick={() => { const reason = window.prompt('Reason this action is no longer required?'); if (reason) onNoLongerRequired(reason); }} className="rounded-md border border-red-300/20 px-3 py-2 text-xs font-black text-red-200">No Longer Required</button></div></div></aside></div>;
}

export function EvidenceVerificationStatus({ actions }: { actions: any[] }) {
  const evidenceUploaded = actions.filter((row) => ['Uploaded', 'Accepted', 'Approved'].includes(row.evidence_status)).length;
  const missing = actions.filter((row) => row.evidence_required && !['Uploaded', 'Accepted', 'Approved'].includes(row.evidence_status)).length;
  const verified = actions.filter((row) => row.verification_status === 'Verified').length;
  const pending = actions.filter((row) => row.verification_required && row.verification_status !== 'Verified').length;
  return <DetailCard title="Evidence / Verification Status"><div className="grid gap-3 md:grid-cols-4"><Metric label="Evidence uploaded" value={evidenceUploaded} tone="green" /><Metric label="Evidence missing" value={missing} tone={missing ? 'red' : 'green'} /><Metric label="Verification approved" value={verified} tone="green" /><Metric label="Verification pending" value={pending} tone={pending ? 'amber' : 'green'} /></div></DetailCard>;
}

export function GenerateSyncActionsControls({ onGenerate, onSync, onCreateUniversal, onCustom, busy }: { onGenerate: () => void; onSync: (source?: string) => void; onCreateUniversal: () => void; onCustom: (values: MOCActionValues) => void; busy?: boolean }) {
  const [custom, setCustom] = useState<MOCActionValues>({ title: '', description: '', actionType: 'Manual', linkedModule: 'Manual', priority: 'MEDIUM', dueDate: '', requiredBeforeApproval: false, requiredBeforeStartup: false, requiredBeforeClosure: true, evidenceRequired: true, verificationRequired: true });
  const update = (patch: Partial<MOCActionValues>) => setCustom((current) => ({ ...current, ...patch }));
  return <DetailCard title="Generate / Sync Actions Controls" action={<button type="button" onClick={onGenerate} disabled={busy} className="inline-flex items-center gap-2 rounded-md bg-blue-600 px-3 py-2 text-xs font-black text-white disabled:opacity-50"><RefreshCcw size={14} /> Generate Required Actions</button>}><div className="flex flex-wrap gap-2">{['Impact Assessment', 'Risk Ranking', 'Engineering Package', 'Temporary / Emergency controls'].map((source) => <button key={source} type="button" disabled={busy} onClick={() => onSync(source)} className="rounded-md border border-cyan-300/20 px-3 py-2 text-xs font-black text-cyan-100 disabled:opacity-50">Sync with {source}</button>)}<button type="button" onClick={onCreateUniversal} disabled={busy} className="rounded-md border border-emerald-300/20 px-3 py-2 text-xs font-black text-emerald-200 disabled:opacity-50">Create Universal Actions</button></div><div className="mt-4 grid gap-3 md:grid-cols-4"><Field label="Custom title"><input className={detailInput} value={custom.title} onChange={(e) => update({ title: e.target.value })} /></Field><Field label="Linked module"><input className={detailInput} value={custom.linkedModule} onChange={(e) => update({ linkedModule: e.target.value })} /></Field><Field label="Priority"><select className={detailInput} value={custom.priority} onChange={(e) => update({ priority: e.target.value })}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>SAFETY_CRITICAL</option></select></Field><Field label="Due date"><input className={detailInput} type="date" value={custom.dueDate ?? ''} onChange={(e) => update({ dueDate: e.target.value })} /></Field><div className="md:col-span-4"><Field label="Description"><textarea className={detailTextarea} value={custom.description ?? ''} onChange={(e) => update({ description: e.target.value })} /></Field></div></div><div className="mt-3 flex flex-wrap gap-3 text-sm text-slate-300">{(['requiredBeforeApproval', 'requiredBeforeStartup', 'requiredBeforeClosure', 'evidenceRequired', 'verificationRequired'] as const).map((key) => <label key={key} className="flex items-center gap-2"><input type="checkbox" checked={Boolean(custom[key])} onChange={(e) => update({ [key]: e.target.checked } as any)} />{key}</label>)}<button type="button" onClick={() => custom.title && onCustom(custom)} className="inline-flex items-center gap-2 rounded-md border border-blue-300/20 px-3 py-2 text-xs font-black text-blue-200"><Plus size={14} /> Add custom action</button></div></DetailCard>;
}

export function TrafficLightClosureChecklist({ items, onRecalculate }: { items: any[]; onRecalculate: () => void }) {
  const tone: Record<string, 'green' | 'amber' | 'red' | 'slate'> = { Green: 'green', Amber: 'amber', Red: 'red', Gray: 'slate' };
  return <DetailCard title="Traffic Light Closure Checklist" action={<button type="button" onClick={onRecalculate} className="inline-flex items-center gap-2 rounded-md border border-blue-300/20 px-3 py-2 text-xs font-black text-blue-200"><TrafficCone size={14} /> Recalculate</button>}><div className="grid gap-2 md:grid-cols-3 xl:grid-cols-4">{items.map((item) => <div key={item.id ?? item.checklist_key} className="rounded-lg border border-white/10 bg-slate-950/35 p-3"><div className="flex items-center justify-between"><p className="text-sm font-bold text-white">{item.title}</p><Badge tone={tone[item.status] ?? 'slate'}>{item.status}</Badge></div><p className="mt-1 text-xs text-slate-500">{item.required ? `Required before ${item.blocking_stage}` : 'Not required'}</p></div>)}</div></DetailCard>;
}

function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-white/10 bg-slate-950/35 p-3"><p className="text-xs uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 font-bold text-white">{value}</p></div>; }

function groupFor(row: any) {
  const text = `${row.action_type ?? ''} ${row.linked_module ?? ''} ${row.source_type ?? ''}`.toLowerCase();
  if (text.includes('document') || text.includes('sop') || text.includes('sds') || text.includes('psi')) return 'Documents / PSI';
  if (text.includes('engineering')) return 'Engineering';
  if (text.includes('hazop') || text.includes('lopa') || text.includes('pssr')) return 'HAZOP / LOPA / PSSR';
  if (text.includes('training')) return 'Training';
  if (text.includes('equipment')) return 'Equipment Registry';
  if (text.includes('procedure') || text.includes('operation')) return 'Operations / Procedures';
  if (text.includes('environment')) return 'Environmental / Compliance';
  if (text.includes('quality') || text.includes('production')) return 'Quality / Production';
  if (text.includes('temporary') || text.includes('emergency')) return 'Temporary / Emergency';
  return 'Manual';
}
