import { CanActivate, ExecutionContext, Injectable } from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { PermissionsService } from '../../permissions/permissions.service';
import { PERMISSIONS_KEY } from '../decorators/permissions.decorator';

@Injectable()
export class PermissionsGuard implements CanActivate {
  constructor(
    private readonly reflector: Reflector,
    private readonly permissions: PermissionsService
  ) {}

  async canActivate(context: ExecutionContext): Promise<boolean> {
    const required = this.reflector.getAllAndOverride<string[]>(PERMISSIONS_KEY, [
      context.getHandler(),
      context.getClass()
    ]);
    if (!required?.length) return true;

    const request = context.switchToHttp().getRequest<{ user?: { id?: string; tenantId?: string; permissions?: string[] } }>();
    const tokenPermissions = request.user?.permissions ?? [];
    const livePermissions = request.user?.id && request.user?.tenantId
      ? await this.permissions.listForUser(request.user.id, request.user.tenantId)
      : [];
    const granted = new Set(expandPermissionAliases([...tokenPermissions, ...livePermissions]));
    return required.every((permission) => hasPermissionGrant(granted, permission));
  }
}

function hasPermissionGrant(granted: Set<string>, permission: string) {
  if (granted.has(permission)) return true;
  if (permission.startsWith('audit.') && (granted.has('audit:manage') || granted.has('audit.manage'))) return true;
  if (isAuditReadPermission(permission) && (granted.has('audit:read') || granted.has('audit.view'))) return true;
  return false;
}

function isAuditReadPermission(permission: string) {
  if (!permission.startsWith('audit.')) return false;
  return (
    permission === 'audit.view' ||
    permission.endsWith('.view') ||
    permission.endsWith('.dashboard.view') ||
    permission.endsWith('.register.view') ||
    permission.endsWith('.calendar.view') ||
    permission.endsWith('.history.view') ||
    permission.endsWith('.settings.view') ||
    permission.endsWith('.preview') ||
    permission.endsWith('.download')
  );
}

function expandPermissionAliases(permissions: string[]) {
  const miInspectionReadPermissions = [
    'mechanical_integrity.inspection_plan.view',
    'mechanical_integrity.inspection_scheduler.view',
    'mechanical_integrity.inspection_scheduler.rule.view',
    'mechanical_integrity.inspection_occurrence.view',
    'mechanical_integrity.inspection_checklist.view',
    'mechanical_integrity.inspection_criteria.view',
    'mechanical_integrity.inspection_record.view',
    'mechanical_integrity.ut_reading.view',
    'mechanical_integrity.remaining_life.view',
    'mechanical_integrity.inspection_finding.view',
    'mechanical_integrity.criticality.view',
    'mechanical_integrity.criticality_config.view',
    'mechanical_integrity.criticality_calculation.view',
    'mechanical_integrity.pm_plan.view',
    'mechanical_integrity.pm_record.view',
    'mechanical_integrity.pm_scheduler.view',
    'mechanical_integrity.calibration_plan.view',
    'mechanical_integrity.calibration_record.view',
    'mechanical_integrity.calibration_scheduler.view',
    'mechanical_integrity.relief_device.view',
    'mechanical_integrity.relief_device_technical.view',
    'mechanical_integrity.relief_basis.view',
    'mechanical_integrity.relief_protection.view',
    'mechanical_integrity.relief_test.view',
    'mechanical_integrity.relief_certificate.view',
    'mechanical_integrity.relief_scheduler.view',
    'mechanical_integrity.sif.view',
    'mechanical_integrity.sif_device.view',
    'mechanical_integrity.sif_sil_data.view',
    'mechanical_integrity.interlock.view',
    'mechanical_integrity.critical_alarm.view',
    'mechanical_integrity.safeguard_test.view',
    'mechanical_integrity.safeguard_scheduler.view',
    'mechanical_integrity.safeguard_demand.view',
    'mechanical_integrity.safeguard_bypass.view',
    'mechanical_integrity.impairment.view',
    'mechanical_integrity.deficiency.view',
    'mechanical_integrity.deviation.view',
    'mechanical_integrity.work_order.view',
    'mechanical_integrity.action.view',
    'mechanical_integrity.readiness.view',
    'mechanical_integrity.review.view',
    'mechanical_integrity.review.inbox',
    'mechanical_integrity.history.view',
    'mechanical_integrity.history.view_audit',
    'mechanical_integrity.report.view',
    'mechanical_integrity.export.view'
  ];
  const miInspectionManagePermissions = [
    ...miInspectionReadPermissions,
    'mechanical_integrity.inspection_plan.create',
    'mechanical_integrity.inspection_plan.edit',
    'mechanical_integrity.inspection_plan.archive',
    'mechanical_integrity.inspection_plan.submit',
    'mechanical_integrity.inspection_plan.approve',
    'mechanical_integrity.inspection_plan.reject',
    'mechanical_integrity.inspection_plan.revision.create',
    'mechanical_integrity.inspection_plan.import',
    'mechanical_integrity.inspection_plan.export',
    'mechanical_integrity.inspection_scheduler.run',
    'mechanical_integrity.inspection_scheduler.rule.manage',
    'mechanical_integrity.inspection_scheduler.override',
    'mechanical_integrity.inspection_occurrence.assign',
    'mechanical_integrity.inspection_occurrence.cancel',
    'mechanical_integrity.inspection_occurrence.export',
    'mechanical_integrity.inspection_checklist.manage',
    'mechanical_integrity.inspection_criteria.manage',
    'mechanical_integrity.inspection_record.create',
    'mechanical_integrity.inspection_record.edit',
    'mechanical_integrity.inspection_record.submit',
    'mechanical_integrity.inspection_record.review',
    'mechanical_integrity.inspection_record.approve',
    'mechanical_integrity.inspection_record.reject',
    'mechanical_integrity.inspection_record.archive',
    'mechanical_integrity.inspection_record.export',
    'mechanical_integrity.inspection_checklist.execute',
    'mechanical_integrity.inspection_checklist.review',
    'mechanical_integrity.ut_reading.create',
    'mechanical_integrity.ut_reading.edit',
    'mechanical_integrity.ut_reading.import',
    'mechanical_integrity.ut_reading.review',
    'mechanical_integrity.ut_reading.approve',
    'mechanical_integrity.ut_reading.reject',
    'mechanical_integrity.ut_reading.supersede',
    'mechanical_integrity.remaining_life.recalculate',
    'mechanical_integrity.inspection_finding.create',
    'mechanical_integrity.inspection_finding.edit',
    'mechanical_integrity.inspection_finding.close',
    'mechanical_integrity.inspection_finding.link_action',
    'mechanical_integrity.criticality.create',
    'mechanical_integrity.criticality.edit',
    'mechanical_integrity.criticality.submit',
    'mechanical_integrity.criticality.review',
    'mechanical_integrity.criticality.approve',
    'mechanical_integrity.criticality.reject',
    'mechanical_integrity.criticality.archive',
    'mechanical_integrity.criticality.export',
    'mechanical_integrity.criticality.override',
    'mechanical_integrity.criticality_config.manage',
    'mechanical_integrity.criticality_calculation.recalculate',
    'mechanical_integrity.pm_plan.create',
    'mechanical_integrity.pm_plan.edit',
    'mechanical_integrity.pm_plan.submit',
    'mechanical_integrity.pm_plan.approve',
    'mechanical_integrity.pm_plan.reject',
    'mechanical_integrity.pm_plan.archive',
    'mechanical_integrity.pm_plan.import',
    'mechanical_integrity.pm_plan.export',
    'mechanical_integrity.pm_record.create',
    'mechanical_integrity.pm_record.edit',
    'mechanical_integrity.pm_record.submit',
    'mechanical_integrity.pm_record.review',
    'mechanical_integrity.pm_record.approve',
    'mechanical_integrity.pm_record.reject',
    'mechanical_integrity.pm_record.export',
    'mechanical_integrity.pm_scheduler.run',
    'mechanical_integrity.calibration_plan.create',
    'mechanical_integrity.calibration_plan.edit',
    'mechanical_integrity.calibration_plan.submit',
    'mechanical_integrity.calibration_plan.approve',
    'mechanical_integrity.calibration_plan.reject',
    'mechanical_integrity.calibration_plan.archive',
    'mechanical_integrity.calibration_plan.import',
    'mechanical_integrity.calibration_plan.export',
    'mechanical_integrity.calibration_record.create',
    'mechanical_integrity.calibration_record.edit',
    'mechanical_integrity.calibration_record.submit',
    'mechanical_integrity.calibration_record.review',
    'mechanical_integrity.calibration_record.approve',
    'mechanical_integrity.calibration_record.reject',
    'mechanical_integrity.calibration_record.export',
    'mechanical_integrity.calibration_scheduler.run',
    'mechanical_integrity.pm_calibration.override',
    'mechanical_integrity.relief_device.create',
    'mechanical_integrity.relief_device.edit',
    'mechanical_integrity.relief_device.archive',
    'mechanical_integrity.relief_device.import',
    'mechanical_integrity.relief_device.export',
    'mechanical_integrity.relief_device_technical.edit',
    'mechanical_integrity.relief_basis.edit',
    'mechanical_integrity.relief_protection.manage',
    'mechanical_integrity.relief_test.create',
    'mechanical_integrity.relief_test.edit',
    'mechanical_integrity.relief_test.submit',
    'mechanical_integrity.relief_test.review',
    'mechanical_integrity.relief_test.approve',
    'mechanical_integrity.relief_test.reject',
    'mechanical_integrity.relief_test.export',
    'mechanical_integrity.relief_certificate.manage',
    'mechanical_integrity.relief_scheduler.run',
    'mechanical_integrity.relief_scheduler.override',
    'mechanical_integrity.sif.create',
    'mechanical_integrity.sif.edit',
    'mechanical_integrity.sif.archive',
    'mechanical_integrity.sif.import',
    'mechanical_integrity.sif.export',
    'mechanical_integrity.sif_device.manage',
    'mechanical_integrity.sif_sil_data.edit',
    'mechanical_integrity.sif_lopa_link.manage',
    'mechanical_integrity.interlock.create',
    'mechanical_integrity.interlock.edit',
    'mechanical_integrity.interlock.archive',
    'mechanical_integrity.interlock.import',
    'mechanical_integrity.interlock.export',
    'mechanical_integrity.critical_alarm.create',
    'mechanical_integrity.critical_alarm.edit',
    'mechanical_integrity.critical_alarm.archive',
    'mechanical_integrity.critical_alarm.import',
    'mechanical_integrity.critical_alarm.export',
    'mechanical_integrity.safeguard_test.create',
    'mechanical_integrity.safeguard_test.edit',
    'mechanical_integrity.safeguard_test.submit',
    'mechanical_integrity.safeguard_test.review',
    'mechanical_integrity.safeguard_test.approve',
    'mechanical_integrity.safeguard_test.reject',
    'mechanical_integrity.safeguard_test.export',
    'mechanical_integrity.safeguard_scheduler.run',
    'mechanical_integrity.safeguard_scheduler.override',
    'mechanical_integrity.safeguard_demand.create',
    'mechanical_integrity.safeguard_demand.edit',
    'mechanical_integrity.safeguard_bypass.configure',
    'mechanical_integrity.impairment.create',
    'mechanical_integrity.impairment.edit',
    'mechanical_integrity.impairment.submit',
    'mechanical_integrity.impairment.approve',
    'mechanical_integrity.impairment.reject',
    'mechanical_integrity.impairment.activate',
    'mechanical_integrity.impairment.extend',
    'mechanical_integrity.impairment.restore',
    'mechanical_integrity.impairment.verify_restoration',
    'mechanical_integrity.impairment.close',
    'mechanical_integrity.impairment.cancel',
    'mechanical_integrity.impairment.import',
    'mechanical_integrity.impairment.export',
    'mechanical_integrity.impairment.admin_override',
    'mechanical_integrity.deficiency.create',
    'mechanical_integrity.deficiency.edit',
    'mechanical_integrity.deficiency.submit',
    'mechanical_integrity.deficiency.review',
    'mechanical_integrity.deficiency.approve',
    'mechanical_integrity.deficiency.reject',
    'mechanical_integrity.deficiency.verify',
    'mechanical_integrity.deficiency.close',
    'mechanical_integrity.deficiency.cancel',
    'mechanical_integrity.deficiency.import',
    'mechanical_integrity.deficiency.export',
    'mechanical_integrity.deviation.create',
    'mechanical_integrity.deviation.edit',
    'mechanical_integrity.deviation.approve',
    'mechanical_integrity.deviation.extend',
    'mechanical_integrity.deviation.close',
    'mechanical_integrity.deviation.export',
    'mechanical_integrity.work_order.create',
    'mechanical_integrity.work_order.edit',
    'mechanical_integrity.work_order.submit',
    'mechanical_integrity.work_order.approve',
    'mechanical_integrity.work_order.reject',
    'mechanical_integrity.work_order.plan',
    'mechanical_integrity.work_order.assign',
    'mechanical_integrity.work_order.start',
    'mechanical_integrity.work_order.complete',
    'mechanical_integrity.work_order.verify',
    'mechanical_integrity.work_order.close',
    'mechanical_integrity.work_order.cancel',
    'mechanical_integrity.work_order.import',
    'mechanical_integrity.work_order.export',
    'mechanical_integrity.action.create',
    'mechanical_integrity.action.edit',
    'mechanical_integrity.action.assign',
    'mechanical_integrity.action.complete',
    'mechanical_integrity.action.verify',
    'mechanical_integrity.action.close',
    'mechanical_integrity.readiness.create',
    'mechanical_integrity.readiness.edit',
    'mechanical_integrity.readiness.run_check',
    'mechanical_integrity.readiness.submit',
    'mechanical_integrity.readiness.review',
    'mechanical_integrity.readiness.approve',
    'mechanical_integrity.readiness.reject',
    'mechanical_integrity.readiness.override',
    'mechanical_integrity.readiness.waive_blocker',
    'mechanical_integrity.readiness.clear_blocker',
    'mechanical_integrity.readiness.close',
    'mechanical_integrity.readiness.import',
    'mechanical_integrity.readiness.export',
    'mechanical_integrity.review.submit',
    'mechanical_integrity.review.approve',
    'mechanical_integrity.review.reject',
    'mechanical_integrity.review.return',
    'mechanical_integrity.review.delegate',
    'mechanical_integrity.review.escalate',
    'mechanical_integrity.review.override_validation',
    'mechanical_integrity.review.configure_rules',
    'mechanical_integrity.review.view_internal_comments',
    'mechanical_integrity.review.export',
    'mechanical_integrity.history.export',
    'mechanical_integrity.report.generate',
    'mechanical_integrity.report.manage_templates',
    'mechanical_integrity.report.schedule',
    'mechanical_integrity.report.export',
    'mechanical_integrity.export.create',
    'mechanical_integrity.export.download',
    'mechanical_integrity.export.include_documents',
    'mechanical_integrity.export.include_audit',
    'mechanical_integrity.export.site_export',
    'mechanical_integrity.export.admin_all'
  ];
  
const pssrTrainingPermissions = [
  'training.pssr.view',
  'training.pssr.dashboard.view',
  'training.pssr.readiness.view',
  'training.pssr.readiness.create',
  'training.pssr.readiness.edit',
  'training.pssr.readiness.archive',
  'training.pssr.impact_check.view',
  'training.pssr.impact_check.run',
  'training.pssr.readiness_check.view',
  'training.pssr.readiness_check.run',
  'training.pssr.required_workers.view',
  'training.pssr.required_workers.manage',
  'training.pssr.assignment.view',
  'training.pssr.assignment.generate',
  'training.pssr.assignment.cancel',
  'training.pssr.readiness.run',
  'training.pssr.blocker.view',
  'training.pssr.blocker.close',
  'training.pssr.blocker.verify',
  'training.pssr.blocker.reopen',
  'training.pssr.waiver.view',
  'training.pssr.waiver.request',
  'training.pssr.waiver.approve',
  'training.pssr.waiver.reject',
  'training.pssr.waiver.revoke',
  'training.pssr.evidence.view',
  'training.pssr.evidence.verify',
  'training.pssr.import',
  'training.pssr.export',
  'training.pssr.history.view',
  'training.pssr.settings.view',
  'training.pssr.settings.edit'
];
const mocTrainingPermissions = [
    'training.moc.view',
    'training.moc.dashboard.view',
    'training.moc.requirement.view',
    'training.moc.requirement.create',
    'training.moc.requirement.edit',
    'training.moc.requirement.archive',
    'training.moc.impact_check.view',
    'training.moc.impact_check.run',
    'training.moc.affected_workers.view',
    'training.moc.affected_workers.manage',
    'training.moc.assignment.view',
    'training.moc.assignment.generate',
    'training.moc.assignment.cancel',
    'training.moc.readiness.view',
    'training.moc.readiness.run',
    'training.moc.blocker.view',
    'training.moc.blocker.close',
    'training.moc.blocker.verify',
    'training.moc.blocker.reopen',
    'training.moc.waiver.view',
    'training.moc.waiver.request',
    'training.moc.waiver.approve',
    'training.moc.waiver.reject',
    'training.moc.waiver.revoke',
    'training.moc.evidence.view',
    'training.moc.evidence.verify',
    'training.moc.import',
    'training.moc.export',
    'training.moc.history.view',
    'training.moc.settings.view',
    'training.moc.settings.edit'
];
const ptwAuthorizationPermissions = [
  'training.ptw_authorization.view',
  'training.ptw_authorization.dashboard.view',
  'training.ptw_authorization.rule.view',
  'training.ptw_authorization.rule.create',
  'training.ptw_authorization.rule.edit',
  'training.ptw_authorization.rule.archive',
  'training.ptw_authorization.rule.activate',
  'training.ptw_authorization.rule.evaluate',
  'training.ptw_authorization.rule.generate_requests',
  'training.ptw_authorization.record.view',
  'training.ptw_authorization.record.create',
  'training.ptw_authorization.record.edit',
  'training.ptw_authorization.record.evaluate',
  'training.ptw_authorization.record.submit_approval',
  'training.ptw_authorization.record.approve',
  'training.ptw_authorization.record.reject',
  'training.ptw_authorization.record.renew',
  'training.ptw_authorization.record.suspend',
  'training.ptw_authorization.record.revoke',
  'training.ptw_authorization.request.view',
  'training.ptw_authorization.request.create',
  'training.ptw_authorization.request.edit',
  'training.ptw_authorization.request.submit',
  'training.ptw_authorization.request.approve',
  'training.ptw_authorization.request.reject',
  'training.ptw_authorization.request.return',
  'training.ptw_authorization.evaluation.view',
  'training.ptw_authorization.evaluation.run',
  'training.ptw_authorization.check.run',
  'training.ptw_authorization.gap.view',
  'training.ptw_authorization.gap.close',
  'training.ptw_authorization.gap.verify',
  'training.ptw_authorization.gap.reopen',
  'training.ptw_authorization.waiver.view',
  'training.ptw_authorization.waiver.request',
  'training.ptw_authorization.waiver.approve',
  'training.ptw_authorization.waiver.reject',
  'training.ptw_authorization.waiver.revoke',
  'training.ptw_authorization.import',
  'training.ptw_authorization.export',
  'training.ptw_authorization.history.view',
  'training.ptw_authorization.settings.view',
  'training.ptw_authorization.settings.edit'
];
const trainingReportsPermissions = [
  'training.reports.view',
  'training.reports.dashboard.view',
  'training.reports.template.view',
  'training.reports.template.create',
  'training.reports.template.edit',
  'training.reports.template.archive',
  'training.reports.template.activate',
  'training.reports.generate',
  'training.reports.generate.company',
  'training.reports.generate.site',
  'training.reports.export.pdf',
  'training.reports.export.xlsx',
  'training.reports.export.csv',
  'training.reports.export.json',
  'training.reports.export.zip',
  'training.reports.download',
  'training.reports.download.restricted',
  'training.reports.package.view',
  'training.reports.package.create',
  'training.reports.package.download',
  'training.reports.scheduled.view',
  'training.reports.scheduled.create',
  'training.reports.scheduled.edit',
  'training.reports.scheduled.archive',
  'training.reports.audit_evidence.view',
  'training.reports.audit_evidence.export',
  'training.reports.worker_evidence.export',
  'training.reports.moc_evidence.export',
  'training.reports.pssr_evidence.export',
  'training.reports.ptw_evidence.export',
  'training.reports.history.view',
  'training.reports.settings.view',
  'training.reports.settings.edit'
];
const trainingReviewPermissions = [
  'training.review.view',
  'training.review.dashboard.view',
  'training.review.inbox.view',
  'training.review.submission.view',
  'training.review.request.view',
  'training.review.request.create',
  'training.review.request.cancel',
  'training.review.request.resubmit',
  'training.review.approve',
  'training.review.approve.safety_critical',
  'training.review.reject',
  'training.review.return',
  'training.review.escalate',
  'training.review.reassign',
  'training.review.comment',
  'training.review.validate',
  'training.review.esign',
  'training.review.rule.view',
  'training.review.rule.create',
  'training.review.rule.edit',
  'training.review.rule.archive',
  'training.review.history.view',
  'training.review.settings.view',
  'training.review.settings.edit'
];
const regulatoryReadPermissions = [
  'regulatory.view',
  'regulatory.dashboard.view',
  'regulatory.register.view',
  'regulatory.item.view',
  'regulatory.jurisdiction.view',
  'regulatory.jurisdiction.dashboard.view',
  'regulatory.authority.view',
  'regulatory.applicability.view',
  'regulatory.applicability.dashboard.view',
  'regulatory.applicability.matrix.view',
  'regulatory.applicability.profile.view',
  'regulatory.applicability.gap.view',
  'regulatory.applicability.stale.view',
  'regulatory.applicability.history.view',
  'regulatory.obligation.view',
  'regulatory.obligation.dashboard.view',
  'regulatory.obligation.register.view',
  'regulatory.obligation.matrix.view',
  'regulatory.obligation.scope.view',
  'regulatory.obligation.evidence_expectation.view',
  'regulatory.obligation.module_mapping.view',
  'regulatory.obligation.link.view',
  'regulatory.obligation.gap.view',
  'regulatory.obligation.stale.view',
  'regulatory.obligation.history.view',
  'regulatory.compliance.view',
  'regulatory.compliance.dashboard.view',
  'regulatory.compliance.register.view',
  'regulatory.compliance.matrix.view',
  'regulatory.compliance.assessment.view',
  'regulatory.compliance.rollup.view',
  'regulatory.compliance.evidence_readiness.view',
  'regulatory.compliance.criteria.view',
  'regulatory.compliance.gap.view',
  'regulatory.compliance.stale.view',
  'regulatory.compliance.history.view',
  'regulatory.scope.view',
  'regulatory.link.view',
  'regulatory.audit_mapping.view',
  'regulatory.audit_mapping.dashboard.view',
  'regulatory.audit_mapping.register.view',
  'regulatory.audit_mapping.matrix.view',
  'regulatory.audit_mapping.traceability.view',
  'regulatory.audit_mapping.coverage.view',
  'regulatory.audit_mapping.gap.view',
  'regulatory.audit_mapping.review.view',
  'regulatory.audit_mapping.history.view',
  'regulatory.evidence.view',
  'regulatory.evidence.dashboard.view',
  'regulatory.evidence.register.view',
  'regulatory.evidence.requirement.view',
  'regulatory.evidence.link.view',
  'regulatory.evidence.preview',
  'regulatory.evidence.download',
  'regulatory.evidence.review.view',
  'regulatory.evidence.request.view',
  'regulatory.evidence.gap.view',
  'regulatory.evidence.package.view',
  'regulatory.evidence.chain.view',
  'regulatory.evidence.access_log.view',
  'regulatory.evidence.stale.view',
  'regulatory.evidence.history.view',
  'regulatory.action.view',
  'regulatory.action.dashboard.view',
  'regulatory.action.register.view',
  'regulatory.action.closure_readiness.view',
  'regulatory.action.verification.view',
  'regulatory.action.effectiveness.view',
  'regulatory.action.sync_log.view',
  'regulatory.action.history.view',
  'regulatory.capa.view',
  'regulatory.review.view',
  'regulatory.report.view',
  'regulatory.history.view',
  'regulatory.settings.view'
];
const regulatoryManagePermissions = [
  ...regulatoryReadPermissions,
  'regulatory.item.create',
  'regulatory.item.edit',
  'regulatory.item.archive',
  'regulatory.item.reactivate',
  'regulatory.item.lock',
  'regulatory.item.unlock',
  'regulatory.item.assign_owner',
  'regulatory.item.change_status',
  'regulatory.item.change_applicability',
  'regulatory.item.change_compliance_status',
  'regulatory.jurisdiction.create',
  'regulatory.jurisdiction.edit',
  'regulatory.jurisdiction.archive',
  'regulatory.jurisdiction.reactivate',
  'regulatory.authority.create',
  'regulatory.authority.edit',
  'regulatory.authority.archive',
  'regulatory.authority.link',
  'regulatory.applicability.assessment.create',
  'regulatory.applicability.assessment.edit',
  'regulatory.applicability.assessment.submit',
  'regulatory.applicability.assessment.archive',
  'regulatory.applicability.decision.make',
  'regulatory.applicability.decision.review',
  'regulatory.applicability.decision.override',
  'regulatory.applicability.profile.create',
  'regulatory.applicability.profile.edit',
  'regulatory.applicability.profile.archive',
  'regulatory.applicability.criteria.manage',
  'regulatory.applicability.gap.manage',
  'regulatory.applicability.settings.edit',
  'regulatory.obligation.create',
  'regulatory.obligation.edit',
  'regulatory.obligation.archive',
  'regulatory.obligation.reactivate',
  'regulatory.obligation.lock',
  'regulatory.obligation.unlock',
  'regulatory.obligation.assign_owner',
  'regulatory.obligation.change_status',
  'regulatory.obligation.change_applicability',
  'regulatory.obligation.change_compliance_status',
  'regulatory.obligation.scope.manage',
  'regulatory.obligation.evidence_expectation.manage',
  'regulatory.obligation.module_mapping.manage',
  'regulatory.obligation.link.manage',
  'regulatory.obligation.gap.manage',
  'regulatory.obligation.settings.edit',
  'regulatory.compliance.assessment.create',
  'regulatory.compliance.assessment.edit',
  'regulatory.compliance.assessment.complete',
  'regulatory.compliance.assessment.archive',
  'regulatory.compliance.status.change',
  'regulatory.compliance.status.manual_declare',
  'regulatory.compliance.status.override',
  'regulatory.compliance.rollup.recalculate',
  'regulatory.compliance.evidence_readiness.manage',
  'regulatory.compliance.criteria.manage',
  'regulatory.compliance.gap.create',
  'regulatory.compliance.gap.edit',
  'regulatory.compliance.gap.resolve',
  'regulatory.compliance.gap.archive',
  'regulatory.compliance.gap.create_action_foundation',
  'regulatory.compliance.stale.reassess',
  'regulatory.compliance.settings.edit',
  'regulatory.scope.manage',
  'regulatory.link.manage',
  'regulatory.audit_mapping.link',
  'regulatory.audit_mapping.create',
  'regulatory.audit_mapping.edit',
  'regulatory.audit_mapping.archive',
  'regulatory.audit_mapping.verify',
  'regulatory.audit_mapping.reject',
  'regulatory.audit_mapping.recalculate',
  'regulatory.audit_mapping.mark_stale',
  'regulatory.audit_mapping.refresh_snapshot',
  'regulatory.audit_mapping.link_audit_program',
  'regulatory.audit_mapping.link_audit_plan',
  'regulatory.audit_mapping.link_checklist',
  'regulatory.audit_mapping.link_execution',
  'regulatory.audit_mapping.link_finding',
  'regulatory.audit_mapping.link_capa',
  'regulatory.audit_mapping.link_evidence',
  'regulatory.audit_mapping.link_score',
  'regulatory.audit_mapping.coverage.recalculate',
  'regulatory.audit_mapping.gap.create',
  'regulatory.audit_mapping.gap.edit',
  'regulatory.audit_mapping.gap.resolve',
  'regulatory.audit_mapping.gap.create_action_foundation',
  'regulatory.audit_mapping.review.submit',
  'regulatory.audit_mapping.settings.edit',
  'regulatory.evidence.link',
  'regulatory.evidence.requirement.create',
  'regulatory.evidence.requirement.edit',
  'regulatory.evidence.requirement.archive',
  'regulatory.evidence.link.create',
  'regulatory.evidence.link.edit',
  'regulatory.evidence.link.remove',
  'regulatory.evidence.link.replace',
  'regulatory.evidence.link.archive',
  'regulatory.evidence.upload',
  'regulatory.evidence.link_document',
  'regulatory.evidence.link_module_record',
  'regulatory.evidence.restricted.view',
  'regulatory.evidence.restricted.manage',
  'regulatory.evidence.review.submit',
  'regulatory.evidence.review.verify',
  'regulatory.evidence.review.reject',
  'regulatory.evidence.review.request_rework',
  'regulatory.evidence.request.create',
  'regulatory.evidence.request.fulfill',
  'regulatory.evidence.request.cancel',
  'regulatory.evidence.gap.create',
  'regulatory.evidence.gap.edit',
  'regulatory.evidence.gap.resolve',
  'regulatory.evidence.gap.create_action_foundation',
  'regulatory.evidence.package.prepare',
  'regulatory.evidence.package.include_restricted',
  'regulatory.evidence.settings.edit',
  'regulatory.action.link',
  'regulatory.action.create',
  'regulatory.action.link_existing',
  'regulatory.action.link_audit_capa',
  'regulatory.action.edit_link',
  'regulatory.action.archive_link',
  'regulatory.action.sync',
  'regulatory.action.refresh_snapshot',
  'regulatory.action.escalate',
  'regulatory.action.open_universal_action',
  'regulatory.action.closure_readiness.check',
  'regulatory.action.verification.submit',
  'regulatory.action.verification.fail',
  'regulatory.action.effectiveness.submit',
  'regulatory.action.settings.edit',
  'regulatory.capa.create',
  'regulatory.capa.edit',
  'regulatory.capa.archive',
  'regulatory.capa.add_source',
  'regulatory.capa.add_action',
  'regulatory.capa.close_foundation',
  'regulatory.capa.reopen',
  'regulatory.review.submit',
  'regulatory.settings.edit'
];
  const aliases: Record<string, string[]> = {
    'users:read': ['users.view'],
    'roles:manage': ['roles.view', 'roles.create', 'roles.edit', 'roles.assign', 'roles.manage', 'permissions.view', 'permissions.edit'],
    'roles.manage': ['roles.view', 'roles.create', 'roles.edit', 'roles.assign', 'permissions.view', 'permissions.edit'],
    'permissions.view': ['roles.view'],
    'permissions.edit': ['permissions.view', 'roles.view', 'roles.assign'],
    'users.edit': ['users.view'],
    'users.create': ['users.view'],
    'users.manage': ['users.view', 'users.create', 'users.edit', 'users.deactivate', 'users.reset_password', 'users.bulk_upload', 'users.invite', 'users.export'],
    'audit:read': ['audit.view', 'audit.dashboard.view'],
    'audit.view': ['audit:read', 'audit.dashboard.view'],
    'audit.dashboard.view': ['audit.view'],
    'training:read': ['training.view', 'training.dashboard.view', 'training.workforce.view', 'training.history.view', 'training.matrix.view', 'training.matrix.dashboard.view', 'training.competency.view', 'training.competency.dashboard.view', 'training.competency.profile.view', 'training.competency.library.view', 'training.competency.assignment.view', 'training.competency.gap.view', 'training.competency.settings.view', 'training.required.view', 'training.required.dashboard.view', 'training.required.library.view', 'training.required.history.view', 'training.required.settings.view', 'training.records.view', 'training.records.dashboard.view', 'training.records.session.view', 'training.records.roster.view', 'training.records.attendance.view', 'training.records.completion.view', 'training.records.history.view', 'training.records.settings.view', 'training.certifications.view', 'training.certifications.dashboard.view', 'training.certifications.settings.view', 'training.assessments.view', 'training.assessments.dashboard.view', 'training.assessments.library.view', 'training.assessments.settings.view', 'training.sop_ack.view', 'training.sop_ack.dashboard.view', 'training.sop_ack.requirement.view', 'training.sop_ack.assignment.view', 'training.sop_ack.waiver.view', 'training.sop_ack.history.view', 'training.sop_ack.settings.view', 'training.reports.view', 'training.reports.dashboard.view', 'training.reports.template.view', 'training.reports.package.view', 'training.reports.scheduled.view', 'training.reports.audit_evidence.view', 'training.reports.history.view', 'training.reports.settings.view', 'training.review.view', 'training.review.dashboard.view', 'training.review.inbox.view', 'training.review.submission.view', 'training.review.request.view', 'training.review.rule.view', 'training.review.history.view', 'training.review.settings.view'],
    'training.view': ['training.dashboard.view', 'training.workforce.view', 'training.history.view', 'training.matrix.view', 'training.matrix.dashboard.view', 'training.competency.view', 'training.competency.dashboard.view', 'training.competency.profile.view', 'training.competency.library.view', 'training.competency.assignment.view', 'training.competency.gap.view', 'training.competency.settings.view', 'training.required.view', 'training.required.dashboard.view', 'training.required.library.view', 'training.required.history.view', 'training.required.settings.view', 'training.records.view', 'training.records.dashboard.view', 'training.records.session.view', 'training.records.roster.view', 'training.records.attendance.view', 'training.records.completion.view', 'training.records.history.view', 'training.records.settings.view', 'training.certifications.view', 'training.certifications.dashboard.view', 'training.certifications.settings.view', 'training.assessments.view', 'training.assessments.dashboard.view', 'training.assessments.library.view', 'training.assessments.settings.view', 'training.sop_ack.view', 'training.sop_ack.dashboard.view', 'training.sop_ack.requirement.view', 'training.sop_ack.assignment.view', 'training.sop_ack.waiver.view', 'training.sop_ack.history.view', 'training.sop_ack.settings.view', 'training.reports.view', 'training.reports.dashboard.view', 'training.reports.template.view', 'training.reports.package.view', 'training.reports.scheduled.view', 'training.reports.audit_evidence.view', 'training.reports.history.view', 'training.reports.settings.view', 'training.review.view', 'training.review.dashboard.view', 'training.review.inbox.view', 'training.review.submission.view', 'training.review.request.view', 'training.review.rule.view', 'training.review.history.view', 'training.review.settings.view'],
    'training.dashboard.view': ['training.view', 'training.workforce.view', 'training.matrix.view', 'training.competency.view'],
    'training.workforce.view': ['training.view', 'training.dashboard.view'],
    'training.matrix.view': ['training.view', 'training.dashboard.view', 'training.matrix.dashboard.view'],
    'training.matrix.dashboard.view': ['training.view', 'training.dashboard.view', 'training.matrix.view'],
    'training.competency.view': ['training.view', 'training.dashboard.view', 'training.competency.dashboard.view', 'training.competency.profile.view', 'training.competency.library.view', 'training.competency.assignment.view', 'training.competency.gap.view', 'training.competency.settings.view', 'training.required.view', 'training.required.dashboard.view', 'training.required.library.view', 'training.required.history.view', 'training.required.settings.view', 'training.records.view', 'training.records.dashboard.view'],
    'training.competency.dashboard.view': ['training.view', 'training.dashboard.view', 'training.competency.view', 'training.competency.profile.view'],
    'training.competency.profile.view': ['training.view', 'training.dashboard.view', 'training.competency.view'],
    'training.competency.library.view': ['training.view', 'training.dashboard.view', 'training.competency.view'],
    'training.competency.assignment.view': ['training.view', 'training.dashboard.view', 'training.competency.view'],
    'training.competency.gap.view': ['training.view', 'training.dashboard.view', 'training.competency.view'],
    'training.records.view': ['training.view', 'training.dashboard.view', 'training.records.dashboard.view', 'training.records.session.view', 'training.records.roster.view', 'training.records.attendance.view', 'training.records.completion.view', 'training.records.history.view', 'training.records.settings.view'],
    'training.records.dashboard.view': ['training.view', 'training.records.view', 'training.records.session.view', 'training.records.completion.view'],
    'training.records.session.view': ['training.view', 'training.records.view', 'training.records.roster.view', 'training.records.attendance.view', 'training.records.completion.view'],
    'training.records.completion.view': ['training.view', 'training.records.view', 'training.records.evidence.link'],
    'equipment:read': ['equipment.view', 'mechanical_integrity.dashboard.view', 'mechanical_integrity.equipment.view', 'mechanical_integrity.technical_data.view', 'mechanical_integrity.technical_data.revision.view', 'mechanical_integrity.criticality.view', 'mechanical_integrity.readiness.view', 'mechanical_integrity.linked_records.view', 'mechanical_integrity.linked_record.view', 'mechanical_integrity.documents.view', 'mechanical_integrity.document_link.view', 'mechanical_integrity.document_requirement.view', 'mechanical_integrity.history.view', 'mechanical_integrity.report.view', 'mechanical_integrity.export.view', 'mechanical_integrity.cml.view', 'mechanical_integrity.cml_reading.view', 'mechanical_integrity.cml_calculation.view', 'mechanical_integrity.cml_alert.view', ...miInspectionReadPermissions],
    'equipment.view': ['mechanical_integrity.dashboard.view', 'mechanical_integrity.equipment.view', 'mechanical_integrity.technical_data.view', 'mechanical_integrity.technical_data.revision.view', 'mechanical_integrity.criticality.view', 'mechanical_integrity.readiness.view', 'mechanical_integrity.linked_records.view', 'mechanical_integrity.linked_record.view', 'mechanical_integrity.documents.view', 'mechanical_integrity.document_link.view', 'mechanical_integrity.document_requirement.view', 'mechanical_integrity.history.view', 'mechanical_integrity.report.view', 'mechanical_integrity.export.view', 'mechanical_integrity.cml.view', 'mechanical_integrity.cml_reading.view', 'mechanical_integrity.cml_calculation.view', 'mechanical_integrity.cml_alert.view', ...miInspectionReadPermissions],
    'equipment:manage': ['equipment.create', 'equipment.edit', 'equipment.upload', 'equipment.qr.generate', 'mechanical_integrity.equipment.create', 'mechanical_integrity.equipment.edit', 'mechanical_integrity.equipment.archive', 'mechanical_integrity.equipment.import', 'mechanical_integrity.equipment.export', 'mechanical_integrity.technical_data.edit', 'mechanical_integrity.technical_data.revision.view', 'mechanical_integrity.criticality.edit', 'mechanical_integrity.readiness.edit', 'mechanical_integrity.linked_records.manage', 'mechanical_integrity.linked_record.create', 'mechanical_integrity.linked_record.edit', 'mechanical_integrity.linked_record.remove', 'mechanical_integrity.documents.manage', 'mechanical_integrity.document_link.create', 'mechanical_integrity.document_link.remove', 'mechanical_integrity.document_requirement.manage', 'mechanical_integrity.report.generate', 'mechanical_integrity.report.export', 'mechanical_integrity.export.create', 'mechanical_integrity.export.download', 'mechanical_integrity.cml.create', 'mechanical_integrity.cml.edit', 'mechanical_integrity.cml.archive', 'mechanical_integrity.cml.import', 'mechanical_integrity.cml.export', 'mechanical_integrity.cml_reading.create', 'mechanical_integrity.cml_reading.edit', 'mechanical_integrity.cml_reading.review', 'mechanical_integrity.cml_reading.approve', 'mechanical_integrity.cml_reading.import', 'mechanical_integrity.cml_calculation.recalculate', 'mechanical_integrity.cml_calculation.override', 'mechanical_integrity.cml_alert.acknowledge', 'mechanical_integrity.cml_alert.resolve', 'mechanical_integrity.export', ...miInspectionManagePermissions],
    'mechanical_integrity:read': ['mechanical_integrity.dashboard.view', 'mechanical_integrity.equipment.view', 'mechanical_integrity.technical_data.view', 'mechanical_integrity.technical_data.revision.view', 'mechanical_integrity.criticality.view', 'mechanical_integrity.readiness.view', 'mechanical_integrity.linked_records.view', 'mechanical_integrity.linked_record.view', 'mechanical_integrity.documents.view', 'mechanical_integrity.document_link.view', 'mechanical_integrity.document_requirement.view', 'mechanical_integrity.history.view', 'mechanical_integrity.history.view_audit', 'mechanical_integrity.report.view', 'mechanical_integrity.export.view', 'mechanical_integrity.cml.view', 'mechanical_integrity.cml_reading.view', 'mechanical_integrity.cml_calculation.view', 'mechanical_integrity.cml_alert.view', ...miInspectionReadPermissions],
    'mechanical_integrity:manage': ['mechanical_integrity.dashboard.view', 'mechanical_integrity.equipment.view', 'mechanical_integrity.equipment.create', 'mechanical_integrity.equipment.edit', 'mechanical_integrity.equipment.archive', 'mechanical_integrity.equipment.import', 'mechanical_integrity.equipment.export', 'mechanical_integrity.equipment.history.view', 'mechanical_integrity.technical_data.view', 'mechanical_integrity.technical_data.edit', 'mechanical_integrity.technical_data.revision.view', 'mechanical_integrity.criticality.view', 'mechanical_integrity.criticality.edit', 'mechanical_integrity.readiness.view', 'mechanical_integrity.readiness.edit', 'mechanical_integrity.linked_records.view', 'mechanical_integrity.linked_records.manage', 'mechanical_integrity.linked_record.view', 'mechanical_integrity.linked_record.create', 'mechanical_integrity.linked_record.edit', 'mechanical_integrity.linked_record.remove', 'mechanical_integrity.documents.view', 'mechanical_integrity.documents.manage', 'mechanical_integrity.document_link.view', 'mechanical_integrity.document_link.create', 'mechanical_integrity.document_link.remove', 'mechanical_integrity.document_requirement.view', 'mechanical_integrity.document_requirement.manage', 'mechanical_integrity.history.view', 'mechanical_integrity.history.view_audit', 'mechanical_integrity.history.export', 'mechanical_integrity.report.view', 'mechanical_integrity.report.generate', 'mechanical_integrity.report.manage_templates', 'mechanical_integrity.report.schedule', 'mechanical_integrity.report.export', 'mechanical_integrity.export.view', 'mechanical_integrity.export.create', 'mechanical_integrity.export.download', 'mechanical_integrity.export.include_documents', 'mechanical_integrity.export.include_audit', 'mechanical_integrity.export.site_export', 'mechanical_integrity.export.admin_all', 'mechanical_integrity.export', ...miInspectionManagePermissions],
    'actions:read': ['actions.view'],
    'actions:manage': ['actions.create', 'actions.edit', 'actions.assign', 'actions.close', 'actions.verify', 'actions.delete', 'actions.export'],
    'documents:read': ['documents.view'],
    'documents:manage': ['documents.upload', 'documents.edit', 'documents.delete', 'documents.approve', 'documents.archive', 'documents.download', 'documents.link', 'documents.comment'],
    'notifications:read': ['notifications.view'],
    'notifications:manage': ['notifications.view', 'notifications.manage', 'notifications.preferences', 'notifications.test'],
    'search:use': ['search.use'],
    'search:manage': ['search.use', 'search.reindex'],
    'settings.manage': ['settings.view', 'company.view', 'company.create', 'company.edit', 'company.manage', 'company.domain.view', 'company.domain.manage', 'company.audit.view', 'site.view', 'site.create', 'site.edit', 'site.delete', 'site.manage', 'department.view', 'department.create', 'department.edit', 'department.delete', 'department.manage', 'unit.view', 'unit.create', 'unit.edit', 'unit.delete', 'unit.manage', 'area.view', 'area.create', 'area.edit', 'area.delete', 'area.manage', 'tenant.context.view', 'tenant.switch_company', 'tenant.switch_site'],
    'company.manage': ['company.view', 'company.create', 'company.edit', 'company.domain.view', 'company.domain.manage', 'company.audit.view', 'tenant.context.view'],
    'billing.manage': ['billing.view', 'billing.checkout', 'billing.plan.view', 'billing.plan.change', 'billing.cancel', 'billing.reactivate', 'billing.payment_method.view', 'billing.payment_method.manage', 'billing.invoice.view', 'billing.invoice.download', 'billing.usage.view', 'billing.usage.export', 'billing.audit.view', 'entitlements.view'],
    'billing.view': ['billing.plan.view', 'billing.payment_method.view', 'billing.invoice.view', 'billing.usage.view', 'entitlements.view'],
    'platform.billing.manage': ['platform.billing.view', 'platform.plans.view', 'platform.plans.manage', 'platform.webhooks.view', 'platform.webhooks.replay', 'entitlements.override'],
    'platform.billing.view': ['platform.plans.view', 'platform.webhooks.view'],
    'site.manage': ['site.view', 'site.create', 'site.edit', 'site.delete', 'department.view', 'department.create', 'department.edit', 'department.delete', 'unit.view', 'unit.create', 'unit.edit', 'unit.delete', 'area.view', 'area.create', 'area.edit', 'area.delete', 'tenant.context.view', 'tenant.switch_site'],
    'department.manage': ['department.view', 'department.create', 'department.edit', 'department.delete'],
    'unit.manage': ['unit.view', 'unit.create', 'unit.edit', 'unit.delete'],
    'area.manage': ['area.view', 'area.create', 'area.edit', 'area.delete'],
    'users:manage': ['users.create', 'users.edit', 'signature.profile.view', 'signature.profile.create', 'signature.profile.edit', 'signature.pin.set', 'signature.pin.change', 'signature.sign', 'signature.reject', 'signature.view', 'signature.requirements.manage', 'signature.audit.view'],
    'ptw:read': ['ptw.view', 'ptw.map.view'],
    'ptw.view': ['ptw.map.view'],
    'ptw.workforce.manage': ['ptw.workforce.view', 'ptw.workforce.add', 'ptw.workforce.edit', 'ptw.workforce.delete', 'ptw.workforce.briefing', 'ptw.workforce.sign_in', 'ptw.workforce.sign_out', 'ptw.workforce.accountability'],
    'ptw:manage': ['ptw.view', 'ptw.create', 'ptw.edit', 'ptw.submit', 'ptw.approve', 'ptw.issue', 'ptw.activate', 'ptw.suspend', 'ptw.extend', 'ptw.close', 'ptw.cancel', 'ptw.gas_test.view', 'ptw.gas_test.add', 'ptw.gas_test.edit', 'ptw.gas_test.delete', 'ptw.gas_test.validate', 'ptw.gas_thresholds.manage', 'ptw.isolation.add', 'ptw.isolation.edit', 'ptw.isolation.delete', 'ptw.isolation.confirm', 'ptw.isolation.verify', 'ptw.isolation.certificate.generate', 'ptw.deisolation.confirm', 'ptw.conflict.override', 'ptw.conflict.view', 'ptw.conflict.check', 'ptw.conflict.resolve', 'ptw.conflict.override.request', 'ptw.conflict.override.approve', 'ptw.conflict.false_positive', 'ptw.simops.view', 'ptw.simops.create', 'ptw.simops.approve', 'ptw.conflict_matrix.manage', 'ptw.signatures.view', 'ptw.signatures.sign', 'ptw.handover.sign', 'ptw.gas.sign', 'ptw.isolation.sign', 'ptw.close.sign', 'signature.sign', 'signature.view', 'ptw.signatures.reject', 'ptw.signatures.revalidate', 'ptw.signature_requirements.manage', 'ptw.attachments.view', 'ptw.attachments.upload', 'ptw.attachments.preview', 'ptw.attachments.download', 'ptw.attachments.delete', 'ptw.attachment_requirements.manage', 'ptw.handover', 'ptw.handover.view', 'ptw.handover.create', 'ptw.handover.edit', 'ptw.handover.acknowledge', 'ptw.handover.complete', 'ptw.handover.suspend', 'ptw.handover.delete', 'ptw.workforce.view', 'ptw.workforce.add', 'ptw.workforce.edit', 'ptw.workforce.delete', 'ptw.workforce.briefing', 'ptw.workforce.sign_in', 'ptw.workforce.sign_out', 'ptw.workforce.accountability', 'ptw.workforce.manage', 'ptw.template.manage', 'ptw.export', 'ptw.map.view', 'ptw.map.manage_layouts', 'ptw.map.manage_zones', 'ptw.map.manage_markers'],
    'ptw.handover': ['ptw.handover.view', 'ptw.handover.create', 'ptw.handover.edit', 'ptw.handover.acknowledge', 'ptw.handover.complete', 'ptw.handover.suspend', 'ptw.handover.delete'],
    'moc:read': ['moc.view', 'moc.dashboard.view'],
    'moc:manage': ['moc.view', 'moc.dashboard.view', 'moc.create', 'moc.edit', 'moc.submit', 'moc.approve', 'moc.workflow.sign', 'moc.approval.sign', 'moc.close.sign', 'signature.sign', 'signature.view', 'moc.reject', 'moc.return', 'moc.implementation.start', 'moc.implementation.complete', 'moc.ready_for_startup', 'moc.close', 'moc.cancel', 'moc.export', 'moc.approval_queue.view', 'moc.temporary_dashboard.view', 'moc.emergency_dashboard.view', 'moc.risk_dashboard.view', 'moc.temporary.extend', 'moc.pssr.trigger', 'moc.upload_documents', 'moc.attachments.upload', 'moc.generate_actions', 'moc.workflow.view', 'moc.workflow.start', 'moc.workflow.approve', 'moc.workflow.reject', 'moc.workflow.return', 'moc.workflow.delegate', 'moc.workflow.escalate', 'moc.workflow.restart', 'moc.temporary.view', 'moc.temporary.edit', 'moc.temporary.approve_extension', 'moc.temporary.close', 'moc.emergency.view', 'moc.emergency.edit', 'moc.emergency.review', 'moc.emergency.convert', 'moc.pssr.view', 'moc.pssr.sync', 'moc.startup.view', 'moc.startup.check', 'moc.release_for_startup', 'moc.return_to_implementation', 'moc.communication.view', 'moc.communication.edit', 'moc.communication.send', 'moc.acknowledgement.view', 'moc.acknowledgement.acknowledge', 'moc.acknowledgement.waive', 'moc.training.view', 'moc.training.create', 'moc.training.complete', 'moc.training.verify', 'moc.training.waive', 'moc.history.view', 'moc.history.export', 'moc.attachments.view', 'moc.attachments.preview', 'moc.attachments.download', 'moc.attachments.delete', 'moc.attachments.link_document', 'moc.report.download'],
    'pssr:read': ['pssr.view'],
    'pssr:manage': ['pssr.view', 'pssr.create', 'pssr.edit', 'pssr.submit', 'pssr.start_preparation', 'pssr.start_review', 'pssr.field_verification', 'pssr.generate_checklist', 'pssr.readiness_check', 'pssr.authorize_startup', 'pssr.authorization.sign', 'pssr.discipline_signoff.sign', 'pssr.certificate.sign', 'signature.sign', 'signature.view', 'pssr.release_startup', 'pssr.close', 'pssr.cancel', 'pssr.trigger_from_moc', 'pssr.sync_moc', 'pssr.report.download'],
    'hazop:read': ['hazop.dashboard.view', 'hazop.view', 'hazop.node.view', 'hazop.scenario.view', 'hazop.recommendation.view'],
    'hazop.view': ['hazop.dashboard.view', 'hazop.node.view', 'hazop.scenario.view', 'hazop.recommendation.view'],
    'hazop:manage': ['hazop.dashboard.view', 'hazop.view', 'hazop.create', 'hazop.edit', 'hazop.delete', 'hazop.cancel', 'hazop.close', 'hazop.node.view', 'hazop.node.create', 'hazop.node.edit', 'hazop.node.delete', 'hazop.scenario.view', 'hazop.scenario.create', 'hazop.scenario.edit', 'hazop.scenario.delete', 'hazop.risk.edit', 'hazop.recommendation.view', 'hazop.recommendation.create', 'hazop.recommendation.edit', 'hazop.recommendation.close', 'hazop.action.create', 'hazop.team.manage', 'hazop.session.manage', 'hazop.sign', 'hazop.approve', 'hazop.attachments.upload', 'hazop.attachments.download', 'hazop.export', 'hazop.config.manage', 'signature.sign', 'signature.view'],
    'psi:read': ['psi.view', 'psi.dashboard.view', 'psi.unit.view', 'psi.completeness.view', 'psi.linked_record.view', 'psi.document.view', 'psi.change_history.view', 'psi.chemical.view', 'psi.process_chemistry.view', 'psi.safe_limit.view', 'psi.equipment_design.view', 'psi.relief_system.view', 'psi.drawing.view', 'psi.electrical_classification.view', 'psi.review.view', 'psi.review.dashboard.view', 'psi.review.inbox.view', 'psi.review.snapshot.view', 'psi.review.history.view', 'psi.review.rule.view', 'psi.review.settings.view', 'psi.report.view', 'psi.report.dashboard.view', 'psi.report.template.view', 'psi.report.download', 'psi.export.view', 'psi.export.download', 'psi.scheduled_report.view', 'psi.report.settings.view'],
    'psi.view': ['psi.dashboard.view', 'psi.unit.view', 'psi.completeness.view', 'psi.linked_record.view', 'psi.document.view', 'psi.change_history.view', 'psi.chemical.view', 'psi.process_chemistry.view', 'psi.safe_limit.view', 'psi.equipment_design.view', 'psi.relief_system.view', 'psi.drawing.view', 'psi.electrical_classification.view', 'psi.review.view', 'psi.review.dashboard.view', 'psi.review.inbox.view', 'psi.review.snapshot.view', 'psi.review.history.view', 'psi.review.rule.view', 'psi.review.settings.view', 'psi.report.view', 'psi.report.dashboard.view', 'psi.report.template.view', 'psi.report.download', 'psi.export.view', 'psi.export.download', 'psi.scheduled_report.view', 'psi.report.settings.view'],
    'psi.unit.view': ['psi.dashboard.view', 'psi.process_chemistry.view', 'psi.chemical.view', 'psi.safe_limit.view', 'psi.equipment_design.view', 'psi.relief_system.view', 'psi.drawing.view', 'psi.electrical_classification.view'],
    'psi:manage': ['psi.view', 'psi.dashboard.view', 'psi.unit.view', 'psi.unit.create', 'psi.unit.edit', 'psi.unit.archive', 'psi.unit.submit_review', 'psi.unit.approve', 'psi.unit.reject', 'psi.completeness.view', 'psi.completeness.run', 'psi.completeness.manage_requirements', 'psi.linked_record.view', 'psi.linked_record.create', 'psi.linked_record.remove', 'psi.document.view', 'psi.document.link', 'psi.document.remove', 'psi.change_history.view', 'psi.export', 'psi.chemical.view', 'psi.chemical.create', 'psi.chemical.edit', 'psi.chemical.archive', 'psi.chemical.import', 'psi.chemical.export', 'psi.chemical.link_sds', 'psi.chemical.remove_sds', 'psi.chemical.waive_sds', 'psi.chemical.approve_sds_waiver', 'psi.chemical.run_sds_check', 'psi.chemical.run_compatibility_check', 'psi.chemical.submit_review', 'psi.chemical.approve', 'psi.chemical.reject', 'psi.process_chemistry.view', 'psi.process_chemistry.create', 'psi.process_chemistry.edit', 'psi.process_chemistry.archive', 'psi.process_chemistry.import', 'psi.process_chemistry.export', 'psi.process_chemistry.link_chemical', 'psi.process_chemistry.remove_chemical', 'psi.process_chemistry.manage_conditions', 'psi.process_chemistry.manage_hazards', 'psi.process_chemistry.manage_scenarios', 'psi.process_chemistry.manage_controls', 'psi.process_chemistry.run_completeness_check', 'psi.process_chemistry.submit_review', 'psi.process_chemistry.approve', 'psi.process_chemistry.reject', 'psi.safe_limit.view', 'psi.safe_limit.create', 'psi.safe_limit.edit', 'psi.safe_limit.archive', 'psi.safe_limit.import', 'psi.safe_limit.export', 'psi.safe_limit.manage_values', 'psi.safe_limit.manage_consequences', 'psi.safe_limit.manage_operator_response', 'psi.safe_limit.manage_safeguards', 'psi.safe_limit.link_document', 'psi.safe_limit.remove_document', 'psi.safe_limit.run_completeness_check', 'psi.safe_limit.run_conflict_check', 'psi.safe_limit.submit_review', 'psi.safe_limit.approve', 'psi.safe_limit.reject', 'psi.safe_limit.override_conflict', 'psi.equipment_design.view', 'psi.equipment_design.create', 'psi.equipment_design.edit', 'psi.equipment_design.archive', 'psi.equipment_design.import', 'psi.equipment_design.export', 'psi.equipment_design.manage_ratings', 'psi.equipment_design.manage_service_basis', 'psi.equipment_design.manage_material_basis', 'psi.equipment_design.manage_capacity_basis', 'psi.equipment_design.manage_codes', 'psi.equipment_design.manage_assumptions', 'psi.equipment_design.link_document', 'psi.equipment_design.remove_document', 'psi.equipment_design.sync_mi', 'psi.equipment_design.run_completeness_check', 'psi.equipment_design.run_conflict_check', 'psi.equipment_design.submit_review', 'psi.equipment_design.approve', 'psi.equipment_design.reject', 'psi.equipment_design.override_conflict', 'psi.relief_system.view', 'psi.relief_system.create', 'psi.relief_system.edit', 'psi.relief_system.archive', 'psi.relief_system.import', 'psi.relief_system.export', 'psi.relief_system.manage_protected_equipment', 'psi.relief_system.link_device', 'psi.relief_system.remove_device', 'psi.relief_system.manage_scenarios', 'psi.relief_system.manage_sizing_basis', 'psi.relief_system.manage_discharge_destination', 'psi.relief_system.link_document', 'psi.relief_system.remove_document', 'psi.relief_system.sync_mi', 'psi.relief_system.run_completeness_check', 'psi.relief_system.run_conflict_check', 'psi.relief_system.submit_review', 'psi.relief_system.approve', 'psi.relief_system.reject', 'psi.relief_system.override_conflict', 'psi.drawing.view', 'psi.drawing.create', 'psi.drawing.edit', 'psi.drawing.archive', 'psi.drawing.import', 'psi.drawing.export', 'psi.drawing.link_document', 'psi.drawing.remove_document', 'psi.drawing.manage_scope', 'psi.drawing.manage_relationships', 'psi.drawing.manage_tag_index', 'psi.drawing.import_tag_index', 'psi.drawing.manage_redlines', 'psi.drawing.verify_as_built', 'psi.drawing.run_completeness_check', 'psi.drawing.run_conflict_check', 'psi.drawing.submit_review', 'psi.drawing.approve', 'psi.drawing.reject', 'psi.drawing.override_conflict', 'psi.electrical_classification.view', 'psi.electrical_classification.create', 'psi.electrical_classification.edit', 'psi.electrical_classification.archive', 'psi.electrical_classification.import', 'psi.electrical_classification.export', 'psi.electrical_classification.manage_hazard_sources', 'psi.electrical_classification.manage_area_details', 'psi.electrical_classification.manage_ventilation_basis', 'psi.electrical_classification.manage_protection_requirements', 'psi.electrical_classification.manage_installed_equipment', 'psi.electrical_classification.run_rating_check', 'psi.electrical_classification.link_document', 'psi.electrical_classification.remove_document', 'psi.electrical_classification.manage_ptw_controls', 'psi.electrical_classification.run_completeness_check', 'psi.electrical_classification.run_conflict_check', 'psi.electrical_classification.submit_review', 'psi.electrical_classification.approve', 'psi.electrical_classification.reject', 'psi.electrical_classification.override_conflict'],
    'psi.unit.edit': ['psi.process_chemistry.create', 'psi.process_chemistry.edit', 'psi.process_chemistry.manage_conditions', 'psi.process_chemistry.manage_hazards', 'psi.process_chemistry.manage_scenarios', 'psi.process_chemistry.manage_controls', 'psi.safe_limit.create', 'psi.safe_limit.edit', 'psi.safe_limit.manage_values', 'psi.safe_limit.manage_consequences', 'psi.safe_limit.manage_operator_response', 'psi.safe_limit.manage_safeguards', 'psi.safe_limit.run_completeness_check', 'psi.safe_limit.run_conflict_check', 'psi.equipment_design.create', 'psi.equipment_design.edit', 'psi.equipment_design.manage_ratings', 'psi.equipment_design.manage_service_basis', 'psi.equipment_design.manage_material_basis', 'psi.equipment_design.manage_capacity_basis', 'psi.equipment_design.manage_codes', 'psi.equipment_design.manage_assumptions', 'psi.equipment_design.run_completeness_check', 'psi.equipment_design.run_conflict_check', 'psi.relief_system.create', 'psi.relief_system.edit', 'psi.relief_system.manage_protected_equipment', 'psi.relief_system.link_device', 'psi.relief_system.manage_scenarios', 'psi.relief_system.manage_sizing_basis', 'psi.relief_system.manage_discharge_destination', 'psi.relief_system.run_completeness_check', 'psi.relief_system.run_conflict_check', 'psi.drawing.create', 'psi.drawing.edit', 'psi.drawing.manage_scope', 'psi.drawing.manage_relationships', 'psi.drawing.manage_tag_index', 'psi.drawing.manage_redlines', 'psi.drawing.run_completeness_check', 'psi.drawing.run_conflict_check', 'psi.electrical_classification.create', 'psi.electrical_classification.edit', 'psi.electrical_classification.manage_hazard_sources', 'psi.electrical_classification.manage_area_details', 'psi.electrical_classification.manage_ventilation_basis', 'psi.electrical_classification.manage_protection_requirements', 'psi.electrical_classification.manage_installed_equipment', 'psi.electrical_classification.run_rating_check', 'psi.electrical_classification.manage_ptw_controls', 'psi.electrical_classification.run_completeness_check', 'psi.electrical_classification.run_conflict_check'],
    'psi.chemical.view': ['psi.view', 'psi.dashboard.view', 'psi.process_chemistry.view'],
    'psi.process_chemistry.view': ['psi.view', 'psi.dashboard.view'],
    'psi.safe_limit.view': ['psi.view', 'psi.dashboard.view'],
    'psi.equipment_design.view': ['psi.view', 'psi.dashboard.view'],
    'psi.relief_system.view': ['psi.view', 'psi.dashboard.view'],
    'psi.drawing.view': ['psi.view', 'psi.dashboard.view'],
    'psi.electrical_classification.view': ['psi.view', 'psi.dashboard.view'],
    'incidents:read': ['incidents.view', 'incidents.register.view', 'incidents.summary.view', 'incidents.detail.view', 'incidents.overview.view', 'incidents.event_details.view', 'incidents.classification.view', 'incidents.severity.view', 'incidents.risk_matrix.view', 'incidents.people.view', 'incidents.injury.view', 'incidents.exposure.view', 'incidents.assets.view', 'incidents.release.view', 'incidents.safeguards.view', 'incidents.sds.view', 'incidents.timeline.view', 'incidents.evidence.view', 'incidents.immediate_actions.view', 'incidents.team.view', 'incidents.rca.view', 'incidents.barriers.view', 'incidents.capa.view', 'incidents.linked_records.view', 'incidents.notifications_reporting.view', 'incidents.reporting.view', 'incidents.review_approval.view', 'incidents.lessons.view', 'incidents.history.view', 'incidents.audit_trail.view', 'incidents.final_report.view'],
    'incidents:manage': ['incidents.view', 'incidents.register.view', 'incidents.summary.view', 'incidents.create', 'incidents.draft.create', 'incidents.draft.edit', 'incidents.draft.delete', 'incidents.submit', 'incidents.edit', 'incidents.edit_basic', 'incidents.event_details.view', 'incidents.event_details.edit', 'incidents.classification.view', 'incidents.classification.edit', 'incidents.classification.review.request', 'incidents.classification.review.approve', 'incidents.classification.review.reject', 'incidents.people.view', 'incidents.people.edit', 'incidents.people.delete', 'incidents.people.review.request', 'incidents.people.review.approve', 'incidents.people.review.reject', 'incidents.injury.view', 'incidents.injury.edit', 'incidents.exposure.view', 'incidents.exposure.edit', 'incidents.assets.view', 'incidents.assets.edit', 'incidents.assets.delete', 'incidents.release.view', 'incidents.release.edit', 'incidents.safeguards.view', 'incidents.safeguards.edit', 'incidents.asset.review.request', 'incidents.asset.review.approve', 'incidents.asset.review.reject', 'incidents.timeline.view', 'incidents.timeline.edit', 'incidents.timeline.delete', 'incidents.timeline.review.request', 'incidents.timeline.review.approve', 'incidents.timeline.review.reject', 'incidents.timeline.gaps.manage', 'incidents.evidence.view', 'incidents.evidence.upload', 'incidents.evidence.edit', 'incidents.evidence.delete', 'incidents.evidence.preview', 'incidents.evidence.download', 'incidents.evidence.version.manage', 'incidents.evidence.mapping.manage', 'incidents.evidence.custody.manage', 'incidents.evidence.review.request', 'incidents.evidence.review.approve', 'incidents.evidence.review.reject', 'incidents.evidence.export_index', 'incidents.document_links.manage', 'incidents.immediate_actions.view', 'incidents.immediate_actions.edit', 'incidents.immediate_actions.delete', 'incidents.immediate_actions.verify', 'incidents.immediate_actions.review.request', 'incidents.immediate_actions.review.approve', 'incidents.immediate_actions.review.reject', 'incidents.site_safety.verify', 'incidents.restart_control.manage', 'incidents.temporary_controls.manage', 'incidents.capa.convert', 'incidents.capa.view', 'incidents.capa.create', 'incidents.capa.edit', 'incidents.capa.delete', 'incidents.capa.generate', 'incidents.capa.link_source', 'incidents.capa.link_evidence', 'incidents.capa.complete', 'incidents.capa.verify', 'incidents.capa.escalate', 'incidents.capa.review.request', 'incidents.capa.review.approve', 'incidents.capa.review.reject', 'incidents.capa.export', 'incidents.actions.link', 'incidents.linked_records.view', 'incidents.linked_records.create', 'incidents.linked_records.edit', 'incidents.linked_records.delete', 'incidents.linked_records.auto_detect', 'incidents.linked_records.refresh', 'incidents.linked_records.export', 'incidents.linked_records.review.request', 'incidents.linked_records.review.approve', 'incidents.linked_records.review.reject', 'incidents.record_impacts.manage', 'incidents.notifications_reporting.view', 'incidents.notifications.send', 'incidents.notifications.resend', 'incidents.notifications.acknowledge', 'incidents.reporting.view', 'incidents.reporting.determine', 'incidents.reporting.edit', 'incidents.reporting.generate_package', 'incidents.reporting.submit', 'incidents.reporting.acknowledge', 'incidents.reporting.override', 'incidents.reporting.review.request', 'incidents.reporting.review.approve', 'incidents.reporting.review.reject', 'incidents.reporting.export', 'incidents.review_approval.view', 'incidents.review_approval.start_workflow', 'incidents.review_approval.add_reviewer', 'incidents.review_approval.edit_reviewer', 'incidents.review_approval.remove_reviewer', 'incidents.review_approval.approve', 'incidents.review_approval.reject', 'incidents.review_approval.request_changes', 'incidents.review_approval.delegate', 'incidents.review_approval.escalate', 'incidents.review_approval.override_blocker', 'incidents.review_approval.e_sign', 'incidents.review_approval.request_closure', 'incidents.review_approval.close', 'incidents.review_approval.reopen', 'incidents.lessons.view', 'incidents.lessons.create', 'incidents.lessons.edit', 'incidents.lessons.delete', 'incidents.lessons.generate', 'incidents.lessons.distribute', 'incidents.lessons.verify', 'incidents.lessons.review.request', 'incidents.lessons.review.approve', 'incidents.lessons.review.reject', 'incidents.history.view', 'incidents.history.export', 'incidents.audit_trail.view', 'incidents.access_history.view', 'incidents.team.view', 'incidents.team.edit', 'incidents.team.delete', 'incidents.team.owner.assign', 'incidents.team.lead.assign', 'incidents.team.member.add', 'incidents.team.member.replace', 'incidents.team.member.remove', 'incidents.team.required_roles.generate', 'incidents.team.acceptance.manage', 'incidents.team.approval.request', 'incidents.team.approval.approve', 'incidents.team.approval.reject', 'incidents.team.raci.manage', 'incidents.team.competency.manage', 'incidents.team.conflict.manage', 'incidents.team.availability.manage', 'incidents.team.notifications.send', 'incidents.team.review.request', 'incidents.team.review.approve', 'incidents.team.review.reject', 'incidents.rca.view', 'incidents.rca.edit', 'incidents.rca.method.select', 'incidents.rca.causal_factors.create', 'incidents.rca.causal_factors.edit', 'incidents.rca.causal_factors.delete', 'incidents.rca.root_causes.create', 'incidents.rca.root_causes.edit', 'incidents.rca.root_causes.delete', 'incidents.rca.evidence.map', 'incidents.rca.hypotheses.manage', 'incidents.rca.quality.override', 'incidents.rca.create_capa', 'incidents.rca.complete', 'incidents.rca.reopen', 'incidents.rca.review.request', 'incidents.rca.review.approve', 'incidents.rca.review.reject', 'incidents.barriers.view', 'incidents.barriers.edit', 'incidents.barriers.delete', 'incidents.barriers.import', 'incidents.barriers.evidence.map', 'incidents.barriers.rca.link', 'incidents.barriers.followups.create', 'incidents.barriers.review.request', 'incidents.barriers.review.approve', 'incidents.barriers.review.reject', 'incidents.barriers.ipl.view', 'incidents.barriers.sis_sif.view', 'incidents.barriers.override', 'incidents.followups.create', 'incidents.assign', 'incidents.status.change', 'incidents.close', 'incidents.reopen', 'incidents.bulk_update', 'incidents.export', 'incidents.export_summary', 'incidents.psm.view', 'incidents.psm.classify', 'incidents.psm.review', 'incidents.psm.review.request', 'incidents.severity.view', 'incidents.severity.edit', 'incidents.severity.recalculate', 'incidents.severity.review', 'incidents.severity.review.request', 'incidents.severity.review.approve', 'incidents.severity.review.reject', 'incidents.risk_matrix.view', 'incidents.actions.create', 'incidents.detail.view', 'incidents.overview.view', 'users.profiles.view', 'users.profiles.invite', 'users.profiles.create'],
    'incidents.create': ['incidents.draft.create', 'incidents.draft.edit', 'incidents.submit', 'incidents.evidence.upload', 'incidents.psm.classify'],
    'incidents.final_report.manage': ['incidents.final_report.view', 'incidents.final_report.configure', 'incidents.final_report.preview', 'incidents.final_report.generate', 'incidents.final_report.download', 'incidents.final_report.export', 'incidents.final_report.mark_official', 'incidents.final_report.publish', 'incidents.final_report.supersede', 'incidents.final_report.archive', 'incidents.final_report.review.request', 'incidents.final_report.review.approve', 'incidents.final_report.review.reject', 'incidents.evidence.export_package'],
    'incidents.edit': ['incidents.edit_basic', 'incidents.event_details.edit', 'incidents.classification.edit', 'incidents.classification.review.request', 'incidents.severity.edit', 'incidents.severity.recalculate', 'incidents.severity.review.request', 'incidents.people.edit', 'incidents.injury.edit', 'incidents.exposure.edit', 'incidents.assets.edit', 'incidents.release.edit', 'incidents.safeguards.edit', 'incidents.timeline.edit', 'incidents.evidence.edit', 'incidents.immediate_actions.edit', 'incidents.team.edit', 'incidents.team.member.add', 'incidents.team.member.replace', 'incidents.team.member.remove', 'incidents.team.acceptance.manage', 'incidents.team.notifications.send', 'incidents.rca.edit', 'incidents.barriers.edit', 'incidents.capa.edit', 'incidents.linked_records.edit'],
    'incidents.team.edit': ['incidents.team.member.add', 'incidents.team.member.replace', 'incidents.team.member.remove', 'incidents.team.acceptance.manage', 'incidents.team.raci.manage', 'incidents.team.competency.manage', 'incidents.team.conflict.manage', 'incidents.team.availability.manage', 'incidents.team.notifications.send'],
    'incidents.view': ['incidents.register.view', 'incidents.summary.view', 'incidents.detail.view', 'incidents.overview.view', 'incidents.event_details.view', 'incidents.classification.view', 'incidents.severity.view', 'incidents.risk_matrix.view', 'incidents.people.view', 'incidents.injury.view', 'incidents.exposure.view', 'incidents.assets.view', 'incidents.release.view', 'incidents.safeguards.view', 'incidents.timeline.view', 'incidents.evidence.view', 'incidents.immediate_actions.view', 'incidents.team.view', 'incidents.rca.view', 'incidents.barriers.view', 'incidents.capa.view', 'incidents.history.view', 'incidents.audit_trail.view', 'incidents.lessons.view', 'incidents.linked_records.view', 'incidents.notifications_reporting.view', 'incidents.reporting.view', 'incidents.review_approval.view', 'incidents.final_report.view'],
    'incidents.register.view': ['incidents.view', 'incidents.detail.view', 'incidents.overview.view', 'incidents.event_details.view', 'incidents.classification.view', 'incidents.severity.view', 'incidents.risk_matrix.view', 'incidents.people.view', 'incidents.assets.view', 'incidents.timeline.view', 'incidents.evidence.view', 'incidents.immediate_actions.view', 'incidents.team.view', 'incidents.rca.view', 'incidents.barriers.view', 'incidents.capa.view'],
    'regulatory:read': regulatoryReadPermissions,
    'regulatory.view': regulatoryReadPermissions,
    'regulatory.dashboard.view': ['regulatory.view'],
    'regulatory.register.view': ['regulatory.view', 'regulatory.item.view'],
    'regulatory.item.view': ['regulatory.view'],
    'regulatory.obligation.view': ['regulatory.view'],
    'regulatory.obligation.dashboard.view': ['regulatory.obligation.view'],
    'regulatory.obligation.register.view': ['regulatory.obligation.view'],
    'regulatory.obligation.matrix.view': ['regulatory.obligation.view'],
    'regulatory.compliance.view': ['regulatory.view'],
    'regulatory.compliance.dashboard.view': ['regulatory.compliance.view'],
    'regulatory.compliance.register.view': ['regulatory.compliance.view'],
    'regulatory.compliance.matrix.view': ['regulatory.compliance.view'],
    'regulatory.compliance.assessment.view': ['regulatory.compliance.view'],
    'regulatory.compliance.rollup.view': ['regulatory.compliance.view'],
    'regulatory.compliance.evidence_readiness.view': ['regulatory.compliance.view'],
    'regulatory.compliance.criteria.view': ['regulatory.compliance.view'],
    'regulatory.compliance.gap.view': ['regulatory.compliance.view'],
    'regulatory.compliance.stale.view': ['regulatory.compliance.view'],
    'regulatory.compliance.history.view': ['regulatory.compliance.view'],
    'regulatory:manage': regulatoryManagePermissions,
    'regulatory.manage': regulatoryManagePermissions,
    'regulatory.item.create': ['regulatory.view', 'regulatory.register.view'],
    'regulatory.item.edit': ['regulatory.view', 'regulatory.item.view'],
    'regulatory.item.archive': ['regulatory.item.edit'],
    'regulatory.item.reactivate': ['regulatory.item.edit'],
    'regulatory.item.lock': ['regulatory.item.edit'],
    'regulatory.item.unlock': ['regulatory.item.edit'],
    'regulatory.item.assign_owner': ['regulatory.item.edit'],
    'regulatory.item.change_status': ['regulatory.item.edit'],
    'regulatory.item.change_applicability': ['regulatory.item.edit', 'regulatory.scope.manage'],
    'regulatory.item.change_compliance_status': ['regulatory.item.edit'],
    'regulatory.obligation.create': ['regulatory.obligation.view', 'regulatory.obligation.register.view'],
    'regulatory.obligation.edit': ['regulatory.obligation.view'],
    'regulatory.obligation.archive': ['regulatory.obligation.edit'],
    'regulatory.obligation.reactivate': ['regulatory.obligation.edit'],
    'regulatory.obligation.lock': ['regulatory.obligation.edit'],
    'regulatory.obligation.unlock': ['regulatory.obligation.edit'],
    'regulatory.obligation.assign_owner': ['regulatory.obligation.edit'],
    'regulatory.obligation.change_status': ['regulatory.obligation.edit'],
    'regulatory.obligation.change_applicability': ['regulatory.obligation.edit', 'regulatory.obligation.scope.manage'],
    'regulatory.obligation.change_compliance_status': ['regulatory.obligation.edit'],
    'regulatory.obligation.scope.manage': ['regulatory.obligation.scope.view', 'regulatory.obligation.edit'],
    'regulatory.obligation.evidence_expectation.manage': ['regulatory.obligation.evidence_expectation.view', 'regulatory.obligation.edit'],
    'regulatory.obligation.module_mapping.manage': ['regulatory.obligation.module_mapping.view', 'regulatory.obligation.edit'],
    'regulatory.obligation.link.manage': ['regulatory.obligation.link.view', 'regulatory.obligation.edit'],
    'regulatory.obligation.gap.manage': ['regulatory.obligation.gap.view'],
    'regulatory.obligation.settings.edit': ['regulatory.settings.edit'],
    'regulatory.compliance.assessment.create': ['regulatory.compliance.assessment.view', 'regulatory.compliance.register.view'],
    'regulatory.compliance.assessment.edit': ['regulatory.compliance.assessment.view'],
    'regulatory.compliance.assessment.complete': ['regulatory.compliance.assessment.edit'],
    'regulatory.compliance.assessment.archive': ['regulatory.compliance.assessment.edit'],
    'regulatory.compliance.status.change': ['regulatory.compliance.assessment.edit'],
    'regulatory.compliance.status.manual_declare': ['regulatory.compliance.status.change'],
    'regulatory.compliance.status.override': ['regulatory.compliance.status.change'],
    'regulatory.compliance.rollup.recalculate': ['regulatory.compliance.rollup.view', 'regulatory.compliance.status.change'],
    'regulatory.compliance.evidence_readiness.manage': ['regulatory.compliance.evidence_readiness.view', 'regulatory.compliance.assessment.edit'],
    'regulatory.compliance.criteria.manage': ['regulatory.compliance.criteria.view', 'regulatory.compliance.assessment.edit'],
    'regulatory.compliance.gap.create': ['regulatory.compliance.gap.view'],
    'regulatory.compliance.gap.edit': ['regulatory.compliance.gap.view'],
    'regulatory.compliance.gap.resolve': ['regulatory.compliance.gap.edit'],
    'regulatory.compliance.gap.archive': ['regulatory.compliance.gap.edit'],
    'regulatory.compliance.gap.create_action_foundation': ['regulatory.compliance.gap.edit', 'regulatory.action.link'],
    'regulatory.compliance.stale.reassess': ['regulatory.compliance.stale.view', 'regulatory.compliance.assessment.edit'],
    'regulatory.compliance.settings.edit': ['regulatory.settings.edit'],
    'regulatory.jurisdiction.create': ['regulatory.jurisdiction.view'],
    'regulatory.jurisdiction.edit': ['regulatory.jurisdiction.view'],
    'regulatory.scope.manage': ['regulatory.scope.view', 'regulatory.item.edit'],
    'regulatory.link.manage': ['regulatory.link.view', 'regulatory.item.edit'],
    'regulatory.audit_mapping.link': ['regulatory.audit_mapping.view', 'regulatory.link.manage'],
    'regulatory.audit_mapping.view': ['regulatory.audit_mapping.dashboard.view', 'regulatory.audit_mapping.register.view', 'regulatory.audit_mapping.matrix.view', 'regulatory.audit_mapping.traceability.view', 'regulatory.audit_mapping.coverage.view', 'regulatory.audit_mapping.gap.view', 'regulatory.audit_mapping.review.view', 'regulatory.audit_mapping.history.view'],
    'regulatory.audit_mapping.dashboard.view': ['regulatory.audit_mapping.view'],
    'regulatory.audit_mapping.register.view': ['regulatory.audit_mapping.view'],
    'regulatory.audit_mapping.matrix.view': ['regulatory.audit_mapping.view'],
    'regulatory.audit_mapping.traceability.view': ['regulatory.audit_mapping.view'],
    'regulatory.audit_mapping.coverage.view': ['regulatory.audit_mapping.view'],
    'regulatory.audit_mapping.gap.view': ['regulatory.audit_mapping.view'],
    'regulatory.audit_mapping.review.view': ['regulatory.audit_mapping.view'],
    'regulatory.audit_mapping.history.view': ['regulatory.audit_mapping.view'],
    'regulatory.audit_mapping.create': ['regulatory.audit_mapping.register.view'],
    'regulatory.audit_mapping.edit': ['regulatory.audit_mapping.view'],
    'regulatory.audit_mapping.archive': ['regulatory.audit_mapping.edit'],
    'regulatory.audit_mapping.verify': ['regulatory.audit_mapping.view', 'regulatory.audit_mapping.review.view'],
    'regulatory.audit_mapping.reject': ['regulatory.audit_mapping.view', 'regulatory.audit_mapping.review.view'],
    'regulatory.audit_mapping.recalculate': ['regulatory.audit_mapping.view', 'regulatory.audit_mapping.coverage.view'],
    'regulatory.audit_mapping.mark_stale': ['regulatory.audit_mapping.edit'],
    'regulatory.audit_mapping.refresh_snapshot': ['regulatory.audit_mapping.edit', 'regulatory.audit_mapping.traceability.view'],
    'regulatory.audit_mapping.link_audit_program': ['regulatory.audit_mapping.link'],
    'regulatory.audit_mapping.link_audit_plan': ['regulatory.audit_mapping.link'],
    'regulatory.audit_mapping.link_checklist': ['regulatory.audit_mapping.link'],
    'regulatory.audit_mapping.link_execution': ['regulatory.audit_mapping.link'],
    'regulatory.audit_mapping.link_finding': ['regulatory.audit_mapping.link'],
    'regulatory.audit_mapping.link_capa': ['regulatory.audit_mapping.link'],
    'regulatory.audit_mapping.link_evidence': ['regulatory.audit_mapping.link'],
    'regulatory.audit_mapping.link_score': ['regulatory.audit_mapping.link'],
    'regulatory.audit_mapping.coverage.recalculate': ['regulatory.audit_mapping.recalculate', 'regulatory.audit_mapping.coverage.view'],
    'regulatory.audit_mapping.gap.create': ['regulatory.audit_mapping.gap.view'],
    'regulatory.audit_mapping.gap.edit': ['regulatory.audit_mapping.gap.view'],
    'regulatory.audit_mapping.gap.resolve': ['regulatory.audit_mapping.gap.edit'],
    'regulatory.audit_mapping.gap.create_action_foundation': ['regulatory.audit_mapping.gap.edit', 'regulatory.action.link'],
    'regulatory.audit_mapping.review.submit': ['regulatory.audit_mapping.review.view'],
    'regulatory.audit_mapping.settings.edit': ['regulatory.settings.edit'],
    'regulatory.evidence.view': ['regulatory.evidence.dashboard.view', 'regulatory.evidence.register.view', 'regulatory.evidence.requirement.view', 'regulatory.evidence.link.view', 'regulatory.evidence.review.view', 'regulatory.evidence.request.view', 'regulatory.evidence.gap.view', 'regulatory.evidence.package.view', 'regulatory.evidence.chain.view', 'regulatory.evidence.access_log.view', 'regulatory.evidence.stale.view', 'regulatory.evidence.history.view'],
    'regulatory.evidence.dashboard.view': ['regulatory.evidence.view'],
    'regulatory.evidence.register.view': ['regulatory.evidence.view', 'regulatory.evidence.link.view'],
    'regulatory.evidence.requirement.view': ['regulatory.evidence.view'],
    'regulatory.evidence.link.view': ['regulatory.evidence.view'],
    'regulatory.evidence.review.view': ['regulatory.evidence.view', 'regulatory.evidence.link.view'],
    'regulatory.evidence.request.view': ['regulatory.evidence.view'],
    'regulatory.evidence.gap.view': ['regulatory.evidence.view'],
    'regulatory.evidence.package.view': ['regulatory.evidence.view'],
    'regulatory.evidence.chain.view': ['regulatory.evidence.view'],
    'regulatory.evidence.access_log.view': ['regulatory.evidence.view'],
    'regulatory.evidence.stale.view': ['regulatory.evidence.view'],
    'regulatory.evidence.history.view': ['regulatory.evidence.view'],
    'regulatory.evidence.link': ['regulatory.evidence.view', 'regulatory.evidence.link.view', 'regulatory.evidence.link.create', 'regulatory.link.manage'],
    'regulatory.evidence.requirement.create': ['regulatory.evidence.requirement.view'],
    'regulatory.evidence.requirement.edit': ['regulatory.evidence.requirement.view'],
    'regulatory.evidence.requirement.archive': ['regulatory.evidence.requirement.view'],
    'regulatory.evidence.link.create': ['regulatory.evidence.link.view'],
    'regulatory.evidence.link.edit': ['regulatory.evidence.link.view'],
    'regulatory.evidence.link.remove': ['regulatory.evidence.link.view'],
    'regulatory.evidence.link.replace': ['regulatory.evidence.link.view'],
    'regulatory.evidence.link.archive': ['regulatory.evidence.link.view'],
    'regulatory.evidence.review.submit': ['regulatory.evidence.review.view'],
    'regulatory.evidence.review.verify': ['regulatory.evidence.review.view'],
    'regulatory.evidence.review.reject': ['regulatory.evidence.review.view'],
    'regulatory.evidence.review.request_rework': ['regulatory.evidence.review.view'],
    'regulatory.evidence.request.create': ['regulatory.evidence.request.view'],
    'regulatory.evidence.request.fulfill': ['regulatory.evidence.request.view'],
    'regulatory.evidence.request.cancel': ['regulatory.evidence.request.view'],
    'regulatory.evidence.gap.create': ['regulatory.evidence.gap.view'],
    'regulatory.evidence.gap.edit': ['regulatory.evidence.gap.view'],
    'regulatory.evidence.gap.resolve': ['regulatory.evidence.gap.view'],
    'regulatory.evidence.gap.create_action_foundation': ['regulatory.evidence.gap.view'],
    'regulatory.evidence.package.prepare': ['regulatory.evidence.package.view'],
    'regulatory.evidence.package.include_restricted': ['regulatory.evidence.package.view', 'regulatory.evidence.restricted.view'],
    'regulatory.evidence.settings.edit': ['regulatory.settings.view'],
    'regulatory.action.dashboard.view': ['regulatory.action.view'],
    'regulatory.action.register.view': ['regulatory.action.view'],
    'regulatory.action.closure_readiness.view': ['regulatory.action.view'],
    'regulatory.action.verification.view': ['regulatory.action.view'],
    'regulatory.action.effectiveness.view': ['regulatory.action.view'],
    'regulatory.action.sync_log.view': ['regulatory.action.view'],
    'regulatory.action.history.view': ['regulatory.action.view', 'regulatory.history.view'],
    'regulatory.action.link': ['regulatory.action.view', 'regulatory.link.manage'],
    'regulatory.action.create': ['regulatory.action.view', 'regulatory.action.link'],
    'regulatory.action.link_existing': ['regulatory.action.view', 'regulatory.action.link'],
    'regulatory.action.link_audit_capa': ['regulatory.action.view', 'regulatory.action.link'],
    'regulatory.action.edit_link': ['regulatory.action.view', 'regulatory.action.link'],
    'regulatory.action.archive_link': ['regulatory.action.view', 'regulatory.action.link'],
    'regulatory.action.sync': ['regulatory.action.view'],
    'regulatory.action.refresh_snapshot': ['regulatory.action.view'],
    'regulatory.action.escalate': ['regulatory.action.view'],
    'regulatory.action.open_universal_action': ['regulatory.action.view', 'actions.view'],
    'regulatory.action.closure_readiness.check': ['regulatory.action.closure_readiness.view'],
    'regulatory.action.verification.submit': ['regulatory.action.verification.view'],
    'regulatory.action.verification.fail': ['regulatory.action.verification.view'],
    'regulatory.action.effectiveness.submit': ['regulatory.action.effectiveness.view'],
    'regulatory.action.settings.edit': ['regulatory.settings.view'],
    'regulatory.capa.view': ['regulatory.action.view'],
    'regulatory.capa.create': ['regulatory.capa.view', 'regulatory.action.create'],
    'regulatory.capa.edit': ['regulatory.capa.view'],
    'regulatory.capa.archive': ['regulatory.capa.view'],
    'regulatory.capa.add_source': ['regulatory.capa.view'],
    'regulatory.capa.add_action': ['regulatory.capa.view', 'regulatory.action.link'],
    'regulatory.capa.close_foundation': ['regulatory.capa.view', 'regulatory.action.closure_readiness.view'],
    'regulatory.capa.reopen': ['regulatory.capa.view'],
    'regulatory.review.submit': ['regulatory.review.view'],
    'regulatory.settings.edit': ['regulatory.settings.view'],
    'workflows:manage': ['workflows.create', 'workflows.approve', 'workflow.view', 'workflow.create', 'workflow.edit', 'workflow.approve', 'workflow.reject', 'workflow.override', 'workflow.manage_templates']
  };
  const expanded = permissions.flatMap((permission) => [permission, ...(aliases[permission] ?? [])]);
  if (expanded.some((permission) => ['training:read', 'training.view', 'training.dashboard.view', 'training.moc.view', 'training.pssr.view', 'training.ptw_authorization.view', 'training.reports.view', 'training.reports.dashboard.view', 'training.review.view', 'training.review.dashboard.view'].includes(permission))) {
    expanded.push(
      'training.moc.view',
      'training.moc.dashboard.view',
      'training.moc.requirement.view',
      'training.moc.impact_check.view',
      'training.moc.affected_workers.view',
      'training.moc.assignment.view',
      'training.moc.readiness.view',
      'training.moc.blocker.view',
      'training.moc.waiver.view',
      'training.moc.evidence.view',
      'training.moc.history.view',
      'training.moc.settings.view',
      'training.pssr.view',
      'training.pssr.dashboard.view',
      'training.pssr.readiness.view',
      'training.pssr.impact_check.view',
      'training.pssr.readiness_check.view',
      'training.pssr.required_workers.view',
      'training.pssr.assignment.view',
      'training.pssr.blocker.view',
      'training.pssr.waiver.view',
      'training.pssr.evidence.view',
      'training.pssr.history.view',
      'training.pssr.settings.view',
      'training.ptw_authorization.view',
      'training.ptw_authorization.dashboard.view',
      'training.ptw_authorization.rule.view',
      'training.ptw_authorization.record.view',
      'training.ptw_authorization.request.view',
      'training.ptw_authorization.evaluation.view',
      'training.ptw_authorization.gap.view',
      'training.ptw_authorization.waiver.view',
      'training.ptw_authorization.history.view',
      'training.ptw_authorization.settings.view',
      'training.reports.view',
      'training.reports.dashboard.view',
      'training.reports.template.view',
      'training.reports.package.view',
      'training.reports.scheduled.view',
      'training.reports.audit_evidence.view',
      'training.reports.history.view',
      'training.reports.settings.view',
      'training.review.view',
      'training.review.dashboard.view',
      'training.review.inbox.view',
      'training.review.submission.view',
      'training.review.request.view',
      'training.review.rule.view',
      'training.review.history.view',
      'training.review.settings.view'
    );
  }
  if (expanded.some((permission) => ['training:manage', 'training.moc.manage', 'training.pssr.manage', 'training.ptw_authorization.manage', 'training.reports.manage', 'training.review.manage'].includes(permission))) {
    expanded.push(...mocTrainingPermissions,
      ...pssrTrainingPermissions,
      ...ptwAuthorizationPermissions,
      ...trainingReportsPermissions,
      ...trainingReviewPermissions);
  }
  const materialCompatibilityManagePermissions = [
    'psi.material_compatibility.view',
    'psi.material_compatibility.create',
    'psi.material_compatibility.edit',
    'psi.material_compatibility.archive',
    'psi.material_compatibility.import',
    'psi.material_compatibility.export',
    'psi.material_compatibility.manage_service_conditions',
    'psi.material_compatibility.manage_material_details',
    'psi.material_compatibility.manage_rating',
    'psi.material_compatibility.manage_degradation_mechanisms',
    'psi.material_compatibility.manage_controls',
    'psi.material_compatibility.link_document',
    'psi.material_compatibility.remove_document',
    'psi.material_compatibility.run_compatibility_check',
    'psi.material_compatibility.run_completeness_check',
    'psi.material_compatibility.run_conflict_check',
    'psi.material_compatibility.submit_review',
    'psi.material_compatibility.approve',
    'psi.material_compatibility.reject',
    'psi.material_compatibility.override_conflict'
  ];
  const safeguardManagePermissions = [
    'psi.safeguard.view',
    'psi.safeguard.create',
    'psi.safeguard.edit',
    'psi.safeguard.archive',
    'psi.safeguard.import',
    'psi.safeguard.export',
    'psi.safeguard.link_hazard',
    'psi.safeguard.remove_hazard',
    'psi.safeguard.manage_function_requirements',
    'psi.safeguard.link_source_record',
    'psi.safeguard.remove_source_record',
    'psi.safeguard.manage_effectiveness',
    'psi.safeguard.manage_testing_status',
    'psi.safeguard.link_document',
    'psi.safeguard.remove_document',
    'psi.safeguard.run_source_status_check',
    'psi.safeguard.run_completeness_check',
    'psi.safeguard.run_conflict_check',
    'psi.safeguard.submit_review',
    'psi.safeguard.approve',
    'psi.safeguard.reject',
    'psi.safeguard.override_conflict'
  ];
  const completenessManagePermissions = [
    'psi.completeness.view',
    'psi.completeness.dashboard.view',
    'psi.completeness.matrix.view',
    'psi.completeness.gap.view',
    'psi.completeness.gap.assign',
    'psi.completeness.gap.close',
    'psi.completeness.gap.verify',
    'psi.completeness.gap.reopen',
    'psi.completeness.run',
    'psi.completeness.run.company',
    'psi.completeness.run.site',
    'psi.completeness.run.unit',
    'psi.completeness.requirement.view',
    'psi.completeness.requirement.create',
    'psi.completeness.requirement.edit',
    'psi.completeness.requirement.archive',
    'psi.completeness.waiver.view',
    'psi.completeness.waiver.request',
    'psi.completeness.waiver.approve',
    'psi.completeness.waiver.reject',
    'psi.completeness.waiver.revoke',
    'psi.completeness.action.create',
    'psi.completeness.export',
    'psi.completeness.settings.view',
    'psi.completeness.settings.edit'
  ];
  const integrationReadPermissions = [
    'psi.integration.view',
    'psi.integration.dashboard.view',
    'psi.integration.moc.view',
    'psi.integration.pssr.view',
    'psi.integration.hazop.view',
    'psi.integration.mi.view',
    'psi.integration.settings.view'
  ];
  const integrationManagePermissions = [
    ...integrationReadPermissions,
    'psi.integration.link.create',
    'psi.integration.link.edit',
    'psi.integration.link.close',
    'psi.integration.link.verify',
    'psi.integration.moc.assess',
    'psi.integration.moc.override_blocker',
    'psi.integration.pssr.run_readiness',
    'psi.integration.pssr.clear_blocker',
    'psi.integration.pssr.override_blocker',
    'psi.integration.hazop.link_basis',
    'psi.integration.hazop.create_psi_action',
    'psi.integration.mi.run_sync_check',
    'psi.integration.mi.resolve_impact',
    'psi.integration.sync.run',
    'psi.integration.sync.resolve',
    'psi.integration.action.create',
    'psi.integration.export',
    'psi.integration.settings.edit'
  ];
  const reviewReadPermissions = [
    'psi.review.view',
    'psi.review.dashboard.view',
    'psi.review.inbox.view',
    'psi.review.snapshot.view',
    'psi.review.history.view',
    'psi.review.rule.view',
    'psi.review.settings.view'
  ];
  const reviewManagePermissions = [
    ...reviewReadPermissions,
    'psi.review.submit',
    'psi.review.withdraw',
    'psi.review.approve',
    'psi.review.reject',
    'psi.review.return',
    'psi.review.comment',
    'psi.review.delegate',
    'psi.review.escalate',
    'psi.review.override',
    'psi.review.rule.create',
    'psi.review.rule.edit',
    'psi.review.rule.archive',
    'psi.review.settings.edit',
    'psi.review.export',
    'psi.completeness.waiver.request',
    'psi.completeness.waiver.approve'
  ];
  const reportReadPermissions = [
    'psi.report.view',
    'psi.report.dashboard.view',
    'psi.report.template.view',
    'psi.report.download',
    'psi.export.view',
    'psi.export.download',
    'psi.scheduled_report.view',
    'psi.report.settings.view'
  ];
  const reportManagePermissions = [
    ...reportReadPermissions,
    'psi.report.generate',
    'psi.report.generate.company',
    'psi.report.generate.site',
    'psi.report.generate.unit',
    'psi.report.template.create',
    'psi.report.template.edit',
    'psi.report.template.archive',
    'psi.report.archive',
    'psi.report.regenerate',
    'psi.export.create',
    'psi.export.create_with_documents',
    'psi.export.archive',
    'psi.export.cancel',
    'psi.export.regenerate',
    'psi.scheduled_report.create',
    'psi.scheduled_report.edit',
    'psi.scheduled_report.archive',
    'psi.report.settings.edit'
  ];
  const psiDashboardAccessPermissions = [
    'psi:read',
    'psi:manage',
    'psi.view',
    'psi.unit.view',
    'psi.chemical.view',
    'psi.process_chemistry.view',
    'psi.safe_limit.view',
    'psi.equipment_design.view',
    'psi.relief_system.view',
    'psi.drawing.view',
    'psi.electrical_classification.view',
    'psi.material_compatibility.view',
    'psi.safeguard.view',
    'psi.completeness.view',
    'psi.completeness.dashboard.view',
    'psi.integration.view',
    'psi.integration.dashboard.view',
    ...reviewReadPermissions,
    ...reportReadPermissions
  ];
  if (permissions.some((permission) => psiDashboardAccessPermissions.includes(permission))) {
    expanded.push('psi.view', 'psi.dashboard.view', 'psi.unit.view');
  }
  if (permissions.some((permission) => ['psi:read', 'psi.view', 'psi.unit.view'].includes(permission))) {
    expanded.push('psi.material_compatibility.view');
    expanded.push('psi.safeguard.view');
    expanded.push('psi.completeness.view', 'psi.completeness.dashboard.view', 'psi.completeness.matrix.view', 'psi.completeness.gap.view', 'psi.completeness.requirement.view', 'psi.completeness.waiver.view', 'psi.completeness.settings.view');
    expanded.push(...integrationReadPermissions);
    expanded.push(...reviewReadPermissions);
    expanded.push(...reportReadPermissions);
  }
  if (permissions.includes('psi:manage')) {
    expanded.push('psi.unit.create', 'psi.unit.edit', 'psi.unit.archive', 'psi.unit.link_equipment', 'psi.unit.unlink_equipment', 'psi.unit.assign_owner', 'psi.unit.assign_reviewer', 'equipment.view', 'users.view');
    expanded.push(...materialCompatibilityManagePermissions);
    expanded.push(...safeguardManagePermissions);
    expanded.push(...completenessManagePermissions);
    expanded.push(...integrationManagePermissions);
    expanded.push(...reviewManagePermissions);
    expanded.push(...reportManagePermissions);
  }
  if (permissions.includes('psi.unit.edit')) {
    expanded.push(
      'psi.unit.create',
      'psi.unit.link_equipment',
      'psi.unit.unlink_equipment',
      'psi.unit.assign_owner',
      'psi.unit.assign_reviewer',
      'equipment.view',
      'users.view',
      'psi.material_compatibility.create',
      'psi.material_compatibility.edit',
      'psi.material_compatibility.manage_service_conditions',
      'psi.material_compatibility.manage_material_details',
      'psi.material_compatibility.manage_rating',
      'psi.material_compatibility.manage_degradation_mechanisms',
      'psi.material_compatibility.manage_controls',
      'psi.material_compatibility.run_compatibility_check',
      'psi.material_compatibility.run_completeness_check',
      'psi.material_compatibility.run_conflict_check',
      'psi.safeguard.create',
      'psi.safeguard.edit',
      'psi.safeguard.link_hazard',
      'psi.safeguard.remove_hazard',
      'psi.safeguard.manage_function_requirements',
      'psi.safeguard.link_source_record',
      'psi.safeguard.remove_source_record',
      'psi.safeguard.manage_effectiveness',
      'psi.safeguard.manage_testing_status',
      'psi.safeguard.link_document',
      'psi.safeguard.remove_document',
      'psi.safeguard.run_source_status_check',
      'psi.safeguard.run_completeness_check',
      'psi.safeguard.run_conflict_check',
      'psi.completeness.run',
      'psi.completeness.run.unit',
      'psi.completeness.gap.assign',
      'psi.completeness.gap.close',
      'psi.completeness.gap.verify',
      'psi.completeness.gap.reopen',
      'psi.completeness.action.create',
      'psi.completeness.waiver.request',
      'psi.integration.link.create',
      'psi.integration.link.edit',
      'psi.integration.moc.assess',
      'psi.integration.pssr.run_readiness',
      'psi.integration.hazop.link_basis',
      'psi.integration.mi.run_sync_check',
      'psi.integration.sync.run',
      'psi.integration.action.create',
      'psi.review.submit',
      'psi.review.comment'
    );
  }
  if (permissions.includes('incidents:manage')) {
    expanded.push('incidents.final_report.view', 'incidents.final_report.configure', 'incidents.final_report.preview', 'incidents.final_report.generate', 'incidents.final_report.download', 'incidents.final_report.export', 'incidents.final_report.mark_official', 'incidents.final_report.publish', 'incidents.final_report.supersede', 'incidents.final_report.archive', 'incidents.final_report.review.request', 'incidents.final_report.review.approve', 'incidents.final_report.review.reject', 'incidents.evidence.export_package');
  }
  return expanded;
}



