'use client';

import type { CriticalityScore } from '../../../types/criticality.types';

export function ConsequenceScoringSection({ scores }: { scores: CriticalityScore[] }) {
  return (
    <section className="rounded-xl border border-border bg-card p-4">
      <h2 className="font-semibold">Consequence Scoring</h2>
      <div className="mt-3 grid gap-2">
        {scores.length ? scores.map((score) => <div key={score.dimension_key} className="flex items-center justify-between rounded-md border border-border p-3 text-sm"><span>{score.dimension_label}</span><span className="font-semibold">{score.score ?? 'Pending'}</span></div>) : <div className="text-sm text-muted-foreground">Consequence dimensions are generated by the backend configuration when the assessment is created.</div>}
      </div>
    </section>
  );
}
