import { CriticalityBadge } from '../../../shared/CriticalityBadge';
import { RiskMatrixCell } from '../../../shared/RiskMatrixCell';
import type { CriticalityCalculation } from '../../../types/criticality.types';

export function RiskCalculationPreviewSection({ calculation }: { calculation?: CriticalityCalculation | null }) {
  return (
    <section className="rounded-xl border border-border bg-card p-4">
      <h2 className="font-semibold">Backend Risk Calculation</h2>
      <div className="mt-3 grid gap-3 md:grid-cols-3">
        <RiskMatrixCell consequence={calculation?.consequence_score} likelihood={calculation?.likelihood_score} score={calculation?.final_risk_score} />
        <div className="rounded-lg border border-border p-3 text-sm"><span className="text-muted-foreground">Category</span><div className="mt-2"><CriticalityBadge value={calculation?.criticality_category} /></div></div>
        <div className="rounded-lg border border-border p-3 text-sm"><span className="text-muted-foreground">Priority</span><div className="mt-2 font-semibold">{calculation?.inspection_priority ?? 'Pending'}</div></div>
      </div>
      <p className="mt-3 text-sm text-muted-foreground">{calculation?.explanation ?? 'Calculation is generated by the backend after scores exist.'}</p>
    </section>
  );
}
