import { z } from 'zod';

export const initiatingEventLibrarySchema = z.object({
  eventCode: z.string().min(1),
  eventName: z.string().min(3),
  description: z.string().optional(),
  eventCategory: z.string().min(1),
  failureMode: z.string().optional(),
  equipmentType: z.string().optional(),
  subtype: z.string().optional(),
  serviceApplication: z.string().optional(),
  baseFrequency: z.coerce.number().positive(),
  frequencyUnit: z.string().min(1),
  lowFrequency: z.coerce.number().optional(),
  highFrequency: z.coerce.number().optional(),
  confidenceLevel: z.string().optional(),
  sourceType: z.string().min(1),
  sourceReference: z.string().min(1),
  standardReference: z.string().optional(),
  applicabilityNotes: z.string().optional(),
  exclusionNotes: z.string().optional(),
  scope: z.string().optional(),
  siteId: z.string().optional(),
  siteModifierAllowed: z.boolean().optional(),
  defaultSiteModifier: z.coerce.number().optional(),
  engineeringJustificationRequired: z.boolean().optional(),
  engineeringJustification: z.string().optional(),
  revisionNotes: z.string().optional(),
  active: z.boolean().optional()
});

export const conditionalModifierLibrarySchema = z.object({
  modifierCode: z.string().min(1),
  modifierName: z.string().min(3),
  description: z.string().optional(),
  modifierType: z.string().min(1),
  applicationContext: z.string().optional(),
  defaultValue: z.coerce.number().min(0).max(1),
  lowValue: z.coerce.number().optional(),
  highValue: z.coerce.number().optional(),
  unit: z.string().optional(),
  confidenceLevel: z.string().optional(),
  sourceType: z.string().min(1),
  sourceReference: z.string().min(1),
  standardReference: z.string().optional(),
  applicabilityNotes: z.string().optional(),
  exclusionNotes: z.string().optional(),
  scope: z.string().optional(),
  siteId: z.string().optional(),
  overrideAllowed: z.boolean().optional(),
  engineeringJustificationRequired: z.boolean().optional(),
  engineeringJustification: z.string().optional(),
  revisionNotes: z.string().optional(),
  active: z.boolean().optional()
});
