"use client";
import { useState } from "react";
import { AuditButton, AuditCard, AuditEmptyState, Field, inputClass } from "../../shared/AuditUi";
import { AuditEvidenceStatusBadge } from "../../shared/AuditEvidenceStatusBadge";
import { useAuditExecutionEvidence } from "../../hooks/useAuditExecutionEvidence";
import type { AuditExecutionDetail } from "../../types/audit-execution.types";

export function ExecutionEvidenceTab({ detail }: { detail: AuditExecutionDetail }) {
  const mutations = useAuditExecutionEvidence();
  const [form, setForm] = useState({ evidenceTitle: "", evidenceType: "Document Control", documentId: "", storageFileId: "", relatedRecordId: "", confidentialityLevel: "Internal" });
  const set = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const save = () => mutations.add.mutate({ executionId: detail.execution.id, payload: form }, { onSuccess: () => setForm({ evidenceTitle: "", evidenceType: "Document Control", documentId: "", storageFileId: "", relatedRecordId: "", confidentialityLevel: "Internal" }) });
  const disabledReason = !form.evidenceTitle ? "Evidence title is required." : !form.documentId && !form.storageFileId && !form.relatedRecordId && form.evidenceType !== "Other" ? "Link a document, storage file, or related record." : "";
  return <div className="grid gap-5 xl:grid-cols-[1fr_380px]"><AuditCard title="Evidence Register">{detail.evidence.length ? <div className="space-y-2">{detail.evidence.map((evidence) => <div key={evidence.id} className="rounded-lg border border-[var(--psm-line)] p-3"><div className="flex flex-wrap justify-between gap-2"><p className="font-semibold text-[var(--psm-fg)]">{evidence.evidence_title}</p><AuditEvidenceStatusBadge status={evidence.evidence_status} /></div><p className="text-sm text-[var(--psm-muted)]">{evidence.evidence_type} - {evidence.confidentiality_level ?? "Internal"}</p></div>)}</div> : <AuditEmptyState title="No evidence linked" message="Evidence must be linked through backend Document Control, storage, or related record metadata." />}</AuditCard><AuditCard title="Link evidence"><div className="space-y-3"><Field label="Evidence title"><input className={inputClass()} value={form.evidenceTitle} onChange={(e) => set("evidenceTitle", e.target.value)} /></Field><Field label="Evidence type"><select className={inputClass()} value={form.evidenceType} onChange={(e) => set("evidenceType", e.target.value)}><option>Document Control</option><option>Storage File</option><option>Photo</option><option>Interview Record</option><option>Walkthrough Record</option><option>External Reference</option><option>Other</option></select></Field><Field label="Document ID"><input className={inputClass()} value={form.documentId} onChange={(e) => set("documentId", e.target.value)} /></Field><Field label="Storage file ID"><input className={inputClass()} value={form.storageFileId} onChange={(e) => set("storageFileId", e.target.value)} /></Field><Field label="Related record ID"><input className={inputClass()} value={form.relatedRecordId} onChange={(e) => set("relatedRecordId", e.target.value)} /></Field><AuditButton onClick={save} disabled={Boolean(disabledReason) || mutations.add.isPending} title={disabledReason || "Link evidence"}>{mutations.add.isPending ? "Saving..." : "Link Evidence"}</AuditButton></div></AuditCard></div>;
}
