"use client";
import { useState } from "react";
import { AuditButton, AuditCard, AuditEmptyState, Field, inputClass } from "../../shared/AuditUi";
import { AuditFieldFindingStatusBadge } from "../../shared/AuditFieldFindingStatusBadge";
import { AuditFindingSeverityBadge } from "../../shared/AuditFindingSeverityBadge";
import { useAuditFieldFindingMutations } from "../../hooks/useAuditFieldFindings";
import type { AuditExecutionDetail } from "../../types/audit-execution.types";

export function ExecutionFieldFindingsTab({ detail }: { detail: AuditExecutionDetail }) {
  const mutations = useAuditFieldFindingMutations();
  const [form, setForm] = useState({ findingTitle: "", findingType: "Observation", findingDescription: "", criticality: "Medium", immediateConcern: false, stopWorkRecommended: false });
  const set = (key: string, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  const save = () => mutations.add.mutate({ executionId: detail.execution.id, payload: form }, { onSuccess: () => setForm({ findingTitle: "", findingType: "Observation", findingDescription: "", criticality: "Medium", immediateConcern: false, stopWorkRecommended: false }) });
  return <div className="grid gap-5 xl:grid-cols-[1fr_380px]"><AuditCard title="Field Findings">{detail.findings.length ? <div className="space-y-2">{detail.findings.map((finding) => <div key={finding.id} className="rounded-lg border border-[var(--psm-line)] p-3"><div className="flex flex-wrap justify-between gap-2"><p className="font-semibold text-[var(--psm-fg)]">{finding.finding_title}</p><div className="flex gap-2"><AuditFindingSeverityBadge value={finding.criticality} /><AuditFieldFindingStatusBadge status={finding.field_finding_status} /></div></div><p className="mt-1 text-sm text-[var(--psm-muted)]">{finding.finding_description}</p></div>)}</div> : <AuditEmptyState title="No field findings" message="No backend field findings have been captured." />}</AuditCard><AuditCard title="Add field finding"><div className="space-y-3"><Field label="Title"><input className={inputClass()} value={form.findingTitle} onChange={(e) => set("findingTitle", e.target.value)} /></Field><Field label="Type"><select className={inputClass()} value={form.findingType} onChange={(e) => set("findingType", e.target.value)}><option>Observation</option><option>Non-Compliance</option><option>Safety Critical Finding</option><option>Regulatory Finding</option><option>System Weakness</option></select></Field><Field label="Criticality"><select className={inputClass()} value={form.criticality} onChange={(e) => set("criticality", e.target.value)}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option><option>Safety-Critical</option><option>Regulatory-Critical</option></select></Field><Field label="Description"><textarea className={inputClass()} value={form.findingDescription} onChange={(e) => set("findingDescription", e.target.value)} /></Field><label className="flex gap-2 text-sm text-[var(--psm-fg)]"><input type="checkbox" checked={form.immediateConcern} onChange={(e) => set("immediateConcern", e.target.checked)} /> Immediate concern</label><label className="flex gap-2 text-sm text-[var(--psm-fg)]"><input type="checkbox" checked={form.stopWorkRecommended} onChange={(e) => set("stopWorkRecommended", e.target.checked)} /> Stop work recommended</label><AuditButton onClick={save} disabled={!form.findingTitle || !form.findingDescription || mutations.add.isPending} title={!form.findingTitle || !form.findingDescription ? "Title and description are required." : "Save finding"}>{mutations.add.isPending ? "Saving..." : "Save Finding"}</AuditButton></div></AuditCard></div>;
}
