export const auditTypes = [
  "Internal PSM Audit",
  "Compliance Audit",
  "Regulatory Audit",
  "Corporate Audit",
  "Site Audit",
  "Unit Audit",
  "Module Audit",
  "Contractor Audit",
  "Process Safety Audit",
  "EHS Audit",
  "Pre-Startup Audit",
  "Training Compliance Audit",
  "PTW Audit",
  "MOC Audit",
  "PSSR Audit",
  "Mechanical Integrity Audit",
  "Incident/CAPA Audit",
  "Document Control Audit",
  "Emergency Preparedness Audit",
  "Custom",
] as const;

export const programCategories = [
  "PSM Compliance",
  "EHS Compliance",
  "Operational Discipline",
  "Process Safety",
  "Asset Integrity",
  "Workforce Competency",
  "Permit-to-Work",
  "Change Management",
  "Startup Readiness",
  "Regulatory Assurance",
  "Contractor Assurance",
  "Corporate Governance",
  "Custom",
] as const;

export const programStatuses = [
  "Draft",
  "Active",
  "Inactive",
  "Pending Review",
  "Approved",
  "Review Overdue",
  "Configuration Incomplete",
  "Ready For Scheduling",
  "Superseded",
  "Archived",
] as const;
export const configurationHealthStatuses = [
  "Complete",
  "Missing Scope",
  "Missing Standards",
  "Missing Owner",
  "Missing Frequency",
  "Missing Modules",
  "Review Overdue",
  "Needs Approval",
  "Ready For Scheduling",
] as const;
export const criticalityLevels = [
  "Low",
  "Medium",
  "High",
  "Critical",
  "Safety-Critical",
  "Regulatory-Critical",
  "PSM-Critical",
] as const;
export const scopeTypes = [
  "Company-wide",
  "Site-wide",
  "Unit-specific",
  "Area-specific",
  "Department-specific",
  "Equipment-specific foundation",
  "Module-specific",
  "Contractor-specific foundation",
  "Process/system-specific",
  "Custom",
] as const;
export const auditFrequencies = [
  "One-time",
  "Monthly",
  "Quarterly",
  "Semi-Annual",
  "Annual",
  "Biennial",
  "Every 3 Years",
  "Turnaround-based",
  "MOC-triggered",
  "Incident-triggered",
  "Risk-based",
  "Custom",
] as const;
export const coverageLevels = [
  "Full",
  "Partial",
  "Sampling",
  "Evidence Review Only",
  "Field Verification",
  "Interview Only",
  "Document Review",
  "System Audit",
  "Custom",
] as const;
export const auditableModules = [
  ["PTW", "Permit to Work"],
  ["MOC", "Management of Change"],
  ["PSSR", "Pre-Startup Safety Review"],
  ["HAZOP_PHA", "HAZOP / PHA"],
  ["LOPA_SIL", "LOPA / SIL"],
  ["PSI", "Process Safety Information"],
  ["MECHANICAL_INTEGRITY", "Mechanical Integrity"],
  ["INCIDENT_INVESTIGATION", "Incident Investigation"],
  ["TRAINING_COMPETENCY", "Training & Competency"],
  ["DOCUMENT_CONTROL", "Document Control"],
  ["ACTION_ENGINE_CAPA", "Action Engine / CAPA"],
  ["EQUIPMENT_REGISTRY", "Equipment Registry"],
  ["CHEMICAL_SDS", "Chemical / SDS foundation"],
  ["EMERGENCY_RESPONSE", "Emergency Response foundation"],
  ["MANAGEMENT_REVIEW", "Management Review foundation"],
  ["CUSTOM", "Custom"],
] as const;

export const standardOptions = [
  "OSHA PSM",
  "EPA RMP",
  "ISO 45001",
  "ISO 14001",
  "ISO 9001",
  "Responsible Care",
  "Company Standard",
  "Site Procedure",
  "Corporate PSM Standard",
  "Local Regulation",
  "Insurance / Loss Prevention Requirement",
  "Industry Best Practice",
  "Custom",
] as const;

export const auditPermissions = {
  view: "audit.view",
  dashboardView: "audit.dashboard.view",
  programView: "audit.program.view",
  programCreate: "audit.program.create",
  programEdit: "audit.program.edit",
  programActivate: "audit.program.activate",
  programArchive: "audit.program.archive",
  programReactivate: "audit.program.reactivate",
  programSubmitReview: "audit.program.submit_review",
  programReview: "audit.program.review",
  scopeManage: "audit.program.scope.manage",
  standardManage: "audit.program.standard.manage",
  moduleManage: "audit.program.module.manage",
  frequencyManage: "audit.program.frequency.manage",
  ownershipManage: "audit.program.ownership.manage",
  integrationManage: "audit.program.integration.manage",
  historyView: "audit.history.view",
  settingsView: "audit.settings.view",
  settingsEdit: "audit.settings.edit",
  planView: "audit.plan.view",
  planDashboardView: "audit.plan.dashboard.view",
  planCalendarView: "audit.plan.calendar.view",
  planCreate: "audit.plan.create",
  planEdit: "audit.plan.edit",
  planSchedule: "audit.plan.schedule",
  planReschedule: "audit.plan.reschedule",
  planPostpone: "audit.plan.postpone",
  planCancel: "audit.plan.cancel",
  planArchive: "audit.plan.archive",
  planReactivate: "audit.plan.reactivate",
  planGenerateFromProgram: "audit.plan.generate_from_program",
  planSubmitReview: "audit.plan.submit_review",
  planReview: "audit.plan.review",
  planScopeManage: "audit.plan.scope.manage",
  planStandardManage: "audit.plan.standard.manage",
  planModuleManage: "audit.plan.module.manage",
  planTeamManage: "audit.plan.team.manage",
  planConflictView: "audit.plan.conflict.view",
  planConflictOverride: "audit.plan.conflict.override",
  planReadinessRun: "audit.plan.readiness.run",
  planHistoryView: "audit.plan.history.view",
  planSettingsView: "audit.plan.settings.view",
  planSettingsEdit: "audit.plan.settings.edit",
  checklistView: "audit.checklist.view",
  checklistDashboardView: "audit.checklist.dashboard.view",
  checklistTemplateView: "audit.checklist.template.view",
  checklistTemplateCreate: "audit.checklist.template.create",
  checklistTemplateEdit: "audit.checklist.template.edit",
  checklistTemplateActivate: "audit.checklist.template.activate",
  checklistTemplateArchive: "audit.checklist.template.archive",
  checklistTemplateReactivate: "audit.checklist.template.reactivate",
  checklistTemplateVersionCreate: "audit.checklist.template.version.create",
  checklistSubmitReview: "audit.checklist.submit_review",
  checklistReview: "audit.checklist.review",
  checklistSectionManage: "audit.checklist.section.manage",
  checklistItemManage: "audit.checklist.item.manage",
  checklistStandardManage: "audit.checklist.standard.manage",
  checklistModuleManage: "audit.checklist.module.manage",
  checklistScopeManage: "audit.checklist.scope.manage",
  checklistAssignmentView: "audit.checklist.assignment.view",
  checklistAssignmentManage: "audit.checklist.assignment.manage",
  checklistQuestionBankView: "audit.checklist.question_bank.view",
  checklistQuestionBankCreate: "audit.checklist.question_bank.create",
  checklistQuestionBankEdit: "audit.checklist.question_bank.edit",
  checklistQuestionBankArchive: "audit.checklist.question_bank.archive",
  checklistReadinessRun: "audit.checklist.readiness.run",
  checklistHistoryView: "audit.checklist.history.view",
  checklistSettingsView: "audit.checklist.settings.view",
  checklistSettingsEdit: "audit.checklist.settings.edit",
  executionView: "audit.execution.view",
  executionDashboardView: "audit.execution.dashboard.view",
  executionRegisterView: "audit.execution.register.view",
  executionCreate: "audit.execution.create",
  executionStart: "audit.execution.start",
  executionPause: "audit.execution.pause",
  executionResume: "audit.execution.resume",
  executionComplete: "audit.execution.complete",
  executionReopen: "audit.execution.reopen",
  executionCancel: "audit.execution.cancel",
  executionWorkspaceView: "audit.execution.workspace.view",
  executionResponseView: "audit.execution.response.view",
  executionResponseCreate: "audit.execution.response.create",
  executionResponseEdit: "audit.execution.response.edit",
  executionResponseReopen: "audit.execution.response.reopen",
  executionEvidenceView: "audit.execution.evidence.view",
  executionEvidenceAdd: "audit.execution.evidence.add",
  executionEvidenceRemove: "audit.execution.evidence.remove",
  executionNoteView: "audit.execution.note.view",
  executionNoteCreate: "audit.execution.note.create",
  executionNoteEdit: "audit.execution.note.edit",
  executionNoteDelete: "audit.execution.note.delete",
  fieldFindingView: "audit.field_finding.view",
  fieldFindingCreate: "audit.field_finding.create",
  fieldFindingEdit: "audit.field_finding.edit",
  fieldFindingCancel: "audit.field_finding.cancel",
  fieldFindingConvert: "audit.field_finding.convert_foundation",
  findingView: "audit.finding.view",
  findingDashboardView: "audit.finding.dashboard.view",
  findingRegisterView: "audit.finding.register.view",
  findingCreate: "audit.finding.create",
  findingEdit: "audit.finding.edit",
  findingClassify: "audit.finding.classify",
  findingConfirm: "audit.finding.confirm",
  findingReject: "audit.finding.reject",
  findingReopen: "audit.finding.reopen",
  findingArchive: "audit.finding.archive",
  findingConvertFromField: "audit.finding.convert_from_field",
  findingSourceManage: "audit.finding.source.manage",
  findingStandardManage: "audit.finding.standard.manage",
  findingModuleManage: "audit.finding.module.manage",
  findingEvidenceView: "audit.finding.evidence.view",
  findingEvidenceAdd: "audit.finding.evidence.add",
  findingEvidenceRemove: "audit.finding.evidence.remove",
  findingOwnerAssign: "audit.finding.owner.assign",
  findingReviewSubmit: "audit.finding.review.submit",
  findingReviewPerform: "audit.finding.review.perform",
  findingDuplicateCheck: "audit.finding.duplicate.check",
  findingDuplicateOverride: "audit.finding.duplicate.override",
  findingCapaFoundationView: "audit.finding.capa_foundation.view",
  findingCapaFoundationCreate: "audit.finding.capa_foundation.create",
  findingHistoryView: "audit.finding.history.view",
  findingSettingsView: "audit.finding.settings.view",
  findingSettingsEdit: "audit.finding.settings.edit",
  capaView: "audit.capa.view",
  capaDashboardView: "audit.capa.dashboard.view",
  capaRegisterView: "audit.capa.register.view",
  capaCreate: "audit.capa.create",
  capaEdit: "audit.capa.edit",
  capaOpen: "audit.capa.open",
  capaClose: "audit.capa.close",
  capaReopen: "audit.capa.reopen",
  capaArchive: "audit.capa.archive",
  capaCreateFromFinding: "audit.capa.create_from_finding",
  capaFindingLink: "audit.capa.finding.link",
  capaActionView: "audit.capa.action.view",
  capaActionCreate: "audit.capa.action.create",
  capaActionEdit: "audit.capa.action.edit",
  capaActionAssign: "audit.capa.action.assign",
  capaActionComplete: "audit.capa.action.complete",
  capaActionVerify: "audit.capa.action.verify",
  capaActionReject: "audit.capa.action.reject",
  capaActionReopen: "audit.capa.action.reopen",
  capaContainmentView: "audit.capa.containment.view",
  capaContainmentManage: "audit.capa.containment.manage",
  capaEvidenceView: "audit.capa.evidence.view",
  capaEvidenceAdd: "audit.capa.evidence.add",
  capaEvidenceRemove: "audit.capa.evidence.remove",
  capaVerificationView: "audit.capa.verification.view",
  capaVerificationPerform: "audit.capa.verification.perform",
  capaEffectivenessView: "audit.capa.effectiveness.view",
  capaEffectivenessPerform: "audit.capa.effectiveness.perform",
  capaClosureReadinessRun: "audit.capa.closure_readiness.run",
  capaSyncActionEngine: "audit.capa.sync_action_engine",
  capaHistoryView: "audit.capa.history.view",
  capaSettingsView: "audit.capa.settings.view",
  capaSettingsEdit: "audit.capa.settings.edit",
  evidenceView: "audit.evidence.view",
  evidenceDashboardView: "audit.evidence.dashboard.view",
  evidenceRegisterView: "audit.evidence.register.view",
  evidenceCreate: "audit.evidence.create",
  evidenceEdit: "audit.evidence.edit",
  evidenceUpload: "audit.evidence.upload",
  evidenceReplace: "audit.evidence.replace",
  evidenceRemove: "audit.evidence.remove",
  evidenceLinkDocument: "audit.evidence.link_document",
  evidenceLinkModuleRecord: "audit.evidence.link_module_record",
  evidencePreview: "audit.evidence.preview",
  evidenceDownload: "audit.evidence.download",
  evidenceViewRestricted: "audit.evidence.view_restricted",
  evidenceManageRestricted: "audit.evidence.manage_restricted",
  evidenceRequirementView: "audit.evidence.requirement.view",
  evidenceRequirementCreate: "audit.evidence.requirement.create",
  evidenceRequirementEdit: "audit.evidence.requirement.edit",
  evidenceRequirementWaive: "audit.evidence.requirement.waive",
  evidenceRequestView: "audit.evidence.request.view",
  evidenceRequestCreate: "audit.evidence.request.create",
  evidenceRequestSend: "audit.evidence.request.send",
  evidenceRequestSubmit: "audit.evidence.request.submit",
  evidenceRequestCancel: "audit.evidence.request.cancel",
  evidenceReviewView: "audit.evidence.review.view",
  evidenceReviewPerform: "audit.evidence.review.perform",
  evidenceVerify: "audit.evidence.verify",
  evidenceReject: "audit.evidence.reject",
  evidenceRequestRework: "audit.evidence.request_rework",
  evidenceChainOfCustodyView: "audit.evidence.chain_of_custody.view",
  evidenceAccessLogView: "audit.evidence.access_log.view",
  evidencePackageView: "audit.evidence.package.view",
  evidencePackagePrepare: "audit.evidence.package.prepare",
  evidenceGapView: "audit.evidence.gap.view",
  evidenceGapManage: "audit.evidence.gap.manage",
  evidenceHistoryView: "audit.evidence.history.view",
  evidenceSettingsView: "audit.evidence.settings.view",
  evidenceSettingsEdit: "audit.evidence.settings.edit",
  scoringView: "audit.scoring.view",
  scoringDashboardView: "audit.scoring.dashboard.view",
  scoringRegisterView: "audit.scoring.register.view",
  scoringRunCreate: "audit.scoring.run.create",
  scoringRunRecalculate: "audit.scoring.run.recalculate",
  scoringRunView: "audit.scoring.run.view",
  scoringRunVerify: "audit.scoring.run.verify",
  scoringRunLock: "audit.scoring.run.lock",
  scoringRunUnlock: "audit.scoring.run.unlock",
  scoringRunArchive: "audit.scoring.run.archive",
  scoringModelView: "audit.scoring.model.view",
  scoringModelCreate: "audit.scoring.model.create",
  scoringModelEdit: "audit.scoring.model.edit",
  scoringModelActivate: "audit.scoring.model.activate",
  scoringModelArchive: "audit.scoring.model.archive",
  scoringRuleView: "audit.scoring.rule.view",
  scoringRuleManage: "audit.scoring.rule.manage",
  scoringAdjustmentView: "audit.scoring.adjustment.view",
  scoringAdjustmentCreate: "audit.scoring.adjustment.create",
  scoringAdjustmentApprove: "audit.scoring.adjustment.approve",
  scoringAdjustmentRemove: "audit.scoring.adjustment.remove",
  scoringExplainabilityView: "audit.scoring.explainability.view",
  scoringTraceabilityView: "audit.scoring.traceability.view",
  scoringStaleView: "audit.scoring.stale.view",
  scoringHistoryView: "audit.scoring.history.view",
  scoringSettingsView: "audit.scoring.settings.view",
  scoringSettingsEdit: "audit.scoring.settings.edit",
  standardsMappingView: "audit.standards_mapping.view",
  standardsMappingDashboardView: "audit.standards_mapping.dashboard.view",
  standardsMappingRegisterView: "audit.standards_mapping.register.view",
  standardsMappingStandardView: "audit.standards_mapping.standard.view",
  standardsMappingStandardCreate: "audit.standards_mapping.standard.create",
  standardsMappingStandardEdit: "audit.standards_mapping.standard.edit",
  standardsMappingStandardArchive: "audit.standards_mapping.standard.archive",
  standardsMappingClauseView: "audit.standards_mapping.clause.view",
  standardsMappingClauseCreate: "audit.standards_mapping.clause.create",
  standardsMappingClauseEdit: "audit.standards_mapping.clause.edit",
  standardsMappingClauseArchive: "audit.standards_mapping.clause.archive",
  standardsMappingMappingView: "audit.standards_mapping.mapping.view",
  standardsMappingMappingCreate: "audit.standards_mapping.mapping.create",
  standardsMappingMappingEdit: "audit.standards_mapping.mapping.edit",
  standardsMappingMappingLink: "audit.standards_mapping.mapping.link",
  standardsMappingMappingUnlink: "audit.standards_mapping.mapping.unlink",
  standardsMappingMappingVerify: "audit.standards_mapping.mapping.verify",
  standardsMappingMappingArchive: "audit.standards_mapping.mapping.archive",
  standardsMappingCoverageView: "audit.standards_mapping.coverage.view",
  standardsMappingCoverageRecalculate: "audit.standards_mapping.coverage.recalculate",
  standardsMappingTraceabilityView: "audit.standards_mapping.traceability.view",
  standardsMappingGapView: "audit.standards_mapping.gap.view",
  standardsMappingGapManage: "audit.standards_mapping.gap.manage",
  standardsMappingOverrideCreate: "audit.standards_mapping.override.create",
  standardsMappingOverrideApprove: "audit.standards_mapping.override.approve",
  standardsMappingOverrideRemove: "audit.standards_mapping.override.remove",
  standardsMappingStaleView: "audit.standards_mapping.stale.view",
  standardsMappingHistoryView: "audit.standards_mapping.history.view",
  standardsMappingSettingsView: "audit.standards_mapping.settings.view",
  standardsMappingSettingsEdit: "audit.standards_mapping.settings.edit",
  reviewView: "audit.review.view",
  reviewDashboardView: "audit.review.dashboard.view",
  reviewInboxView: "audit.review.inbox.view",
  reviewSubmissionView: "audit.review.submission.view",
  reviewPackageView: "audit.review.package.view",
  reviewPackageCreate: "audit.review.package.create",
  reviewPackageSubmit: "audit.review.package.submit",
  reviewPackageCancel: "audit.review.package.cancel",
  reviewPackageResubmit: "audit.review.package.resubmit",
  reviewPackageRefreshSnapshot: "audit.review.package.refresh_snapshot",
  reviewApprove: "audit.review.approve",
  reviewApproveWithConditions: "audit.review.approve_with_conditions",
  reviewReject: "audit.review.reject",
  reviewReturn: "audit.review.return",
  reviewRequestInfo: "audit.review.request_info",
  reviewDelegate: "audit.review.delegate",
  reviewReassign: "audit.review.reassign",
  reviewEscalate: "audit.review.escalate",
  reviewEsign: "audit.review.esign",
  reviewConditionView: "audit.review.condition.view",
  reviewConditionManage: "audit.review.condition.manage",
  reviewValidationView: "audit.review.validation.view",
  reviewValidationRun: "audit.review.validation.run",
  reviewRuleView: "audit.review.rule.view",
  reviewRuleCreate: "audit.review.rule.create",
  reviewRuleEdit: "audit.review.rule.edit",
  reviewRuleActivate: "audit.review.rule.activate",
  reviewRuleArchive: "audit.review.rule.archive",
  reviewLockSource: "audit.review.lock_source",
  reviewReopenSource: "audit.review.reopen_source",
  reviewHistoryView: "audit.review.history.view",
  reviewSettingsView: "audit.review.settings.view",
  reviewSettingsEdit: "audit.review.settings.edit",
  reportView: "audit.report.view",
  reportDashboardView: "audit.report.dashboard.view",
  reportRegisterView: "audit.report.register.view",
  reportCreate: "audit.report.create",
  reportGenerate: "audit.report.generate",
  reportRegenerate: "audit.report.regenerate",
  reportPreview: "audit.report.preview",
  reportDownload: "audit.report.download",
  reportExport: "audit.report.export",
  reportArchive: "audit.report.archive",
  reportLock: "audit.report.lock",
  reportUnlock: "audit.report.unlock",
  reportMarkHistorical: "audit.report.mark_historical",
  reportTemplateView: "audit.report.template.view",
  reportTemplateCreate: "audit.report.template.create",
  reportTemplateEdit: "audit.report.template.edit",
  reportTemplateApprove: "audit.report.template.approve",
  reportTemplateArchive: "audit.report.template.archive",
  reportPackageView: "audit.report.package.view",
  reportPackagePrepare: "audit.report.package.prepare",
  reportPackageExport: "audit.report.package.export",
  reportRestrictedView: "audit.report.restricted.view",
  reportRestrictedExport: "audit.report.restricted.export",
  reportAccessLogView: "audit.report.access_log.view",
  reportDownloadLogView: "audit.report.download_log.view",
  reportApprovalSubmit: "audit.report.approval.submit",
  reportApprovalView: "audit.report.approval.view",
  reportValidationRun: "audit.report.validation.run",
  reportHistoryView: "audit.report.history.view",
  reportSettingsView: "audit.report.settings.view",
  reportSettingsEdit: "audit.report.settings.edit",
  historyDashboardView: "audit.history.dashboard.view",
  historyTimelineView: "audit.history.timeline.view",
  historyActivityView: "audit.history.activity.view",
  historySnapshotView: "audit.history.snapshot.view",
  trendView: "audit.trend.view",
  trendDashboardView: "audit.trend.dashboard.view",
  trendRunCreate: "audit.trend.run.create",
  trendRunRecalculate: "audit.trend.run.recalculate",
  trendRunArchive: "audit.trend.run.archive",
  trendExplainabilityView: "audit.trend.explainability.view",
  trendSourceRecordsView: "audit.trend.source_records.view",
  repeatFindingView: "audit.repeat_finding.view",
  repeatFindingReview: "audit.repeat_finding.review",
  repeatFindingConfirm: "audit.repeat_finding.confirm",
  repeatFindingReject: "audit.repeat_finding.reject",
  recurringIssueView: "audit.recurring_issue.view",
  recurringIssueManage: "audit.recurring_issue.manage",
  continuousImprovementView: "audit.continuous_improvement.view",
  continuousImprovementCreate: "audit.continuous_improvement.create",
  continuousImprovementEdit: "audit.continuous_improvement.edit",
  continuousImprovementClose: "audit.continuous_improvement.close",
  continuousImprovementCreateActionFoundation: "audit.continuous_improvement.create_action_foundation",
  trendHistoryView: "audit.trend.history.view",
  trendSettingsView: "audit.trend.settings.view",
  trendSettingsEdit: "audit.trend.settings.edit",
  settingsSummaryView: "audit.settings.summary.view",
  notificationSettingsView: "audit.notification.settings.view",
  notificationSettingsEdit: "audit.notification.settings.edit",
  retentionSettingsView: "audit.retention.settings.view",
  retentionSettingsEdit: "audit.retention.settings.edit",
  globalSearchIndex: "audit.global_search.index",
  finalHardeningView: "audit.final_hardening.view",
  finalHardeningVerify: "audit.final_hardening.verify",
  finalHardeningSecurityTest: "audit.final_hardening.security_test",
  finalHardeningE2eTest: "audit.final_hardening.e2e_test",
  executionInterviewView: "audit.execution.interview.view",
  executionInterviewCreate: "audit.execution.interview.create",
  executionInterviewEdit: "audit.execution.interview.edit",
  executionWalkthroughView: "audit.execution.walkthrough.view",
  executionWalkthroughCreate: "audit.execution.walkthrough.create",
  executionWalkthroughEdit: "audit.execution.walkthrough.edit",
  executionReadinessRun: "audit.execution.readiness.run",
  executionHistoryView: "audit.execution.history.view",
  executionSettingsView: "audit.execution.settings.view",
  executionSettingsEdit: "audit.execution.settings.edit",
} as const;

export const auditPlanStatuses = [
  "Draft",
  "Planning In Progress",
  "Scheduled",
  "Pending Approval",
  "Approved",
  "Ready For Checklist",
  "Checklist In Progress Foundation",
  "Ready For Execution Foundation",
  "In Execution Foundation",
  "Completed Foundation",
  "Overdue",
  "Postponed",
  "Cancelled",
  "Superseded",
  "Archived",
] as const;
export const auditScheduleStatuses = [
  "Not Scheduled",
  "Scheduled",
  "Upcoming",
  "Due Soon",
  "Due Today",
  "Overdue",
  "Rescheduled",
  "Postponed",
  "Cancelled",
  "Completed Foundation",
] as const;
export const auditPlanReadinessStatuses = [
  "Complete",
  "Missing Program",
  "Missing Scope",
  "Missing Standards",
  "Missing Modules",
  "Missing Team",
  "Missing Lead Auditor",
  "Missing Dates",
  "Pending Approval",
  "Conflict Detected",
  "Ready For Checklist",
] as const;
export const auditPlanConflictStatuses = [
  "No Conflict",
  "Potential Conflict",
  "Hard Conflict",
  "Needs Review",
  "Resolved",
  "Override Approved",
] as const;
export const auditModes = [
  "Onsite",
  "Remote",
  "Hybrid",
  "Desktop Review",
  "Field Verification",
  "Interview-Based",
  "Document Review",
  "System Review",
] as const;
export const auditPlanCategories = [
  "Program Audit",
  "Recurring Audit",
  "One-Time Audit",
  "Triggered Audit",
  "Follow-Up Audit",
  "Regulatory Audit",
  "Corporate Audit",
  "Custom",
] as const;
export const auditTeamRoles = [
  "Lead Auditor",
  "Co-Auditor",
  "Technical Expert",
  "Process Safety Engineer",
  "HSE Representative",
  "Operations Representative",
  "Maintenance Representative",
  "Site Representative",
  "Unit Representative",
  "Contractor Representative",
  "Observer",
  "Approver",
  "Custom",
] as const;
