"use client";
import { AuditHeader } from "../AuditHeader";
import { AuditLayout } from "../AuditLayout";
import { AuditCard, AuditErrorState, AuditLoadingState } from "../shared/AuditUi";
import { useAuditCoverageMatrix } from "../hooks/useAuditCoverageMatrix";
import { AuditStandardsSummaryCards } from "./AuditStandardsSummaryCards";
import { AuditCoverageMatrixTable } from "./AuditCoverageMatrixTable";
export function AuditCoverageMatrixPage() {
  const query = useAuditCoverageMatrix();
  if (query.isLoading) return <AuditLayout><AuditLoadingState /></AuditLayout>;
  if (query.error || !query.data) return <AuditLayout><AuditErrorState message={query.error} onRetry={() => query.refetch()} /></AuditLayout>;
  return <AuditLayout><div className="space-y-5"><AuditHeader title="Standards Coverage Matrix" subtitle="Clause-by-clause mapping coverage with evidence, gap, and mapping counts generated by backend." actionHref="/audit-compliance/standards-mapping/new" /><AuditStandardsSummaryCards summary={query.data.summary} /><AuditCard title="Coverage matrix"><AuditCoverageMatrixTable rows={query.data.rows} /></AuditCard></div></AuditLayout>;
}
