import { ESignatureRequiredBadge } from '../shared/ESignatureRequiredBadge';
import { SafetyCriticalBadge } from '../shared/SafetyCriticalBadge';
import { StartupBlockedBadge } from '../shared/StartupBlockedBadge';
import { KeyValueList, ReviewCard } from './ReviewApprovalPrimitives';
import type { MiApprovalInstance } from '../types/review-approval.types';

export function RiskReadinessReviewCard({ approval }: { approval: MiApprovalInstance }) {
  return (
    <ReviewCard title="Risk / Readiness Impact" description="Approval impact flags generated by source data and approval rules.">
      <div className="mb-4 flex flex-wrap gap-2">
        <SafetyCriticalBadge value={approval.safety_critical} />
        <StartupBlockedBadge blocked={approval.startup_blocker} />
        <ESignatureRequiredBadge required={approval.e_signature_required} />
      </div>
      <KeyValueList items={[
        ['Risk level', approval.risk_level],
        ['Priority', approval.priority],
        ['PSM critical', approval.psm_critical],
        ['Readiness impact', approval.readiness_impact],
        ['Startup blocker', approval.startup_blocker],
        ['Stale approval', approval.stale_approval],
        ['Last action', approval.last_action],
        ['Workflow instance', approval.workflow_instance_id]
      ]} />
    </ReviewCard>
  );
}
