import type { PsiCompletenessGap } from '../types/psi-completeness.types';
import { PsiCard } from '../shared/PsiUi';

export function PsiPssrBlockerPanel({ rows = [] }: { rows?: PsiCompletenessGap[] }) {
  return <PsiCard title="PSSR Blockers" subtitle="Startup readiness blockers generated by the completeness engine."><ul className="space-y-2 text-sm">{rows.length ? rows.map((gap) => <li key={gap.id} className="rounded-lg border border-danger/25 bg-danger/10 p-3"><strong>{gap.gap_title}</strong><p className="text-[var(--psm-muted)]">{gap.recommended_action ?? gap.reason}</p></li>) : <li className="text-[var(--psm-muted)]">No PSSR blockers in this scope.</li>}</ul></PsiCard>;
}
