'use client';

import { useState } from 'react';
import type { PsiCompletenessRequirement } from '../types/psi-completeness.types';
import { PsiButton, PsiCard } from '../shared/PsiUi';

export function PsiRequirementForm({ initial, onSubmit, saving }: { initial?: Partial<PsiCompletenessRequirement> | undefined; onSubmit: (values: Record<string, unknown>) => void; saving?: boolean | undefined }) {
  const [values, setValues] = useState<Record<string, unknown>>({ requirement_title: initial?.requirement_title ?? initial?.requirement_name ?? '', psi_module: initial?.psi_module ?? '', requirement_category: initial?.requirement_category ?? '', applicability_scope: initial?.applicability_scope ?? 'Unit', severity_if_missing: initial?.severity_if_missing ?? 'Medium', weight: initial?.weight ?? 1, pssr_blocker_if_missing: initial?.pssr_blocker_if_missing ?? false, moc_required_if_changed: initial?.moc_required_if_changed ?? false, action_required_if_missing: initial?.action_required_if_missing ?? true, waiver_allowed: initial?.waiver_allowed ?? true, active: initial?.active ?? true });
  const set = (key: string, value: unknown) => setValues((current) => ({ ...current, [key]: value }));
  return <PsiCard title="Requirement Form" subtitle="Configure what must exist, how evidence is evaluated, and what readiness blockers are generated."><form className="grid gap-4 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); onSubmit(values); }}><input className="rounded-lg border border-[var(--psm-line)] bg-[var(--psm-surface-2)] p-3" placeholder="Requirement title" value={String(values.requirement_title ?? '')} onChange={(e) => set('requirement_title', e.target.value)} /><input className="rounded-lg border border-[var(--psm-line)] bg-[var(--psm-surface-2)] p-3" placeholder="PSI module" value={String(values.psi_module ?? '')} onChange={(e) => set('psi_module', e.target.value)} /><input className="rounded-lg border border-[var(--psm-line)] bg-[var(--psm-surface-2)] p-3" placeholder="Category" value={String(values.requirement_category ?? '')} onChange={(e) => set('requirement_category', e.target.value)} /><input className="rounded-lg border border-[var(--psm-line)] bg-[var(--psm-surface-2)] p-3" placeholder="Required evidence type" onChange={(e) => set('required_evidence_type', e.target.value)} /><select className="rounded-lg border border-[var(--psm-line)] bg-[var(--psm-surface-2)] p-3" value={String(values.severity_if_missing)} onChange={(e) => set('severity_if_missing', e.target.value)}>{['Info','Low','Medium','High','Critical','Startup Blocker'].map((item) => <option key={item}>{item}</option>)}</select><input type="number" className="rounded-lg border border-[var(--psm-line)] bg-[var(--psm-surface-2)] p-3" value={Number(values.weight ?? 1)} onChange={(e) => set('weight', Number(e.target.value))} /><label className="flex items-center gap-2"><input type="checkbox" checked={Boolean(values.pssr_blocker_if_missing)} onChange={(e) => set('pssr_blocker_if_missing', e.target.checked)} /> PSSR blocker if missing</label><label className="flex items-center gap-2"><input type="checkbox" checked={Boolean(values.moc_required_if_changed)} onChange={(e) => set('moc_required_if_changed', e.target.checked)} /> MOC required if changed</label><div className="md:col-span-2"><PsiButton type="submit" disabled={saving} title={saving ? 'Requirement save is in progress.' : undefined}>{saving ? 'Saving...' : 'Save Requirement'}</PsiButton></div></form></PsiCard>;
}
