import { BellRing, CheckCircle2, RefreshCw, RotateCcw, Send, ShieldCheck, ThumbsDown, Undo2 } from 'lucide-react';

export function ReviewSignoffHeader({ header, readOnly, busy, onSubmit, onChanges, onApprove, onReject, onReopen, onWithdraw, onReminder, onRefresh }: { header: any; readOnly: boolean; busy?: boolean; onSubmit: () => void; onChanges: () => void; onApprove: () => void; onReject: () => void; onReopen: () => void; onWithdraw: () => void; onReminder: () => void; onRefresh: () => void }) {
  const disabled = readOnly || busy;
  return <section className="rounded-xl border border-cyan-300/10 bg-[#071525] p-4"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><div className="text-lg font-black text-white">Review & Sign-Off</div><p className="mt-1 text-sm text-slate-400">Formal review, approval, electronic signature, and closure control.</p><div className="mt-3 flex flex-wrap gap-2 text-xs"><Badge value={header.reviewStatus} /><Badge value={header.approvalStatus} /><Badge value={header.signatureStatus} /><Badge value={header.currentStep} /></div><div className="mt-3 grid gap-2 text-xs text-slate-400 sm:grid-cols-3"><span>Submitted: {date(header.submittedAt)}</span><span>Approved: {date(header.approvedAt)}</span><span>Signed: {date(header.signedAt)}</span></div></div><div className="flex max-w-3xl flex-wrap gap-2"><Action disabled={disabled} title="Readiness blockers must be cleared unless an authorized override is confirmed." onClick={onSubmit}><Send size={14} /> Submit for Review</Action><Action disabled={disabled} onClick={onChanges}><Undo2 size={14} /> Request Changes</Action><Action disabled={disabled} onClick={onApprove}><CheckCircle2 size={14} /> Approve</Action><Action disabled={disabled} onClick={onReject}><ThumbsDown size={14} /> Reject</Action><Action disabled={busy} onClick={onReminder}><BellRing size={14} /> Send Reminder</Action>{readOnly ? <Action disabled={busy} onClick={onReopen}><RotateCcw size={14} /> Reopen</Action> : <Action disabled={disabled} onClick={onWithdraw}><Undo2 size={14} /> Withdraw</Action>}<Action disabled={busy} onClick={onRefresh}><RefreshCw size={14} /> Refresh</Action></div></div>{header.locked ? <div className="mt-4 flex items-center gap-2 rounded-lg border border-amber-400/20 bg-amber-500/10 p-3 text-sm text-amber-100"><ShieldCheck size={16} />Approved/closed study is locked. Reopen with a reason to create a controlled revision.</div> : null}</section>;
}

function Action({ children, disabled, title, onClick }: { children: React.ReactNode; disabled?: boolean | undefined; title?: string | undefined; onClick: () => void }) { return <button type="button" title={title} disabled={disabled} onClick={onClick} className="lopa-button-secondary disabled:cursor-not-allowed disabled:opacity-45">{children}</button>; }
function Badge({ value }: { value?: string }) { return <span className="rounded-full border border-cyan-300/15 bg-[#03101d] px-2 py-1 font-semibold text-slate-200">{value || 'Not started'}</span>; }
function date(value?: string | null) { return value ? new Date(value).toLocaleString() : '-'; }
