import type { RegulatoryBreakdown, RegulatoryHistoryEvent, RegulatoryItem, RegulatoryUser } from './regulatory.types';

export type RegulatoryObligation = {
  id: string;
  company_id?: string | null;
  site_id?: string | null;
  department_id?: string | null;
  unit_id?: string | null;
  area_id?: string | null;
  equipment_id?: string | null;
  regulatory_item_id?: string | null;
  jurisdiction_id?: string | null;
  authority_id?: string | null;
  parent_obligation_id?: string | null;
  obligation_code?: string | null;
  obligation_title?: string | null;
  obligation_type?: string | null;
  obligation_reference?: string | null;
  short_summary?: string | null;
  requirement_summary?: string | null;
  version?: string | null;
  effective_date?: string | null;
  expiry_date?: string | null;
  obligation_status?: string | null;
  obligation_status_calculated?: string | null;
  applicability_status?: string | null;
  compliance_status?: string | null;
  evidence_expectation_status?: string | null;
  module_mapping_status?: string | null;
  stale_status?: string | null;
  stale_reason?: string | null;
  category?: string | null;
  topic?: string | null;
  related_psm_element?: string | null;
  related_module?: string | null;
  criticality?: string | null;
  risk_basis?: string | null;
  frequency?: string | null;
  due_date?: string | null;
  start_date?: string | null;
  next_due_date?: string | null;
  last_completed_date?: string | null;
  trigger_event?: string | null;
  owner_user_id?: string | null;
  compliance_owner_user_id?: string | null;
  reviewer_user_id?: string | null;
  review_frequency?: string | null;
  next_review_date?: string | null;
  evidence_required?: boolean | null;
  action_required_foundation?: boolean | null;
  capa_required_foundation?: boolean | null;
  status_rationale?: string | null;
  applicability_rationale?: string | null;
  scope_change_reason?: string | null;
  notes?: string | null;
  linked_audit_count?: number | null;
  linked_evidence_count?: number | null;
  linked_action_count?: number | null;
  due_status?: string | null;
  parent_requirement_label?: string | null;
  owner_label?: string | null;
  owner?: RegulatoryUser | null;
  complianceOwner?: RegulatoryUser | null;
  reviewer?: RegulatoryUser | null;
  parent?: RegulatoryItem | null;
  readOnly?: boolean | null;
  readOnlyReason?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
};

export type RegulatoryObligationRegister = {
  rows: RegulatoryObligation[];
  allRows?: RegulatoryObligation[];
  total: number;
  page: number;
  limit: number;
  hasMore?: boolean;
  summary?: Record<string, number>;
};

export type RegulatoryObligationGap = {
  id: string;
  regulatory_item_id?: string | null;
  obligation_id?: string | null;
  jurisdiction_id?: string | null;
  gap_type?: string | null;
  gap_title?: string | null;
  gap_description?: string | null;
  gap_status?: string | null;
  severity?: string | null;
  criticality?: string | null;
  owner_user_id?: string | null;
  due_date?: string | null;
  recommended_fix?: string | null;
  action_id?: string | null;
  waiver_reason?: string | null;
  detected_at?: string | null;
  resolved_at?: string | null;
  resolution_note?: string | null;
  updated_at?: string | null;
};

export type RegulatoryObligationDashboard = {
  header?: { title?: string; subtitle?: string; generatedAt?: string };
  summary?: Record<string, number>;
  byParentRequirement?: RegulatoryBreakdown[];
  byJurisdiction?: RegulatoryBreakdown[];
  bySite?: RegulatoryBreakdown[];
  byUnit?: RegulatoryBreakdown[];
  byCategory?: RegulatoryBreakdown[];
  byPsmElement?: RegulatoryBreakdown[];
  byRelatedModule?: RegulatoryBreakdown[];
  byCriticality?: RegulatoryBreakdown[];
  byOwner?: RegulatoryBreakdown[];
  dueSoonPreview?: RegulatoryObligation[];
  overduePreview?: RegulatoryObligation[];
  missingOwnerPreview?: RegulatoryObligation[];
  missingEvidenceExpectationPreview?: RegulatoryObligation[];
  missingModuleMappingPreview?: RegulatoryObligation[];
  highRiskPreview?: RegulatoryObligation[];
  psmCriticalPreview?: RegulatoryObligation[];
  stalePreview?: RegulatoryObligation[];
  recentChanges?: RegulatoryObligation[];
  readinessSummary?: { status?: string; blockers?: Array<{ key: string; label: string; count: number }> };
  openGaps?: RegulatoryObligationGap[];
};

export type RegulatoryObligationDetail = {
  obligation: RegulatoryObligation;
  overviewCards?: Record<string, unknown>;
  parentRequirement?: RegulatoryItem | null;
  scopes?: { rows: Array<Record<string, unknown>> };
  evidenceExpectations?: { rows: Array<Record<string, unknown>> };
  moduleMappings?: { rows: Array<Record<string, unknown>> };
  links?: { rows: Array<Record<string, unknown>>; summary?: RegulatoryBreakdown[] };
  gaps?: { rows: RegulatoryObligationGap[] };
  historyPreview?: RegulatoryHistoryEvent[];
  readiness?: { status?: string; blockers?: Array<Record<string, unknown>>; openGaps?: number };
  readOnly?: boolean;
  readOnlyReason?: string | null;
  placeholder?: string;
};

export type RegulatoryObligationLookups = {
  obligationTypes: string[];
  obligationCategories: string[];
  obligationStatuses: string[];
  obligationFrequencies: string[];
  obligationTriggerEvents: string[];
  evidenceExpectationStatuses: string[];
  moduleMappingStatuses: string[];
  obligationGapTypes: string[];
  obligationStaleStatuses: string[];
  criticalityLevels: string[];
  complianceStatuses: string[];
  linkModules: string[];
};
