import type { PsiCompletenessDashboard, PsiCompletenessGap, PsiCompletenessMatrixRow, PsiCompletenessRequirement, PsiCompletenessResponse, PsiCompletenessRun, PsiCompletenessScore, PsiCompletenessSettings, PsiCompletenessWaiver, PsiPaged } from '../types/psi-completeness.types';
import { get, patch, post, remove } from './psi-api';

const base = '/process-safety-information';

export const psiCompletenessService = {
  get: (unitId: string) => get<PsiCompletenessResponse>(`${base}/units/${unitId}/completeness`),
  unitCompleteness: (unitId: string) => get<PsiCompletenessResponse>(`${base}/units/${unitId}/completeness`),
  equipmentCompleteness: (equipmentId: string) => get<Record<string, unknown>>(`${base}/equipment/${equipmentId}/completeness`),
  dashboard: (params: Record<string, unknown> = {}) => get<PsiCompletenessDashboard>(`${base}/completeness/dashboard`, params),
  scores: (params: Record<string, unknown> = {}) => get<PsiCompletenessScore[]>(`${base}/completeness/scores`, params),
  scoresByUnit: (params: Record<string, unknown> = {}) => get<PsiCompletenessScore[]>(`${base}/completeness/scores/by-unit`, params),
  scoresByModule: (params: Record<string, unknown> = {}) => get<PsiCompletenessScore[]>(`${base}/completeness/scores/by-module`, params),
  matrix: (params: Record<string, unknown> = {}) => get<PsiPaged<PsiCompletenessMatrixRow>>(`${base}/completeness/matrix`, params),
  unitMatrix: (unitId: string, params: Record<string, unknown> = {}) => get<PsiPaged<PsiCompletenessMatrixRow>>(`${base}/units/${unitId}/completeness/matrix`, params),
  equipmentMatrix: (equipmentId: string, params: Record<string, unknown> = {}) => get<PsiPaged<PsiCompletenessMatrixRow>>(`${base}/equipment/${equipmentId}/completeness/matrix`, params),
  gaps: (params: Record<string, unknown> = {}) => get<PsiPaged<PsiCompletenessGap>>(`${base}/completeness/gaps`, params),
  criticalGaps: (params: Record<string, unknown> = {}) => get<PsiPaged<PsiCompletenessGap>>(`${base}/completeness/critical-gaps`, params),
  pssrBlockers: (params: Record<string, unknown> = {}) => get<PsiPaged<PsiCompletenessGap>>(`${base}/completeness/pssr-blockers`, params),
  mocRequired: (params: Record<string, unknown> = {}) => get<PsiPaged<PsiCompletenessGap>>(`${base}/completeness/moc-required`, params),
  reviewOverdue: (params: Record<string, unknown> = {}) => get<PsiPaged<PsiCompletenessGap>>(`${base}/completeness/review-overdue`, params),
  documentGaps: (params: Record<string, unknown> = {}) => get<PsiPaged<PsiCompletenessGap>>(`${base}/completeness/document-gaps`, params),
  conflicts: (params: Record<string, unknown> = {}) => get<PsiPaged<PsiCompletenessGap>>(`${base}/completeness/conflicts`, params),
  gapDetail: (gapId: string) => get<Record<string, unknown>>(`${base}/completeness/gaps/${gapId}`),
  patchGap: (gapId: string, input: Record<string, unknown>) => patch<PsiCompletenessGap>(`${base}/completeness/gaps/${gapId}`, input),
  assignGap: (gapId: string, input: Record<string, unknown>) => post<PsiCompletenessGap>(`${base}/completeness/gaps/${gapId}/assign`, input),
  createAction: (gapId: string, input: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/completeness/gaps/${gapId}/create-action`, input),
  markResolved: (gapId: string, input: Record<string, unknown>) => post<PsiCompletenessGap>(`${base}/completeness/gaps/${gapId}/mark-resolved`, input),
  verifyGap: (gapId: string, input: Record<string, unknown>) => post<PsiCompletenessGap>(`${base}/completeness/gaps/${gapId}/verify`, input),
  reopenGap: (gapId: string, input: Record<string, unknown>) => post<PsiCompletenessGap>(`${base}/completeness/gaps/${gapId}/reopen`, input),
  requirements: (params: Record<string, unknown> = {}) => get<PsiCompletenessRequirement[]>(`${base}/completeness/requirements`, params),
  createRequirement: (input: Record<string, unknown>) => post<PsiCompletenessRequirement>(`${base}/completeness/requirements`, input),
  requirement: (requirementId: string) => get<PsiCompletenessRequirement>(`${base}/completeness/requirements/${requirementId}`),
  updateRequirement: (requirementId: string, input: Record<string, unknown>) => patch<PsiCompletenessRequirement>(`${base}/completeness/requirements/${requirementId}`, input),
  archiveRequirement: (requirementId: string, input: Record<string, unknown>) => remove<PsiCompletenessRequirement>(`${base}/completeness/requirements/${requirementId}`, input),
  templates: () => get<Record<string, unknown>[]>(`${base}/completeness/templates`),
  applyTemplates: (input: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/completeness/templates/apply`, input),
  run: (input: string | Record<string, unknown> = {}) => typeof input === 'string' ? post<PsiCompletenessResponse>(`${base}/units/${input}/completeness/run`) : post<Record<string, unknown>>(`${base}/completeness/run`, input),
  runUnit: (unitId: string, input: Record<string, unknown> = {}) => post<Record<string, unknown>>(`${base}/units/${unitId}/completeness/run`, input),
  runEquipment: (equipmentId: string, input: Record<string, unknown> = {}) => post<Record<string, unknown>>(`${base}/equipment/${equipmentId}/completeness/run`, input),
  runHistory: (params: Record<string, unknown> = {}) => get<PsiCompletenessRun[]>(`${base}/completeness/run-history`, params),
  runDetail: (runId: string) => get<Record<string, unknown>>(`${base}/completeness/run-history/${runId}`),
  retryRun: (runId: string) => post<Record<string, unknown>>(`${base}/completeness/run-history/${runId}/retry`),
  cancelRun: (runId: string, input: Record<string, unknown>) => post<PsiCompletenessRun>(`${base}/completeness/run-history/${runId}/cancel`, input),
  waivers: (params: Record<string, unknown> = {}) => get<PsiCompletenessWaiver[]>(`${base}/completeness/waivers`, params),
  requestWaiver: (input: Record<string, unknown>) => post<PsiCompletenessWaiver>(`${base}/completeness/waivers/request`, input),
  approveWaiver: (waiverId: string, input: Record<string, unknown>) => post<PsiCompletenessWaiver>(`${base}/completeness/waivers/${waiverId}/approve`, input),
  rejectWaiver: (waiverId: string, input: Record<string, unknown>) => post<PsiCompletenessWaiver>(`${base}/completeness/waivers/${waiverId}/reject`, input),
  revokeWaiver: (waiverId: string, input: Record<string, unknown>) => post<PsiCompletenessWaiver>(`${base}/completeness/waivers/${waiverId}/revoke`, input),
  settings: () => get<PsiCompletenessSettings>(`${base}/completeness/settings`),
  updateSettings: (input: Record<string, unknown>) => patch<PsiCompletenessSettings>(`${base}/completeness/settings`, input),
  exportRows: (params: Record<string, unknown> = {}) => get<Record<string, unknown>>(`${base}/completeness/export`, params),
  reports: () => get<Record<string, unknown>>(`${base}/completeness/reports`),
  generateReport: (input: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/completeness/reports/generate`, input),
  lookups: (kind: string) => get<string[]>(`${base}/lookups/${kind}`)
};
