"use client";
import type { AuditCapaDetail } from "../../types/audit-capa.types";
import { useAuditCapaMutations } from "../../hooks/useAuditCapaMutations";
import { AuditButton, AuditCard } from "../../shared/AuditUi";
import { AuditCapaClosureReadinessBadge } from "../../shared/AuditCapaClosureReadinessBadge";

export function CapaClosureReadinessTab({ detail }: { detail: AuditCapaDetail }) {
  const mutations = useAuditCapaMutations(detail.capa.id);
  const checks = detail.readiness.length ? detail.readiness : [{ id: "calculated", readiness_status: detail.capa.closure_readiness_status, blocker_title: "Calculated readiness", blocker_description: detail.calculated?.missingItems?.join("; ") || "No missing items reported." }];
  return (
    <AuditCard title="Closure readiness / missing data" subtitle="Closure readiness is generated by the backend from findings, action completion, evidence, verification, effectiveness, review, and policy settings." action={<AuditButton onClick={() => mutations.runClosureReadiness.mutate()} disabled={mutations.runClosureReadiness.isPending} title="Run backend closure readiness">Run Readiness</AuditButton>}>
      <div className="mb-4"><AuditCapaClosureReadinessBadge value={detail.capa.closure_readiness_status} /></div>
      <div className="grid gap-3 lg:grid-cols-2">{checks.map((row) => <div key={row.id} className="rounded-xl border border-[var(--psm-line)] bg-[var(--psm-surface-2)] p-4"><p className="font-semibold text-[var(--psm-fg)]">{row.blocker_title ?? row.check_name ?? "Readiness check"}</p><p className="mt-1 text-sm text-[var(--psm-muted)]">{row.blocker_description ?? row.readiness_status ?? "-"}</p></div>)}</div>
    </AuditCard>
  );
}
