import { Archive, Download, Eye, RefreshCw, Trash2 } from 'lucide-react';
import type { HazopAttachment } from '../../types/hazop-attachment.types';
import { HazopAttachmentReviewStatusBadge } from './HazopAttachmentReviewStatusBadge';
import { HazopAttachmentTypeBadge } from './HazopAttachmentTypeBadge';

export function HazopAttachmentRegister({ rows, readonly, canDownload, canReplace, canArchive, canDelete, onPreview, onDownload, onReplace, onArchive, onDelete }: { rows: HazopAttachment[]; readonly?: boolean; canDownload?: boolean; canReplace?: boolean; canArchive?: boolean; canDelete?: boolean; onPreview: (row: HazopAttachment) => void; onDownload: (row: HazopAttachment) => void; onReplace: (row: HazopAttachment) => void; onArchive: (row: HazopAttachment) => void; onDelete: (row: HazopAttachment) => void }) {
  return <div className="overflow-hidden rounded-xl border border-[var(--psm-line)] bg-[var(--psm-surface)]"><div className="flex items-center justify-between border-b border-[var(--psm-line)] p-4"><h3 className="font-semibold">Attachment Register</h3><span className="text-xs text-[var(--psm-muted)]">{rows.length} files</span></div><div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-sm"><thead className="bg-[var(--psm-surface-2)] text-xs uppercase text-[var(--psm-muted)]"><tr>{['File', 'Type', 'Category', 'Linked Section', 'Uploaded', 'Size', 'Review', 'Visibility', 'Version', 'Storage', 'Scan', 'Actions'].map((head) => <th key={head} className="px-4 py-3 text-left">{head}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t border-[var(--psm-line)] hover:bg-[var(--psm-surface-2)]"><td className="px-4 py-3"><button onClick={() => onPreview(row)} className="text-left"><div className="font-semibold">{row.file_name}</div><div className="text-xs text-[var(--psm-muted)]">{row.description ?? 'No description'}</div></button></td><td className="px-4 py-3"><HazopAttachmentTypeBadge type={row.file_type} mime={row.mime_type} /></td><td className="px-4 py-3">{row.category}</td><td className="px-4 py-3">{row.linked_section}</td><td className="px-4 py-3 text-xs text-[var(--psm-muted)]">{row.uploadedBy?.displayName ?? row.uploaded_by ?? '-'}<br />{row.uploaded_at ? new Date(row.uploaded_at).toLocaleString() : '-'}</td><td className="px-4 py-3">{formatBytes(row.file_size ?? 0)}</td><td className="px-4 py-3"><HazopAttachmentReviewStatusBadge value={row.review_status} /></td><td className="px-4 py-3">{row.visibility}</td><td className="px-4 py-3">v{row.version ?? 1}</td><td className="px-4 py-3">{row.storage_status ?? (row.storage_key ? 'Stored' : 'Metadata')}</td><td className="px-4 py-3">{row.scan_status ?? '-'}</td><td className="px-4 py-3"><div className="flex gap-2"><button title="Preview" onClick={() => onPreview(row)} className="rounded-lg border border-[var(--psm-line)] p-2"><Eye size={14} /></button>{canDownload ? <button title="Download" onClick={() => onDownload(row)} className="rounded-lg border border-[var(--psm-line)] p-2"><Download size={14} /></button> : null}{canReplace && !readonly ? <button title="Replace" onClick={() => onReplace(row)} className="rounded-lg border border-[var(--psm-line)] p-2"><RefreshCw size={14} /></button> : null}{canArchive && !readonly ? <button title="Archive" onClick={() => onArchive(row)} className="rounded-lg border border-amber-500/30 p-2 text-amber-200"><Archive size={14} /></button> : null}{canDelete && !readonly ? <button title="Delete" onClick={() => onDelete(row)} className="rounded-lg border border-red-500/30 p-2 text-red-200"><Trash2 size={14} /></button> : null}</div></td></tr>)}</tbody></table></div>{!rows.length ? <div className="p-8 text-center text-sm text-[var(--psm-muted)]">No attachments match the current filters.</div> : null}</div>;
}

function formatBytes(bytes: number) {
  if (!bytes) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB'];
  const index = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
  return `${(bytes / Math.pow(1024, index)).toFixed(index ? 1 : 0)} ${units[index]}`;
}
