import type { HazopAttachmentFilters as FilterState } from '../../types/hazop-attachment.types';

export const attachmentCategories = ['All', 'Study scope document', 'P&ID snapshot / reference copy', 'Field photo', 'Equipment photo', 'Process sketch', 'HAZOP worksheet import/export', 'Meeting minutes', 'Attendance evidence', 'Risk acceptance evidence', 'Recommendation evidence', 'Safeguard/IPL evidence', 'Proof test evidence', 'Vendor document', 'Engineering calculation', 'Incident evidence', 'MOC evidence', 'PSSR evidence', 'Training evidence', 'Email / correspondence', 'Management approval', 'Other'];
export const linkedSections = ['All', 'Overview', 'Nodes & Deviations', 'Risk Ranking', 'Safeguards / IPL', 'Recommendations / Actions', 'Team & Sessions', 'Linked Records', 'Review & Sign-Off', 'Final Report', 'General'];

export function HazopAttachmentFilters({ filters, onChange }: { filters: FilterState; onChange: (filters: FilterState) => void }) {
  const set = (key: keyof FilterState, value: string) => onChange({ ...filters, [key]: value });
  return <div className="grid gap-3 rounded-xl border border-[var(--psm-line)] bg-[var(--psm-surface)] p-3 lg:grid-cols-[1fr_220px_200px_180px_160px]"><input className="input" value={filters.search ?? ''} placeholder="Search file, category, tags, description..." onChange={(e) => set('search', e.target.value)} /><select className="input" value={filters.category ?? 'All'} onChange={(e) => set('category', e.target.value)}>{attachmentCategories.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={filters.linkedSection ?? 'All'} onChange={(e) => set('linkedSection', e.target.value)}>{linkedSections.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={filters.reviewStatus ?? 'All'} onChange={(e) => set('reviewStatus', e.target.value)}><option>All</option><option>Pending Review</option><option>Approved</option><option>Rejected</option><option>Not Required</option></select><select className="input" value={filters.visibility ?? 'All'} onChange={(e) => set('visibility', e.target.value)}><option>All</option><option>Study Team</option><option>Restricted</option><option>Confidential</option><option>Public Internal</option></select></div>;
}
