'use client';

import { Bell, CheckCircle2, Send, Users } from 'lucide-react';
import { Badge, DetailCard, EmptyState, Field, Metric, ProgressBar, detailInput, detailTextarea, statusTone } from '../moc-detail-ui';

const btn = 'inline-flex items-center justify-center gap-2 rounded-md border border-cyan-300/15 px-3 py-2 text-xs font-black text-slate-100 hover:border-blue-300/50 hover:bg-blue-500/10';
const primary = 'inline-flex items-center justify-center gap-2 rounded-md bg-blue-600 px-3 py-2 text-xs font-black text-white hover:bg-blue-500';

export function CommunicationTrainingSummaryCard({ summary }: { summary: any }) {
  return <DetailCard title="Communication & Training Summary"><div className="grid gap-3 md:grid-cols-5"><Metric label="Communication" value={summary?.communicationStatus ?? 'Not Started'} tone={statusTone(summary?.communicationStatus)} /><Metric label="Training Required" value={summary?.trainingRequired ? 'Yes' : 'No'} tone={summary?.trainingRequired ? 'amber' : 'slate'} /><Metric label="Training" value={`${summary?.trainingCompletionPercent ?? 0}%`} tone={(summary?.trainingCompletionPercent ?? 0) === 100 ? 'green' : 'amber'} /><Metric label="Acknowledgement" value={`${summary?.acknowledgementCompletionPercent ?? 0}%`} tone={(summary?.acknowledgementCompletionPercent ?? 0) === 100 ? 'green' : 'amber'} /><Metric label="Blockers" value={summary?.startupBlockingTrainingIncompleteCount ?? 0} tone={(summary?.startupBlockingTrainingIncompleteCount ?? 0) ? 'red' : 'green'} /></div><div className="mt-4 grid gap-3 md:grid-cols-4"><Info label="Total Stakeholders" value={summary?.totalStakeholders ?? 0} /><Info label="Pending Acknowledgements" value={summary?.pendingAcknowledgements ?? 0} /><Info label="Required Roles" value={(summary?.requiredTrainingRoles ?? []).join(', ') || '-'} /><Info label="Last Communication" value={summary?.lastCommunicationSent ? new Date(summary.lastCommunicationSent).toLocaleString() : '-'} /></div></DetailCard>;
}

export function StakeholdersPanel({ rows, draft, setDraft, onAdd, onImportImpact, onImportEquipment }: any) {
  return <DetailCard title="Stakeholders / Affected Groups Panel" action={<div className="flex gap-2"><button className={btn} onClick={onImportImpact}>Import Impact</button><button className={btn} onClick={onImportEquipment}>Import Equipment</button></div>}><div className="grid gap-3 md:grid-cols-4"><Field label="Stakeholder Type"><select className={detailInput} value={draft.stakeholderType} onChange={(e) => setDraft((v: any) => ({ ...v, stakeholderType: e.target.value }))}>{['Operations','Maintenance','Engineering','HSE','Control Room','Contractors','Production Planning','Quality','Laboratory','Inspection / Mechanical Integrity','Management','Security','Emergency Response','Other'].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Notes"><input className={detailInput} value={draft.notes ?? ''} onChange={(e) => setDraft((v: any) => ({ ...v, notes: e.target.value }))} /></Field><label className="mt-6 flex items-center gap-2 text-sm text-slate-300"><input type="checkbox" checked={Boolean(draft.acknowledgementRequired)} onChange={(e) => setDraft((v: any) => ({ ...v, acknowledgementRequired: e.target.checked }))} /> Ack required</label><button className={primary} onClick={onAdd}><Users className="h-4 w-4" /> Add Stakeholder</button></div><div className="mt-4 grid gap-2">{rows?.length ? rows.map((row: any) => <div key={row.id} className="rounded-lg border border-white/10 bg-white/[0.03] p-3"><div className="flex items-center justify-between"><p className="font-black text-white">{row.stakeholder_type}</p><Badge tone={row.training_required ? 'amber' : 'slate'}>{row.training_required ? 'Training' : 'Comms'}</Badge></div><p className="mt-1 text-xs text-slate-500">Ack {row.acknowledgement_required ? 'required' : 'not required'} · Startup {row.required_before_startup ? 'yes' : 'no'} · Closure {row.required_before_closure ? 'yes' : 'no'}</p><p className="mt-1 text-sm text-slate-300">{row.notes}</p></div>) : <EmptyState title="No stakeholders or affected groups yet." />}</div></DetailCard>;
}

export function CommunicationPlanPanel({ plan, draft, setDraft, onSave, onSend, onSchedule }: any) {
  return <DetailCard title="Communication Plan Panel" action={<div className="flex gap-2"><button className={btn} onClick={onSchedule}>Schedule</button><button className={primary} onClick={onSend}><Send className="h-4 w-4" /> Send</button></div>}><div className="grid gap-3 md:grid-cols-2"><Field label="Objective"><input className={detailInput} value={draft.objective ?? ''} onChange={(e) => setDraft((v: any) => ({ ...v, objective: e.target.value }))} /></Field><Field label="Method"><select className={detailInput} value={draft.method ?? 'In-app notification'} onChange={(e) => setDraft((v: any) => ({ ...v, method: e.target.value }))}>{['Email','In-app notification','Toolbox talk','Shift briefing','Control room briefing','Training session','Contractor briefing','Meeting','Other'].map((m) => <option key={m}>{m}</option>)}</select></Field><Field label="Effective Date"><input className={detailInput} type="date" value={draft.effectiveDate ?? ''} onChange={(e) => setDraft((v: any) => ({ ...v, effectiveDate: e.target.value }))} /></Field><Field label="Planned Date"><input className={detailInput} type="datetime-local" value={String(draft.plannedDate ?? '').slice(0, 16)} onChange={(e) => setDraft((v: any) => ({ ...v, plannedDate: e.target.value }))} /></Field><Field label="Message Summary"><textarea className={detailTextarea} value={draft.messageSummary ?? ''} onChange={(e) => setDraft((v: any) => ({ ...v, messageSummary: e.target.value }))} /></Field><Field label="Safety Precautions"><textarea className={detailTextarea} value={draft.safetyPrecautions ?? ''} onChange={(e) => setDraft((v: any) => ({ ...v, safetyPrecautions: e.target.value }))} /></Field></div><button className={`${btn} mt-4`} onClick={onSave}>Save Communication Plan</button><p className="mt-2 text-xs text-slate-500">Current status: {plan?.status ?? 'Not Started'}</p></DetailCard>;
}

export function CommunicationLogTable({ rows, onResend, onReminder }: any) {
  return <DetailCard title="Communication Log">{rows?.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr>{['ID','Method','Subject','Sent To','Sent By','Sent At','Status','Actions'].map((h) => <th key={h} className="border-b border-white/10 px-3 py-2">{h}</th>)}</tr></thead><tbody>{rows.map((row: any) => <tr key={row.id} className="border-b border-white/5 text-slate-300"><td className="px-3 py-3">{row.communication_number ?? row.id.slice(0,8)}</td><td className="px-3 py-3">{row.method}</td><td className="px-3 py-3">{row.subject}</td><td className="px-3 py-3">{row.sent_to?.length ?? 0}</td><td className="px-3 py-3">{row.sent_by}</td><td className="px-3 py-3">{row.sent_at ? new Date(row.sent_at).toLocaleString() : '-'}</td><td className="px-3 py-3"><Badge tone={statusTone(row.status)}>{row.status}</Badge></td><td className="px-3 py-3"><button className={btn} onClick={() => onResend(row.id)}>Resend</button><button className={`${btn} ml-2`} onClick={() => onReminder(row.id)}><Bell className="h-3 w-3" /> Reminder</button></td></tr>)}</tbody></table></div> : <EmptyState title="No communication logs yet." />}</DetailCard>;
}

export function AcknowledgementTracker({ rows, onAck, onWaive }: any) {
  return <DetailCard title="Acknowledgement Tracker">{rows?.length ? <div className="grid gap-2">{rows.map((row: any) => <div key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-white/10 bg-white/[0.03] p-3"><div><p className="font-bold text-white">{row.user_id ?? row.role_id ?? row.stakeholder_id ?? 'Group acknowledgement'}</p><p className="text-xs text-slate-500">Reminders {row.reminder_count ?? 0} · {row.acknowledged_at ? new Date(row.acknowledged_at).toLocaleString() : 'Pending'}</p></div><Badge tone={statusTone(row.status)}>{row.status}</Badge><div className="flex gap-2"><button className={btn} onClick={() => onAck(row.id)}><CheckCircle2 className="h-4 w-4" /> Acknowledge</button><button className={btn} onClick={() => onWaive(row.id)}>Waive</button></div></div>)}</div> : <EmptyState title="No acknowledgement assignments yet." />}</DetailCard>;
}

export function StartupTrainingBlockersPanel({ rows }: any) {
  return <DetailCard title="Startup Training Blockers Panel">{rows?.length ? <div className="space-y-2">{rows.map((row: any) => <div key={`${row.type}-${row.id}`} className="rounded-lg border border-red-300/20 bg-red-500/10 p-3"><p className="font-black text-red-100">{row.title}</p><p className="text-xs text-red-200/80">{row.type} · {row.severity}</p></div>)}</div> : <EmptyState title="No communication or training startup blockers." />}</DetailCard>;
}

function Info({ label, value }: any) {
  return <div><p className="text-xs uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 font-bold text-slate-100">{value ?? '-'}</p></div>;
}
