'use client';

import { useRegulatoryItemHistory } from '../hooks/useRegulatoryHistory';
import { RegulatoryCard, RegulatoryErrorState, RegulatoryLoadingState } from '../shared/RegulatoryUi';

export function RegulatoryHistoryTab({ id }: { id: string }) {
  const query = useRegulatoryItemHistory(id);
  if (query.isLoading) return <RegulatoryLoadingState rows={4} />;
  if (query.isError) return <RegulatoryErrorState message={query.error} onRetry={() => query.refetch()} />;
  return (
    <RegulatoryCard title="Regulatory History" subtitle="Immutable regulatory history events generated by backend mutations and audit hooks.">
      {query.data?.rows?.length ? <div className="space-y-3">{query.data.rows.map((event) => <div key={event.id} className="rounded-lg border border-[var(--psm-line)] bg-[var(--psm-surface-2)] p-3"><div className="font-semibold text-[var(--psm-fg)]">{event.event_title}</div><div className="mt-1 text-xs text-[var(--psm-muted)]">{event.event_type} · {event.created_at ? new Date(event.created_at).toLocaleString() : 'No timestamp'}</div>{event.event_description ? <p className="mt-2 text-sm text-[var(--psm-muted)]">{event.event_description}</p> : null}</div>)}</div> : <p className="text-sm text-[var(--psm-muted)]">No history events are available for this item.</p>}
    </RegulatoryCard>
  );
}
