import { get, patch, post, remove } from '@/features/audit/services/audit-api';
import type {
  RegulatoryEvidenceAccessEvent,
  RegulatoryEvidenceDashboard,
  RegulatoryEvidenceDetail,
  RegulatoryEvidenceGap,
  RegulatoryEvidenceHistoryResponse,
  RegulatoryEvidenceLink,
  RegulatoryEvidenceLookups,
  RegulatoryEvidencePackage,
  RegulatoryEvidencePackageDetail,
  RegulatoryEvidenceRegister,
  RegulatoryEvidenceRequest,
  RegulatoryEvidenceRequirement
} from '../types/regulatory-evidence.types';

const base = '/regulatory/evidence';

export const regulatoryEvidenceService = {
  dashboard: (params?: Record<string, unknown>) => get<RegulatoryEvidenceDashboard>(base, params),
  dashboardSummary: (params?: Record<string, unknown>) => get<Record<string, number>>(`${base}/dashboard/summary`, params),
  register: (params?: Record<string, unknown>) => get<RegulatoryEvidenceRegister>(`${base}/register`, params),
  filtered: (view: string, params?: Record<string, unknown>) => get<RegulatoryEvidenceRegister>(`${base}/${view}`, params),
  requirements: (params?: Record<string, unknown>) => get<{ rows: RegulatoryEvidenceRequirement[]; total: number; summary?: Record<string, number> }>(`${base}/requirements`, params),
  requirement: (requirementId: string) => get<RegulatoryEvidenceRequirement>(`${base}/requirements/${requirementId}`),
  createRequirement: (data: Record<string, unknown>) => post<RegulatoryEvidenceRequirement>(`${base}/requirements`, data),
  updateRequirement: (requirementId: string, data: Record<string, unknown>) => patch<RegulatoryEvidenceRequirement>(`${base}/requirements/${requirementId}`, data),
  archiveRequirement: (requirementId: string, reason: string) => post<RegulatoryEvidenceRequirement>(`${base}/requirements/${requirementId}/archive`, { reason }),
  reactivateRequirement: (requirementId: string, data?: Record<string, unknown>) => post<RegulatoryEvidenceRequirement>(`${base}/requirements/${requirementId}/reactivate`, data ?? {}),
  links: (params?: Record<string, unknown>) => get<RegulatoryEvidenceRegister>(`${base}/links`, params),
  link: (evidenceLinkId: string) => get<RegulatoryEvidenceLink>(`${base}/links/${evidenceLinkId}`),
  createLink: (data: Record<string, unknown>) => post<RegulatoryEvidenceLink>(`${base}/links`, data),
  updateLink: (evidenceLinkId: string, data: Record<string, unknown>) => patch<RegulatoryEvidenceLink>(`${base}/links/${evidenceLinkId}`, data),
  removeLink: (evidenceLinkId: string, reason: string) => remove<RegulatoryEvidenceLink>(`${base}/links/${evidenceLinkId}`, { reason }),
  replaceLink: (evidenceLinkId: string, data: Record<string, unknown>) => post<RegulatoryEvidenceLink>(`${base}/links/${evidenceLinkId}/replace`, data),
  archiveLink: (evidenceLinkId: string, reason: string) => post<RegulatoryEvidenceLink>(`${base}/links/${evidenceLinkId}/archive`, { reason }),
  markStale: (evidenceLinkId: string, data: Record<string, unknown>) => post<RegulatoryEvidenceLink>(`${base}/links/${evidenceLinkId}/mark-stale`, data),
  restrict: (evidenceLinkId: string, data: Record<string, unknown>) => post<RegulatoryEvidenceLink>(`${base}/links/${evidenceLinkId}/restrict`, data),
  preview: (evidenceLinkId: string) => get<RegulatoryEvidenceDetail>(`${base}/links/${evidenceLinkId}/preview`),
  download: (evidenceLinkId: string) => get<RegulatoryEvidenceDetail>(`${base}/links/${evidenceLinkId}/download`),
  submitReview: (evidenceLinkId: string, data: Record<string, unknown>) => post<RegulatoryEvidenceLink>(`${base}/links/${evidenceLinkId}/submit-review`, data),
  verify: (evidenceLinkId: string, data: Record<string, unknown>) => post<RegulatoryEvidenceDetail>(`${base}/links/${evidenceLinkId}/verify`, data),
  reject: (evidenceLinkId: string, data: Record<string, unknown>) => post<RegulatoryEvidenceDetail>(`${base}/links/${evidenceLinkId}/reject`, data),
  requestRework: (evidenceLinkId: string, data: Record<string, unknown>) => post<RegulatoryEvidenceDetail>(`${base}/links/${evidenceLinkId}/request-rework`, data),
  waive: (evidenceLinkId: string, data: Record<string, unknown>) => post<RegulatoryEvidenceDetail>(`${base}/links/${evidenceLinkId}/waive`, data),
  reviews: (params?: Record<string, unknown>) => get<RegulatoryEvidenceRegister>(`${base}/review`, params),
  requests: (params?: Record<string, unknown>) => get<{ rows: RegulatoryEvidenceRequest[]; total: number; summary?: Record<string, number> }>(`${base}/requests`, params),
  createRequest: (data: Record<string, unknown>) => post<RegulatoryEvidenceRequest>(`${base}/requests`, data),
  request: (requestId: string) => get<RegulatoryEvidenceRequest>(`${base}/requests/${requestId}`),
  updateRequest: (requestId: string, data: Record<string, unknown>) => patch<RegulatoryEvidenceRequest>(`${base}/requests/${requestId}`, data),
  fulfillRequest: (requestId: string, data: Record<string, unknown>) => post<RegulatoryEvidenceRequest>(`${base}/requests/${requestId}/fulfill`, data),
  cancelRequest: (requestId: string, reason: string) => post<RegulatoryEvidenceRequest>(`${base}/requests/${requestId}/cancel`, { reason }),
  gaps: (params?: Record<string, unknown>) => get<{ rows: RegulatoryEvidenceGap[]; total: number; summary?: Record<string, number> }>(`${base}/gaps`, params),
  detectGaps: (data?: Record<string, unknown>) => post<{ rows: RegulatoryEvidenceGap[]; total: number }>(`${base}/gaps/detect`, data ?? {}),
  createGap: (data: Record<string, unknown>) => post<RegulatoryEvidenceGap>(`${base}/gaps`, data),
  gap: (gapId: string) => get<RegulatoryEvidenceGap>(`${base}/gaps/${gapId}`),
  updateGap: (gapId: string, data: Record<string, unknown>) => patch<RegulatoryEvidenceGap>(`${base}/gaps/${gapId}`, data),
  resolveGap: (gapId: string, reason: string) => post<RegulatoryEvidenceGap>(`${base}/gaps/${gapId}/resolve`, { reason }),
  archiveGap: (gapId: string, reason: string) => post<RegulatoryEvidenceGap>(`${base}/gaps/${gapId}/archive`, { reason }),
  createActionFoundation: (gapId: string, data?: Record<string, unknown>) => post<RegulatoryEvidenceGap>(`${base}/gaps/${gapId}/create-action-foundation`, data ?? {}),
  packages: (params?: Record<string, unknown>) => get<{ rows: RegulatoryEvidencePackage[]; total: number; summary?: Record<string, number> }>(`${base}/packages`, params),
  createPackage: (data: Record<string, unknown>) => post<RegulatoryEvidencePackage>(`${base}/packages`, data),
  packageDetail: (packageId: string) => get<RegulatoryEvidencePackageDetail>(`${base}/packages/${packageId}`),
  updatePackage: (packageId: string, data: Record<string, unknown>) => patch<RegulatoryEvidencePackage>(`${base}/packages/${packageId}`, data),
  preparePackage: (packageId: string, data?: Record<string, unknown>) => post<RegulatoryEvidencePackageDetail>(`${base}/packages/${packageId}/prepare`, data ?? {}),
  addPackageItem: (packageId: string, data: Record<string, unknown>) => post<Record<string, unknown>>(`${base}/packages/${packageId}/items`, data),
  removePackageItem: (packageId: string, itemId: string, reason: string) => remove<Record<string, unknown>>(`${base}/packages/${packageId}/items/${itemId}`, { reason }),
  archivePackage: (packageId: string, reason: string) => post<RegulatoryEvidencePackage>(`${base}/packages/${packageId}/archive`, { reason }),
  accessLog: (params?: Record<string, unknown>) => get<{ rows: RegulatoryEvidenceAccessEvent[]; total: number; summary?: Record<string, number> }>(`${base}/access-log`, params),
  chain: (evidenceLinkId: string) => get<{ rows: Record<string, unknown>[] }>(`${base}/links/${evidenceLinkId}/chain-of-custody`),
  history: (params?: Record<string, unknown>) => get<RegulatoryEvidenceHistoryResponse>(`${base}/history`, params),
  settings: () => get<Record<string, unknown>>(`${base}/settings`),
  updateSettings: (data: Record<string, unknown>) => patch<Record<string, unknown>>(`${base}/settings`, data),
  sourceItem: (regulationId: string, params?: Record<string, unknown>) => get<RegulatoryEvidenceRegister>(`/regulatory/${regulationId}/evidence`, params),
  sourceObligation: (obligationId: string, params?: Record<string, unknown>) => get<RegulatoryEvidenceRegister>(`/regulatory/obligations/${obligationId}/evidence`, params),
  scoped: (scope: 'sites' | 'units' | 'areas' | 'equipment', id: string, params?: Record<string, unknown>) => get<RegulatoryEvidenceRegister>(`/regulatory/${scope}/${id}/evidence`, params),
  lookups: async (): Promise<RegulatoryEvidenceLookups> => {
    const endpoints: Record<keyof RegulatoryEvidenceLookups, string> = {
      evidenceSourceTypes: 'evidence-source-types',
      evidenceTypes: 'evidence-types',
      evidenceStatuses: 'evidence-statuses',
      evidenceReviewStatuses: 'evidence-review-statuses',
      evidenceReadinessStatuses: 'evidence-readiness-statuses',
      evidenceSourceModules: 'evidence-source-modules',
      evidenceRequirementStatuses: 'evidence-requirement-statuses',
      evidenceGapTypes: 'evidence-gap-types',
      evidencePackageTypes: 'evidence-package-types',
      evidencePackageStatuses: 'evidence-package-statuses',
      evidenceConfidentialityLevels: 'evidence-confidentiality-levels',
      evidenceStaleStatuses: 'evidence-stale-statuses',
      criticalityLevels: 'criticality-levels'
    };
    const keys = Object.keys(endpoints) as Array<keyof RegulatoryEvidenceLookups>;
    const values = await Promise.all(keys.map((key) => get<{ rows: string[] }>(`/regulatory/lookups/${endpoints[key]}`).then((data) => data.rows ?? [])));
    return keys.reduce((acc, key, index) => ({ ...acc, [key]: values[index] }), {} as RegulatoryEvidenceLookups);
  }
};
