import Link from 'next/link';
import { CompetencyProfileStatusBadge } from '../shared/CompetencyProfileStatusBadge';
import { CompetencyProfileTypeBadge } from '../shared/CompetencyProfileTypeBadge';
import { CompetencyReviewStatusBadge } from '../shared/CompetencyReviewStatusBadge';
import { ProfileMatrixSyncStatusBadge } from '../shared/ProfileMatrixSyncStatusBadge';
import { ProfileVersionBadge } from '../shared/ProfileVersionBadge';
import { TrainingButton } from '../shared/TrainingUi';

export function ProfileDetailHeader({ profile }: { profile: Record<string, any> }) {
  return <div className="rounded-xl border border-[var(--psm-line)] bg-[var(--psm-surface)] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-primary">Competency Profile</p><h1 className="mt-1 text-2xl font-bold">{profile.profile_name}</h1><p className="mt-1 text-sm text-[var(--psm-muted)]">{profile.profile_code} / {profile.job_role ?? 'Custom role'} / Owner {profile.owner_user_id ?? 'unassigned'}</p><div className="mt-3 flex flex-wrap gap-2"><CompetencyProfileTypeBadge value={profile.profile_type} /><CompetencyProfileStatusBadge value={profile.profile_status} /><CompetencyReviewStatusBadge value={profile.review_status} /><ProfileMatrixSyncStatusBadge value={profile.matrix_sync_status} /><ProfileVersionBadge value={profile.version} /></div></div><div className="flex flex-wrap gap-2"><TrainingButton href={`/training-competency/roles-competency-profiles/profiles/${profile.id}/edit`} variant="secondary" disabled={['Approved','Locked'].includes(profile.profile_status)} title={['Approved','Locked'].includes(profile.profile_status) ? 'Approved/locked profiles require New Version.' : ''}>Edit</TrainingButton><TrainingButton href="/training-competency/roles-competency-profiles/profiles" variant="secondary">Back to Registry</TrainingButton></div></div><nav className="mt-4 flex gap-2 overflow-x-auto">{['Overview','Requirements','Workers','Evaluations','Version History'].map((label) => <Link key={label} className="rounded-full border border-[var(--psm-line)] px-3 py-1.5 text-xs font-semibold text-[var(--psm-muted)]" href={`/training-competency/roles-competency-profiles/profiles/${profile.id}${label === 'Overview' ? '' : `/${label.toLowerCase().replaceAll(' ', '-')}`}`}>{label}</Link>)}</nav></div>;
}
