import Link from 'next/link';
import { CompetencyProfileStatusBadge } from '../shared/CompetencyProfileStatusBadge';
import { CompetencyProfileTypeBadge } from '../shared/CompetencyProfileTypeBadge';
import { CompetencyReviewStatusBadge } from '../shared/CompetencyReviewStatusBadge';
import { ProfileMatrixSyncStatusBadge } from '../shared/ProfileMatrixSyncStatusBadge';
import { TrainingButton } from '../shared/TrainingUi';

export function ProfileTable({ rows, compact }: { rows: Record<string, any>[]; compact?: boolean }) {
  if (!rows.length) return <p className="text-sm text-[var(--psm-muted)]">No competency profiles match this view.</p>;
  return <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-xs uppercase text-[var(--psm-muted)]"><tr>{['Profile','Code','Job Role','Scope','Worker Type','Competencies','Safety-Critical','PTW Links','Workers','Status','Review','Matrix','Owner','Actions'].slice(0, compact ? 7 : 14).map((h) => <th key={h} className="px-3 py-2">{h}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t border-[var(--psm-line)]"><td className="px-3 py-3 font-semibold"><Link className="text-primary hover:underline" href={`/training-competency/roles-competency-profiles/profiles/${row.id}`}>{row.profile_name}</Link><div className="mt-1"><CompetencyProfileTypeBadge value={row.profile_type} /></div></td><td className="px-3 py-3">{row.profile_code}</td><td className="px-3 py-3">{row.job_role ?? 'Custom'}</td><td className="px-3 py-3">{row.site_id ?? 'Company'}</td><td className="px-3 py-3">{row.worker_type ?? 'Any'}</td><td className="px-3 py-3">{row.competency_count ?? 0}</td><td className="px-3 py-3">{row.safety_critical_count ?? 0}</td>{!compact ? <><td className="px-3 py-3">{row.ptw_critical ? 'Linked' : 'None'}</td><td className="px-3 py-3">{row.assigned_workers ?? 0}</td><td className="px-3 py-3"><CompetencyProfileStatusBadge value={row.profile_status} /></td><td className="px-3 py-3"><CompetencyReviewStatusBadge value={row.review_status} /></td><td className="px-3 py-3"><ProfileMatrixSyncStatusBadge value={row.matrix_sync_status} /></td><td className="px-3 py-3">{row.owner_user_id ?? 'Unassigned'}</td><td className="px-3 py-3"><div className="flex gap-2"><TrainingButton href={`/training-competency/roles-competency-profiles/profiles/${row.id}`} variant="secondary">View</TrainingButton><TrainingButton href={`/training-competency/roles-competency-profiles/profiles/${row.id}/edit`} variant="secondary" disabled={row.actions?.edit === false} title={row.actions?.disabledReasons?.edit}>Edit</TrainingButton></div></td></> : null}</tr>)}</tbody></table></div>;
}
