import { ReliefTestResultBadge } from '../shared/ReliefTestResultBadge';

export function ReliefDeviceFailedPanel({ rows }: { rows?: Array<Record<string, any>> }) {
  return (
    <section className="rounded-xl border border-[var(--psm-line)] bg-[var(--psm-surface)] p-4">
      <h2 className="font-semibold">Failed test workflow</h2>
      <div className="mt-3 space-y-2">
        {(rows ?? []).slice(0, 8).map((row) => (
          <div key={row.id} className="rounded-lg bg-danger/10 p-3 text-sm">
            <div className="flex items-center justify-between gap-3">
              <span>{row.test_record_number ?? row.testRecordNumber}</span>
              <ReliefTestResultBadge result={row.final_result ?? row.finalResult} />
            </div>
            <p className="mt-1 text-xs text-[var(--psm-muted)]">Action/deficiency foundation and startup blocker are generated by backend readiness.</p>
          </div>
        ))}
        {!rows?.length ? <p className="text-sm text-[var(--psm-muted)]">No failed relief device tests.</p> : null}
      </div>
    </section>
  );
}
