'use client';
import { useState } from 'react';
import { Plus, Save } from 'lucide-react';
import { SilPanel } from './SilPanel';

const control = 'w-full rounded border border-slate-300 bg-white px-2 py-1.5 text-xs text-slate-900 dark:border-slate-700 dark:bg-[#0a1b2e] dark:text-slate-100';

export function SifEngineeringEditors({ sif, readOnly, onComponent, onArchitecture, onProofTest }: { sif: any; readOnly: boolean; onComponent: (values: any) => void; onArchitecture: (values: any) => void; onProofTest: (values: any) => void }) {
  const [component, setComponent] = useState({ componentType: 'Sensor', componentTag: '', componentName: '', processVariable: '', actionOnTrip: '', failureDataReference: '', proofTestRequirement: '' });
  const [architecture, setArchitecture] = useState({ sensorVoting: '', logicSolverArchitecture: '', finalElementVoting: '', overallArchitecture: '', commonCauseConsideration: '', independenceFromBpcs: '', independenceFromInitiatingEvent: '' });
  const [proofTest, setProofTest] = useState({ proofTestInterval: '', proofTestProcedureDocumentId: '', maintenanceBasis: '', bypassAllowed: false, maximumBypassDuration: '', overrideManagementNotes: '' });
  const update = (set: any, key: string, value: any) => set((old: any) => ({ ...old, [key]: value }));
  if (readOnly) return null;
  return <div className="grid grid-cols-1 gap-4 2xl:grid-cols-3">
    <SilPanel title="Add SIF Component" subtitle="Component data is stored against this study-specific SIF."><form className="space-y-2" onSubmit={event => { event.preventDefault(); onComponent(component); }}><select className={control} value={component.componentType} onChange={e => update(setComponent, 'componentType', e.target.value)}>{['Sensor','Logic Solver','Final Element','Auxiliary','Other'].map(x => <option key={x}>{x}</option>)}</select><input className={control} placeholder="Tag" value={component.componentTag} onChange={e => update(setComponent, 'componentTag', e.target.value)}/><input className={control} placeholder="Name" value={component.componentName} onChange={e => update(setComponent, 'componentName', e.target.value)}/><input className={control} placeholder="Process variable / action" value={component.processVariable} onChange={e => update(setComponent, 'processVariable', e.target.value)}/><input className={control} placeholder="Failure data reference" value={component.failureDataReference} onChange={e => update(setComponent, 'failureDataReference', e.target.value)}/><button className="lopa-button-secondary"><Plus size={14}/> Save component</button></form></SilPanel>
    <SilPanel title="Save Architecture / Voting"><form className="space-y-2" onSubmit={event => { event.preventDefault(); onArchitecture(architecture); }}><input className={control} placeholder="Sensor voting, e.g. 1oo2" value={architecture.sensorVoting} onChange={e => update(setArchitecture, 'sensorVoting', e.target.value)}/><input className={control} placeholder="Logic solver architecture" value={architecture.logicSolverArchitecture} onChange={e => update(setArchitecture, 'logicSolverArchitecture', e.target.value)}/><input className={control} placeholder="Final element voting" value={architecture.finalElementVoting} onChange={e => update(setArchitecture, 'finalElementVoting', e.target.value)}/><input className={control} placeholder="Overall architecture" value={architecture.overallArchitecture} onChange={e => update(setArchitecture, 'overallArchitecture', e.target.value)}/><textarea className={control} placeholder="Common-cause / independence basis" value={architecture.commonCauseConsideration} onChange={e => update(setArchitecture, 'commonCauseConsideration', e.target.value)}/><button className="lopa-button-secondary"><Save size={14}/> Save architecture</button></form></SilPanel>
    <SilPanel title="Save Proof Test / Bypass"><form className="space-y-2" onSubmit={event => { event.preventDefault(); onProofTest(proofTest); }}><input className={control} placeholder="Proof-test interval" value={proofTest.proofTestInterval} onChange={e => update(setProofTest, 'proofTestInterval', e.target.value)}/><input className={control} placeholder="Proof-test procedure document ID" value={proofTest.proofTestProcedureDocumentId} onChange={e => update(setProofTest, 'proofTestProcedureDocumentId', e.target.value)}/><textarea className={control} placeholder="Maintenance basis" value={proofTest.maintenanceBasis} onChange={e => update(setProofTest, 'maintenanceBasis', e.target.value)}/><label className="flex items-center gap-2 text-xs text-slate-600 dark:text-slate-300"><input type="checkbox" checked={proofTest.bypassAllowed} onChange={e => update(setProofTest, 'bypassAllowed', e.target.checked)}/> Bypass allowed</label><input className={control} placeholder="Override/bypass management notes" value={proofTest.overrideManagementNotes} onChange={e => update(setProofTest, 'overrideManagementNotes', e.target.value)}/><button className="lopa-button-secondary"><Save size={14}/> Save proof-test basis</button></form></SilPanel>
  </div>;
}
