'use client';
import { useState } from 'react';
import { X } from 'lucide-react';

function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/65 p-4"><div className="max-h-[92vh] w-full max-w-2xl overflow-auto rounded-lg border border-slate-200 bg-white shadow-2xl dark:border-slate-700 dark:bg-[#071525]"><div className="sticky top-0 flex items-center justify-between border-b border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-[#071525]"><h3 className="font-bold text-slate-900 dark:text-white">{title}</h3><button onClick={onClose}><X size={18}/></button></div>{children}</div></div>; }
const input = 'w-full rounded border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 dark:border-slate-700 dark:bg-[#0a1b2e] dark:text-slate-100';
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="space-y-1 text-xs font-semibold text-slate-600 dark:text-slate-300"><span>{label}</span>{children}</label>; }

export function DetermineSilDialog({ mode, onClose, onSubmit, busy }: { mode: 'determine'|'reassess'|'lock'|'unlock'; onClose: () => void; onSubmit: (values: any) => void; busy: boolean }) { const [reason,setReason]=useState(''); const actionTitle = mode.charAt(0).toUpperCase() + mode.slice(1); return <Modal title={mode === 'determine' ? 'Determine SIL' : `${actionTitle} SIL Basis`} onClose={onClose}><form className="space-y-4 p-4" onSubmit={event => { event.preventDefault(); onSubmit({ reason: reason || undefined, notes: reason || undefined }); }}><p className="rounded border border-cyan-500/20 bg-cyan-500/5 p-3 text-xs text-slate-600 dark:text-slate-300">The backend uses the approved company/site methodology and current Risk Calculation. A target entered in the browser cannot replace the configured mapping.</p><Field label={mode === 'determine' ? 'Determination basis / notes' : 'Reason *'}><textarea className={input} rows={4} value={reason} onChange={e=>setReason(e.target.value)} required={mode !== 'determine'}/></Field><div className="flex justify-end gap-2"><button type="button" className="lopa-button-secondary" onClick={onClose}>Cancel</button><button className="lopa-button-primary" disabled={busy}>Confirm</button></div></form></Modal>; }

export function SifSpecificationDialog({ targetSil, onClose, onSubmit, busy }: { targetSil?: string; onClose: () => void; onSubmit: (values: any) => void; busy: boolean }) { const [values,setValues]=useState<any>({ title:'',sifTag:'',safetyFunction:'',safeState:'',requiredAction:'',responseTimeRequired:'',proofTestBasis:'',targetSil,complete:false }); const set=(key:string,value:any)=>setValues((old:any)=>({...old,[key]:value})); return <Modal title="Create SIF Specification" onClose={onClose}><form className="grid gap-4 p-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();onSubmit(values)}}><Field label="SIF tag *"><input className={input} value={values.sifTag} onChange={e=>set('sifTag',e.target.value)} required/></Field><Field label="SIF title *"><input className={input} value={values.title} onChange={e=>set('title',e.target.value)} required/></Field><Field label="Safety function *"><textarea className={input} value={values.safetyFunction} onChange={e=>set('safetyFunction',e.target.value)} required/></Field><Field label="Safe state *"><textarea className={input} value={values.safeState} onChange={e=>set('safeState',e.target.value)} required/></Field><Field label="Required action *"><textarea className={input} value={values.requiredAction} onChange={e=>set('requiredAction',e.target.value)} required/></Field><Field label="Response time required *"><input className={input} value={values.responseTimeRequired} onChange={e=>set('responseTimeRequired',e.target.value)} required/></Field><Field label="Proof-test basis"><textarea className={input} value={values.proofTestBasis} onChange={e=>set('proofTestBasis',e.target.value)}/></Field><Field label="Equipment / system"><input className={input} value={values.equipmentSystem ?? ''} onChange={e=>set('equipmentSystem',e.target.value)}/></Field><div className="flex justify-end gap-2 sm:col-span-2"><button type="button" className="lopa-button-secondary" onClick={onClose}>Cancel</button><button className="lopa-button-primary" disabled={busy}>Save SIF</button></div></form></Modal>; }

export function LinkSifRecordDialog({ onClose, onSubmit, busy }: { onClose: () => void; onSubmit: (values: any) => void; busy: boolean }) { const [values,setValues]=useState<any>({linkedRecordType:'Equipment',linkedRecordId:'',required:true}); return <Modal title="Link SIF / SIL Record" onClose={onClose}><form className="space-y-4 p-4" onSubmit={e=>{e.preventDefault();onSubmit(values)}}><Field label="Record type"><select className={input} value={values.linkedRecordType} onChange={e=>setValues({...values,linkedRecordType:e.target.value})}>{['Equipment','Document','SRS','MOC','PSSR','MI','Proof Test Procedure','SIS / SIF'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Real record ID *"><input className={input} value={values.linkedRecordId} onChange={e=>setValues({...values,linkedRecordId:e.target.value})} required/></Field><Field label="Relationship"><input className={input} value={values.relationship ?? ''} onChange={e=>setValues({...values,relationship:e.target.value})}/></Field><label className="flex gap-2 text-xs"><input type="checkbox" checked={values.required} onChange={e=>setValues({...values,required:e.target.checked})}/> Required for SIL basis lock</label><div className="flex justify-end gap-2"><button type="button" className="lopa-button-secondary" onClick={onClose}>Cancel</button><button className="lopa-button-primary" disabled={busy}>Link</button></div></form></Modal>; }

export function CreateSilActionDialog({ onClose, onSubmit, busy }: { onClose: () => void; onSubmit: (values: any) => void; busy: boolean }) { const [values,setValues]=useState<any>({title:'',description:'',ownerId:'',priority:'High',dueDate:'',blocking:true}); const set=(k:string,v:any)=>setValues((x:any)=>({...x,[k]:v})); return <Modal title="Create Universal Action" onClose={onClose}><form className="grid gap-4 p-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();onSubmit(values)}}><Field label="Title *"><input className={input} value={values.title} onChange={e=>set('title',e.target.value)} required/></Field><Field label="Owner user ID *"><input className={input} value={values.ownerId} onChange={e=>set('ownerId',e.target.value)} required/></Field><Field label="Description *"><textarea className={input} value={values.description} onChange={e=>set('description',e.target.value)} required/></Field><Field label="Due date *"><input type="date" className={input} value={values.dueDate} onChange={e=>set('dueDate',e.target.value)} required/></Field><Field label="Priority"><select className={input} value={values.priority} onChange={e=>set('priority',e.target.value)}>{['Low','Medium','High','Critical'].map(x=><option key={x}>{x}</option>)}</select></Field><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={values.blocking} onChange={e=>set('blocking',e.target.checked)}/> Closure blocker</label><div className="flex justify-end gap-2 sm:col-span-2"><button type="button" className="lopa-button-secondary" onClick={onClose}>Cancel</button><button className="lopa-button-primary" disabled={busy}>Create Action</button></div></form></Modal>; }
