import type { MiSafeguardRow } from '../types/safeguard-common.types';
import { SafeguardRegisterTable, SectionCard } from './SafeguardUiPrimitives';

export function SafeguardDuePanel({ rows, onOpen }: { rows?: MiSafeguardRow[]; onOpen?: (row: MiSafeguardRow) => void }) {
  return (
    <SectionCard title="Due / Upcoming Proof Tests" description="Scheduled tests generated by backend rules and safeguard test requirements.">
      <SafeguardRegisterTable rows={rows} kind="Due safeguard" onOpen={onOpen} />
    </SectionCard>
  );
}
