import Link from 'next/link';
import { RequirementSourceBadge } from '../shared/RequirementSourceBadge';
import { TrainingCategoryBadge } from '../shared/TrainingCategoryBadge';
import { TrainingBadge, TrainingEmptyState } from '../shared/TrainingUi';

export function MatrixRuleTable({ rows = [] }: { rows?: Record<string, any>[] }) {
  if (!rows.length) return <TrainingEmptyState title="No matrix rules" message="Create a rule in the builder. Active rules generate required training during evaluation." />;
  return <div className="overflow-x-auto rounded-xl border border-[var(--psm-line)] bg-[var(--psm-surface)]"><table className="min-w-full text-sm"><thead className="bg-[var(--psm-surface-2)] text-left text-xs uppercase tracking-wide text-[var(--psm-muted)]"><tr>{['Rule','Training','Category','Source','Scope','Mandatory','Safety / PSM','PTW','MOC','PSSR','Status','Actions'].map((h) => <th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t border-[var(--psm-line)]"><td className="px-3 py-3 font-semibold">{row.rule_title}<div className="text-xs text-[var(--psm-muted)]">{row.rule_code}</div></td><td className="px-3 py-3">{row.training_title}<div className="text-xs text-[var(--psm-muted)]">{row.training_code ?? 'Temporary reference'}</div></td><td className="px-3 py-3"><TrainingCategoryBadge value={row.training_category} /></td><td className="px-3 py-3"><RequirementSourceBadge value={row.requirement_source} /></td><td className="px-3 py-3">{row.applicability_scope}</td><td className="px-3 py-3">{row.mandatory ? 'Yes' : 'Optional'}</td><td className="px-3 py-3">{row.safety_critical || row.psm_critical ? <TrainingBadge tone="danger">Critical</TrainingBadge> : <TrainingBadge>Standard</TrainingBadge>}</td><td className="px-3 py-3">{row.blocks_ptw_authorization ? 'Yes' : 'No'}</td><td className="px-3 py-3">{row.blocks_moc_implementation ? 'Yes' : 'No'}</td><td className="px-3 py-3">{row.blocks_pssr_startup ? 'Yes' : 'No'}</td><td className="px-3 py-3"><TrainingBadge tone={row.active ? 'good' : row.rule_status === 'Archived' ? 'danger' : 'warn'}>{row.rule_status}</TrainingBadge></td><td className="px-3 py-3"><Link className="font-semibold text-primary" href={`/training-competency/training-matrix/rules/${row.id}`}>Open</Link></td></tr>)}</tbody></table></div>;
}
