import { EvidenceStatusBadge } from '../shared/EvidenceStatusBadge';
import { MatrixCellStatusBadge } from '../shared/MatrixCellStatusBadge';
import { RequirementSourceBadge } from '../shared/RequirementSourceBadge';
import { TrainingCategoryBadge } from '../shared/TrainingCategoryBadge';
import { TrainingEmptyState } from '../shared/TrainingUi';

export function WorkerMatrixRequirementTable({ rows = [] }: { rows?: Record<string, any>[] }) {
  if (!rows.length) return <TrainingEmptyState title="No worker matrix requirements" message="Create active rules and run evaluation. Missing future Training Records data is shown as missing evidence, not completed training." />;
  return <div className="overflow-x-auto rounded-xl border border-[var(--psm-line)] bg-[var(--psm-surface)]"><table className="min-w-full text-sm"><thead className="bg-[var(--psm-surface-2)] text-left text-xs uppercase tracking-wide text-[var(--psm-muted)]"><tr>{['Training','Category','Source','Why Required','Scope','Mandatory','Recurrence','Due','Expiry','Status','Evidence','Actions'].map((h) => <th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t border-[var(--psm-line)]"><td className="px-3 py-3 font-semibold">{row.training_title}<div className="text-xs text-[var(--psm-muted)]">{row.training_code ?? 'Temporary matrix reference'}</div></td><td className="px-3 py-3"><TrainingCategoryBadge value={row.training_category} /></td><td className="px-3 py-3"><RequirementSourceBadge value={row.requirement_source} /></td><td className="max-w-sm px-3 py-3 text-[var(--psm-muted)]">{row.requirement_reason}</td><td className="px-3 py-3">{row.applies_to_scope}</td><td className="px-3 py-3">{row.mandatory ? 'Yes' : 'Optional'}</td><td className="px-3 py-3">{row.recurrence_interval_days ? `${row.recurrence_interval_days} days` : 'One-time'}</td><td className="px-3 py-3">{row.due_date ?? 'Not determined'}</td><td className="px-3 py-3">{row.expiry_date ?? 'Not determined'}</td><td className="px-3 py-3"><MatrixCellStatusBadge value={row.assignment_status} /></td><td className="px-3 py-3"><EvidenceStatusBadge value="Missing Evidence" /></td><td className="px-3 py-3 text-primary">Evidence</td></tr>)}</tbody></table></div>;
}
