import { Download, FileText, Printer } from 'lucide-react';
import { ptwIsolationService, type PermitIsolationCertificate, type PermitIsolationSummary } from '../../services/ptw-isolation.service';

export function IsolationCertificatePanel({ permitId, summary, certificate, onGenerate }: { permitId: string; summary?: PermitIsolationSummary | undefined; certificate?: PermitIsolationCertificate | null | undefined; onGenerate: () => void }) {
  async function download() {
    const blob = await ptwIsolationService.downloadCertificate(permitId);
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${certificate?.certificate_number ?? 'isolation-certificate'}.pdf`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  }

  return (
    <section className="psm-card p-5">
      <div className="mb-4 flex items-center justify-between gap-3">
        <div className="flex items-center gap-2 font-semibold uppercase tracking-wide"><FileText size={17} />Isolation Certificate</div>
        <button disabled={!summary?.total || summary?.confirmed !== summary?.total} onClick={onGenerate} className="psm-button psm-button-primary disabled:cursor-not-allowed disabled:opacity-45">Generate Isolation Certificate</button>
      </div>
      <div className="grid gap-3 md:grid-cols-2">
        <Info label="Certificate Number" value={certificate?.certificate_number ?? 'Not generated'} />
        <Info label="Version" value={certificate?.version ? `v${certificate.version}` : '-'} />
        <Info label="Generated By" value={certificate?.generated_by ?? '-'} />
        <Info label="Generated At" value={certificate?.generated_at ? new Date(certificate.generated_at).toLocaleString() : '-'} />
      </div>
      <div className="mt-4 flex flex-wrap gap-2">
        <button disabled={!certificate} onClick={download} className="psm-button psm-button-secondary disabled:cursor-not-allowed disabled:opacity-45"><Download size={15} /> Download PDF</button>
        <button disabled={!certificate} onClick={() => window.print()} className="psm-button psm-button-secondary disabled:cursor-not-allowed disabled:opacity-45"><Printer size={15} /> Print PDF</button>
      </div>
    </section>
  );
}

function Info({ label, value }: { label: string; value: string }) {
  return <div className="rounded-lg border border-[var(--psm-line)] bg-[var(--psm-surface-2)] p-3"><div className="text-xs uppercase text-[var(--psm-muted)]">{label}</div><div className="mt-1 font-semibold">{value}</div></div>;
}
