import { FileText, Package, RefreshCw, Table2, Eye, UploadCloud } from 'lucide-react';
import { ReportReadinessBadge } from '../shared/ReportReadinessBadge';
import { ReportStatusBadge } from '../shared/ReportStatusBadge';

export function FinalReportHeader({ header, busy, onPreview, onGenerate, onPackage, onExport, onPublish, onRefresh, disabledReason }: { header: any; busy?: boolean; onPreview: () => void; onGenerate: () => void; onPackage: () => void; onExport: () => void; onPublish: () => void; onRefresh: () => void; disabledReason?: string }) {
  const button = 'inline-flex items-center gap-2 rounded-lg border border-cyan-300/10 bg-slate-100 px-3 py-2 text-xs font-bold text-slate-800 hover:bg-slate-200 disabled:cursor-not-allowed disabled:opacity-50 dark:bg-[#0b2035] dark:text-blue-100 dark:hover:bg-blue-500/10';
  const primary = 'inline-flex items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white hover:bg-blue-500 disabled:cursor-not-allowed disabled:opacity-50';
  const blocked = header?.reportReadinessStatus === 'Blocked';
  return <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-cyan-300/10 dark:bg-[#06111f] dark:shadow-none">
    <div className="flex flex-wrap items-start justify-between gap-4">
      <div>
        <div className="text-xs font-bold uppercase tracking-wide text-blue-600 dark:text-blue-300">Final Report / Export</div>
        <h2 className="mt-1 text-xl font-black text-slate-950 dark:text-white">{header?.lopaNumber} · {header?.studyTitle}</h2>
        <p className="mt-1 text-sm text-slate-500">{header?.subtitle}</p>
        <div className="mt-3 flex flex-wrap gap-2"><ReportStatusBadge status={header?.studyStatus} /><ReportReadinessBadge status={header?.reportReadinessStatus} /><ReportStatusBadge status={header?.approvalStatus} /><ReportStatusBadge status={header?.signatureStatus} /><ReportStatusBadge status={header?.officialReportStatus} /></div>
      </div>
      <div className="grid grid-cols-2 gap-3 text-xs text-slate-500 sm:grid-cols-4">
        <Metric label="Version" value={header?.latestReportVersion ?? '-'} />
        <Metric label="Generated" value={header?.latestGeneratedAt ? new Date(header.latestGeneratedAt).toLocaleString() : '-'} />
        <Metric label="Generated by" value={header?.latestGeneratedBy ?? '-'} />
        <Metric label="Updated" value={header?.lastUpdatedAt ? new Date(header.lastUpdatedAt).toLocaleString() : '-'} />
      </div>
    </div>
    {blocked ? <div className="mt-3 rounded-lg border border-amber-400/25 bg-amber-500/10 p-2 text-xs text-amber-700 dark:text-amber-100">{disabledReason ?? 'Official generation is disabled until report blockers are cleared.'}</div> : null}
    <div className="mt-4 flex flex-wrap gap-2">
      <button className={button} disabled={busy} onClick={onPreview}><Eye size={14}/>Preview Report</button>
      <button className={primary} disabled={busy || blocked} title={blocked ? disabledReason : undefined} onClick={onGenerate}><FileText size={14}/>Generate PDF Report</button>
      <button className={button} disabled={busy} onClick={onPackage}><Package size={14}/>Generate Report Package</button>
      <button className={button} disabled={busy} onClick={onExport}><Table2 size={14}/>Export Excel/CSV</button>
      <button className={button} disabled={busy || blocked} title={blocked ? disabledReason : undefined} onClick={onPublish}><UploadCloud size={14}/>Publish to Document Control</button>
      <button className={button} disabled={busy} onClick={onRefresh}><RefreshCw size={14}/>Refresh</button>
    </div>
  </div>;
}
function Metric({ label, value }: { label: string; value: any }) { return <div className="rounded-lg border border-slate-200 bg-slate-50 p-2 dark:border-cyan-300/10 dark:bg-[#0a1b2d]"><div>{label}</div><div className="mt-1 font-bold text-slate-900 dark:text-white">{value}</div></div>; }
