import type { ChangeEvent } from 'react';
import { PsiCard } from '../../shared/PsiUi';

export function ChemicalStorageCompatibilitySection({ value, lookups, onChange }: { value: Record<string, any>; lookups?: Record<string, string[]> | undefined; onChange: (patch: Record<string, any>) => void }) {
  const change = (event: ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => onChange({ [event.target.name]: event.target.type === 'checkbox' ? (event.target as HTMLInputElement).checked : event.target.value });
  return <PsiCard title="6. Storage / Compatibility" subtitle="Structured compatibility warning foundation for chemical, material, acid/base, oxidizer, water/air reactive, and segregation checks."><div className="grid gap-3 md:grid-cols-2"><Select name="storage_class" label="Storage class" value={value.storage_class} options={lookups?.storageClasses ?? []} onChange={change} /><Field name="compatible_storage_group" label="Compatible storage group" value={value.compatible_storage_group} onChange={change} />{['incompatible_chemicals_json','incompatible_materials_json','acid_base_notes','metal_compatibility_notes','elastomer_compatibility_notes','segregation_requirement','ventilation_requirement'].map((name) => <Field key={name} name={name} label={label(name)} value={value[name]} onChange={change} />)}<Select name="compatibility_risk_level" label="Compatibility risk level" value={value.compatibility_risk_level} options={lookups?.compatibilityRiskLevels ?? []} onChange={change} />{['water_reactive','air_reactive','oxidizer','organic_peroxide'].map((name) => <label key={name} className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name={name} checked={Boolean(value[name])} onChange={change} /> {label(name)}</label>)}</div></PsiCard>;
}
function label(name: string) { return name.replace(/_/g, ' ').replace(/\b\w/g, (m) => m.toUpperCase()); }
function Field({ label, ...props }: any) { return <label className="space-y-1 text-sm font-semibold">{label}<input {...props} value={props.value ?? ''} className="w-full rounded-lg border border-[var(--psm-line)] bg-[var(--psm-surface-2)] px-3 py-2" /></label>; }
function Select({ label, options, ...props }: any) { return <label className="space-y-1 text-sm font-semibold">{label}<select {...props} value={props.value ?? ''} className="w-full rounded-lg border border-[var(--psm-line)] bg-[var(--psm-surface-2)] px-3 py-2"><option value="">Select</option>{options.map((option: string) => <option key={option}>{option}</option>)}</select></label>; }
