'use client';

import { useSopAckRequirementDetail } from '../hooks/useSopAckRequirementDetail';
import { useSopAckRequirementMutations } from '../hooks/useSopAckRequirementMutations';
import { SopAckRequirementStatusBadge } from '../shared/SopAckRequirementStatusBadge';
import { TrainingBadge, TrainingButton, TrainingCard, TrainingEmptyState, TrainingErrorState, TrainingLoadingState } from '../shared/TrainingUi';
import { SopAckAssignmentTable } from './SopAckAssignmentTable';
import { SopAckHeader } from './SopAckHeader';

export function SopAckRequirementDetailPage({ requirementId }: { requirementId: string }) {
  const query = useSopAckRequirementDetail(requirementId);
  const mutations = useSopAckRequirementMutations(requirementId);
  if (query.isLoading) return <TrainingLoadingState rows={6} />;
  if (query.isError) return <TrainingErrorState message={query.error} onRetry={() => query.refetch()} />;
  const detail = query.data!;
  const requirement = detail.requirement;
  return (
    <div className="space-y-5">
      <SopAckHeader title={requirement.requirement_title} subtitle={`${requirement.requirement_code} / ${requirement.requirement_source}`} actions={false} />
      <TrainingCard title="Requirement Snapshot" action={<SopAckRequirementStatusBadge value={requirement.requirement_status} />}>
        <div className="grid gap-3 md:grid-cols-4">
          {[
            ['SOP / document', requirement.sop_title ?? requirement.document_number ?? 'Missing linked procedure'],
            ['Required version', requirement.required_version ?? requirement.current_version_at_requirement ?? 'Not set'],
            ['Version policy', requirement.current_version_policy],
            ['Review status', requirement.review_status ?? 'Not reviewed'],
            ['Document status', requirement.document_status ?? 'Not available'],
            ['Owner', requirement.owner_user_id ?? 'Not assigned'],
            ['Reviewer', requirement.reviewer_user_id ?? 'Not assigned'],
            ['Next review due', requirement.next_review_due ?? 'Not scheduled']
          ].map(([label, value]) => <Info key={String(label)} label={String(label)} value={value} />)}
        </div>
        <div className="mt-4 flex flex-wrap gap-2">
          {requirement.safety_critical ? <TrainingBadge tone="danger">Safety critical</TrainingBadge> : null}
          {requirement.psm_critical ? <TrainingBadge tone="warn">PSM critical</TrainingBadge> : null}
          {requirement.blocks_ptw_authorization ? <TrainingBadge tone="danger">Blocks PTW</TrainingBadge> : null}
          {requirement.blocks_moc_implementation ? <TrainingBadge tone="danger">Blocks MOC</TrainingBadge> : null}
          {requirement.blocks_pssr_startup ? <TrainingBadge tone="danger">Blocks PSSR</TrainingBadge> : null}
        </div>
      </TrainingCard>
      <div className="grid gap-4 xl:grid-cols-3">
        <JsonPanel title="Applicability scopes" rows={detail.scopes} />
        <JsonPanel title="Due / re-acknowledgement rules" rows={detail.dueRules} />
        <JsonPanel title="Evidence / e-sign / assessment rules" rows={detail.evidenceRules} />
      </div>
      <TrainingCard title="Actions" subtitle="All mutations are sent to the backend and create training audit/history events.">
        <div className="flex flex-wrap gap-2">
          <TrainingButton href={`/training-competency/sop-acknowledgements/requirements/${requirement.id}/edit`} variant="secondary">Edit</TrainingButton>
          <TrainingButton disabled={mutations.activate.isPending} title="Activate requirement and allow assignment generation." onClick={() => mutations.activate.mutate({})}>Activate</TrainingButton>
          <TrainingButton variant="secondary" disabled={mutations.generateAssignments.isPending} title="Generate worker assignments from backend applicability rules." onClick={() => mutations.generateAssignments.mutate({})}>Generate Assignments</TrainingButton>
          <TrainingButton variant="secondary" disabled={mutations.evaluate.isPending} title="Evaluate current worker/version gaps from the backend." onClick={() => mutations.evaluate.mutate({})}>Evaluate</TrainingButton>
          <TrainingButton variant="danger" disabled={mutations.archive.isPending} title="Archive requires backend permission and reason." onClick={() => mutations.archive.mutate({ reason: 'Archived from requirement detail page.' })}>Archive</TrainingButton>
        </div>
      </TrainingCard>
      <TrainingCard title="Assignments generated by this requirement"><SopAckAssignmentTable rows={detail.assignments ?? []} /></TrainingCard>
      <JsonPanel title="Links to Matrix / Competency / Training / PTW / MOC / PSSR" rows={detail.links} />
      <JsonPanel title="Requirement history" rows={detail.history} />
    </div>
  );
}

function Info({ label, value }: { label: string; value: unknown }) {
  return <div className="rounded-lg bg-[var(--psm-surface-2)] p-3"><p className="text-xs uppercase text-[var(--psm-muted)]">{label}</p><p className="mt-1 text-sm font-semibold">{String(value ?? '-')}</p></div>;
}

function JsonPanel({ title, rows }: { title: string; rows: Array<Record<string, any>> }) {
  return <TrainingCard title={title}>{rows?.length ? <div className="space-y-2">{rows.map((row, index) => <pre key={row.id ?? index} className="overflow-x-auto rounded-lg bg-[var(--psm-surface-2)] p-3 text-xs">{JSON.stringify(row, null, 2)}</pre>)}</div> : <TrainingEmptyState title="No backend rows" message={`${title} has no rows for this requirement yet.`} />}</TrainingCard>;
}
