'use client';

import { useState } from 'react';
import { ActionButton, PrimaryButton } from '../safeguards/SafeguardUiPrimitives';

export function LinkDocumentDialog({ onClose, onSubmit, saving, defaults = {} }: { onClose: () => void; onSubmit: (input: Record<string, unknown>) => void; saving?: boolean; defaults?: Record<string, unknown> }) {
  const [form, setForm] = useState<Record<string, any>>({ documentId: '', documentType: 'Inspection report', linkedModule: 'Equipment', linkedRecordId: '', relationshipType: 'Evidence', purpose: '', required: false, readinessImpact: false, expiryRequired: false, ...defaults });
  const update = (key: string, value: unknown) => setForm((current) => ({ ...current, [key]: value }));
  const missing = !form.documentId ? 'Document ID is required.' : !form.documentType ? 'Document type is required.' : !form.linkedModule ? 'Linked module is required.' : !form.linkedRecordId ? 'Linked record is required.' : '';
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><section className="w-full max-w-2xl rounded-xl border border-[var(--psm-line)] bg-[var(--psm-surface)] p-5 shadow-xl"><h2 className="text-lg font-bold">Link Document</h2><p className="mt-1 text-sm text-[var(--psm-muted)]">Links an existing Document Control record. File, version, approval, and expiry remain owned by Document Control.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{['documentId','documentType','linkedModule','linkedRecordId','relationshipType'].map((key) => <label key={key} className="text-sm font-semibold">{key.replace(/([A-Z])/g, ' $1')}<input className="mt-1 w-full rounded-lg border border-[var(--psm-line)] bg-[var(--psm-surface-2)] px-3 py-2 text-sm" value={form[key] ?? ''} onChange={(event) => update(key, event.target.value)} /></label>)}<label className="text-sm font-semibold md:col-span-2">Purpose / notes<textarea rows={3} className="mt-1 w-full rounded-lg border border-[var(--psm-line)] bg-[var(--psm-surface-2)] px-3 py-2 text-sm" value={form.purpose ?? ''} onChange={(event) => update('purpose', event.target.value)} /></label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={!!form.required} onChange={(event) => update('required', event.target.checked)} /> Required</label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={!!form.readinessImpact} onChange={(event) => update('readinessImpact', event.target.checked)} /> Readiness impact</label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={!!form.expiryRequired} onChange={(event) => update('expiryRequired', event.target.checked)} /> Expiry/review required</label></div><div className="mt-5 flex justify-end gap-2"><ActionButton onClick={onClose}>Cancel</ActionButton><PrimaryButton disabled={saving || Boolean(missing)} title={missing} onClick={() => onSubmit(form)}>{saving ? 'Saving...' : 'Link Document'}</PrimaryButton></div></section></div>;
}
