import { DocumentRequirementBadge } from '../shared/DocumentRequirementBadge';
import { DocumentStatusBadge } from '../shared/DocumentStatusBadge';
import { DocumentTypeBadge } from '../shared/DocumentTypeBadge';
import { ActionButton, cardValue } from '../safeguards/SafeguardUiPrimitives';
import type { MiDocumentLink } from '../types/mi-document.types';

export function MiDocumentsTable({ rows, onRemove }: { rows?: MiDocumentLink[]; onRemove?: (id: string) => void }) {
  if (!rows?.length) return <div className="rounded-xl border border-dashed border-[var(--psm-line)] p-6 text-sm text-[var(--psm-muted)]">No MI document links found for the current filters.</div>;
  return <div className="overflow-x-auto rounded-xl border border-[var(--psm-line)] bg-[var(--psm-surface)]"><table className="min-w-[1250px] w-full text-left text-sm"><thead className="bg-[var(--psm-surface-2)] text-xs uppercase text-[var(--psm-muted)]"><tr>{['Document Title','Document Type','Linked Module','Linked Record','Equipment','Version','Status','Approval','Expiry','Required','Readiness','Linked By','Last Updated','Actions'].map((head) => <th key={head} className="px-4 py-3">{head}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t border-[var(--psm-line)] align-top"><td className="px-4 py-3 font-semibold">{cardValue(row.document_title ?? row.document?.title ?? row.document_id)}</td><td className="px-4 py-3"><DocumentTypeBadge type={row.document_type} /></td><td className="px-4 py-3">{cardValue(row.linked_module)}</td><td className="px-4 py-3">{cardValue(row.linked_record_number ?? row.linked_record_id)}</td><td className="px-4 py-3">{cardValue(row.equipment_id)}</td><td className="px-4 py-3">{cardValue(row.version)}</td><td className="px-4 py-3"><DocumentStatusBadge status={row.status} /></td><td className="px-4 py-3">{cardValue(row.approval_status)}</td><td className="px-4 py-3">{cardValue(row.expiry_date)}</td><td className="px-4 py-3"><DocumentRequirementBadge required={row.required} /></td><td className="px-4 py-3">{row.readiness_impact ? 'Impacts readiness' : 'No'}</td><td className="px-4 py-3">{cardValue(row.linked_by)}</td><td className="px-4 py-3">{cardValue(row.linked_at)}</td><td className="px-4 py-3"><ActionButton onClick={() => onRemove?.(row.id)} disabled={!row.active} title="Inactive link">Remove Link</ActionButton></td></tr>)}</tbody></table></div>;
}
