export type ImpairmentStatus = 'Draft' | 'Pending Approval' | 'Approved' | 'Active' | 'Expiring Soon' | 'Expired' | 'Extension Requested' | 'Extension Approved' | 'Extension Rejected' | 'Pending Restoration' | 'Restored' | 'Restoration Verified' | 'Closed' | 'Rejected' | 'Cancelled';

export type ImpairmentRiskLevel = 'Low' | 'Medium' | 'High' | 'Critical';

export type MiSafeguardImpairment = {
  id: string;
  record_number?: string | null;
  safeguard_type?: string | null;
  safeguard_id?: string | null;
  safeguard_tag?: string | null;
  safeguard_description?: string | null;
  equipment_id?: string | null;
  equipment_tag?: string | null;
  equipment_criticality?: string | null;
  safety_critical?: boolean | null;
  psm_critical?: boolean | null;
  lopa_sil_ipl?: boolean | null;
  current_safeguard_status?: string | null;
  last_test_at?: string | null;
  next_test_due_at?: string | null;
  impairment_type?: string | null;
  reason?: string | null;
  work_description?: string | null;
  operational_need?: string | null;
  testing_maintenance_related?: boolean | null;
  planned_emergency?: string | null;
  requested_start_at?: string | null;
  expected_restoration_at?: string | null;
  affected_function?: string | null;
  affected_scenario?: string | null;
  affected_equipment?: string | null;
  consequence_if_needed?: string | null;
  notes?: string | null;
  risk_level?: ImpairmentRiskLevel | string | null;
  risk_assessment_summary?: string | null;
  mitigation_required?: boolean | null;
  temporary_mitigation_summary?: string | null;
  operator_monitoring_required?: boolean | null;
  temporary_alarm_or_protection?: boolean | null;
  extra_rounds_required?: boolean | null;
  reduced_operating_envelope?: boolean | null;
  standby_equipment_required?: boolean | null;
  fire_gas_watch_required?: boolean | null;
  manual_control_required?: boolean | null;
  emergency_readiness_required?: boolean | null;
  control_room_communication_required?: boolean | null;
  shift_handover_required?: boolean | null;
  management_notification_required?: boolean | null;
  start_at?: string | null;
  max_duration_value?: number | null;
  max_duration_unit?: string | null;
  expiry_at?: string | null;
  reminder_at?: string | null;
  extension_allowed?: boolean | null;
  escalation_level?: string | null;
  auto_create_action_if_expired?: boolean | null;
  status?: ImpairmentStatus | string | null;
  restoration_status?: string | null;
  requester_user_id?: string | null;
  authorized_by?: string | null;
  approved_by?: string | null;
  activated_by?: string | null;
  restored_by?: string | null;
  verified_by?: string | null;
  startup_blocked?: boolean | null;
  pssr_blocker?: boolean | null;
  moc_required?: boolean | null;
  moc_suggested?: boolean | null;
  ptw_required?: boolean | null;
  ptw_linked?: boolean | null;
  loto_required?: boolean | null;
  loto_linked?: boolean | null;
  pssr_required?: boolean | null;
  lopa_warning_required?: boolean | null;
  missing_mitigation?: boolean | null;
  timeRemainingLabel?: string | null;
  expiryStatus?: string | null;
  updated_at?: string | null;
  created_at?: string | null;
};

export type MiImpairmentSummary = {
  totalRecords: number;
  activeBypasses: number;
  activeImpairments: number;
  activeOverrides: number;
  activeInhibits: number;
  expiredBypasses: number;
  pendingApproval: number;
  pendingRestorationVerification: number;
  criticalSafeguardsImpaired: number;
  lopaSilIplsImpaired: number;
  psvReliefDevicesImpaired: number;
  sifsImpaired: number;
  interlocksImpaired: number;
  criticalAlarmsImpaired: number;
  startupBlocked: number;
  mocRequiredSuggested: number;
  ptwLotoLinked: number;
  restoredThisMonth: number;
};

export type MiImpairmentRegistryResponse = {
  rows: MiSafeguardImpairment[];
  page: number;
  limit: number;
  total: number;
  summary: MiImpairmentSummary;
  savedViews: string[];
  lastUpdated: string;
};

export type MiImpairmentDetailResponse = {
  impairment: MiSafeguardImpairment;
  approvals: Array<Record<string, unknown>>;
  extensions: Array<Record<string, unknown>>;
  restorations: Array<Record<string, unknown>>;
  linkedRecords: Array<Record<string, unknown>>;
  notifications: Array<Record<string, unknown>>;
  history: Array<Record<string, unknown>>;
  readOnly: boolean;
  readOnlyReason?: string | null;
  readiness: { status: string; blockers: string[]; warnings: string[] };
};

export type MiImpairmentLookups = {
  impairmentTypes: string[];
  statuses: string[];
  riskLevels: string[];
  safeguardTypes: string[];
};
