export type MiWorkOrderRow = {
  id: string;
  work_order_number?: string | null;
  title?: string | null;
  description?: string | null;
  equipment_id?: string | null;
  equipment_tag?: string | null;
  source_module?: string | null;
  source_record_id?: string | null;
  source_record_number?: string | null;
  source_summary?: string | null;
  current_equipment_status?: string | null;
  current_readiness_status?: string | null;
  equipment_criticality?: string | null;
  linked_deficiency_id?: string | null;
  linked_deviation_id?: string | null;
  linked_action_id?: string | null;
  work_order_type?: string | null;
  work_category?: string | null;
  work_reason?: string | null;
  required_work_scope?: string | null;
  repair_method?: string | null;
  expected_outcome?: string | null;
  acceptance_criteria?: string | null;
  work_instructions?: string | null;
  completion_evidence_required?: boolean | null;
  status?: string | null;
  priority?: string | null;
  risk_level?: string | null;
  safety_critical_work?: boolean | null;
  psm_critical_work?: boolean | null;
  readiness_impact?: string | null;
  startup_blocker?: boolean | null;
  startup_blocker_reason?: string | null;
  operation_allowed_before_completion?: boolean | null;
  temporary_control_required?: boolean | null;
  temporary_control_description?: string | null;
  ffs_required?: boolean | null;
  engineering_review_required?: boolean | null;
  pssr_impact?: boolean | null;
  lopa_sil_impact?: boolean | null;
  owner_user_id?: string | null;
  assigned_user_id?: string | null;
  assigned_team_id?: string | null;
  contractor_vendor?: string | null;
  planned_start_at?: string | null;
  planned_finish_at?: string | null;
  estimated_duration_minutes?: number | string | null;
  due_date?: string | null;
  required_outage_type?: string | null;
  shutdown_window?: string | null;
  online_work_allowed?: boolean | null;
  job_plan?: string | null;
  sequencing_notes?: string | null;
  required_coordination?: string | null;
  simops_concern?: boolean | null;
  pre_job_briefing_required?: boolean | null;
  toolbox_talk_required?: boolean | null;
  ptw_required?: boolean | null;
  ptw_type?: string | null;
  linked_ptw_id?: string | null;
  loto_required?: boolean | null;
  linked_loto_id?: string | null;
  confined_space_required?: boolean | null;
  hot_work_required?: boolean | null;
  line_break_required?: boolean | null;
  electrical_isolation_required?: boolean | null;
  working_at_height_required?: boolean | null;
  lifting_required?: boolean | null;
  gas_test_required?: boolean | null;
  ppe_requirements?: string | null;
  safety_precautions?: string | null;
  jsa_required?: boolean | null;
  jha_required?: boolean | null;
  risk_assessment_document_id?: string | null;
  method_statement_document_id?: string | null;
  parts_required?: boolean | null;
  spare_parts_list?: string | null;
  material_list?: string | null;
  tools_required?: string | null;
  special_equipment?: string | null;
  crane_lifting_required?: boolean | null;
  scaffolding_required?: boolean | null;
  contractor_required?: boolean | null;
  vendor_required?: boolean | null;
  parts_status?: string | null;
  estimated_cost?: number | string | null;
  cost_center?: string | null;
  purchase_request_reference?: string | null;
  external_cmms_reference?: string | null;
  required_shutdown?: boolean | null;
  verification_required?: boolean | null;
  moc_required?: boolean | null;
  moc_suggested?: boolean | null;
  notes?: string | null;
  read_only?: boolean | null;
  updated_at?: string | null;
  created_at?: string | null;
};

export type MiWorkOrderSummary = {
  totalOpenWorkOrders?: number;
  criticalWorkOrders?: number;
  safetyCriticalWork?: number;
  overdueWorkOrders?: number;
  dueThisWeek?: number;
  pendingPlanning?: number;
  waitingApproval?: number;
  waitingPtw?: number;
  waitingLoto?: number;
  waitingParts?: number;
  waitingShutdown?: number;
  inProgress?: number;
  pendingVerification?: number;
  failedVerification?: number;
  closedThisMonth?: number;
  linkedDeficienciesOpen?: number;
  startupBlockerWork?: number;
  mocRequiredWork?: number;
  myAssignedWork?: number;
  contractorAssignedWork?: number;
};

export type MiWorkOrderRegistryResponse = {
  rows: MiWorkOrderRow[];
  page: number;
  limit: number;
  total: number;
  summary?: MiWorkOrderSummary;
  savedViews?: string[];
  lastUpdated?: string;
};

export type MiWorkOrderDetailResponse = {
  workOrder: MiWorkOrderRow & Record<string, unknown>;
  tasks?: Array<Record<string, unknown>>;
  parts?: Array<Record<string, unknown>>;
  executionLogs?: Array<Record<string, unknown>>;
  verifications?: Array<Record<string, unknown>>;
  linkedRecords?: Array<Record<string, unknown>>;
  actionLinks?: Array<Record<string, unknown>>;
  approvals?: Array<Record<string, unknown>>;
  history?: Array<Record<string, unknown>>;
  readiness: { status: 'Ready' | 'Warning' | 'Blocked'; blockers: string[]; warnings: string[] };
};

export type MiWorkOrderLookups = {
  workOrderTypes: string[];
  actionTypes: string[];
  workCategories: string[];
  workStatuses: string[];
  priorities: string[];
  riskLevels: string[];
  partsStatuses: string[];
};
