'use client';

import { CheckCircle2, Wand2 } from 'lucide-react';
import { Badge, DetailCard, EmptyState, Field, detailInput, detailTextarea, statusTone } from '../moc-detail-ui';

const btn = 'inline-flex items-center justify-center gap-2 rounded-md border border-cyan-300/15 px-3 py-2 text-xs font-black text-slate-100 hover:border-blue-300/50 hover:bg-blue-500/10';
const primary = 'inline-flex items-center justify-center gap-2 rounded-md bg-emerald-600 px-3 py-2 text-xs font-black text-white hover:bg-emerald-500';

export function TrainingRequirementsPanel({ rows, draft, setDraft, onCreate, onGenerate }: any) {
  return <DetailCard title="Training Requirements Panel" action={<button className={btn} onClick={onGenerate}><Wand2 className="h-4 w-4" /> Generate From Impact</button>}><div className="grid gap-3 md:grid-cols-4"><Field label="Title"><input className={detailInput} value={draft.title ?? ''} onChange={(e) => setDraft((v: any) => ({ ...v, title: e.target.value }))} /></Field><Field label="Training Type"><select className={detailInput} value={draft.trainingType ?? 'General awareness'} onChange={(e) => setDraft((v: any) => ({ ...v, trainingType: e.target.value }))}>{['SOP training','Operating limits training','Equipment change briefing','Safety system training','Emergency procedure training','Contractor briefing','Control room briefing','Maintenance procedure training','General awareness','Other'].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Role"><input className={detailInput} value={draft.roleName ?? ''} onChange={(e) => setDraft((v: any) => ({ ...v, roleName: e.target.value }))} /></Field><button className={primary} onClick={onCreate}>Create Requirement</button></div><div className="mt-4 grid gap-2">{rows?.length ? rows.map((row: any) => <div key={row.id} className="rounded-lg border border-white/10 bg-white/[0.03] p-3"><div className="flex justify-between gap-2"><p className="font-black text-white">{row.title ?? row.training_topic}</p><Badge tone={statusTone(row.status)}>{row.status}</Badge></div><p className="text-xs text-slate-500">{row.training_type} · {row.role_name} · before startup {row.required_before_startup ? 'yes' : 'no'}</p></div>) : <EmptyState title="No training requirements generated yet." />}</div></DetailCard>;
}

export function TrainingCompletionTracker({ rows, onComplete, onVerify }: any) {
  return <DetailCard title="Training Completion Tracker">{rows?.length ? <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr>{['Trainee','Role','Department','Status','Completed','Evidence','Verified','Actions'].map((h) => <th key={h} className="border-b border-white/10 px-3 py-2">{h}</th>)}</tr></thead><tbody>{rows.map((row: any) => <tr key={row.id} className="border-b border-white/5 text-slate-300"><td className="px-3 py-3">{row.user_id ?? '-'}</td><td className="px-3 py-3">{row.role_id ?? '-'}</td><td className="px-3 py-3">{row.department_id ?? '-'}</td><td className="px-3 py-3"><Badge tone={statusTone(row.status)}>{row.status}</Badge></td><td className="px-3 py-3">{row.completed_at ?? '-'}</td><td className="px-3 py-3">{row.evidence_attachment_id ?? '-'}</td><td className="px-3 py-3">{row.verified_at ?? '-'}</td><td className="px-3 py-3"><button className={btn} onClick={() => onComplete(row.id)}><CheckCircle2 className="h-4 w-4" /> Complete</button><button className={`${btn} ml-2`} onClick={() => onVerify(row.id)}>Verify</button></td></tr>)}</tbody></table></div> : <EmptyState title="No training assignments yet." />}</DetailCard>;
}
