import { CausalFactorStatusBadge } from '../shared/CausalFactorStatusBadge';
import { ConfidenceLevelBadge } from '../shared/ConfidenceLevelBadge';
import { EvidenceSupportBadge } from '../shared/EvidenceSupportBadge';
import { RootCauseCategoryBadge } from '../shared/RootCauseCategoryBadge';
import { RcaActionButton, RcaEmpty, RcaPanel } from './RcaPrimitives';

export function CausalFactorsRegister({ rows, onEdit, onConfirm, onReject, onLinkEvidence, onConvert, onDelete }: any) {
  return <RcaPanel title="Causal Factors Register" subtitle="Causal factors remain separate from root causes until confirmed and promoted.">{!rows?.length ? <RcaEmpty text="No causal factors recorded." /> : <div className="overflow-auto"><table className="w-full min-w-[1280px] text-left text-xs"><thead className="text-slate-500"><tr>{['#','Title','Category','Status','Evidence','Confidence','Owner','Due','Timeline/Evidence','Statement','Actions'].map((h) => <th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{rows.map((row: any) => <tr key={row.id} className="border-t border-slate-200 align-top dark:border-cyan-300/10"><td className="p-2 font-bold">{row.causal_factor_number}</td><td className="p-2"><b>{row.title}</b><p className="text-slate-500">{row.description}</p></td><td className="p-2"><RootCauseCategoryBadge value={row.category} /></td><td className="p-2"><CausalFactorStatusBadge value={row.status} /></td><td className="p-2"><EvidenceSupportBadge value={row.evidence_support_level} /></td><td className="p-2"><ConfidenceLevelBadge value={row.confidence_level} /></td><td className="p-2">{row.owner_id ?? '-'}</td><td className="p-2">{row.due_date ?? '-'}</td><td className="p-2">{(row.related_timeline_event_ids_json?.length ?? 0)} timeline · {(row.related_evidence_ids_json?.length ?? 0)} evidence</td><td className="p-2">{row.cause_statement ?? '-'}</td><td className="p-2"><div className="flex min-w-[260px] flex-wrap gap-2"><RcaActionButton label="View/Edit" onClick={() => onEdit(row)} /><RcaActionButton label="Confirm" onClick={() => onConfirm(row.id)} /><RcaActionButton label="Reject" danger onClick={() => onReject(row.id)} /><RcaActionButton label="Link Evidence" onClick={() => onLinkEvidence(row.id)} /><RcaActionButton label="Convert Root Cause" onClick={() => onConvert(row.id)} /><RcaActionButton label="Supersede" danger onClick={() => onDelete(row.id)} /></div></td></tr>)}</tbody></table></div>}</RcaPanel>;
}
