import { get, patch, post, remove } from "./audit-api";
import type { AuditEvidenceContext, AuditEvidenceDashboard, AuditEvidenceDetail, AuditEvidenceRegister } from "../types/audit-evidence.types";

export const auditEvidenceService = {
  dashboard: (params?: Record<string, unknown>) => get<AuditEvidenceDashboard>("/audit-compliance/evidence/dashboard", params),
  register: (params?: Record<string, unknown>) => get<AuditEvidenceRegister>("/audit-compliance/evidence", params),
  context: () => get<AuditEvidenceContext>("/audit-compliance/evidence/context"),
  settings: (siteId?: string) => get<Record<string, any>>("/audit-compliance/evidence/settings", siteId ? { siteId } : undefined),
  updateSettings: (payload: Record<string, unknown>) => patch<Record<string, any>>("/audit-compliance/evidence/settings", payload),
  detail: (id: string) => get<AuditEvidenceDetail>(`/audit-compliance/evidence/${id}`),
  create: (payload: Record<string, unknown>) => post<AuditEvidenceDetail>("/audit-compliance/evidence", payload),
  upload: (payload: Record<string, unknown>) => post<AuditEvidenceDetail>("/audit-compliance/evidence/upload", payload),
  linkDocument: (payload: Record<string, unknown>) => post<AuditEvidenceDetail>("/audit-compliance/evidence/link-document", payload),
  linkModuleRecord: (payload: Record<string, unknown>) => post<AuditEvidenceDetail>("/audit-compliance/evidence/link-module-record", payload),
  update: (id: string, payload: Record<string, unknown>) => patch<AuditEvidenceDetail>(`/audit-compliance/evidence/${id}`, payload),
  transition: (id: string, action: string, payload: Record<string, unknown> = {}) => post<AuditEvidenceDetail>(`/audit-compliance/evidence/${id}/${action}`, payload),
  addLink: (id: string, payload: Record<string, unknown>) => post<AuditEvidenceDetail>(`/audit-compliance/evidence/${id}/links`, payload),
  removeLink: (id: string, linkId: string, reason: string) => remove<AuditEvidenceDetail>(`/audit-compliance/evidence/${id}/links/${linkId}`, { reason }),
  review: (id: string, action: "verify" | "reject" | "request-rework", payload: Record<string, unknown>) => post<AuditEvidenceDetail>(`/audit-compliance/evidence/${id}/${action}`, payload),
  access: (id: string, type: "preview" | "download") => get<Record<string, any>>(`/audit-compliance/evidence/${id}/${type}`),
  requirements: (params?: Record<string, unknown>) => get<AuditEvidenceRegister>("/audit-compliance/evidence/requirements", params),
  saveRequirement: (payload: Record<string, unknown>, id?: string) => id ? patch<Record<string, any>>(`/audit-compliance/evidence/requirements/${id}`, payload) : post<Record<string, any>>("/audit-compliance/evidence/requirements", payload),
  waiveRequirement: (id: string, reason: string) => post<Record<string, any>>(`/audit-compliance/evidence/requirements/${id}/waive`, { reason }),
  requests: (params?: Record<string, unknown>) => get<AuditEvidenceRegister>("/audit-compliance/evidence/requests", params),
  saveRequest: (payload: Record<string, unknown>, id?: string) => id ? patch<Record<string, any>>(`/audit-compliance/evidence/requests/${id}`, payload) : post<Record<string, any>>("/audit-compliance/evidence/requests", payload),
  requestTransition: (id: string, action: string, payload: Record<string, unknown> = {}) => post<Record<string, any>>(`/audit-compliance/evidence/requests/${id}/${action}`, payload),
  submitRequestEvidence: (id: string, payload: Record<string, unknown>) => post<Record<string, any>>(`/audit-compliance/evidence/requests/${id}/submit-evidence`, payload),
  gaps: (params?: Record<string, unknown>) => get<AuditEvidenceRegister>("/audit-compliance/evidence/gaps", params),
  detectGaps: (params?: Record<string, unknown>) => post<Record<string, any>>("/audit-compliance/evidence/gaps/detect", params),
  resolveGap: (id: string, resolutionNote: string) => post<Record<string, any>>(`/audit-compliance/evidence/gaps/${id}/resolve`, { resolutionNote }),
  packages: (params?: Record<string, unknown>) => get<AuditEvidenceRegister>("/audit-compliance/evidence/packages", params),
  savePackage: (payload: Record<string, unknown>) => post<Record<string, any>>("/audit-compliance/evidence/packages", payload),
  prepareManifest: (id: string) => post<Record<string, any>>(`/audit-compliance/evidence/packages/${id}/prepare-manifest`),
  addPackageEvidence: (id: string, evidenceId: string) => post<Record<string, any>>(`/audit-compliance/evidence/packages/${id}/add-evidence`, { evidenceId }),
  accessLog: (params?: Record<string, unknown>) => get<AuditEvidenceRegister>("/audit-compliance/evidence/access-log", params),
  history: (params?: Record<string, unknown>) => get<AuditEvidenceRegister>("/audit-compliance/evidence/history", params),
  source: (path: string, params?: Record<string, unknown>) => get<AuditEvidenceRegister>(`/audit-compliance/${path}/evidence`, params),
};
