import { get, patch, post } from './audit-api';
import type { AuditHistoryDashboard, AuditHistoryList } from '../types/audit-history.types';
import type { AuditRepeatFindingList, AuditTrendRunDetail, AuditTrendRunList } from '../types/audit-trend.types';

export const auditHistoryService = {
  history: (params?: Record<string, unknown>) => get<AuditHistoryList>('/audit-compliance/history/timeline', params),
  dashboard: (params?: Record<string, unknown>) => get<AuditHistoryDashboard>('/audit-compliance/history/dashboard', params),
  dashboardSummary: (params?: Record<string, unknown>) => get<AuditHistoryDashboard['summary']>('/audit-compliance/history/dashboard/summary', params),
  timeline: (params?: Record<string, unknown>) => get<AuditHistoryList>('/audit-compliance/history/timeline', params),
  activity: (params?: Record<string, unknown>) => get<AuditHistoryList>('/audit-compliance/history/activity', params),
  snapshots: (params?: Record<string, unknown>) => get<{ rows: Record<string, unknown>[]; total: number; page: number; limit: number }>('/audit-compliance/history/snapshots', params),
  dimension: (dimension: string, params?: Record<string, unknown>) => get<AuditHistoryList>(`/audit-compliance/history/${dimension}`, params),
  repeatFindings: (params?: Record<string, unknown>) => get<AuditRepeatFindingList>('/audit-compliance/history/repeat-findings', params),
  detectRepeatFindings: (data?: Record<string, unknown>) => post<{ rows: Record<string, unknown>[]; total: number; criteria: string[]; insufficientData: boolean }>('/audit-compliance/history/repeat-findings/detect', data),
  reviewRepeatFinding: (matchId: string, action: 'confirm' | 'reject' | 'mark-recurring' | 'mark-systemic', data: Record<string, unknown>) => post<Record<string, unknown>>(`/audit-compliance/history/repeat-findings/${matchId}/${action}`, data),
  recurringIssues: (params?: Record<string, unknown>) => get<{ rows: Record<string, unknown>[]; total: number; page: number; limit: number }>('/audit-compliance/history/recurring-issues', params),
  recurringIssue: (clusterId: string) => get<Record<string, unknown>>(`/audit-compliance/history/recurring-issues/${clusterId}`),
  recurringTransition: (clusterId: string, action: 'close' | 'reopen', data: Record<string, unknown>) => post<Record<string, unknown>>(`/audit-compliance/history/recurring-issues/${clusterId}/${action}`, data),
  trendRuns: (params?: Record<string, unknown>) => get<AuditTrendRunList>('/audit-compliance/history/trends/runs', params),
  trendView: (path: string, params?: Record<string, unknown>) => get<Record<string, unknown>>(`/audit-compliance/history/${path}`, params),
  createTrendRun: (data: Record<string, unknown>) => post<AuditTrendRunDetail>('/audit-compliance/history/trends/runs', data),
  trendRun: (trendRunId: string) => get<AuditTrendRunDetail>(`/audit-compliance/history/trends/runs/${trendRunId}`),
  trendRunSection: <T = unknown>(trendRunId: string, section: string) => get<T>(`/audit-compliance/history/trends/runs/${trendRunId}/${section}`),
  recalculateTrendRun: (trendRunId: string) => post<AuditTrendRunDetail>(`/audit-compliance/history/trends/runs/${trendRunId}/recalculate`),
  archiveTrendRun: (trendRunId: string, data: Record<string, unknown>) => post<AuditTrendRunDetail>(`/audit-compliance/history/trends/runs/${trendRunId}/archive`, data),
  continuousImprovement: (params?: Record<string, unknown>) => get<{ rows: Record<string, unknown>[]; total: number; page: number; limit: number }>('/audit-compliance/history/continuous-improvement', params),
  createOpportunity: (data: Record<string, unknown>) => post<Record<string, unknown>>('/audit-compliance/history/continuous-improvement', data),
  updateOpportunity: (opportunityId: string, data: Record<string, unknown>) => patch<Record<string, unknown>>(`/audit-compliance/history/continuous-improvement/${opportunityId}`, data),
  opportunityAction: (opportunityId: string, action: 'create-action-foundation' | 'close' | 'archive', data: Record<string, unknown>) => post<Record<string, unknown>>(`/audit-compliance/history/continuous-improvement/${opportunityId}/${action}`, data),
  settings: (params?: Record<string, unknown>) => get<Record<string, unknown>>('/audit-compliance/history/settings', params),
  updateSettings: (data: Record<string, unknown>) => patch<Record<string, unknown>>('/audit-compliance/history/settings', data),
  sourceHistory: (resource: string, id: string, params?: Record<string, unknown>) => get<AuditHistoryList>(`/audit-compliance/${resource}/${id}/history`, params),
  sourceTrends: (resource: string, id: string, params?: Record<string, unknown>) => get<AuditTrendRunList>(`/audit-compliance/${resource}/${id}/trends`, params),
  lookups: () => Promise.all([
    get<string[]>('/audit-compliance/lookups/trend-run-types'),
    get<string[]>('/audit-compliance/lookups/trend-statuses'),
    get<string[]>('/audit-compliance/lookups/trend-result-categories'),
    get<string[]>('/audit-compliance/lookups/trend-directions'),
    get<string[]>('/audit-compliance/lookups/trend-confidence-levels'),
    get<string[]>('/audit-compliance/lookups/repeat-statuses'),
    get<string[]>('/audit-compliance/lookups/recurring-issue-statuses'),
    get<string[]>('/audit-compliance/lookups/improvement-opportunity-types'),
    get<string[]>('/audit-compliance/lookups/improvement-opportunity-statuses'),
  ]).then(([trendRunTypes, trendStatuses, trendResultCategories, trendDirections, trendConfidenceLevels, repeatStatuses, recurringIssueStatuses, improvementOpportunityTypes, improvementOpportunityStatuses]) => ({ trendRunTypes, trendStatuses, trendResultCategories, trendDirections, trendConfidenceLevels, repeatStatuses, recurringIssueStatuses, improvementOpportunityTypes, improvementOpportunityStatuses })),
};
