'use client';

import { useState } from 'react';
import { TrainingButton, TrainingCard, formatTrainingError } from '../shared/TrainingUi';
import type { TrainingAssessment } from '../types/assessment.types';

export function AssessmentForm({ initial, onSubmit, saving }: { initial?: Partial<TrainingAssessment> | undefined; onSubmit: (values: Record<string, unknown>) => Promise<void>; saving?: boolean }) {
  const [form, setForm] = useState<Record<string, string | boolean | number>>({ assessmentTitle: initial?.assessment_title ?? '', assessmentCode: initial?.assessment_code ?? '', assessmentType: initial?.assessment_type ?? 'Quiz', assessmentCategory: initial?.assessment_category ?? '', assessmentStatus: initial?.assessment_status ?? 'Draft', passingScore: initial?.passing_score ?? 80, maxScore: initial?.max_score ?? 100, attemptLimit: initial?.attempt_limit ?? 1, timeLimitMinutes: initial?.time_limit_minutes ?? 30, validityDays: initial?.validity_days ?? '', manualGradingRequired: Boolean(initial?.manual_grading_required), verificationRequired: Boolean(initial?.verification_required), safetyCritical: Boolean(initial?.safety_critical), psmCritical: Boolean(initial?.psm_critical), ptwCritical: Boolean(initial?.ptw_critical), mocCritical: Boolean(initial?.moc_critical), pssrCritical: Boolean(initial?.pssr_critical), trainingItemId: initial?.training_item_id ?? '', competencyRequirementId: initial?.competency_requirement_id ?? '' });
  const [error, setError] = useState<string | null>(null);
  const update = (key: string, value: string | boolean | number) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async () => { setError(null); if (!String(form.assessmentTitle).trim()) return setError('Assessment title is required.'); try { await onSubmit(form); } catch (err) { setError(formatTrainingError(err)); } };
  return <TrainingCard title="Assessment setup" subtitle="Backend is the source of truth for grading, pass/fail, verification, expiry, and blocker state."><div className="grid gap-4 md:grid-cols-2"><Field label="Title" value={String(form.assessmentTitle)} onChange={(v) => update('assessmentTitle', v)} /><Field label="Code" value={String(form.assessmentCode)} onChange={(v) => update('assessmentCode', v)} /><Field label="Type" value={String(form.assessmentType)} onChange={(v) => update('assessmentType', v)} /><Field label="Category" value={String(form.assessmentCategory)} onChange={(v) => update('assessmentCategory', v)} /><Field label="Status" value={String(form.assessmentStatus)} onChange={(v) => update('assessmentStatus', v)} /><Field label="Passing score" type="number" value={String(form.passingScore)} onChange={(v) => update('passingScore', Number(v))} /><Field label="Max score" type="number" value={String(form.maxScore)} onChange={(v) => update('maxScore', Number(v))} /><Field label="Attempt limit" type="number" value={String(form.attemptLimit)} onChange={(v) => update('attemptLimit', Number(v))} /><Field label="Time limit minutes" type="number" value={String(form.timeLimitMinutes)} onChange={(v) => update('timeLimitMinutes', Number(v))} /><Field label="Validity days" type="number" value={String(form.validityDays)} onChange={(v) => update('validityDays', Number(v))} /><Field label="Required Training ID" value={String(form.trainingItemId)} onChange={(v) => update('trainingItemId', v)} /><Field label="Competency Requirement ID" value={String(form.competencyRequirementId)} onChange={(v) => update('competencyRequirementId', v)} /></div><div className="mt-4 grid gap-3 md:grid-cols-3">{['manualGradingRequired', 'verificationRequired', 'safetyCritical', 'psmCritical', 'ptwCritical', 'mocCritical', 'pssrCritical'].map((key) => <label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(form[key])} onChange={(event) => update(key, event.target.checked)} /> {key.replace(/([A-Z])/g, ' $1')}</label>)}</div>{error ? <p className="mt-4 rounded-lg border border-danger/30 bg-danger/10 p-3 text-sm text-danger">{error}</p> : null}<div className="mt-5 flex justify-end"><TrainingButton onClick={submit} disabled={saving}>{saving ? 'Saving...' : 'Save Assessment'}</TrainingButton></div></TrainingCard>;
}

function Field({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; type?: string }) {
  return <label className="text-sm font-medium">{label}<input className="mt-1 w-full rounded-lg border border-[var(--psm-line)] bg-[var(--psm-surface-2)] px-3 py-2" type={type} value={value} onChange={(event) => onChange(event.target.value)} /></label>;
}
