create table if not exists public.mi_critical_alarms (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  department_id text,
  unit_id text,
  area_id text,
  alarm_tag text not null,
  alarm_description text,
  alarm_type text not null default 'Critical process alarm',
  protected_equipment_id text,
  process_variable text,
  setpoint numeric,
  setpoint_unit text,
  priority text not null default 'High',
  consequence_of_missed_alarm text,
  operator_response_time numeric,
  response_time_unit text,
  required_operator_action text,
  rationalization_document_id text,
  alarm_philosophy_document_id text,
  dcs_plc_reference text,
  safety_critical boolean not null default false,
  psm_critical boolean not null default false,
  linked_sif_id text,
  linked_interlock_id text,
  linked_lopa_scenario_id text,
  test_frequency_value numeric,
  test_frequency_unit text,
  last_test_date date,
  next_test_due_date date,
  due_status text not null default 'Not Scheduled',
  last_test_result text,
  shelved_suppressed_status text,
  status text not null default 'Active',
  startup_blocked boolean not null default false,
  responsible_engineer_id text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  archived_by text,
  archive_reason text
);
