create table if not exists public.mi_safeguard_demands (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  safeguard_type text not null,
  sif_id text,
  interlock_id text,
  alarm_id text,
  demand_event_number text not null,
  event_datetime timestamptz not null,
  demand_type text not null,
  actual_trip boolean not null default false,
  spurious_trip boolean not null default false,
  successful_action boolean not null default false,
  failed_action boolean not null default false,
  process_condition text,
  cause text,
  consequence_prevented text,
  linked_incident_id text,
  event_log_document_id text,
  investigation_required boolean not null default false,
  notes text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
