alter table if exists public.incidents
  add column if not exists final_report_readiness_status text,
  add column if not exists final_report_status text,
  add column if not exists final_report_official_report_id text,
  add column if not exists final_report_published_document_id text,
  add column if not exists final_report_last_generated_at timestamptz,
  add column if not exists final_report_last_export_at timestamptz;

create table if not exists public.incident_report_templates (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text null,
  template_name text not null,
  template_type text not null,
  template_version text not null default '1.0',
  language text not null default 'English',
  supported_formats_json jsonb not null default '[]'::jsonb,
  required_sections_json jsonb not null default '[]'::jsonb,
  optional_sections_json jsonb not null default '[]'::jsonb,
  redaction_profiles_json jsonb not null default '[]'::jsonb,
  document_template_id text null,
  header_footer_branding_json jsonb not null default '{}'::jsonb,
  approval_signature_block_json jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_report_snapshots (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  snapshot_number text not null,
  source_tabs_json jsonb not null default '[]'::jsonb,
  source_versions_json jsonb not null default '{}'::jsonb,
  approval_state_json jsonb not null default '{}'::jsonb,
  redaction_profile text not null default 'Standard',
  snapshot_status text not null default 'Created',
  notes text null,
  created_by text null,
  created_at timestamptz not null default now()
);

create table if not exists public.incident_reports (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  report_number text not null,
  report_type text not null,
  template_id text null references public.incident_report_templates(id),
  template_version text null,
  snapshot_id text null references public.incident_report_snapshots(id),
  output_format text not null,
  status text not null default 'Draft',
  official boolean not null default false,
  published boolean not null default false,
  document_id text null,
  document_number text null,
  document_revision text null,
  document_control_link text null,
  storage_key text null,
  file_size bigint null,
  redaction_profile text not null default 'Standard',
  included_sections_json jsonb not null default '[]'::jsonb,
  appendices_json jsonb not null default '[]'::jsonb,
  generation_errors_json jsonb not null default '[]'::jsonb,
  generated_by text null,
  generated_at timestamptz null,
  published_by text null,
  published_at timestamptz null,
  superseded_by text null,
  superseded_at timestamptz null,
  archived_at timestamptz null,
  notes text null,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_report_sections (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  report_id text null references public.incident_reports(id) on delete cascade,
  section_key text not null,
  section_title text not null,
  included boolean not null default true,
  required boolean not null default false,
  source_status text not null default 'Not Checked',
  missing_data text null,
  redaction_required boolean not null default false,
  display_order integer not null default 0,
  notes text null,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_report_exports (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  report_id text null references public.incident_reports(id) on delete set null,
  export_type text not null,
  status text not null default 'Requested',
  requested_by text null,
  requested_at timestamptz not null default now(),
  completed_at timestamptz null,
  error_message text null,
  storage_key text null,
  file_size bigint null,
  redaction_profile text null,
  purpose_reason text null,
  created_at timestamptz not null default now()
);

create table if not exists public.incident_report_reviews (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  report_id text null references public.incident_reports(id) on delete set null,
  status text not null default 'Requested',
  reviewer_id text null,
  due_date date null,
  comments text null,
  approved_by text null,
  approved_at timestamptz null,
  rejected_by text null,
  rejected_at timestamptz null,
  rejection_reason text null,
  rework_required boolean not null default false,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_report_packages (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  report_id text null references public.incident_reports(id) on delete set null,
  package_number text not null,
  package_type text not null default 'Evidence Package',
  status text not null default 'Draft',
  redaction_profile text not null default 'Standard',
  storage_key text null,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_report_package_items (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  package_id text not null references public.incident_report_packages(id) on delete cascade,
  item_type text not null,
  source_record_id text null,
  source_title_snapshot text null,
  included boolean not null default true,
  restricted_content boolean not null default false,
  notes text null,
  created_by text null,
  created_at timestamptz not null default now()
);

create table if not exists public.incident_report_distributions (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  report_id text null references public.incident_reports(id) on delete set null,
  action_type text not null,
  recipient_user_id text null,
  recipient_email text null,
  channel text not null default 'Notification Center',
  purpose_reason text null,
  status text not null default 'Sent',
  notification_id text null,
  created_by text null,
  created_at timestamptz not null default now()
);
