alter table if exists public.incidents
  add column if not exists barrier_analysis_required boolean default false,
  add column if not exists barrier_analysis_required_reason text,
  add column if not exists barrier_analysis_status text default 'Not Started',
  add column if not exists barrier_analysis_review_status text default 'Not Requested',
  add column if not exists barrier_analysis_ready_for_capa boolean default false,
  add column if not exists barrier_followups_required_count integer default 0;

create table if not exists public.incident_barrier_analysis (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  analysis_required boolean not null default false,
  analysis_required_reason text,
  analysis_status text not null default 'Not Started',
  review_status text not null default 'Not Requested',
  readiness_status text not null default 'Not Ready',
  readiness_score integer not null default 0,
  ready_for_capa boolean not null default false,
  blocker_summary_json jsonb not null default '[]'::jsonb,
  notes text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, incident_id)
);

create table if not exists public.incident_barriers (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  analysis_id text references public.incident_barrier_analysis(id) on delete cascade,
  barrier_number text,
  barrier_name text not null,
  barrier_type text not null,
  category text,
  expected_function text not null,
  related_hazard text,
  equipment_id text,
  chemical_id text,
  timeline_event_id text,
  hazop_scenario_id text,
  lopa_record_id text,
  ipl_record_id text,
  sif_record_id text,
  ptw_record_id text,
  moc_record_id text,
  pssr_record_id text,
  mi_record_id text,
  demand_occurred text default 'Unknown',
  demand_at timestamptz,
  expected_response text,
  actual_response text,
  response_time interval,
  response_successful text,
  partial_response boolean not null default false,
  late_response boolean not null default false,
  no_response boolean not null default false,
  detection_occurred text,
  operator_action_required boolean not null default false,
  performance_status text not null default 'Not determined',
  failure_status text,
  failure_mode text,
  failure_mechanism text,
  immediate_cause text,
  contributing_cause text,
  failure_description text,
  credited_ipl text default 'Not Determined',
  ipl_type text,
  ipl_function text,
  ipl_independence_status text,
  ipl_effectiveness_status text,
  ipl_auditability_status text,
  pfdavg_snapshot numeric,
  rrf_snapshot numeric,
  proof_test_status text,
  last_proof_test date,
  bypass_status text,
  failure_impact text,
  lopa_review_required boolean not null default false,
  sis_sif_involved boolean not null default false,
  sif_tag text,
  sif_function text,
  sif_response text,
  trip_interlock_activated text,
  trip_setpoint text,
  bypass_override_active boolean not null default false,
  bypass_authorized text,
  sif_failed_degraded_bypassed boolean not null default false,
  sil_impact_review_required boolean not null default false,
  psv_relief_involved boolean not null default false,
  psv_tag text,
  protected_equipment_id text,
  psv_lifted text,
  psv_failed_to_lift boolean not null default false,
  psv_lifted_early_late text,
  psv_leak_chatter boolean not null default false,
  set_pressure text,
  last_inspection_test date,
  inspection_overdue boolean not null default false,
  relief_path_clear text,
  discharge_flare_issue boolean not null default false,
  mi_followup_required boolean not null default false,
  alarm_interlock_involved boolean not null default false,
  alarm_tag text,
  alarm_priority text,
  alarm_activated text,
  alarm_acknowledged text,
  operator_response_time interval,
  response_according_to_procedure text,
  alarm_missed_suppressed_flooded boolean not null default false,
  interlock_bypassed boolean not null default false,
  alarm_management_followup_required boolean not null default false,
  procedure_required boolean not null default false,
  procedure_followed text,
  procedure_available text,
  procedure_current text,
  ptw_required boolean not null default false,
  ptw_issued text,
  ptw_complied_with text,
  isolation_loto_required boolean not null default false,
  isolation_completed text,
  moc_required boolean not null default false,
  moc_completed text,
  pssr_required boolean not null default false,
  pssr_completed text,
  control_failed_missing boolean not null default false,
  ppe_required boolean not null default false,
  ppe_used text,
  ppe_adequate text,
  ppe_failed boolean not null default false,
  emergency_response_required boolean not null default false,
  emergency_response_activated text,
  emergency_response_effective text,
  fire_gas_detection_involved boolean not null default false,
  evacuation_shelter_in_place_involved boolean not null default false,
  decontamination_involved boolean not null default false,
  evidence_ids_json jsonb not null default '[]'::jsonb,
  rca_item_ids_json jsonb not null default '[]'::jsonb,
  related_records_json jsonb not null default '[]'::jsonb,
  followup_required boolean not null default false,
  review_status text not null default 'Not Requested',
  notes text,
  change_reason text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.incident_barrier_followups (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  barrier_id text references public.incident_barriers(id) on delete cascade,
  followup_type text not null,
  title text not null,
  description text,
  required_reason text,
  priority text,
  owner_id text,
  due_date date,
  source_panel text,
  universal_action_id text,
  status text not null default 'Open',
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_barrier_reviews (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  analysis_id text references public.incident_barrier_analysis(id) on delete cascade,
  status text not null default 'Requested',
  reviewer_id text,
  due_date date,
  comments text,
  approved_by text,
  approved_at timestamptz,
  rejected_by text,
  rejected_at timestamptz,
  rejection_reason text,
  rework_required boolean not null default false,
  rework_notes text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
