-- Training & Competency Phase 3 - Roles & Competency Profiles core tables.

create table if not exists public.training_competency_profiles (
  id text primary key,
  company_id text not null,
  site_id text null,
  profile_code text not null,
  profile_name text not null,
  profile_type text not null,
  description text null,
  job_role text null,
  department_id text null,
  worker_type text null,
  employer_type text null,
  contractor_company_name text null,
  owner_user_id text null,
  reviewer_user_id text null,
  version text not null default '1.0',
  profile_status text not null default 'Draft',
  review_status text not null default 'Not Submitted',
  matrix_sync_status text null default 'Not Synced',
  effective_date date null,
  next_review_due date null,
  safety_critical boolean not null default false,
  psm_critical boolean not null default false,
  ptw_critical boolean not null default false,
  notes text null,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz null,
  archived_by text null,
  archive_reason text null,
  constraint training_competency_profiles_code_scope_uniq unique(company_id, site_id, profile_code)
);

create table if not exists public.training_competency_profile_scopes (
  id text primary key,
  company_id text not null,
  site_id text null,
  profile_id text not null references public.training_competency_profiles(id) on delete cascade,
  scope_type text not null,
  site_scope_id text null,
  department_id text null,
  unit_id text null,
  area_id text null,
  equipment_id text null,
  worker_type_filter text null,
  employer_type_filter text null,
  contractor_company_filter text null,
  job_role_filter text null,
  ptw_role_filter text null,
  safety_critical_filter boolean null,
  assignment_mode text not null default 'Manual assignment',
  auto_assign boolean not null default false,
  applicability_rule_json jsonb null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.training_role_duties (
  id text primary key,
  company_id text not null,
  site_id text null,
  profile_id text not null references public.training_competency_profiles(id) on delete cascade,
  duty_title text not null,
  duty_description text null,
  task_type text not null,
  safety_critical boolean not null default false,
  psm_critical boolean not null default false,
  ptw_critical boolean not null default false,
  requires_authorization boolean not null default false,
  unit_id text null,
  area_id text null,
  equipment_id text null,
  related_hazard text null,
  related_sop_id text null,
  related_psi_module text null,
  related_psi_record_id text null,
  related_ptw_type text null,
  related_emergency_response_duty text null,
  minimum_supervision_requirement text null,
  notes text null,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  removed_at timestamptz null,
  removed_by text null
);

create table if not exists public.training_competencies (
  id text primary key,
  company_id text not null,
  site_id text null,
  competency_code text not null,
  competency_name text not null,
  category text not null,
  description text null,
  default_required_level text null,
  default_evidence_rule_json jsonb null,
  safety_critical_default boolean not null default false,
  psm_critical_default boolean not null default false,
  ptw_critical_default boolean not null default false,
  renewal_interval_days_default integer null,
  linked_training_reference_id text null,
  linked_sop_id text null,
  active boolean not null default true,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz null,
  archived_by text null,
  constraint training_competencies_code_scope_uniq unique(company_id, site_id, competency_code)
);

create table if not exists public.training_competency_requirements (
  id text primary key,
  company_id text not null,
  site_id text null,
  profile_id text not null references public.training_competency_profiles(id) on delete cascade,
  competency_id text null references public.training_competencies(id) on delete set null,
  competency_code text null,
  competency_title text not null,
  competency_category text not null,
  competency_description text null,
  required_level text not null,
  mandatory boolean not null default true,
  safety_critical boolean not null default false,
  psm_critical boolean not null default false,
  ptw_critical boolean not null default false,
  recurring boolean not null default false,
  renewal_interval_days integer null,
  evidence_required boolean not null default true,
  verification_required boolean not null default false,
  assessment_required boolean not null default false,
  certificate_required boolean not null default false,
  sop_acknowledgement_required boolean not null default false,
  practical_demonstration_required boolean not null default false,
  supervisor_signoff_required boolean not null default false,
  hse_signoff_required boolean not null default false,
  minimum_passing_score numeric null,
  grace_period_days integer null,
  expiry_warning_days integer null,
  linked_training_reference_id text null,
  linked_sop_id text null,
  linked_psi_module text null,
  linked_psi_record_id text null,
  linked_ptw_role text null,
  notes text null,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  removed_at timestamptz null,
  removed_by text null
);

create table if not exists public.training_competency_evidence_rules (
  id text primary key,
  company_id text not null,
  site_id text null,
  competency_requirement_id text not null references public.training_competency_requirements(id) on delete cascade,
  accepted_evidence_types_json jsonb not null default '[]'::jsonb,
  primary_evidence_type text null,
  evidence_source_module text null,
  evidence_validity_days integer null,
  verification_workflow_required boolean not null default false,
  reviewer_role text null,
  assessor_role text null,
  esign_required boolean not null default false,
  minimum_score numeric null,
  retake_required_after_failure boolean not null default false,
  max_attempts integer null,
  evidence_document_required boolean not null default false,
  evidence_review_frequency_days integer null,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint training_competency_evidence_rules_req_uniq unique(company_id, competency_requirement_id)
);

create table if not exists public.training_worker_competency_profile_assignments (
  id text primary key,
  company_id text not null,
  site_id text null,
  worker_id text not null references public.training_workers(id) on delete cascade,
  profile_id text not null references public.training_competency_profiles(id) on delete cascade,
  profile_version text null,
  unit_id text null,
  area_id text null,
  assignment_source text not null default 'Manual assignment',
  assignment_reason text null,
  primary_profile boolean not null default false,
  effective_date date null,
  expiry_date date null,
  assignment_status text not null default 'Active',
  notes text null,
  assigned_by text null,
  assigned_at timestamptz not null default now(),
  removed_by text null,
  removed_at timestamptz null,
  remove_reason text null
);

create table if not exists public.training_competency_evaluation_runs (
  id text primary key,
  company_id text not null,
  site_id text null,
  run_scope text not null,
  scope_record_id text null,
  triggered_by_type text not null,
  triggered_by_user_id text null,
  triggered_by_module text null,
  triggered_by_record_id text null,
  status text not null default 'Queued',
  started_at timestamptz null,
  completed_at timestamptz null,
  total_workers integer not null default 0,
  evaluated_workers integer not null default 0,
  total_profiles integer not null default 0,
  evaluated_profiles integer not null default 0,
  gaps_created integer not null default 0,
  gaps_resolved integer not null default 0,
  warnings_count integer not null default 0,
  errors_count integer not null default 0,
  error_message text null,
  result_summary_json jsonb null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.training_competency_evaluations (
  id text primary key,
  company_id text not null,
  site_id text null,
  worker_id text not null references public.training_workers(id) on delete cascade,
  profile_id text not null references public.training_competency_profiles(id) on delete cascade,
  competency_requirement_id text null references public.training_competency_requirements(id) on delete set null,
  evaluation_run_id text null references public.training_competency_evaluation_runs(id) on delete set null,
  competency_status text not null default 'Not Assessed',
  evidence_status text not null default 'Missing Evidence',
  verification_status text not null default 'Not Verified',
  expiry_status text null,
  gap_status text null,
  gap_severity text null,
  ptw_blocker boolean not null default false,
  moc_blocker boolean not null default false,
  pssr_blocker boolean not null default false,
  safety_critical_work_blocker boolean not null default false,
  evidence_source_module text null,
  evidence_source_record_id text null,
  evidence_document_id text null,
  evidence_summary_json jsonb null,
  reason text null,
  recommended_action text null,
  evaluated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.training_competency_gaps (
  id text primary key,
  company_id text not null,
  site_id text null,
  worker_id text null references public.training_workers(id) on delete cascade,
  profile_id text null references public.training_competency_profiles(id) on delete cascade,
  competency_requirement_id text null references public.training_competency_requirements(id) on delete set null,
  evaluation_id text null references public.training_competency_evaluations(id) on delete set null,
  gap_title text not null,
  gap_type text not null,
  gap_severity text not null,
  gap_status text not null default 'Open',
  site_scope_id text null,
  unit_id text null,
  area_id text null,
  required_evidence text null,
  evidence_found text null,
  due_date date null,
  expiry_date date null,
  ptw_blocker boolean not null default false,
  moc_blocker boolean not null default false,
  pssr_blocker boolean not null default false,
  safety_critical_work_blocker boolean not null default false,
  owner_user_id text null,
  supervisor_user_id text null,
  action_id text null,
  waiver_id text null,
  first_detected_at timestamptz not null default now(),
  last_detected_at timestamptz not null default now(),
  resolved_at timestamptz null,
  resolved_by text null,
  verified_at timestamptz null,
  verified_by text null,
  closure_note text null,
  recommended_action text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.training_competency_profile_versions (
  id text primary key,
  company_id text not null,
  site_id text null,
  profile_id text not null references public.training_competency_profiles(id) on delete cascade,
  version text not null,
  version_type text not null,
  version_status text not null default 'Draft',
  change_summary text null,
  before_value_json jsonb null,
  after_value_json jsonb null,
  diff_json jsonb null,
  created_by text null,
  created_at timestamptz not null default now(),
  approved_by text null,
  approved_at timestamptz null,
  superseded_by_profile_id text null,
  superseded_at timestamptz null
);

create table if not exists public.training_competency_matrix_links (
  id text primary key,
  company_id text not null,
  site_id text null,
  profile_id text not null references public.training_competency_profiles(id) on delete cascade,
  competency_requirement_id text null references public.training_competency_requirements(id) on delete set null,
  matrix_rule_id text null,
  sync_status text not null default 'Not Synced',
  last_synced_at timestamptz null,
  sync_message text null,
  created_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.training_competency_waivers (
  id text primary key,
  company_id text not null,
  site_id text null,
  worker_id text null references public.training_workers(id) on delete cascade,
  gap_id text not null references public.training_competency_gaps(id) on delete cascade,
  profile_id text null references public.training_competency_profiles(id) on delete set null,
  competency_requirement_id text null references public.training_competency_requirements(id) on delete set null,
  waiver_type text not null,
  waiver_reason text not null,
  risk_justification text null,
  compensating_control text null,
  expiry_date date null,
  linked_moc_id text null,
  linked_pssr_id text null,
  linked_ptw_id text null,
  evidence_document_id text null,
  approval_status text not null default 'Requested',
  approved_by text null,
  approved_at timestamptz null,
  rejected_by text null,
  rejected_at timestamptz null,
  rejection_reason text null,
  revoked_by text null,
  revoked_at timestamptz null,
  revoke_reason text null,
  e_signature_status text null,
  created_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.training_competency_history_events (
  id text primary key,
  company_id text not null,
  site_id text null,
  unit_id text null,
  area_id text null,
  worker_id text null,
  profile_id text null,
  competency_requirement_id text null,
  gap_id text null,
  event_type text not null,
  event_title text not null,
  event_description text null,
  before_value_json jsonb null,
  after_value_json jsonb null,
  actor_user_id text null,
  source_module text not null default 'Training Roles & Competency Profiles',
  source_record_id text null,
  created_at timestamptz not null default now()
);

create table if not exists public.training_competency_settings (
  id text primary key,
  company_id text not null,
  site_id text null,
  default_profile_review_frequency_days integer not null default 365,
  auto_assign_profiles_on_worker_change boolean not null default true,
  auto_sync_profiles_to_matrix boolean not null default true,
  auto_evaluate_on_profile_change boolean not null default true,
  auto_create_actions_for_critical_gaps boolean not null default false,
  auto_notify_workers boolean not null default true,
  auto_notify_supervisors boolean not null default true,
  block_ptw_on_competency_gap boolean not null default true,
  block_moc_on_competency_gap boolean not null default true,
  block_pssr_on_competency_gap boolean not null default true,
  allow_safety_critical_waivers boolean not null default false,
  require_esign_for_blocker_waiver boolean not null default true,
  require_review_for_safety_critical_profiles boolean not null default true,
  settings_json jsonb null,
  updated_by text null,
  updated_at timestamptz not null default now(),
  constraint training_competency_settings_scope_uniq unique(company_id, site_id)
);
