create table if not exists public.mi_safeguard_tests (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  safeguard_type text not null,
  sif_id text,
  interlock_id text,
  alarm_id text,
  protected_equipment_id text,
  occurrence_id text,
  test_record_number text not null,
  planned boolean not null default true,
  unplanned_reason text,
  test_date date not null,
  test_type text not null,
  test_location text,
  online_offline_status text,
  shutdown_required boolean not null default false,
  bypass_required boolean not null default false,
  ptw_id text,
  loto_id text,
  technician_user_id text,
  engineer_user_id text,
  reviewer_user_id text,
  vendor_name text,
  procedure_document_id text,
  status text not null default 'Draft',
  review_status text not null default 'Not Submitted',
  final_result text not null default 'Not Completed',
  evaluation_status text not null default 'Not Evaluated',
  notes text,
  bypass_used boolean not null default false,
  bypass_type text,
  bypass_start_time timestamptz,
  bypass_end_time timestamptz,
  bypass_authorized_by text,
  temporary_mitigation_used text,
  bypass_restored boolean not null default true,
  restoration_verified_by text,
  restoration_time timestamptz,
  submitted_by text,
  submitted_at timestamptz,
  approved_by text,
  approved_at timestamptz,
  rejected_by text,
  rejected_at timestamptz,
  rejection_reason text,
  returned_by text,
  returned_at timestamptz,
  return_reason text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  archived_by text
);

create table if not exists public.mi_safeguard_test_steps (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  test_id text not null references public.mi_safeguard_tests(id) on delete cascade,
  step_number integer not null default 1,
  device_tag text,
  device_role text,
  test_instruction text,
  expected_response text,
  actual_response text,
  pass_fail text not null default 'Not Tested',
  response_time numeric,
  response_time_unit text,
  setpoint_verified boolean not null default false,
  trip_point_verified boolean not null default false,
  reset_verified boolean not null default false,
  evidence_required boolean not null default false,
  evidence_document_id text,
  comment text,
  finding_created boolean not null default false,
  required boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mi_safeguard_test_evaluations (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  test_id text not null references public.mi_safeguard_tests(id) on delete cascade,
  safeguard_type text not null,
  sif_id text,
  interlock_id text,
  alarm_id text,
  all_required_steps_passed boolean not null default false,
  required_response_achieved boolean not null default false,
  trip_action_achieved boolean not null default false,
  alarm_annunciated boolean not null default false,
  final_element_safe_state boolean not null default false,
  reset_behavior_correct boolean not null default false,
  response_time_within_limit boolean not null default false,
  evidence_complete boolean not null default false,
  bypass_restored boolean not null default true,
  final_result text not null,
  failed_steps_count integer not null default 0,
  evaluation_inputs_json jsonb not null default '{}'::jsonb,
  evaluation_outputs_json jsonb not null default '{}'::jsonb,
  evaluation_error text,
  evaluated_at timestamptz not null default now(),
  evaluated_by text,
  official boolean not null default false,
  created_at timestamptz not null default now()
);
