-- Mechanical Integrity Phase 5 - inspection execution records.

create table if not exists public.mi_inspection_records (
  id text primary key default gen_random_uuid()::text,
  company_id text not null references public."Company"(id) on delete cascade,
  site_id text not null references public."Site"(id) on delete cascade,
  equipment_id text not null references public.mi_equipment(id) on delete cascade,
  plan_id text null references public.mi_inspection_plans(id) on delete set null,
  occurrence_id text null references public.mi_inspection_schedule_occurrences(id) on delete set null,
  inspection_number text not null,
  inspection_type text not null,
  inspection_method text not null,
  planned boolean not null default true,
  unplanned_reason text null,
  status text not null default 'Draft',
  review_status text not null default 'Not Submitted',
  result text not null default 'Not Evaluated',
  inspection_date date not null default current_date,
  start_time time null,
  end_time time null,
  inspector_user_id text null,
  inspector_name text null,
  inspector_qualification text null,
  inspection_vendor text null,
  reviewer_user_id text null,
  responsible_engineer_id text null,
  online_offline_status text null,
  shutdown_required boolean not null default false,
  entry_required boolean not null default false,
  confined_space_permit_id text null,
  ptw_id text null,
  loto_id text null,
  procedure_document_id text null,
  instrument_used text null,
  instrument_serial_number text null,
  instrument_calibration_document_id text null,
  report_document_id text null,
  notes text null,
  plan_snapshot_json jsonb not null default '{}'::jsonb,
  occurrence_snapshot_json jsonb not null default '{}'::jsonb,
  calculation_preview_json jsonb not null default '{}'::jsonb,
  remaining_life_updated boolean not null default false,
  next_due_updated boolean not null default false,
  submitted_by text null,
  submitted_at timestamptz null,
  approved_by text null,
  approved_at timestamptz null,
  rejected_by text null,
  rejected_at timestamptz null,
  rejection_reason text null,
  returned_by text null,
  returned_at timestamptz null,
  return_reason text null,
  created_by text not null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz null,
  archived_by text null,
  archive_reason text null,
  constraint mi_inspection_records_number_unique unique (company_id, site_id, inspection_number)
);
