create table if not exists public.mi_relief_devices (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  unit_id text,
  area_id text,
  equipment_system_id text,
  device_tag text not null,
  device_name text,
  description text,
  device_type text not null default 'PSV',
  device_category text,
  manufacturer text,
  model text,
  serial_number text,
  asset_number text,
  installation_date date,
  commissioning_date date,
  status text not null default 'Active',
  owner_department text,
  custodian_user_id text,
  vendor_name text,
  building_location text,
  installation_location text,
  line_number text,
  p_and_id text,
  isometric_drawing text,
  installation_drawing text,
  valve_station_or_rack text,
  service_fluid text,
  safety_critical boolean not null default true,
  psm_critical boolean not null default false,
  protected_equipment_count integer not null default 0,
  last_test_date date,
  next_test_due_date date,
  due_status text not null default 'Not Scheduled',
  last_test_result text,
  pop_test_result text,
  leak_test_result text,
  certificate_status text not null default 'Missing',
  seal_status text,
  car_seal_status text,
  active_impairment boolean not null default false,
  startup_blocked boolean not null default false,
  readiness_status text not null default 'Missing Data',
  readiness_blockers_json jsonb not null default '[]'::jsonb,
  notes text,
  archived boolean not null default false,
  archived_at timestamptz,
  archived_by text,
  archive_reason text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mi_relief_device_readiness (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  relief_device_id text not null references public.mi_relief_devices(id) on delete cascade,
  readiness_status text not null default 'Missing Data',
  startup_blocked boolean not null default false,
  missing_required_data_json jsonb not null default '[]'::jsonb,
  blockers_json jsonb not null default '[]'::jsonb,
  warnings_json jsonb not null default '[]'::jsonb,
  last_evaluated_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
