alter table public.incidents
  add column if not exists immediate_actions_review_status text,
  add column if not exists immediate_actions_review_requested_by text,
  add column if not exists immediate_actions_review_requested_at timestamptz,
  add column if not exists immediate_actions_review_decision text,
  add column if not exists immediate_actions_review_decided_by text,
  add column if not exists immediate_actions_review_decided_at timestamptz,
  add column if not exists immediate_actions_review_reason text,
  add column if not exists immediate_actions_readiness_status text,
  add column if not exists site_safety_status text,
  add column if not exists restart_control_status text,
  add column if not exists restart_blocked_reason text,
  add column if not exists immediate_actions_status text;

alter table public.incident_immediate_actions_initial
  add column if not exists action_type text,
  add column if not exists category text,
  add column if not exists status text,
  add column if not exists priority text,
  add column if not exists due_at timestamptz,
  add column if not exists completed_at timestamptz,
  add column if not exists verified boolean not null default false,
  add column if not exists verification_status text,
  add column if not exists verified_by text,
  add column if not exists verified_at timestamptz,
  add column if not exists verification_notes text,
  add column if not exists restart_blocker boolean not null default false,
  add column if not exists capa_required boolean not null default false,
  add column if not exists capa_action_id text,
  add column if not exists emergency_response boolean not null default false,
  add column if not exists isolation_shutdown_permit boolean not null default false,
  add column if not exists spill_release_fire_response boolean not null default false,
  add column if not exists first_aid_medical_response boolean not null default false,
  add column if not exists return_to_service_required boolean not null default false,
  add column if not exists updated_by text,
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.incident_restart_controls (
  id text primary key,
  tenant_id text references public."Tenant"(id) on delete cascade,
  company_id text,
  site_id text,
  incident_id text not null,
  restart_blocked boolean not null default false,
  blocked_reason text,
  moc_required boolean not null default false,
  pssr_required boolean not null default false,
  mi_required boolean not null default false,
  approval_required boolean not null default false,
  approval_status text,
  approved_by text,
  approved_at timestamptz,
  notes text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_by text,
  updated_at timestamptz not null default now()
);
