-- Mechanical Integrity Phase 3 - CML/TML core registry.

create table if not exists public.mi_cmls (
  id text primary key default gen_random_uuid()::text,
  equipment_id text not null references public.mi_equipment(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  unit_id text null,
  area_id text null,
  cml_number text not null,
  cml_type text not null default 'CML',
  component_type text null,
  location_description text null,
  circuit_or_component_id text null,
  line_number text null,
  drawing_reference text null,
  grid_reference text null,
  service_fluid text null,
  material_of_construction text null,
  damage_mechanism text null,
  inspection_method text null,
  nominal_thickness numeric(12,4) null,
  minimum_required_thickness numeric(12,4) null,
  retirement_thickness numeric(12,4) null,
  corrosion_allowance numeric(12,4) null,
  thickness_unit text not null default 'mm',
  original_thickness numeric(12,4) null,
  original_thickness_date date null,
  alert_thickness numeric(12,4) null,
  high_corrosion_rate_threshold numeric(12,5) null,
  low_remaining_life_threshold_years numeric(12,3) null,
  inspection_frequency_value integer null,
  inspection_frequency_unit text null,
  status text not null default 'Active',
  criticality text null,
  active boolean not null default true,
  notes text null,
  created_by text null,
  updated_by text null,
  archived_at timestamptz null,
  archived_by text null,
  archive_reason text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_cmls_number_unique unique (equipment_id, cml_number)
);
