create table if not exists public.mi_deficiencies (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  equipment_id text not null,
  cml_id text,
  safeguard_type text,
  safeguard_id text,
  record_number text not null,
  record_kind text not null default 'Deficiency',
  title text not null,
  description text,
  deficiency_type text not null,
  source_module text,
  source_record_id text,
  source_record_number text,
  location_description text,
  observed_condition text,
  required_condition text,
  immediate_action_taken text,
  severity text not null,
  risk_level text not null,
  consequence_if_not_corrected text,
  probability_of_worsening text,
  critical_equipment boolean not null default false,
  safety_critical_impact boolean not null default false,
  psm_critical_impact boolean not null default false,
  environmental_impact boolean not null default false,
  production_impact boolean not null default false,
  regulatory_impact boolean not null default false,
  fitness_for_service_impact text,
  startup_blocker boolean not null default false,
  operation_allowed boolean not null default true,
  operation_restrictions text,
  ffs_required boolean not null default false,
  engineering_review_required boolean not null default false,
  moc_required boolean not null default false,
  moc_suggested boolean not null default false,
  pssr_impact boolean not null default false,
  lopa_sil_impact boolean not null default false,
  due_date date,
  target_closure_date date,
  status text not null default 'Draft',
  owner_user_id text,
  reviewer_user_id text,
  approver_user_id text,
  reported_by text,
  discovery_date date,
  submitted_at timestamptz,
  approved_at timestamptz,
  verified_at timestamptz,
  closed_at timestamptz,
  rejected_reason text,
  cancel_reason text,
  read_only boolean not null default false,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_deficiencies_record_kind_chk check (record_kind in ('Deficiency')),
  constraint mi_deficiencies_status_chk check (status in ('Draft','Submitted','Under Review','Approved','Action Assigned','In Progress','Waiting on MOC','Waiting on Shutdown','Waiting on Parts','Temporary Control Active','Ready for Verification','Verification Failed','Verified','Closed','Rejected','Cancelled')),
  constraint mi_deficiencies_severity_chk check (severity in ('Low','Medium','High','Critical')),
  constraint mi_deficiencies_risk_chk check (risk_level in ('Low','Medium','High','Critical'))
);

create table if not exists public.mi_deviations (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  equipment_id text not null,
  record_number text not null,
  deviation_type text not null,
  title text not null,
  normal_requirement text,
  requested_deviation text not null,
  reason text,
  risk_assessment_json jsonb not null default '{}'::jsonb,
  temporary_controls_json jsonb not null default '{}'::jsonb,
  start_date date not null,
  expiry_date date not null,
  extension_allowed boolean not null default false,
  extension_limit_value numeric,
  extension_limit_unit text,
  status text not null default 'Draft',
  owner_user_id text,
  approved_by text,
  approved_at timestamptz,
  closed_by text,
  closed_at timestamptz,
  rejection_reason text,
  read_only boolean not null default false,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_deviations_status_chk check (status in ('Draft','Submitted','Pending Approval','Approved','Active','Expiring Soon','Expired','Extension Requested','Extension Approved','Pending Closure Verification','Closed','Rejected','Cancelled'))
);
