alter table if exists public.incidents
  add column if not exists capa_required boolean default false,
  add column if not exists capa_required_reason text,
  add column if not exists capa_status text default 'Not Started',
  add column if not exists capa_review_status text default 'Not Requested',
  add column if not exists capa_ready_for_review boolean default false,
  add column if not exists capa_ready_for_closure boolean default false,
  add column if not exists capa_open_count integer default 0,
  add column if not exists capa_overdue_count integer default 0;

create table if not exists public.incident_capa (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  capa_required boolean not null default false,
  required_reason text,
  status text not null default 'Not Started',
  review_status text not null default 'Not Requested',
  ready_for_review boolean not null default false,
  ready_for_closure boolean not null default false,
  readiness_status text not null default 'Not Ready',
  readiness_score integer not null default 0,
  blocker_summary_json jsonb not null default '[]'::jsonb,
  notes text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, incident_id)
);

create table if not exists public.incident_capa_items (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  capa_id text references public.incident_capa(id) on delete cascade,
  capa_number text,
  universal_action_id text,
  action_title_snapshot text not null,
  description text,
  action_type text not null,
  action_category text,
  source_type text,
  priority text not null,
  risk_ranking text,
  risk_reduction_objective text,
  risk_reduction_target text,
  expected_outcome text,
  prevent_recurrence boolean not null default true,
  permanent_fix boolean not null default false,
  interim_control boolean not null default false,
  management_system_impact text,
  regulatory_impact text,
  business_impact text,
  priority_basis text,
  priority_override_reason text,
  owner_id text,
  department text,
  supporting_user_ids_json jsonb not null default '[]'::jsonb,
  due_date date,
  acceptance_required boolean not null default false,
  acceptance_status text,
  reminder_schedule text,
  escalation_owner_id text,
  assigned_by text,
  assigned_at timestamptz,
  implementation_steps text,
  resources_required text,
  work_order_required boolean not null default false,
  moc_required boolean not null default false,
  pssr_required boolean not null default false,
  ptw_required boolean not null default false,
  procedure_update_required boolean not null default false,
  training_required boolean not null default false,
  equipment_shutdown_required boolean not null default false,
  target_completion_date date,
  dependencies_json jsonb not null default '[]'::jsonb,
  implementation_status text not null default 'Not Started',
  evidence_required boolean not null default false,
  evidence_status text not null default 'Not Submitted',
  evidence_type text,
  evidence_ids_json jsonb not null default '[]'::jsonb,
  completion_statement text,
  completed_by text,
  completed_at timestamptz,
  completion_notes text,
  evidence_decision text,
  evidence_rejection_reason text,
  verification_required boolean not null default true,
  verification_method text,
  verification_due_date date,
  verification_status text not null default 'Not Started',
  effectiveness_status text not null default 'Not Determined',
  escalation_status text not null default 'Not Escalated',
  escalation_level text,
  escalation_reason text,
  escalated_by text,
  escalated_at timestamptz,
  management_review_required boolean not null default false,
  status text not null default 'Draft',
  notes text,
  change_reason text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.incident_capa_source_links (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  capa_item_id text references public.incident_capa_items(id) on delete cascade,
  source_type text not null,
  source_id text,
  source_title_snapshot text,
  capa_linked boolean not null default true,
  coverage_status text not null default 'Linked',
  justification_if_no_capa text,
  linked_action_id text,
  status text not null default 'Active',
  created_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.incident_capa_verifications (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  capa_item_id text not null references public.incident_capa_items(id) on delete cascade,
  verification_method text,
  verification_owner_id text,
  verification_due_date date,
  verification_status text not null default 'Not Started',
  verification_result text,
  effective text not null default 'Not Determined',
  rework_required boolean not null default false,
  rework_notes text,
  evidence_ids_json jsonb not null default '[]'::jsonb,
  verified_by text,
  verified_at timestamptz,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_capa_reviews (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  status text not null default 'Requested',
  reviewer_id text,
  due_date date,
  comments text,
  approved_by text,
  approved_at timestamptz,
  rejected_by text,
  rejected_at timestamptz,
  rejection_reason text,
  rework_required boolean not null default false,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
