create table if not exists public.mi_approval_instances (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text not null,
  approval_number text not null,
  source_module text not null,
  source_record_id text not null,
  source_record_number text null,
  equipment_id text null references public."Equipment"("id") on delete set null,
  approval_type text not null default 'Standard Review',
  current_stage text not null default 'Submitted',
  status text not null default 'Submitted',
  priority text not null default 'Normal',
  risk_level text null,
  safety_critical boolean not null default false,
  psm_critical boolean not null default false,
  readiness_impact boolean not null default false,
  startup_blocker boolean not null default false,
  e_signature_required boolean not null default false,
  submitted_by text not null references public."User"("id") on delete restrict,
  submitted_at timestamptz not null default now(),
  due_at timestamptz null,
  completed_at timestamptz null,
  cancelled_at timestamptz null,
  cancellation_reason text null,
  workflow_instance_id text null references public.workflow_instances(id) on delete set null,
  stale_approval boolean not null default false,
  last_validation_status text not null default 'Not Run',
  last_action text null,
  created_by text null references public."User"("id") on delete set null,
  updated_by text null references public."User"("id") on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_approval_instances_number_unique unique (company_id, site_id, approval_number),
  constraint mi_approval_instances_status_check check (status in ('Draft','Submitted','Pending Approval','In Review','Approved','Approved With Conditions','Rejected','Returned for Correction','More Information Requested','Delegated','Escalated','Cancelled','Superseded','Completed','Expired / Overdue')),
  constraint mi_approval_instances_priority_check check (priority in ('Low','Normal','Medium','High','Critical','Emergency')),
  constraint mi_approval_instances_last_validation_check check (last_validation_status in ('Not Run','Passed','Warning','Failed','Overridden'))
);

create table if not exists public.mi_approval_stages (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text not null,
  approval_instance_id uuid not null references public.mi_approval_instances(id) on delete cascade,
  stage_number integer not null,
  stage_name text not null,
  approver_role text null,
  approver_user_id text null references public."User"("id") on delete set null,
  delegated_to_user_id text null references public."User"("id") on delete set null,
  status text not null default 'Pending',
  due_at timestamptz null,
  acted_by text null references public."User"("id") on delete set null,
  acted_at timestamptz null,
  action text null,
  comments text null,
  e_signature_id text null references public.electronic_signatures(id) on delete set null,
  workflow_step_id text null references public.workflow_instance_steps(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_approval_stages_unique_stage unique (approval_instance_id, stage_number, stage_name),
  constraint mi_approval_stages_status_check check (status in ('Pending','In Progress','Approved','Rejected','Returned','Skipped','Delegated','Escalated','Cancelled'))
);

create table if not exists public.mi_approval_rules (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text null,
  rule_name text not null,
  source_module text not null,
  record_type text null,
  risk_level text null,
  safety_critical boolean null,
  psm_critical boolean null,
  readiness_impact boolean null,
  startup_blocker boolean null,
  lopa_sil_impact boolean null,
  moc_required boolean null,
  approval_chain_json jsonb not null default '[]'::jsonb,
  e_signature_required boolean not null default false,
  due_duration_value integer null,
  due_duration_unit text null,
  escalation_rule_json jsonb null,
  active boolean not null default true,
  created_by text null references public."User"("id") on delete set null,
  updated_by text null references public."User"("id") on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_approval_rules_due_unit_check check (due_duration_unit is null or due_duration_unit in ('hours','days','weeks'))
);

create table if not exists public.mi_approval_validation_results (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text not null,
  approval_instance_id uuid not null references public.mi_approval_instances(id) on delete cascade,
  validation_key text not null,
  validation_title text not null,
  validation_status text not null,
  severity text not null default 'Warning',
  message text not null,
  source_module text null,
  source_record_id text null,
  override_allowed boolean not null default false,
  overridden_by text null references public."User"("id") on delete set null,
  override_reason text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_approval_validation_unique unique (approval_instance_id, validation_key),
  constraint mi_approval_validation_status_check check (validation_status in ('Passed','Warning','Failed','Overridden')),
  constraint mi_approval_validation_severity_check check (severity in ('Info','Warning','Major','Critical','Startup Blocker'))
);

create table if not exists public.mi_approval_change_snapshots (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text not null,
  approval_instance_id uuid not null references public.mi_approval_instances(id) on delete cascade,
  source_module text not null,
  source_record_id text not null,
  snapshot_type text not null default 'Submission',
  before_snapshot_json jsonb null,
  after_snapshot_json jsonb not null default '{}'::jsonb,
  change_summary_json jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.mi_approval_comments (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text not null,
  approval_instance_id uuid not null references public.mi_approval_instances(id) on delete cascade,
  stage_id uuid null references public.mi_approval_stages(id) on delete set null,
  comment_type text not null default 'General comment',
  comment_text text not null,
  internal_only boolean not null default false,
  required_action boolean not null default false,
  attachment_document_id text null,
  created_by text not null references public."User"("id") on delete restrict,
  created_at timestamptz not null default now()
);

create table if not exists public.mi_approval_conditions (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text not null,
  approval_instance_id uuid not null references public.mi_approval_instances(id) on delete cascade,
  stage_id uuid null references public.mi_approval_stages(id) on delete set null,
  condition_text text not null,
  owner_user_id text null references public."User"("id") on delete set null,
  due_date date null,
  status text not null default 'Open',
  linked_action_id text null references public."Action"("id") on delete set null,
  created_by text not null references public."User"("id") on delete restrict,
  created_at timestamptz not null default now(),
  closed_by text null references public."User"("id") on delete set null,
  closed_at timestamptz null,
  constraint mi_approval_conditions_status_check check (status in ('Open','Action Created','Closed','Cancelled'))
);

create table if not exists public.mi_approval_history_events (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text not null,
  approval_instance_id uuid not null references public.mi_approval_instances(id) on delete cascade,
  source_module text not null,
  source_record_id text not null,
  equipment_id text null,
  event_type text not null,
  event_title text not null,
  event_description text null,
  before_value_json jsonb null,
  after_value_json jsonb null,
  actor_user_id text null references public."User"("id") on delete set null,
  created_at timestamptz not null default now()
);
