create table if not exists public.mi_sifs (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  department_id text,
  unit_id text,
  area_id text,
  sif_tag text not null,
  sif_number text,
  sif_description text,
  sif_type text not null default 'Custom',
  sis_system_name text,
  srs_document_id text,
  status text not null default 'Draft',
  lifecycle_phase text not null default 'Design',
  owner_department_id text,
  responsible_engineer_id text,
  operations_owner_id text,
  maintenance_owner_id text,
  vendor_name text,
  installation_date date,
  commissioning_date date,
  safety_critical boolean not null default true,
  psm_critical boolean not null default true,
  startup_blocker_potential boolean not null default true,
  last_test_date date,
  next_test_due_date date,
  due_status text not null default 'Not Scheduled',
  last_test_result text,
  active_bypass_count integer not null default 0,
  active_inhibit_count integer not null default 0,
  active_override_count integer not null default 0,
  degraded boolean not null default false,
  startup_blocked boolean not null default false,
  readiness_status text not null default 'Missing Data',
  readiness_blockers_json jsonb not null default '[]'::jsonb,
  notes text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  archived_by text,
  archive_reason text
);

create table if not exists public.mi_sif_readiness (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  sif_id text not null references public.mi_sifs(id) on delete cascade,
  readiness_status text not null default 'Missing Data',
  startup_blocked boolean not null default false,
  blockers_json jsonb not null default '[]'::jsonb,
  warnings_json jsonb not null default '[]'::jsonb,
  missing_required_data_json jsonb not null default '[]'::jsonb,
  last_evaluated_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
