create table if not exists public.mi_sif_cause_effect (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  sif_id text not null references public.mi_sifs(id) on delete cascade,
  initiating_cause text,
  process_variable text,
  source_tag text,
  setpoint numeric,
  setpoint_unit text,
  trip_condition text,
  alarm_trip_priority text,
  time_delay numeric,
  time_delay_unit text,
  voting_logic text,
  reset_type text,
  final_action text,
  equipment_shutdown boolean not null default false,
  valve_close_open text,
  pump_trip boolean not null default false,
  compressor_trip boolean not null default false,
  esd_activation boolean not null default false,
  alarm_activation boolean not null default false,
  interlock_activation boolean not null default false,
  isolation_action text,
  safe_state text,
  operator_action_required text,
  cause_effect_document_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mi_sif_architecture (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  sif_id text not null references public.mi_sifs(id) on delete cascade,
  architecture_type text,
  voting_arrangement text,
  sensor_voting text,
  logic_solver_voting text,
  final_element_voting text,
  redundancy text,
  common_cause_considerations text,
  diagnostic_coverage numeric,
  proof_test_coverage numeric,
  bypass_philosophy text,
  reset_philosophy text,
  manual_reset_required boolean not null default false,
  automatic_reset_allowed boolean not null default false,
  trip_energy_state text,
  fail_safe_state text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
