create table if not exists public.mi_sif_devices (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  sif_id text not null references public.mi_sifs(id) on delete cascade,
  device_tag text not null,
  device_role text not null,
  device_type text not null default 'Custom',
  linked_equipment_id text,
  measurement_parameter text,
  range_lower numeric,
  range_upper numeric,
  range_unit text,
  setpoint numeric,
  trip_point numeric,
  alarm_point numeric,
  calibration_plan_id text,
  last_calibration_date date,
  next_calibration_due date,
  device_status text not null default 'Active',
  bypass_status text,
  inhibit_status text,
  failure_status text,
  proof_test_included boolean not null default true,
  notes text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mi_sif_sil_data (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  sif_id text not null references public.mi_sifs(id) on delete cascade,
  target_sil text,
  achieved_sil text,
  required_rrf numeric,
  achieved_rrf numeric,
  pfd_avg numeric,
  demand_rate numeric,
  proof_test_interval_value numeric,
  proof_test_interval_unit text,
  proof_test_coverage numeric,
  mission_time numeric,
  diagnostic_coverage numeric,
  safe_failure_fraction numeric,
  hardware_fault_tolerance text,
  verification_document_id text,
  last_verification_date date,
  next_review_due date,
  verification_status text not null default 'Not Verified',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
