alter table if exists public.subscription_plans enable row level security;
alter table if exists public.subscription_plan_prices enable row level security;
alter table if exists public.subscription_plan_entitlements enable row level security;
alter table if exists public.company_billing_customers enable row level security;
alter table if exists public.company_subscriptions enable row level security;
alter table if exists public.company_entitlements enable row level security;
alter table if exists public.company_usage_counters enable row level security;
alter table if exists public.company_usage_events enable row level security;
alter table if exists public.billing_invoices enable row level security;
alter table if exists public.billing_payment_methods enable row level security;
alter table if exists public.billing_events enable row level security;
alter table if exists public.billing_audit_events enable row level security;
alter table if exists public.billing_admin_overrides enable row level security;

drop policy if exists service_role_all_subscription_plans on public.subscription_plans;
create policy service_role_all_subscription_plans on public.subscription_plans for all to service_role using (true) with check (true);
drop policy if exists service_role_all_subscription_plan_prices on public.subscription_plan_prices;
create policy service_role_all_subscription_plan_prices on public.subscription_plan_prices for all to service_role using (true) with check (true);
drop policy if exists service_role_all_subscription_plan_entitlements on public.subscription_plan_entitlements;
create policy service_role_all_subscription_plan_entitlements on public.subscription_plan_entitlements for all to service_role using (true) with check (true);
drop policy if exists service_role_all_company_billing_customers on public.company_billing_customers;
create policy service_role_all_company_billing_customers on public.company_billing_customers for all to service_role using (true) with check (true);
drop policy if exists service_role_all_company_subscriptions on public.company_subscriptions;
create policy service_role_all_company_subscriptions on public.company_subscriptions for all to service_role using (true) with check (true);
drop policy if exists service_role_all_company_entitlements on public.company_entitlements;
create policy service_role_all_company_entitlements on public.company_entitlements for all to service_role using (true) with check (true);
drop policy if exists service_role_all_company_usage_counters on public.company_usage_counters;
create policy service_role_all_company_usage_counters on public.company_usage_counters for all to service_role using (true) with check (true);
drop policy if exists service_role_all_company_usage_events on public.company_usage_events;
create policy service_role_all_company_usage_events on public.company_usage_events for all to service_role using (true) with check (true);
drop policy if exists service_role_all_billing_invoices on public.billing_invoices;
create policy service_role_all_billing_invoices on public.billing_invoices for all to service_role using (true) with check (true);
drop policy if exists service_role_all_billing_payment_methods on public.billing_payment_methods;
create policy service_role_all_billing_payment_methods on public.billing_payment_methods for all to service_role using (true) with check (true);
drop policy if exists service_role_all_billing_events on public.billing_events;
create policy service_role_all_billing_events on public.billing_events for all to service_role using (true) with check (true);
drop policy if exists service_role_all_billing_audit_events on public.billing_audit_events;
create policy service_role_all_billing_audit_events on public.billing_audit_events for all to service_role using (true) with check (true);
drop policy if exists service_role_all_billing_admin_overrides on public.billing_admin_overrides;
create policy service_role_all_billing_admin_overrides on public.billing_admin_overrides for all to service_role using (true) with check (true);
