alter table public.incidents
  add column if not exists team_review_status text,
  add column if not exists team_review_requested_by text,
  add column if not exists team_review_requested_at timestamptz,
  add column if not exists team_review_decision text,
  add column if not exists team_review_decided_by text,
  add column if not exists team_review_decided_at timestamptz,
  add column if not exists team_review_reason text,
  add column if not exists team_readiness_status text,
  add column if not exists team_notification_status text;

create table if not exists public.incident_investigation_team_members (
  id text primary key,
  tenant_id text references public."Tenant"(id) on delete cascade,
  company_id text,
  site_id text,
  incident_id text not null,
  user_id text,
  display_name text,
  email text,
  organization text,
  internal_external text,
  job_title text,
  department text,
  discipline text,
  team_role text,
  responsibility text,
  raci_role text,
  required_member boolean not null default false,
  lead_investigator boolean not null default false,
  reviewer boolean not null default false,
  approver boolean not null default false,
  acceptance_status text,
  accepted_at timestamptz,
  competency_status text,
  training_status text,
  independence_status text,
  conflict_status text,
  availability_status text,
  workload_status text,
  notification_status text,
  last_notified_at timestamptz,
  notes text,
  status text not null default 'Active',
  created_by text,
  created_at timestamptz not null default now(),
  updated_by text,
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_team_required_roles (
  id text primary key,
  tenant_id text references public."Tenant"(id) on delete cascade,
  company_id text,
  site_id text,
  incident_id text not null,
  role_name text not null,
  discipline text,
  required boolean not null default true,
  coverage_status text,
  generated_reason text,
  assigned_member_id text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_by text,
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_team_sessions (
  id text primary key,
  tenant_id text references public."Tenant"(id) on delete cascade,
  company_id text,
  site_id text,
  incident_id text not null,
  session_title text,
  session_type text,
  scheduled_at timestamptz,
  duration_minutes integer,
  location text,
  meeting_link text,
  status text,
  facilitator_id text,
  notes text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_by text,
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_team_notifications (
  id text primary key,
  tenant_id text references public."Tenant"(id) on delete cascade,
  company_id text,
  site_id text,
  incident_id text not null,
  member_id text,
  notification_type text,
  subject text,
  message text,
  status text,
  sent_by text,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);
