create table if not exists public.mi_relief_device_test_requirements (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  relief_device_id text not null references public.mi_relief_devices(id) on delete cascade,
  test_required boolean not null default true,
  test_type text,
  frequency_value integer,
  frequency_unit text,
  last_test_date date,
  next_test_due_date date,
  due_status text not null default 'Not Scheduled',
  test_due_basis text,
  test_procedure_document_id text,
  pop_pressure_tolerance_type text,
  pop_pressure_tolerance_value numeric,
  pop_pressure_tolerance_unit text,
  leak_test_required boolean not null default false,
  seat_tightness_standard text,
  certificate_required boolean not null default true,
  third_party_test_required boolean not null default false,
  test_vendor text,
  review_required boolean not null default true,
  e_signature_required boolean not null default false,
  scheduler_active boolean not null default true,
  manual_override_due_date date,
  manual_override_reason text,
  scheduler_notes text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
