create table if not exists public.mi_safeguard_history_events (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  safeguard_type text,
  sif_id text,
  interlock_id text,
  alarm_id text,
  test_id text,
  protected_equipment_id text,
  event_type text not null,
  event_title text not null,
  event_description text,
  before_value_json jsonb,
  after_value_json jsonb,
  actor_user_id text,
  source_module text not null default 'MechanicalIntegrity',
  source_record_id text,
  created_at timestamptz not null default now()
);
