-- Training & Competency Phase 2 - Training Matrix core tables.

create table if not exists public.training_matrix_rules (
  id text primary key,
  company_id text not null,
  site_id text null,
  rule_code text not null,
  rule_title text not null,
  training_reference_id text null,
  training_code text null,
  training_title text not null,
  training_category text not null,
  requirement_source text not null,
  applicability_scope text not null,
  applicability_condition_json jsonb not null default '{}'::jsonb,
  worker_type_filter text null,
  employer_type_filter text null,
  contractor_company_filter text null,
  department_id text null,
  unit_id text null,
  area_id text null,
  equipment_id text null,
  job_role_filter text null,
  competency_profile_id text null,
  ptw_role_filter text null,
  sop_id text null,
  psi_module text null,
  psi_record_id text null,
  moc_trigger_type text null,
  pssr_trigger_type text null,
  mandatory boolean not null default true,
  safety_critical boolean not null default false,
  psm_critical boolean not null default false,
  one_time boolean not null default false,
  recurring boolean not null default false,
  recurrence_interval_days integer null,
  initial_due_rule_json jsonb null,
  expiry_warning_days integer null,
  grace_period_days integer null,
  evidence_required boolean not null default true,
  verification_required boolean not null default false,
  approval_required boolean not null default false,
  blocks_ptw_authorization boolean not null default false,
  blocks_moc_implementation boolean not null default false,
  blocks_pssr_startup boolean not null default false,
  blocks_safety_critical_work boolean not null default false,
  waiver_allowed boolean not null default true,
  owner_role text null,
  priority integer not null default 0,
  rule_status text not null default 'Draft',
  active boolean not null default false,
  notes text null,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz null,
  archived_by text null,
  archive_reason text null
);

create table if not exists public.training_matrix_evaluation_runs (
  id text primary key,
  company_id text not null,
  site_id text null,
  run_scope text not null,
  scope_record_id text null,
  triggered_by_type text not null default 'Manual run',
  triggered_by_user_id text null,
  triggered_by_module text null,
  triggered_by_record_id text null,
  status text not null default 'Queued',
  started_at timestamptz null,
  completed_at timestamptz null,
  total_workers integer not null default 0,
  evaluated_workers integer not null default 0,
  total_rules integer not null default 0,
  evaluated_rules integer not null default 0,
  assignments_created integer not null default 0,
  gaps_created integer not null default 0,
  gaps_resolved integer not null default 0,
  warnings_count integer not null default 0,
  errors_count integer not null default 0,
  error_message text null,
  result_summary_json jsonb null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.training_matrix_assignments (
  id text primary key,
  company_id text not null,
  site_id text null,
  worker_id text not null references public.training_workers(id) on delete cascade,
  matrix_rule_id text not null references public.training_matrix_rules(id) on delete cascade,
  training_reference_id text null,
  training_code text null,
  training_title text not null,
  requirement_source text not null,
  requirement_reason text not null,
  applies_to_scope text not null,
  applies_to_record_id text null,
  mandatory boolean not null default true,
  safety_critical boolean not null default false,
  psm_critical boolean not null default false,
  due_date date null,
  expiry_date date null,
  recurrence_interval_days integer null,
  assignment_status text not null default 'Required - Missing',
  created_by_engine_run_id text null references public.training_matrix_evaluation_runs(id) on delete set null,
  first_assigned_at timestamptz not null default now(),
  last_evaluated_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(company_id, worker_id, matrix_rule_id)
);

create table if not exists public.training_matrix_evaluations (
  id text primary key,
  company_id text not null,
  site_id text null,
  worker_id text not null references public.training_workers(id) on delete cascade,
  matrix_rule_id text not null references public.training_matrix_rules(id) on delete cascade,
  matrix_assignment_id text null references public.training_matrix_assignments(id) on delete set null,
  evaluation_run_id text null references public.training_matrix_evaluation_runs(id) on delete set null,
  training_reference_id text null,
  evaluation_status text not null default 'Completed',
  completion_status text not null default 'Missing Evidence',
  evidence_status text not null default 'Missing Evidence',
  verification_status text not null default 'Not Verified',
  due_status text not null default 'Not Determined',
  expiry_status text not null default 'Not Determined',
  gap_status text not null default 'Open',
  gap_severity text null,
  ptw_blocker boolean not null default false,
  moc_blocker boolean not null default false,
  pssr_blocker boolean not null default false,
  safety_critical_work_blocker boolean not null default false,
  evidence_source_module text null,
  evidence_source_record_id text null,
  evidence_document_id text null,
  evidence_summary_json jsonb null,
  reason text null,
  recommended_action text null,
  evaluated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.training_matrix_gaps (
  id text primary key,
  company_id text not null,
  site_id text null,
  worker_id text not null references public.training_workers(id) on delete cascade,
  matrix_rule_id text null references public.training_matrix_rules(id) on delete set null,
  matrix_assignment_id text null references public.training_matrix_assignments(id) on delete set null,
  evaluation_id text null references public.training_matrix_evaluations(id) on delete set null,
  training_reference_id text null,
  training_code text null,
  training_title text not null,
  gap_title text not null,
  gap_type text not null,
  gap_severity text not null,
  gap_status text not null default 'Open',
  due_date date null,
  expiry_date date null,
  evidence_expected text null,
  evidence_found text null,
  requirement_reason text null,
  ptw_blocker boolean not null default false,
  moc_blocker boolean not null default false,
  pssr_blocker boolean not null default false,
  safety_critical_work_blocker boolean not null default false,
  owner_user_id text null,
  supervisor_user_id text null,
  action_id text null,
  waiver_id text null,
  first_detected_at timestamptz not null default now(),
  last_detected_at timestamptz not null default now(),
  resolved_at timestamptz null,
  resolved_by text null,
  verified_at timestamptz null,
  verified_by text null,
  closure_note text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.training_matrix_worker_summaries (
  id text primary key,
  company_id text not null,
  site_id text null,
  worker_id text not null references public.training_workers(id) on delete cascade,
  total_required integer not null default 0,
  complete_count integer not null default 0,
  incomplete_count integer not null default 0,
  overdue_count integer not null default 0,
  expiring_soon_count integer not null default 0,
  missing_evidence_count integer not null default 0,
  pending_verification_count integer not null default 0,
  waived_count integer not null default 0,
  safety_critical_gap_count integer not null default 0,
  ptw_blocker_count integer not null default 0,
  moc_blocker_count integer not null default 0,
  pssr_blocker_count integer not null default 0,
  overall_matrix_status text not null default 'Unknown / Not Evaluated',
  training_status text not null default 'Not Assessed',
  certification_status text null,
  competency_status text null,
  ptw_authorization_status text null,
  last_evaluation_run_id text null,
  evaluated_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(company_id, worker_id)
);

create table if not exists public.training_matrix_waivers (
  id text primary key,
  company_id text not null,
  site_id text null,
  worker_id text not null references public.training_workers(id) on delete cascade,
  gap_id text not null references public.training_matrix_gaps(id) on delete cascade,
  matrix_rule_id text null references public.training_matrix_rules(id) on delete set null,
  waiver_type text not null default 'Temporary',
  waiver_reason text not null,
  risk_justification text null,
  compensating_control text null,
  expiry_date date null,
  linked_moc_id text null,
  linked_pssr_id text null,
  linked_ptw_id text null,
  evidence_document_id text null,
  approval_status text not null default 'Requested',
  approved_by text null,
  approved_at timestamptz null,
  rejected_by text null,
  rejected_at timestamptz null,
  rejection_reason text null,
  revoked_by text null,
  revoked_at timestamptz null,
  revoke_reason text null,
  e_signature_status text null,
  created_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.training_matrix_action_links (
  id text primary key,
  company_id text not null,
  site_id text null,
  gap_id text not null references public.training_matrix_gaps(id) on delete cascade,
  action_id text not null,
  action_status text null,
  action_owner_id text null,
  linked_by text null,
  linked_at timestamptz not null default now(),
  unlinked_by text null,
  unlinked_at timestamptz null
);

create table if not exists public.training_matrix_history_events (
  id text primary key,
  company_id text not null,
  site_id text null,
  unit_id text null,
  area_id text null,
  worker_id text null,
  matrix_rule_id text null,
  gap_id text null,
  run_id text null,
  event_type text not null,
  event_title text not null,
  event_description text null,
  before_value_json jsonb null,
  after_value_json jsonb null,
  actor_user_id text null,
  source_module text not null default 'Training Matrix',
  source_record_id text null,
  created_at timestamptz not null default now()
);

create table if not exists public.training_matrix_settings (
  id text primary key,
  company_id text not null,
  site_id text null,
  default_expiry_warning_days integer not null default 30,
  default_grace_period_days integer not null default 0,
  auto_evaluate_on_worker_change boolean not null default true,
  auto_evaluate_on_rule_change boolean not null default true,
  auto_create_actions_for_critical_gaps boolean not null default false,
  auto_notify_workers boolean not null default true,
  auto_notify_supervisors boolean not null default true,
  block_ptw_on_required_training_gap boolean not null default true,
  block_moc_on_required_training_gap boolean not null default true,
  block_pssr_on_required_training_gap boolean not null default true,
  allow_safety_critical_waivers boolean not null default false,
  require_esign_for_blocker_waiver boolean not null default true,
  scheduled_matrix_run_enabled boolean not null default false,
  scheduled_matrix_run_frequency text null,
  settings_json jsonb null,
  updated_by text null,
  updated_at timestamptz not null default now()
);
