create table if not exists public.mi_sif_test_requirements (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  sif_id text not null references public.mi_sifs(id) on delete cascade,
  proof_test_required boolean not null default true,
  proof_test_type text,
  frequency_value numeric,
  frequency_unit text,
  interval_source text,
  last_test_date date,
  next_test_due_date date,
  due_status text not null default 'Not Scheduled',
  test_procedure_document_id text,
  acceptance_criteria_json jsonb not null default '{}'::jsonb,
  proof_test_coverage numeric,
  online_test_allowed boolean not null default false,
  shutdown_required boolean not null default false,
  bypass_required boolean not null default false,
  ptw_required boolean not null default false,
  loto_required boolean not null default false,
  review_required boolean not null default true,
  e_signature_required boolean not null default false,
  report_required boolean not null default true,
  scheduler_active boolean not null default true,
  manual_override_due_date date,
  manual_override_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mi_safeguard_test_requirements (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  safeguard_type text not null,
  sif_id text,
  interlock_id text,
  alarm_id text,
  test_type text,
  frequency_value numeric,
  frequency_unit text,
  last_test_date date,
  next_test_due_date date,
  due_status text not null default 'Not Scheduled',
  test_procedure_document_id text,
  acceptance_criteria_json jsonb not null default '{}'::jsonb,
  review_required boolean not null default true,
  e_signature_required boolean not null default false,
  report_required boolean not null default true,
  scheduler_active boolean not null default true,
  manual_override_due_date date,
  manual_override_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
