create table if not exists public.mi_relief_device_protected_equipment (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  relief_device_id text not null references public.mi_relief_devices(id) on delete cascade,
  equipment_id text not null references public.mi_equipment(id) on delete restrict,
  protected_equipment_tag text,
  protected_equipment_type text,
  protected_equipment_mawp numeric,
  protected_equipment_design_pressure numeric,
  protected_equipment_design_temperature numeric,
  service_fluid text,
  service_status text,
  criticality text,
  relationship_type text not null default 'Primary protection',
  primary_protection boolean not null default true,
  backup_protection boolean not null default false,
  shared_header boolean not null default false,
  multiple_equipment_protected boolean not null default false,
  relief_path_description text,
  upstream_isolation text,
  downstream_isolation text,
  car_seal_required boolean not null default false,
  snapshot_json jsonb not null default '{}'::jsonb,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
