-- Mechanical Integrity Phase 6 - criticality assessments.

create table if not exists public.mi_criticality_assessments (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  equipment_id text not null,
  config_id text references public.mi_criticality_configs(id),
  assessment_number text not null,
  assessment_type text not null,
  assessment_reason text not null,
  assessment_date date not null default current_date,
  assessment_method text not null default 'Configured Matrix',
  status text not null default 'Draft',
  approval_status text not null default 'Not Submitted',
  revision_number integer not null default 1,
  previous_assessment_id text references public.mi_criticality_assessments(id),
  assessor_user_id text,
  assessor_name text,
  reviewer_user_id text,
  reviewer_name text,
  review_frequency_months integer,
  next_review_due date,
  notes text,
  equipment_snapshot_json jsonb not null default '{}'::jsonb,
  config_snapshot_json jsonb not null default '{}'::jsonb,
  integrity_drivers_json jsonb not null default '{}'::jsonb,
  safety_critical boolean not null default false,
  safety_critical_reason text,
  primary_safety_function text,
  failure_consequence text,
  safeguard_role text,
  protected_equipment_id text,
  ipl_candidate boolean not null default false,
  lopa_sil_linked_scenario_id text,
  sif_linked boolean not null default false,
  critical_alarm_interlock_linked boolean not null default false,
  psv_relief_protection_linked boolean not null default false,
  bypass_allowed boolean,
  bypass_approval_required boolean,
  testing_required boolean,
  psm_critical boolean not null default false,
  psm_critical_reason text,
  psm_element_affected text,
  related_hazard_scenario text,
  startup_blocker_potential boolean not null default false,
  process_containment_role boolean not null default false,
  energy_isolation_relevance boolean not null default false,
  chemical_release_potential boolean not null default false,
  fire_explosion_potential boolean not null default false,
  toxic_exposure_potential boolean not null default false,
  environmental_release_potential boolean not null default false,
  consequence_score numeric,
  likelihood_score numeric,
  weighted_score numeric,
  final_risk_score numeric,
  risk_matrix_cell text,
  criticality_category text,
  inspection_priority text,
  rbi_candidate boolean not null default false,
  risk_change_direction text,
  calculation_status text not null default 'Not Calculated',
  manual_override boolean not null default false,
  override_category text,
  override_reason text,
  submitted_by text,
  submitted_at timestamptz,
  approved_by text,
  approved_at timestamptz,
  rejected_by text,
  rejected_at timestamptz,
  rejection_reason text,
  returned_by text,
  returned_at timestamptz,
  return_reason text,
  archived_at timestamptz,
  archived_by text,
  archive_reason text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, site_id, assessment_number)
);
