-- Mechanical Integrity Phase 4 - inspection plan core tables.

create table if not exists public.mi_inspection_plans (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  equipment_id text not null references public.mi_equipment(id) on delete cascade,
  plan_number text not null,
  plan_title text not null,
  plan_description text null,
  plan_type text not null,
  inspection_category text null,
  inspection_method text not null,
  status text not null default 'Draft',
  approval_status text not null default 'Draft',
  revision_number integer not null default 0,
  parent_plan_id text null references public.mi_inspection_plans(id),
  effective_date date null,
  expiry_review_date date null,
  responsible_department_id text null,
  responsible_team_id text null,
  responsible_user_id text null,
  vendor_required boolean not null default false,
  vendor_name text null,
  priority text not null default 'Normal',
  criticality_basis text null,
  scheduler_active boolean not null default true,
  current_next_due_date date null,
  current_due_status text not null default 'Not Scheduled',
  current_due_basis text null,
  current_scheduler_status text not null default 'Not Configured',
  created_by text null,
  updated_by text null,
  approved_by text null,
  approved_at timestamptz null,
  archived_by text null,
  archived_at timestamptz null,
  archive_reason text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_inspection_plan_number_unique unique (company_id, site_id, plan_number)
);
