create table if not exists public.mi_safeguard_impairments (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  equipment_id text,
  record_number text not null,
  safeguard_type text not null,
  safeguard_id text not null,
  safeguard_tag text,
  impairment_type text not null,
  reason text not null,
  work_description text,
  operational_need text,
  testing_maintenance_related boolean not null default false,
  planned_emergency text not null default 'Planned',
  affected_function text,
  affected_hazard_scenario text,
  affected_equipment text,
  consequence_if_unavailable text,
  notes text,
  risk_level text not null,
  risk_assessment_json jsonb not null default '{}'::jsonb,
  risk_assessment_snapshot_json jsonb not null default '{}'::jsonb,
  temporary_mitigation_required boolean not null default false,
  temporary_mitigation_measures text,
  additional_operator_monitoring boolean not null default false,
  temporary_alarm boolean not null default false,
  temporary_physical_protection boolean not null default false,
  extra_field_rounds boolean not null default false,
  reduced_operating_envelope boolean not null default false,
  reduced_inventory_pressure_temperature boolean not null default false,
  standby_personnel boolean not null default false,
  fire_watch_gas_watch boolean not null default false,
  manual_control_procedure boolean not null default false,
  emergency_response_readiness boolean not null default false,
  communication_to_control_room boolean not null default false,
  control_room_notified boolean not null default false,
  shift_handover_required boolean not null default false,
  management_notification_required boolean not null default false,
  start_time timestamptz not null,
  expected_restoration_time timestamptz not null,
  max_allowed_duration_value integer not null,
  max_allowed_duration_unit text not null default 'hours',
  expiry_time timestamptz not null,
  reminder_time timestamptz,
  extension_allowed boolean not null default false,
  extension_limit_value integer,
  extension_limit_unit text,
  extension_reason text,
  extension_approver text,
  expired_escalation_level text,
  auto_create_action_if_expired boolean not null default true,
  status text not null default 'Draft',
  startup_blocker boolean not null default false,
  lopa_sil_impact boolean not null default false,
  pssr_impact boolean not null default false,
  moc_required boolean not null default false,
  moc_suggested boolean not null default false,
  ptw_linked boolean not null default false,
  loto_linked boolean not null default false,
  emergency_override boolean not null default false,
  restoration_status text,
  requested_by text not null,
  authorized_by text,
  approved_by text,
  activated_by text,
  restored_by text,
  verified_by text,
  closed_by text,
  created_by text not null,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  submitted_at timestamptz,
  approved_at timestamptz,
  activated_at timestamptz,
  restored_at timestamptz,
  verified_at timestamptz,
  closed_at timestamptz,
  cancel_reason text,
  rejection_reason text,
  read_only boolean not null default false,
  metadata_json jsonb not null default '{}'::jsonb,
  constraint mi_safeguard_impairments_status_chk check (status in ('Draft','Pending Approval','Approved','Active','Expiring Soon','Expired','Extension Requested','Extension Approved','Extension Rejected','Pending Restoration','Restored','Restoration Verified','Closed','Rejected','Cancelled')),
  constraint mi_safeguard_impairments_risk_chk check (risk_level in ('Low','Medium','High','Critical')),
  constraint mi_safeguard_impairments_type_chk check (impairment_type in ('Bypass','Impairment','Override','Inhibit','Defeat','Isolation','Out of service','Removed from service','Suppressed','Shelved','Disabled','Degraded','Unavailable')),
  constraint mi_safeguard_impairments_duration_chk check (max_allowed_duration_value > 0)
);
