create table if not exists public.mi_work_orders (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text not null,
  equipment_id text not null references public."Equipment"("id") on delete cascade,
  cml_id uuid null,
  safeguard_type text null,
  safeguard_id text null,
  work_order_number text not null,
  title text not null,
  description text null,
  work_order_type text not null,
  work_category text null,
  work_reason text null,
  required_work_scope text null,
  repair_method text null,
  expected_outcome text null,
  acceptance_criteria text null,
  work_instructions text null,
  completion_evidence_required boolean not null default false,
  verification_required boolean not null default false,
  status text not null default 'Draft',
  priority text not null default 'Medium',
  risk_level text not null default 'Medium',
  safety_critical_work boolean not null default false,
  psm_critical_work boolean not null default false,
  readiness_impact text null,
  startup_blocker boolean not null default false,
  startup_blocker_reason text null,
  operation_allowed_before_completion boolean not null default true,
  temporary_control_required boolean not null default false,
  temporary_control_description text null,
  ffs_required boolean not null default false,
  engineering_review_required boolean not null default false,
  moc_required boolean not null default false,
  moc_suggested boolean not null default false,
  pssr_impact boolean not null default false,
  lopa_sil_impact boolean not null default false,
  owner_user_id text null,
  assigned_user_id text null,
  assigned_team_id text null,
  contractor_vendor text null,
  planned_start_at timestamptz null,
  planned_finish_at timestamptz null,
  estimated_duration_minutes integer null,
  due_date date null,
  required_shutdown boolean not null default false,
  shutdown_window text null,
  online_work_allowed boolean not null default true,
  required_outage_type text null,
  job_plan text null,
  job_steps_json jsonb null,
  sequencing_notes text null,
  simops_concern boolean not null default false,
  required_coordination text null,
  pre_job_briefing_required boolean not null default false,
  toolbox_talk_required boolean not null default false,
  ptw_required boolean not null default false,
  ptw_type text null,
  linked_ptw_id text null,
  loto_required boolean not null default false,
  linked_loto_id text null,
  confined_space_required boolean not null default false,
  hot_work_required boolean not null default false,
  line_break_required boolean not null default false,
  electrical_isolation_required boolean not null default false,
  working_at_height_required boolean not null default false,
  lifting_required boolean not null default false,
  gas_test_required boolean not null default false,
  ppe_requirements text null,
  safety_precautions text null,
  jsa_required boolean not null default false,
  jha_required boolean not null default false,
  risk_assessment_document_id text null,
  method_statement_document_id text null,
  parts_required boolean not null default false,
  spare_parts_list text null,
  material_list text null,
  tools_required text null,
  special_equipment text null,
  crane_lifting_required boolean not null default false,
  scaffolding_required boolean not null default false,
  contractor_required boolean not null default false,
  vendor_required boolean not null default false,
  parts_status text not null default 'Not Required',
  estimated_cost numeric null,
  cost_center text null,
  purchase_request_reference text null,
  external_cmms_reference text null,
  source_module text null,
  source_record_id text null,
  source_summary text null,
  linked_deficiency_id text null references public.mi_deficiencies(id) on delete set null,
  linked_deviation_id text null references public.mi_deviations(id) on delete set null,
  linked_action_id text null,
  submitted_at timestamptz null,
  approved_at timestamptz null,
  started_at timestamptz null,
  completed_at timestamptz null,
  verified_at timestamptz null,
  closed_at timestamptz null,
  rejected_reason text null,
  cancel_reason text null,
  read_only boolean not null default false,
  created_by text not null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_work_orders_company_site_number_unique unique (company_id, site_id, work_order_number),
  constraint mi_work_orders_status_check check (status in ('Draft','Submitted','Waiting Approval','Approved','Planning','Waiting PTW','Waiting LOTO','Waiting Parts','Waiting Shutdown','Scheduled','Ready to Start','In Progress','On Hold','Completed','Pending Verification','Verification Failed','Verified','Closed','Rejected','Cancelled')),
  constraint mi_work_orders_priority_check check (priority in ('Low','Medium','High','Urgent','Emergency')),
  constraint mi_work_orders_risk_level_check check (risk_level in ('Low','Medium','High','Critical')),
  constraint mi_work_orders_parts_status_check check (parts_status in ('Not Required','Required','Requested','Ordered','Partially Available','Available','Issued','Consumed','Not Available')),
  constraint mi_work_orders_planned_range_check check (planned_finish_at is null or planned_start_at is null or planned_finish_at >= planned_start_at)
);

create table if not exists public.mi_work_order_tasks (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text not null,
  work_order_id uuid not null references public.mi_work_orders(id) on delete cascade,
  task_number text not null,
  task_title text not null,
  task_description text null,
  required boolean not null default false,
  status text not null default 'Open',
  assigned_user_id text null,
  completed_by text null,
  completed_at timestamptz null,
  evidence_required boolean not null default false,
  evidence_document_id text null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_work_order_tasks_status_check check (status in ('Open','Assigned','In Progress','Blocked','Completed','Verified','Closed','Overdue','Cancelled'))
);

create table if not exists public.mi_work_order_parts (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text not null,
  work_order_id uuid not null references public.mi_work_orders(id) on delete cascade,
  part_name text not null,
  part_number text null,
  quantity_required numeric not null default 1,
  quantity_used numeric null,
  unit text null,
  status text not null default 'Required',
  purchase_reference text null,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_work_order_parts_status_check check (status in ('Not Required','Required','Requested','Ordered','Partially Available','Available','Issued','Consumed','Not Available'))
);
