-- Mechanical Integrity Phase 5 - UT readings captured during inspection execution.

create table if not exists public.mi_inspection_record_cml_readings (
  id text primary key default gen_random_uuid()::text,
  company_id text not null references public."Company"(id) on delete cascade,
  site_id text not null references public."Site"(id) on delete cascade,
  inspection_record_id text not null references public.mi_inspection_records(id) on delete cascade,
  equipment_id text not null references public.mi_equipment(id) on delete cascade,
  cml_id text not null references public.mi_cmls(id) on delete cascade,
  cml_thickness_reading_id text null references public.mi_cml_thickness_readings(id) on delete set null,
  plan_id text null references public.mi_inspection_plans(id) on delete set null,
  occurrence_id text null references public.mi_inspection_schedule_occurrences(id) on delete set null,
  reading_date date not null default current_date,
  current_thickness numeric(12,4) null,
  thickness_unit text not null default 'mm',
  normalized_thickness numeric(12,4) null,
  previous_approved_thickness numeric(12,4) null,
  previous_approved_reading_date date null,
  original_thickness numeric(12,4) null,
  minimum_required_thickness numeric(12,4) null,
  alert_thickness numeric(12,4) null,
  retirement_thickness numeric(12,4) null,
  reading_status text not null default 'Draft',
  review_status text not null default 'Not Submitted',
  calculation_status text not null default 'Not Calculated',
  alert_state text not null default 'Not Evaluated',
  not_inspected boolean not null default false,
  not_inspected_reason text null,
  not_accessible boolean not null default false,
  not_accessible_reason text null,
  inspector_user_id text null,
  inspector_name text null,
  surface_condition text null,
  scan_direction text null,
  temperature_condition text null,
  measurement_point_label text null,
  notes text null,
  attachment_document_id text null,
  approved_by text null,
  approved_at timestamptz null,
  rejected_by text null,
  rejected_at timestamptz null,
  rejected_reason text null,
  superseded_by_reading_id text null references public.mi_inspection_record_cml_readings(id) on delete set null,
  calculation_preview_json jsonb not null default '{}'::jsonb,
  created_by text not null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
