create table if not exists public.mi_interlocks (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  department_id text,
  unit_id text,
  area_id text,
  interlock_tag text not null,
  interlock_description text,
  interlock_type text not null default 'Process interlock',
  protected_equipment_id text,
  cause_description text,
  effect_action text,
  process_variable text,
  setpoint numeric,
  setpoint_unit text,
  trip_condition text,
  reset_method text,
  logic_location text,
  dcs_plc_reference text,
  safety_critical boolean not null default false,
  psm_critical boolean not null default false,
  linked_sif_id text,
  linked_lopa_scenario_id text,
  test_frequency_value numeric,
  test_frequency_unit text,
  last_test_date date,
  next_test_due_date date,
  due_status text not null default 'Not Scheduled',
  last_test_result text,
  bypass_status text,
  inhibit_status text,
  status text not null default 'Active',
  startup_blocked boolean not null default false,
  responsible_engineer_id text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  archived_by text,
  archive_reason text
);
