-- Mechanical Integrity Phase 5 - auditable remaining-life evaluations.

create table if not exists public.mi_remaining_life_evaluations (
  id text primary key default gen_random_uuid()::text,
  company_id text not null references public."Company"(id) on delete cascade,
  site_id text not null references public."Site"(id) on delete cascade,
  equipment_id text not null references public.mi_equipment(id) on delete cascade,
  cml_id text not null references public.mi_cmls(id) on delete cascade,
  inspection_record_id text null references public.mi_inspection_records(id) on delete set null,
  cml_reading_id text null references public.mi_inspection_record_cml_readings(id) on delete set null,
  cml_calculation_snapshot_id text null references public.mi_cml_calculation_snapshots(id) on delete set null,
  evaluation_type text not null default 'Preview',
  evaluation_status text not null default 'Calculated',
  baseline_thickness numeric(12,4) null,
  baseline_date date null,
  previous_thickness numeric(12,4) null,
  previous_reading_date date null,
  current_thickness numeric(12,4) null,
  current_reading_date date null,
  minimum_required_thickness numeric(12,4) null,
  alert_thickness numeric(12,4) null,
  retirement_thickness numeric(12,4) null,
  short_term_corrosion_rate numeric(12,5) null,
  long_term_corrosion_rate numeric(12,5) null,
  governing_corrosion_rate numeric(12,5) null,
  governing_rate_method text null,
  remaining_life_years numeric(12,3) null,
  half_life_interval_years numeric(12,3) null,
  half_life_due_date date null,
  alert_state text not null default 'Not Evaluated',
  calculation_inputs_json jsonb not null default '{}'::jsonb,
  calculation_result_json jsonb not null default '{}'::jsonb,
  calculation_error text null,
  official boolean not null default false,
  calculated_at timestamptz not null default now(),
  calculated_by text null,
  created_at timestamptz not null default now()
);
