-- Mechanical Integrity Phase 7 - preventive maintenance plan foundation.

create table if not exists public.mi_pm_plans (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  equipment_id text not null,
  plan_number text not null,
  plan_title text not null,
  plan_description text,
  pm_category text,
  pm_task_type text not null,
  status text not null default 'Draft',
  approval_status text not null default 'Not Submitted',
  revision_number integer not null default 1,
  parent_plan_id text references public.mi_pm_plans(id),
  effective_date date not null default current_date,
  review_date date,
  priority text not null default 'Normal',
  responsible_department_id text,
  responsible_team_id text,
  responsible_user_id text,
  vendor_required boolean not null default false,
  vendor_name text,
  scheduler_active boolean not null default true,
  current_next_due_date date,
  current_due_status text not null default 'Not Scheduled',
  current_scheduler_status text not null default 'Not Run',
  procedure_document_id text,
  required_evidence boolean not null default false,
  required_measurements boolean not null default false,
  required_photos boolean not null default false,
  required_tools_json jsonb not null default '[]'::jsonb,
  required_spares_json jsonb not null default '[]'::jsonb,
  required_consumables_json jsonb not null default '[]'::jsonb,
  required_shutdown boolean not null default false,
  online_maintenance_allowed boolean not null default true,
  isolation_required boolean not null default false,
  loto_required boolean not null default false,
  ptw_required boolean not null default false,
  confined_space_required boolean not null default false,
  vendor_report_required boolean not null default false,
  supervisor_verification_required boolean not null default false,
  esignature_required boolean not null default false,
  acceptance_criteria text,
  notes text,
  created_by text,
  updated_by text,
  approved_by text,
  approved_at timestamptz,
  rejected_by text,
  rejected_at timestamptz,
  rejection_reason text,
  archived_by text,
  archived_at timestamptz,
  archive_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, site_id, plan_number)
);

create table if not exists public.mi_pm_plan_checklist_items (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  plan_id text not null references public.mi_pm_plans(id) on delete cascade,
  item_number text not null,
  section_title text,
  task_title text not null,
  task_instruction text,
  response_type text not null default 'Done/Not Done',
  acceptance_criteria text,
  evidence_required boolean not null default false,
  attachment_required boolean not null default false,
  required boolean not null default true,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
