create table if not exists public.mi_safeguard_bypass_foundation (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  safeguard_type text not null,
  sif_id text,
  interlock_id text,
  alarm_id text,
  bypass_allowed boolean not null default false,
  inhibit_allowed boolean not null default false,
  override_allowed boolean not null default false,
  approval_required boolean not null default true,
  maximum_duration_value numeric,
  maximum_duration_unit text,
  temporary_mitigation_required boolean not null default true,
  operations_approval_required boolean not null default true,
  engineering_approval_required boolean not null default true,
  moc_required_for_extended_bypass boolean not null default true,
  startup_blocker_if_active boolean not null default true,
  alarm_banner_required boolean not null default true,
  notification_escalation_required boolean not null default true,
  bypass_procedure_document_id text,
  active_bypass_count integer not null default 0,
  active_inhibit_count integer not null default 0,
  active_override_count integer not null default 0,
  latest_status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
