alter table public.incidents
  add column if not exists unsafe_condition_remains boolean not null default false,
  add column if not exists unsafe_condition_description text,
  add column if not exists site_access_restricted boolean not null default false,
  add column if not exists barricade_cordon_active boolean not null default false,
  add column if not exists equipment_isolated boolean not null default false,
  add column if not exists energy_isolation_completed boolean not null default false,
  add column if not exists release_stopped boolean not null default false,
  add column if not exists fire_extinguished text,
  add column if not exists spill_contained text,
  add column if not exists atmosphere_tested text,
  add column if not exists permit_suspended text,
  add column if not exists site_safety_verified_by text,
  add column if not exists site_safety_verified_at timestamptz,
  add column if not exists site_safety_verification_evidence text,
  add column if not exists return_to_service_allowed text,
  add column if not exists required_before_restart text,
  add column if not exists inspection_required boolean not null default false,
  add column if not exists mi_signoff_required boolean not null default false,
  add column if not exists hse_signoff_required boolean not null default false,
  add column if not exists operations_signoff_required boolean not null default false,
  add column if not exists emergency_response_activated boolean not null default false;

alter table public.incident_immediate_actions_initial
  add column if not exists action_number text,
  add column if not exists title text,
  add column if not exists description text,
  add column if not exists related_hazard text,
  add column if not exists related_timeline_event_id text,
  add column if not exists related_equipment_id text,
  add column if not exists related_chemical_id text,
  add column if not exists related_person_id text,
  add column if not exists verification_required boolean not null default false,
  add column if not exists verification_criteria text,
  add column if not exists verification_evidence text,
  add column if not exists evidence_required boolean not null default false,
  add column if not exists evidence_count integer not null default 0,
  add column if not exists evidence_id text,
  add column if not exists linked_evidence_ids text[] not null default '{}',
  add column if not exists change_reason text,
  add column if not exists alarm_raised boolean not null default false,
  add column if not exists evacuation_initiated boolean not null default false,
  add column if not exists emergency_response_team_called boolean not null default false,
  add column if not exists fire_brigade_called boolean not null default false,
  add column if not exists ambulance_medical_called boolean not null default false,
  add column if not exists external_agency_called boolean not null default false,
  add column if not exists emergency_response_start_time timestamptz,
  add column if not exists emergency_response_end_time timestamptz,
  add column if not exists response_commander text,
  add column if not exists response_summary text,
  add column if not exists equipment_stopped boolean not null default false,
  add column if not exists equipment_isolated boolean not null default false,
  add column if not exists energy_isolation_completed boolean not null default false,
  add column if not exists lockout_tagout_applied text,
  add column if not exists process_shutdown boolean not null default false,
  add column if not exists unit_shutdown boolean not null default false,
  add column if not exists bypass_active boolean not null default false,
  add column if not exists permit_suspended boolean not null default false,
  add column if not exists ptw_number text,
  add column if not exists isolation_certificate_reference text,
  add column if not exists isolation_owner text,
  add column if not exists isolation_verified_by text,
  add column if not exists isolation_verified_at timestamptz,
  add column if not exists spill_release_occurred boolean not null default false,
  add column if not exists spill_release_contained boolean not null default false,
  add column if not exists release_source_isolated boolean not null default false,
  add column if not exists cleanup_started boolean not null default false,
  add column if not exists cleanup_completed boolean not null default false,
  add column if not exists fire_occurred boolean not null default false,
  add column if not exists fire_extinguished boolean not null default false,
  add column if not exists fire_response_used text,
  add column if not exists extinguishing_agent_used text,
  add column if not exists environmental_containment_completed boolean not null default false,
  add column if not exists waste_generated text,
  add column if not exists waste_disposal_required boolean not null default false,
  add column if not exists environmental_sample_required boolean not null default false,
  add column if not exists first_aid_provided boolean not null default false,
  add column if not exists first_aid_provider text,
  add column if not exists medical_treatment_arranged boolean not null default false,
  add column if not exists decontamination_performed boolean not null default false,
  add column if not exists emergency_services_called boolean not null default false,
  add column if not exists transported_to_medical boolean not null default false,
  add column if not exists medical_response_time timestamptz,
  add column if not exists medical_evidence_id text,
  add column if not exists restricted_medical_notes text,
  add column if not exists temporary_control_added boolean not null default false,
  add column if not exists temporary_control_type text,
  add column if not exists temporary_control_description text,
  add column if not exists temporary_control_owner_id text,
  add column if not exists temporary_control_start_at timestamptz,
  add column if not exists temporary_control_expiry_at timestamptz,
  add column if not exists review_frequency text,
  add column if not exists last_verified_by text,
  add column if not exists last_verified_at timestamptz,
  add column if not exists next_verification_due_at timestamptz,
  add column if not exists replacement_permanent_action_required boolean not null default false,
  add column if not exists linked_capa_action_id text,
  add column if not exists capa_conversion_status text,
  add column if not exists verification_method text,
  add column if not exists failed_verification_reason text,
  add column if not exists rework_required boolean not null default false,
  add column if not exists cancellation_reason text,
  add column if not exists superseded_by_action_id text;

alter table public.incident_restart_controls
  add column if not exists equipment_unit_process_affected text,
  add column if not exists return_to_service_allowed text,
  add column if not exists required_before_restart text,
  add column if not exists inspection_required boolean not null default false,
  add column if not exists hse_signoff_required boolean not null default false,
  add column if not exists operations_signoff_required boolean not null default false,
  add column if not exists evidence_links text[] not null default '{}';

create index if not exists idx_incident_immediate_actions_initial_action_number on public.incident_immediate_actions_initial(tenant_id, incident_id, action_number);
create index if not exists idx_incident_immediate_actions_initial_verification on public.incident_immediate_actions_initial(tenant_id, incident_id, verification_status, verification_required);
create index if not exists idx_incident_immediate_actions_initial_capa on public.incident_immediate_actions_initial(tenant_id, incident_id, capa_conversion_status);
