alter table public.incidents
  add column if not exists notifications_reporting_review_status text,
  add column if not exists notifications_reporting_readiness_status text,
  add column if not exists reporting_determination_status text,
  add column if not exists reporting_required_status text,
  add column if not exists reporting_next_deadline_at timestamptz,
  add column if not exists reporting_open_reports_count integer not null default 0,
  add column if not exists reporting_overdue_reports_count integer not null default 0,
  add column if not exists reporting_failed_notifications_count integer not null default 0,
  add column if not exists reporting_missing_required_count integer not null default 0;

create table if not exists public.incident_reporting_determinations (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text references public."Company"(id) on delete set null,
  site_id text references public."Site"(id) on delete set null,
  incident_id text not null references public.incidents(id) on delete cascade,
  determination_status text not null default 'Not Determined',
  reporting_required text not null default 'Not Determined',
  jurisdiction text,
  applicable_rule_key text,
  trigger_reasons_json jsonb not null default '[]'::jsonb,
  evidence_source_fields_json jsonb not null default '[]'::jsonb,
  confidence text,
  reviewer_id text references public."User"(id) on delete set null,
  review_status text not null default 'Not Requested',
  notes text,
  created_by text references public."User"(id) on delete set null,
  updated_by text references public."User"(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_notifications (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text references public."Company"(id) on delete set null,
  site_id text references public."Site"(id) on delete set null,
  incident_id text not null references public.incidents(id) on delete cascade,
  notification_number text not null,
  notification_type text not null,
  recipient_user_id text references public."User"(id) on delete set null,
  recipient_group text,
  recipient_external_contact text,
  channel text not null default 'In-app',
  subject text not null,
  message_redacted_snapshot text,
  trigger_reason text,
  priority text not null default 'Normal',
  acknowledgement_required boolean not null default false,
  acknowledgement_due_at timestamptz,
  status text not null default 'Draft',
  sent_by text references public."User"(id) on delete set null,
  sent_at timestamptz,
  acknowledged_by text references public."User"(id) on delete set null,
  acknowledged_at timestamptz,
  failed_reason text,
  notification_center_id text references public.notifications(id) on delete set null,
  related_report_id text,
  related_action_id text,
  include_incident_summary boolean not null default true,
  include_restricted_data boolean not null default false,
  include_attachments boolean not null default false,
  notes text,
  created_by text references public."User"(id) on delete set null,
  updated_by text references public."User"(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_regulatory_reports (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text references public."Company"(id) on delete set null,
  site_id text references public."Site"(id) on delete set null,
  incident_id text not null references public.incidents(id) on delete cascade,
  report_number text not null,
  report_type text not null,
  jurisdiction text,
  agency text,
  applicable_rule_key text,
  trigger_reason text,
  required_status text not null default 'Not Determined',
  deadline_at timestamptz,
  owner_id text references public."User"(id) on delete set null,
  reviewer_id text references public."User"(id) on delete set null,
  submission_method text,
  status text not null default 'Not Determined',
  submitted_by text references public."User"(id) on delete set null,
  submitted_at timestamptz,
  submitted_to text,
  submission_reference text,
  acknowledgement_received boolean not null default false,
  acknowledgement_number text,
  acknowledgement_at timestamptz,
  rejected boolean not null default false,
  rejection_reason text,
  package_document_id text,
  package_status text,
  required_data_checklist_json jsonb not null default '[]'::jsonb,
  required_evidence_json jsonb not null default '[]'::jsonb,
  attachments_json jsonb not null default '[]'::jsonb,
  notes text,
  created_by text references public."User"(id) on delete set null,
  updated_by text references public."User"(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_reporting_requirements (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text references public."Company"(id) on delete set null,
  site_id text references public."Site"(id) on delete set null,
  incident_id text not null references public.incidents(id) on delete cascade,
  report_id text references public.incident_regulatory_reports(id) on delete cascade,
  requirement_key text not null,
  requirement_label text not null,
  status text not null default 'Missing',
  source_tab text,
  missing_field text,
  required_evidence text,
  blocking boolean not null default true,
  created_by text references public."User"(id) on delete set null,
  updated_by text references public."User"(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_external_stakeholder_notifications (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text references public."Company"(id) on delete set null,
  site_id text references public."Site"(id) on delete set null,
  incident_id text not null references public.incidents(id) on delete cascade,
  stakeholder_type text not null,
  stakeholder_name text,
  contact text,
  notification_required boolean not null default false,
  reason text,
  channel text,
  deadline_at timestamptz,
  status text not null default 'Not Determined',
  acknowledgement_status text,
  notes text,
  created_by text references public."User"(id) on delete set null,
  updated_by text references public."User"(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_reporting_reviews (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text references public."Company"(id) on delete set null,
  site_id text references public."Site"(id) on delete set null,
  incident_id text not null references public.incidents(id) on delete cascade,
  status text not null default 'Requested',
  reviewer_id text references public."User"(id) on delete set null,
  due_date date,
  comments text,
  approved_by text references public."User"(id) on delete set null,
  approved_at timestamptz,
  rejected_by text references public."User"(id) on delete set null,
  rejected_at timestamptz,
  rejection_reason text,
  rework_required boolean not null default false,
  created_by text references public."User"(id) on delete set null,
  updated_by text references public."User"(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
