create table if not exists public.mi_readiness_assessments (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text not null,
  equipment_id text not null references public."Equipment"("id") on delete cascade,
  assessment_number text not null,
  assessment_reason text not null,
  assessment_date date not null default current_date,
  status text not null default 'Draft',
  current_equipment_status text null,
  previous_readiness_decision text null,
  recommended_decision text not null default 'Pending Verification',
  proposed_decision text null,
  approved_decision text null,
  decision_source text not null default 'Backend readiness engine',
  engineering_justification text null,
  ffs_required boolean not null default false,
  ffs_assessment_reference text null,
  technical_basis text null,
  risk_acceptance_statement text null,
  operation_allowed boolean not null default false,
  startup_blocked boolean not null default false,
  pssr_impact boolean not null default false,
  moc_required boolean not null default false,
  lopa_sil_impact boolean not null default false,
  restriction_active boolean not null default false,
  restriction_expiry_date date null,
  next_review_due date null,
  assessor_user_id text not null,
  reviewer_user_id text null,
  approved_by text null,
  approved_at timestamptz null,
  rejected_by text null,
  rejected_at timestamptz null,
  rejection_reason text null,
  override_reason text null,
  override_approved_by text null,
  override_approved_at timestamptz null,
  read_only boolean not null default false,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_readiness_assessment_number_unique unique (company_id, site_id, assessment_number),
  constraint mi_readiness_status_check check (status in ('Draft','Check Complete','Submitted','In Review','Approved','Rejected','Override Requested','Closed','Cancelled','Superseded')),
  constraint mi_readiness_recommended_decision_check check (recommended_decision in ('Fit for Service','Fit for Service with Restrictions','Not Fit for Service','Startup Blocked','Operate Temporarily Under Deviation','Engineering Review Required','Pending Verification','Out of Service','Decommissioned / Retired')),
  constraint mi_readiness_proposed_decision_check check (proposed_decision is null or proposed_decision in ('Fit for Service','Fit for Service with Restrictions','Not Fit for Service','Startup Blocked','Operate Temporarily Under Deviation','Engineering Review Required','Pending Verification','Out of Service','Decommissioned / Retired')),
  constraint mi_readiness_approved_decision_check check (approved_decision is null or approved_decision in ('Fit for Service','Fit for Service with Restrictions','Not Fit for Service','Startup Blocked','Operate Temporarily Under Deviation','Engineering Review Required','Pending Verification','Out of Service','Decommissioned / Retired'))
);

create table if not exists public.mi_readiness_blockers (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text not null,
  assessment_id uuid not null references public.mi_readiness_assessments(id) on delete cascade,
  equipment_id text not null references public."Equipment"("id") on delete cascade,
  source_module text not null,
  source_record_id text null,
  source_record_number text null,
  blocker_type text not null,
  blocker_title text not null,
  blocker_description text null,
  severity text not null default 'Warning',
  blocker_status text not null default 'Open',
  readiness_impact text null,
  startup_blocker boolean not null default false,
  recommended_action text null,
  owner_user_id text null,
  due_date date null,
  cleared_by text null,
  cleared_at timestamptz null,
  waiver_reason text null,
  waived_by text null,
  waived_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_readiness_blocker_severity_check check (severity in ('Info','Warning','Major','Critical','Startup Blocker')),
  constraint mi_readiness_blocker_status_check check (blocker_status in ('Open','Accepted With Restriction','Controlled','Action Assigned','Waiting Verification','Cleared','Waived With Approval'))
);

create table if not exists public.mi_readiness_restrictions (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text not null,
  assessment_id uuid not null references public.mi_readiness_assessments(id) on delete cascade,
  equipment_id text not null references public."Equipment"("id") on delete cascade,
  restriction_type text not null,
  restriction_description text not null,
  reduced_pressure text null,
  reduced_temperature text null,
  reduced_rate text null,
  additional_monitoring text null,
  temporary_controls text null,
  expiry_date date not null,
  owner_user_id text null,
  status text not null default 'Active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_readiness_restriction_status_check check (status in ('Draft','Active','Expired','Closed','Superseded'))
);
