create table if not exists public.mi_safeguard_occurrences (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  safeguard_type text not null,
  sif_id text,
  interlock_id text,
  alarm_id text,
  occurrence_number text not null,
  due_date date not null,
  due_basis text,
  status text not null default 'Scheduled',
  assigned_user_id text,
  assigned_team_id text,
  scheduled_start_date date,
  scheduled_end_date date,
  superseded_by_occurrence_id text,
  completed_test_id text,
  completed_at timestamptz,
  completed_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
