create table if not exists public.mi_relief_device_seals (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  relief_device_id text not null references public.mi_relief_devices(id) on delete cascade,
  seal_required boolean not null default false,
  seal_number text,
  seal_status text,
  car_seal_status text,
  lock_status text,
  upstream_valve_status text,
  downstream_valve_status text,
  seal_installed_by text,
  seal_installed_at timestamptz,
  seal_broken boolean not null default false,
  seal_broken_reason text,
  seal_restored_at timestamptz,
  seal_inspection_frequency_value integer,
  seal_inspection_frequency_unit text,
  last_seal_verification date,
  next_seal_verification_due date,
  notes text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
