create table if not exists public.mi_report_templates (
  id text primary key default gen_random_uuid()::text,
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text null references public."Site"("id") on delete set null,
  template_name text not null,
  report_category text not null,
  report_type text not null,
  description text null,
  config_json jsonb not null default '{}'::jsonb,
  output_formats_json jsonb not null default '["PDF","Excel","CSV","JSON"]'::jsonb,
  active boolean not null default true,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz null
);

create table if not exists public.mi_generated_reports (
  id text primary key default gen_random_uuid()::text,
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text null references public."Site"("id") on delete set null,
  report_number text not null,
  report_title text not null,
  report_category text not null,
  report_type text not null,
  template_id text null references public.mi_report_templates(id) on delete set null,
  status text not null default 'Generated',
  filters_json jsonb not null default '{}'::jsonb,
  output_format text not null default 'PDF',
  metadata_json jsonb not null default '{}'::jsonb,
  file_document_id text null,
  file_key text null,
  generated_by text not null,
  generated_at timestamptz null,
  error_message text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mi_export_jobs (
  id text primary key default gen_random_uuid()::text,
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text null references public."Site"("id") on delete set null,
  export_number text not null,
  export_type text not null,
  status text not null default 'Queued',
  scope_type text not null default 'Site',
  equipment_id text null,
  filters_json jsonb not null default '{}'::jsonb,
  output_format text not null default 'CSV',
  include_documents boolean not null default false,
  include_history boolean not null default true,
  include_audit boolean not null default false,
  include_linked_records boolean not null default false,
  metadata_json jsonb not null default '{}'::jsonb,
  file_document_id text null,
  file_key text null,
  package_id text null,
  requested_by text not null,
  requested_at timestamptz not null default now(),
  started_at timestamptz null,
  completed_at timestamptz null,
  failed_at timestamptz null,
  error_message text null,
  records_count integer null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mi_export_packages (
  id text primary key default gen_random_uuid()::text,
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text null references public."Site"("id") on delete set null,
  package_number text not null,
  package_type text not null,
  title text not null,
  description text null,
  equipment_id text null,
  status text not null default 'Building',
  manifest_json jsonb not null default '{}'::jsonb,
  zip_file_document_id text null,
  zip_file_key text null,
  created_by text not null,
  created_at timestamptz not null default now(),
  completed_at timestamptz null
);

create table if not exists public.mi_export_package_items (
  id text primary key default gen_random_uuid()::text,
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text null references public."Site"("id") on delete set null,
  package_id text not null references public.mi_export_packages(id) on delete cascade,
  item_type text not null,
  source_module text not null,
  source_record_id text null,
  document_id text null,
  file_key text null,
  item_title text not null,
  item_status text not null default 'Included',
  included boolean not null default true,
  exclusion_reason text null,
  created_at timestamptz not null default now()
);

create table if not exists public.mi_scheduled_reports (
  id text primary key default gen_random_uuid()::text,
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text null references public."Site"("id") on delete set null,
  schedule_name text not null,
  report_template_id text not null references public.mi_report_templates(id) on delete cascade,
  schedule_frequency text not null,
  schedule_config_json jsonb not null default '{}'::jsonb,
  recipients_json jsonb not null default '[]'::jsonb,
  output_format text not null default 'PDF',
  active boolean not null default true,
  next_run_at timestamptz null,
  last_run_at timestamptz null,
  created_by text not null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mi_history_event_views (
  id text primary key default gen_random_uuid()::text,
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text null references public."Site"("id") on delete set null,
  equipment_id text null,
  source_module text not null,
  source_record_id text null,
  source_record_number text null,
  event_type text not null,
  event_title text not null,
  event_description text null,
  event_severity text not null default 'Info',
  actor_user_id text null,
  event_at timestamptz not null default now(),
  readiness_impact boolean not null default false,
  startup_impact boolean not null default false,
  before_value_json jsonb null,
  after_value_json jsonb null,
  linked_records_json jsonb not null default '[]'::jsonb,
  audit_log_id text null,
  searchable_text text null,
  created_at timestamptz not null default now()
);
