-- Mechanical Integrity Phase 1 - inspection, PM, calibration and scheduler foundation.

create table if not exists public.mi_equipment_schedule_summary (
  id text primary key default gen_random_uuid()::text,
  equipment_id text not null references public.mi_equipment(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  inspection_required boolean not null default false,
  inspection_frequency_value integer null,
  inspection_frequency_unit text null,
  last_inspection_date date null,
  next_inspection_due_date date null,
  next_inspection_due_source text null,
  next_inspection_basis text null,
  pm_required boolean not null default false,
  pm_frequency_value integer null,
  pm_frequency_unit text null,
  last_pm_date date null,
  next_pm_due_date date null,
  calibration_required boolean not null default false,
  calibration_frequency_value integer null,
  calibration_frequency_unit text null,
  last_calibration_date date null,
  next_calibration_due_date date null,
  remaining_life_years numeric null,
  half_life_due_date date null,
  fixed_interval_due_date date null,
  rule_based_due_date date null,
  scheduler_status text null,
  scheduler_last_run_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_equipment_schedule_summary_equipment_unique unique (equipment_id)
);
