-- Mechanical Integrity Phase 1 - criticality, readiness, safeguard and impairment foundation.

create table if not exists public.mi_equipment_integrity_status (
  id text primary key default gen_random_uuid()::text,
  equipment_id text not null references public.mi_equipment(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  critical_equipment boolean not null default false,
  safety_critical_equipment boolean not null default false,
  psm_critical boolean not null default false,
  environmental_critical boolean not null default false,
  production_critical boolean not null default false,
  consequence_rating text null,
  likelihood_rating text null,
  criticality_score numeric null,
  criticality_category text null,
  risk_ranking_method text null,
  fitness_status text not null default 'Not Evaluated',
  readiness_status text not null default 'Not Evaluated',
  startup_blocked boolean not null default false,
  startup_block_reason text null,
  restrictions_summary text null,
  inspection_status text null,
  pm_status text null,
  calibration_status text null,
  bypass_active boolean not null default false,
  active_impairment_count integer not null default 0,
  open_deficiency_count integer not null default 0,
  critical_deficiency_count integer not null default 0,
  last_readiness_check_at timestamptz null,
  readiness_checked_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_equipment_integrity_status_equipment_unique unique (equipment_id)
);

create table if not exists public.mi_equipment_safeguard_role (
  id text primary key default gen_random_uuid()::text,
  equipment_id text not null references public.mi_equipment(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  is_safeguard boolean not null default false,
  safeguard_type text null,
  is_ipl_candidate boolean not null default false,
  linked_lopa_scenario_id text null,
  linked_sif_id text null,
  linked_alarm_id text null,
  linked_interlock_id text null,
  proof_test_required boolean not null default false,
  bypass_allowed boolean null,
  bypass_approval_required boolean null,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_equipment_safeguard_role_equipment_unique unique (equipment_id)
);
