-- Mechanical Integrity Phase 5 - inspection findings foundation.

create table if not exists public.mi_inspection_findings (
  id text primary key default gen_random_uuid()::text,
  company_id text not null references public."Company"(id) on delete cascade,
  site_id text not null references public."Site"(id) on delete cascade,
  equipment_id text not null references public.mi_equipment(id) on delete cascade,
  inspection_record_id text not null references public.mi_inspection_records(id) on delete cascade,
  cml_id text null references public.mi_cmls(id) on delete set null,
  finding_number text not null,
  finding_type text not null,
  severity text not null default 'Medium',
  title text not null,
  description text null,
  location_description text null,
  evidence_document_id text null,
  immediate_action_required boolean not null default false,
  repair_required boolean not null default false,
  engineering_review_required boolean not null default false,
  deficiency_required boolean not null default false,
  recommended_action text null,
  due_date date null,
  owner_user_id text null,
  status text not null default 'Open',
  linked_action_id text null,
  linked_deficiency_id text null,
  created_by text not null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_by text null,
  closed_at timestamptz null,
  closure_notes text null,
  constraint mi_inspection_findings_number_unique unique (company_id, site_id, finding_number)
);
