create table if not exists public.mi_linked_records (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text not null,
  equipment_id text null references public."Equipment"("id") on delete cascade,
  source_module text not null,
  source_record_id text not null,
  source_record_number text null,
  target_module text not null,
  target_record_id text not null,
  target_record_number text null,
  relationship_type text not null,
  relationship_description text null,
  readiness_impact boolean not null default false,
  primary_link boolean not null default false,
  permission_limited boolean not null default false,
  broken_link boolean not null default false,
  active boolean not null default true,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_linked_records_unique_active unique (company_id, source_module, source_record_id, target_module, target_record_id, relationship_type)
);

create table if not exists public.mi_document_links (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text not null,
  equipment_id text null references public."Equipment"("id") on delete cascade,
  linked_module text not null,
  linked_record_id text not null,
  linked_record_number text null,
  document_id text not null references public.documents("id") on delete cascade,
  file_id text null,
  document_type text not null,
  relationship_type text not null default 'Evidence',
  purpose text null,
  required boolean not null default false,
  readiness_impact boolean not null default false,
  expiry_required boolean not null default false,
  owner_user_id text null,
  active boolean not null default true,
  linked_by text null,
  linked_at timestamptz not null default now(),
  removed_by text null,
  removed_at timestamptz null,
  remove_reason text null,
  constraint mi_document_links_unique_active unique (company_id, linked_module, linked_record_id, document_id, relationship_type)
);

create table if not exists public.mi_document_requirements (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text null,
  requirement_name text not null,
  requirement_scope text not null default 'Equipment',
  equipment_type text null,
  equipment_category text null,
  module_name text null,
  record_type text null,
  document_type text not null,
  required_condition_json jsonb null,
  readiness_impact boolean not null default false,
  startup_blocker_if_missing boolean not null default false,
  expiry_required boolean not null default false,
  approval_required_for_waiver boolean not null default true,
  active boolean not null default true,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mi_document_requirement_evaluations (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text not null,
  equipment_id text null references public."Equipment"("id") on delete cascade,
  source_module text not null,
  source_record_id text null,
  requirement_id uuid not null references public.mi_document_requirements(id) on delete cascade,
  document_type text not null,
  required boolean not null default true,
  status text not null,
  linked_document_id uuid null references public.mi_document_links(id) on delete set null,
  missing_reason text null,
  readiness_blocker boolean not null default false,
  evaluated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.mi_document_waivers (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text not null,
  equipment_id text null references public."Equipment"("id") on delete cascade,
  requirement_id uuid not null references public.mi_document_requirements(id) on delete cascade,
  linked_module text not null,
  linked_record_id text null,
  waiver_reason text not null,
  risk_assessment_json jsonb null,
  expiry_date date null,
  status text not null default 'Requested',
  requested_by text null,
  approved_by text null,
  approved_at timestamptz null,
  rejected_by text null,
  rejected_at timestamptz null,
  rejection_reason text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_document_waiver_status_check check (status in ('Requested','Approved','Rejected','Expired','Cancelled'))
);

create table if not exists public.mi_linked_record_history_events (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text not null,
  equipment_id text null references public."Equipment"("id") on delete cascade,
  link_id uuid null references public.mi_linked_records(id) on delete set null,
  document_link_id uuid null references public.mi_document_links(id) on delete set null,
  event_type text not null,
  event_title text not null,
  event_description text null,
  before_value_json jsonb null,
  after_value_json jsonb null,
  actor_user_id text null,
  source_module text null,
  source_record_id text null,
  created_at timestamptz not null default now()
);

create table if not exists public.mi_linked_record_import_jobs (
  id uuid primary key default gen_random_uuid(),
  company_id text not null references public."Tenant"("id") on delete cascade,
  site_id text null,
  uploaded_by text null,
  file_name text not null,
  file_key text null,
  status text not null default 'Uploaded',
  total_rows integer not null default 0,
  valid_rows integer not null default 0,
  error_rows integer not null default 0,
  created_count integer not null default 0,
  updated_count integer not null default 0,
  skipped_count integer not null default 0,
  error_report_key text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
