create table if not exists public.mi_relief_device_tests (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  relief_device_id text not null references public.mi_relief_devices(id) on delete restrict,
  protected_equipment_id text references public.mi_equipment(id) on delete set null,
  occurrence_id text,
  test_record_number text not null,
  planned boolean not null default true,
  unplanned_reason text,
  test_date date not null default current_date,
  test_type text,
  test_location text,
  removed_for_test boolean not null default false,
  tested_in_place boolean not null default false,
  test_vendor text,
  technician_user_id text,
  technician_name text,
  inspector_user_id text,
  reviewer_user_id text,
  procedure_document_id text,
  test_medium text,
  ambient_conditions text,
  status text not null default 'Draft',
  review_status text not null default 'Not Submitted',
  final_result text not null default 'Not Evaluated',
  notes text,
  submitted_by text,
  submitted_at timestamptz,
  approved_by text,
  approved_at timestamptz,
  rejected_by text,
  rejected_at timestamptz,
  rejection_reason text,
  returned_by text,
  returned_at timestamptz,
  return_reason text,
  archived boolean not null default false,
  archived_at timestamptz,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mi_relief_device_test_results (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  relief_device_id text not null references public.mi_relief_devices(id) on delete restrict,
  test_id text not null references public.mi_relief_device_tests(id) on delete cascade,
  nameplate_set_pressure numeric,
  required_set_pressure numeric,
  pressure_unit text,
  as_found_pop_pressure numeric,
  as_found_deviation numeric,
  as_found_deviation_percent numeric,
  as_found_tolerance_limit numeric,
  as_found_pop_result text,
  as_found_leak_result text,
  as_found_seat_condition text,
  adjustment_required boolean not null default false,
  repair_required boolean not null default false,
  repair_performed boolean not null default false,
  repair_type text,
  parts_replaced_json jsonb not null default '[]'::jsonb,
  spring_replaced boolean not null default false,
  seat_replaced boolean not null default false,
  seal_replaced boolean not null default false,
  repair_notes text,
  replacement_device_id text,
  moc_required boolean not null default false,
  linked_moc_id text,
  as_left_set_pressure numeric,
  as_left_pop_pressure numeric,
  as_left_deviation numeric,
  as_left_deviation_percent numeric,
  as_left_tolerance_limit numeric,
  as_left_pop_result text,
  as_left_leak_result text,
  as_left_seat_condition text,
  final_set_pressure numeric,
  ready_for_installation boolean not null default false,
  result_calculation_json jsonb not null default '{}'::jsonb,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mi_relief_device_leak_tests (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  relief_device_id text not null references public.mi_relief_devices(id) on delete restrict,
  test_id text not null references public.mi_relief_device_tests(id) on delete cascade,
  leak_test_required boolean not null default false,
  leak_test_performed boolean not null default false,
  leak_test_method text,
  test_pressure numeric,
  test_pressure_unit text,
  duration_value numeric,
  duration_unit text,
  acceptance_criteria text,
  observed_leakage numeric,
  observed_leakage_unit text,
  seat_tightness_result text,
  pass_fail text,
  notes text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
