-- Mechanical Integrity Phase 7 - calibration plan foundation.

create table if not exists public.mi_calibration_plans (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  equipment_id text not null,
  plan_number text not null,
  plan_title text not null,
  plan_description text,
  instrument_type text not null,
  calibration_type text not null,
  measurement_parameter text,
  range_lower numeric,
  range_upper numeric,
  range_unit text,
  tolerance_type text not null default 'Absolute value',
  tolerance_value numeric,
  tolerance_unit text,
  tolerance_percent numeric,
  accuracy_class text,
  acceptance_criteria text,
  adjustment_allowed boolean not null default true,
  as_found_required boolean not null default true,
  as_left_required boolean not null default false,
  certificate_required boolean not null default true,
  reference_standard_required boolean not null default false,
  reference_standard_certificate_required boolean not null default false,
  procedure_document_id text,
  status text not null default 'Draft',
  approval_status text not null default 'Not Submitted',
  revision_number integer not null default 1,
  parent_plan_id text references public.mi_calibration_plans(id),
  effective_date date not null default current_date,
  review_date date,
  responsible_user_id text,
  reviewer_user_id text,
  scheduler_active boolean not null default true,
  current_next_due_date date,
  current_due_status text not null default 'Not Scheduled',
  current_scheduler_status text not null default 'Not Run',
  created_by text,
  updated_by text,
  approved_by text,
  approved_at timestamptz,
  rejected_by text,
  rejected_at timestamptz,
  rejection_reason text,
  archived_by text,
  archived_at timestamptz,
  archive_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, site_id, plan_number)
);

create table if not exists public.mi_calibration_plan_points (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  plan_id text not null references public.mi_calibration_plans(id) on delete cascade,
  point_number text not null,
  input_value numeric not null,
  expected_output numeric not null,
  unit text,
  tolerance_type text not null default 'Absolute value',
  tolerance_value numeric,
  tolerance_unit text,
  tolerance_percent numeric,
  required boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
