create table if not exists public.mi_relief_device_technical_data (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  relief_device_id text not null references public.mi_relief_devices(id) on delete cascade,
  set_pressure numeric,
  set_pressure_unit text,
  cold_differential_test_pressure numeric,
  cdtp_unit text,
  mawp_reference numeric,
  accumulation_percent numeric,
  backpressure numeric,
  superimposed_backpressure numeric,
  built_up_backpressure numeric,
  operating_pressure numeric,
  blowdown numeric,
  blowdown_unit text,
  rated_capacity numeric,
  required_relieving_capacity numeric,
  capacity_unit text,
  orifice_designation text,
  effective_area numeric,
  inlet_size text,
  outlet_size text,
  inlet_rating text,
  outlet_rating text,
  inlet_flange text,
  outlet_flange text,
  service_fluid text,
  phase text,
  molecular_weight numeric,
  operating_temperature numeric,
  relieving_temperature numeric,
  specific_gravity_or_density numeric,
  compressibility_factor numeric,
  viscosity numeric,
  corrosive_service boolean not null default false,
  toxic_service boolean not null default false,
  flammable_service boolean not null default false,
  sour_h2s_service boolean not null default false,
  body_material text,
  trim_material text,
  spring_material text,
  seat_material text,
  gasket_material text,
  material_specification text,
  corrosion_allowance numeric,
  valve_type text,
  bonnet_type text,
  spring_range text,
  seat_type text,
  cap_type text,
  lifting_lever boolean not null default false,
  balanced_bellows boolean not null default false,
  pilot_type text,
  rupture_disk_burst_pressure numeric,
  rupture_disk_material text,
  technical_data_json jsonb not null default '{}'::jsonb,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
