alter table public.incidents
  add column if not exists timeline_review_status text,
  add column if not exists timeline_review_requested_by text,
  add column if not exists timeline_review_requested_at timestamptz,
  add column if not exists timeline_review_decision text,
  add column if not exists timeline_review_decided_by text,
  add column if not exists timeline_review_decided_at timestamptz,
  add column if not exists timeline_review_reason text,
  add column if not exists timeline_readiness_status text;

create table if not exists public.incident_timeline_events (
  id text primary key,
  tenant_id text references public."Tenant"(id) on delete cascade,
  company_id text,
  site_id text,
  incident_id text not null,
  event_number integer,
  event_time timestamptz,
  event_time_end timestamptz,
  phase text,
  title text,
  description text,
  location text,
  involved_people text,
  related_equipment_id text,
  related_chemical_id text,
  related_evidence_id text,
  source_type text,
  source_reference text,
  source_reliability text,
  confidence text,
  status text not null default 'Draft',
  gap_flag boolean not null default false,
  conflict_flag boolean not null default false,
  notes text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.incident_timeline_gaps (
  id text primary key,
  tenant_id text references public."Tenant"(id) on delete cascade,
  company_id text,
  site_id text,
  incident_id text not null,
  timeline_event_id text,
  gap_type text,
  title text,
  description text,
  severity text,
  status text not null default 'Open',
  owner_id text,
  due_date date,
  resolution_notes text,
  resolved_by text,
  resolved_at timestamptz,
  created_by text,
  created_at timestamptz not null default now(),
  updated_by text,
  updated_at timestamptz
);
