-- Mechanical Integrity Phase 7 - calibration execution records.

create table if not exists public.mi_calibration_records (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  equipment_id text not null,
  plan_id text references public.mi_calibration_plans(id),
  occurrence_id text references public.mi_calibration_occurrences(id),
  record_number text not null,
  planned boolean not null default true,
  unplanned_reason text,
  status text not null default 'Draft',
  review_status text not null default 'Not Submitted',
  result text,
  calibration_date date not null default current_date,
  start_time timestamptz,
  end_time timestamptz,
  technician_user_id text,
  technician_name text,
  vendor_or_lab text,
  reviewer_user_id text,
  procedure_document_id text,
  reference_standard text,
  reference_standard_serial_number text,
  reference_standard_certificate_document_id text,
  calibration_certificate_document_id text,
  environmental_conditions text,
  adjustment_performed boolean not null default false,
  as_found_result text,
  as_left_result text,
  notes text,
  submitted_by text,
  submitted_at timestamptz,
  approved_by text,
  approved_at timestamptz,
  rejected_by text,
  rejected_at timestamptz,
  rejection_reason text,
  returned_by text,
  returned_at timestamptz,
  return_reason text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  archived_by text,
  unique (company_id, site_id, record_number)
);

create table if not exists public.mi_calibration_record_points (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  calibration_record_id text not null references public.mi_calibration_records(id) on delete cascade,
  plan_point_id text references public.mi_calibration_plan_points(id),
  point_number text not null,
  input_value numeric not null,
  expected_output numeric not null,
  as_found_output numeric,
  as_found_error numeric,
  as_found_pass_fail text,
  adjustment_performed boolean not null default false,
  as_left_output numeric,
  as_left_error numeric,
  as_left_pass_fail text,
  unit text,
  tolerance_applied_json jsonb not null default '{}'::jsonb,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
