alter table public.incidents
  add column if not exists rca_method text,
  add column if not exists rca_lead_id text,
  add column if not exists rca_due_date date,
  add column if not exists rca_review_status text,
  add column if not exists rca_readiness_status text,
  add column if not exists rca_capa_mapping_status text,
  add column if not exists rca_completed_at timestamptz,
  add column if not exists rca_completed_by text;

create table if not exists public.incident_rca (
  id text primary key,
  tenant_id text references public."Tenant"(id) on delete cascade,
  company_id text,
  site_id text,
  incident_id text not null,
  rca_required boolean not null default false,
  rca_required_reason text,
  rca_status text not null default 'Not Started',
  selected_method text,
  method_version text,
  method_config_json jsonb,
  method_selected_by text,
  method_selected_at timestamptz,
  method_change_reason text,
  rca_lead_id text,
  due_date date,
  scope text,
  objective text,
  notes text,
  completed_by text,
  completed_at timestamptz,
  review_status text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_rca_causal_factors (
  id text primary key,
  tenant_id text references public."Tenant"(id) on delete cascade,
  company_id text,
  site_id text,
  incident_id text not null,
  rca_id text not null,
  causal_factor_number text,
  title text not null,
  description text,
  category text,
  cause_statement text,
  status text not null default 'Draft',
  evidence_support_level text,
  confidence_level text,
  related_timeline_event_ids_json jsonb,
  related_evidence_ids_json jsonb,
  related_people_ids_json jsonb,
  related_equipment_ids_json jsonb,
  related_chemical_ids_json jsonb,
  related_records_json jsonb,
  related_immediate_action_ids_json jsonb,
  hypothesis boolean not null default false,
  owner_id text,
  due_date date,
  notes text,
  rejection_reason text,
  confirmed_by text,
  confirmed_at timestamptz,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.incident_rca_five_why_chains (
  id text primary key,
  tenant_id text references public."Tenant"(id) on delete cascade,
  company_id text,
  site_id text,
  incident_id text not null,
  rca_id text not null,
  causal_factor_id text,
  problem_statement text,
  status text not null default 'Draft',
  root_cause_conclusion text,
  evidence_support_level text,
  reviewer_comments text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_rca_five_why_steps (
  id text primary key,
  tenant_id text references public."Tenant"(id) on delete cascade,
  company_id text,
  site_id text,
  incident_id text not null,
  chain_id text not null,
  step_number integer not null,
  why_statement text,
  evidence_ids_json jsonb,
  notes text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_rca_fishbone_items (
  id text primary key,
  tenant_id text references public."Tenant"(id) on delete cascade,
  company_id text,
  site_id text,
  incident_id text not null,
  rca_id text not null,
  category text not null,
  cause_item text not null,
  description text,
  evidence_support_level text,
  evidence_ids_json jsonb,
  timeline_event_ids_json jsonb,
  status text not null default 'Draft',
  root_cause_candidate boolean not null default false,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_rca_cause_tree_nodes (
  id text primary key,
  tenant_id text references public."Tenant"(id) on delete cascade,
  company_id text,
  site_id text,
  incident_id text not null,
  rca_id text not null,
  node_type text not null,
  title text not null,
  description text,
  evidence_support_level text,
  status text not null default 'Draft',
  root_cause_candidate boolean not null default false,
  linked_action_id text,
  position_json jsonb,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_rca_cause_tree_edges (
  id text primary key,
  tenant_id text references public."Tenant"(id) on delete cascade,
  company_id text,
  site_id text,
  incident_id text not null,
  rca_id text not null,
  source_node_id text not null,
  target_node_id text not null,
  relationship_type text not null,
  created_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.incident_rca_root_causes (
  id text primary key,
  tenant_id text references public."Tenant"(id) on delete cascade,
  company_id text,
  site_id text,
  incident_id text not null,
  rca_id text not null,
  root_cause_number text,
  root_cause_statement text not null,
  category text,
  description text,
  linked_causal_factor_ids_json jsonb,
  linked_evidence_ids_json jsonb,
  evidence_support_level text,
  confidence_level text,
  cause_classification text,
  systemic_cause boolean not null default false,
  management_system_element text,
  risk_control_gap text,
  capa_required boolean not null default true,
  capa_required_justification text,
  capa_recommendation text,
  universal_action_id text,
  owner_id text,
  due_date date,
  review_status text not null default 'Draft',
  notes text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  archived_by text
);

create table if not exists public.incident_rca_systemic_weaknesses (
  id text primary key,
  tenant_id text references public."Tenant"(id) on delete cascade,
  company_id text,
  site_id text,
  incident_id text not null,
  rca_id text not null,
  management_system_element text not null,
  weakness_description text not null,
  related_root_cause_ids_json jsonb,
  related_evidence_ids_json jsonb,
  repeated_issue boolean not null default false,
  similar_prior_incidents_json jsonb,
  existing_control text,
  gap_description text,
  capa_required boolean not null default true,
  notes text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_rca_hypotheses (
  id text primary key,
  tenant_id text references public."Tenant"(id) on delete cascade,
  company_id text,
  site_id text,
  incident_id text not null,
  rca_id text not null,
  hypothesis text not null,
  related_causal_factor_id text,
  evidence_needed text,
  owner_id text,
  due_date date,
  status text not null default 'Open',
  resolution text,
  notes text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_rca_reviews (
  id text primary key,
  tenant_id text references public."Tenant"(id) on delete cascade,
  company_id text,
  site_id text,
  incident_id text not null,
  rca_id text not null,
  status text not null default 'Not Requested',
  reviewer_id text,
  due_date date,
  comments text,
  approved_by text,
  approved_at timestamptz,
  rejected_by text,
  rejected_at timestamptz,
  rejection_reason text,
  rework_required boolean not null default false,
  rework_notes text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
