alter table public.incidents
  add column if not exists linked_records_review_status text not null default 'Not Requested',
  add column if not exists linked_records_readiness_status text not null default 'Not Started',
  add column if not exists linked_records_missing_required_count integer not null default 0,
  add column if not exists linked_records_broken_count integer not null default 0,
  add column if not exists linked_records_update_required_count integer not null default 0;

create table if not exists public.incident_linked_records (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  link_number text not null,
  module text not null,
  record_type text not null,
  record_id text,
  record_number_snapshot text,
  record_title_snapshot text not null,
  relationship text not null default 'Related record',
  source_generated_type text not null default 'Related record',
  link_status text not null default 'Active',
  impact_status text not null default 'No change required',
  update_required boolean not null default false,
  owner_id text,
  due_date date,
  restricted boolean not null default false,
  blocking boolean not null default false,
  source_module text,
  source_record_id text,
  stale_reason text,
  current_status_snapshot text,
  last_known_status text,
  universal_action_id text,
  notes text,
  change_reason text,
  created_by text,
  updated_by text,
  linked_at timestamptz not null default now(),
  last_refreshed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.incident_required_links (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  required_link_type text not null,
  required boolean not null default false,
  source_reason text,
  status text not null default 'Not Required',
  linked_record_id text references public.incident_linked_records(id) on delete set null,
  blocking boolean not null default false,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, incident_id, required_link_type)
);

create table if not exists public.incident_record_impacts (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  linked_record_id text references public.incident_linked_records(id) on delete cascade,
  impact_type text not null default 'No change required',
  update_required boolean not null default false,
  reason text,
  owner_id text,
  due_date date,
  update_status text not null default 'Not Required',
  universal_action_id text,
  notes text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_linked_record_reviews (
  id text primary key,
  tenant_id text not null references public."Tenant"(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  incident_id text not null references public.incidents(id) on delete cascade,
  status text not null default 'Requested',
  reviewer_id text,
  due_date date,
  comments text,
  approved_by text,
  approved_at timestamptz,
  rejected_by text,
  rejected_at timestamptz,
  rejection_reason text,
  rework_required boolean not null default false,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
