create table if not exists public.mi_sif_protection_scope (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  sif_id text not null references public.mi_sifs(id) on delete cascade,
  protected_equipment_id text,
  protected_equipment_tag text,
  protected_equipment_type text,
  protected_equipment_criticality text,
  process_unit_area text,
  hazard_scenario_title text,
  hazard_scenario_description text,
  initiating_event text,
  cause_of_demand text,
  consequence_if_failed text,
  process_safety_consequence text,
  environmental_consequence text,
  personnel_safety_consequence text,
  startup_impact text,
  protected_system_boundary text,
  safe_state_description text,
  trip_action_summary text,
  required_response_time numeric,
  response_time_unit text,
  demand_mode text not null default 'Not evaluated',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mi_sif_lopa_sil_links (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  sif_id text not null references public.mi_sifs(id) on delete cascade,
  lopa_scenario_id text,
  lopa_scenario_number text,
  sil_assessment_id text,
  ipl_identifier text,
  credited_as_ipl boolean not null default false,
  target_sil text,
  achieved_sil text,
  required_rrf numeric,
  achieved_rrf numeric,
  pfd_avg numeric,
  proof_test_interval_value numeric,
  proof_test_interval_unit text,
  demand_rate numeric,
  ipl_independence_notes text,
  ipl_effectiveness_notes text,
  verification_status text not null default 'Not Verified',
  verification_document_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
