-- Mechanical Integrity Phase 4 - company/site scheduler rule configuration.

create table if not exists public.mi_inspection_schedule_rules (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text null,
  rule_name text not null,
  rule_scope text not null default 'company',
  equipment_type_key text null,
  plan_type text null,
  inspection_method text null,
  criticality_category text null,
  service_severity text null,
  damage_mechanism text null,
  maximum_interval_value integer not null,
  maximum_interval_unit text not null default 'Years',
  half_life_enabled boolean not null default true,
  remaining_life_enabled boolean not null default true,
  fixed_interval_cap_enabled boolean not null default true,
  rbi_modifier_enabled boolean not null default false,
  due_soon_threshold_value integer not null default 30,
  due_soon_threshold_unit text not null default 'Days',
  critical_overdue_threshold_value integer not null default 30,
  critical_overdue_threshold_unit text not null default 'Days',
  grace_period_value integer not null default 0,
  grace_period_unit text not null default 'Days',
  active boolean not null default true,
  version integer not null default 1,
  effective_date date not null default current_date,
  notes text null,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
