-- Mechanical Integrity Phase 1 - equipment technical data.

create table if not exists public.mi_equipment_technical_data (
  id text primary key default gen_random_uuid()::text,
  equipment_id text not null references public.mi_equipment(id) on delete cascade,
  company_id text not null,
  site_id text not null,
  design_pressure text null,
  design_pressure_unit text null,
  design_temperature text null,
  design_temperature_unit text null,
  operating_pressure text null,
  operating_pressure_unit text null,
  operating_temperature text null,
  operating_temperature_unit text null,
  design_code text null,
  material_of_construction text null,
  corrosion_allowance text null,
  nominal_thickness text null,
  minimum_required_thickness text null,
  capacity_value text null,
  capacity_unit text null,
  line_size text null,
  diameter text null,
  rating_class text null,
  service_fluid text null,
  chemical_id text null,
  sds_id text null,
  insulation boolean null,
  heat_tracing boolean null,
  relief_protection boolean null,
  p_and_id_reference text null,
  drawing_reference text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mi_equipment_technical_data_equipment_unique unique (equipment_id)
);
