-- Mechanical Integrity Phase 7 - preventive maintenance execution records.

create table if not exists public.mi_pm_records (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  equipment_id text not null,
  plan_id text references public.mi_pm_plans(id),
  occurrence_id text references public.mi_pm_occurrences(id),
  record_number text not null,
  planned boolean not null default true,
  unplanned_reason text,
  status text not null default 'Draft',
  review_status text not null default 'Not Submitted',
  result text,
  pm_date date not null default current_date,
  start_time timestamptz,
  end_time timestamptz,
  technician_user_id text,
  technician_name text,
  vendor_name text,
  reviewer_user_id text,
  shutdown_required boolean not null default false,
  ptw_id text,
  loto_id text,
  procedure_document_id text,
  notes text,
  submitted_by text,
  submitted_at timestamptz,
  approved_by text,
  approved_at timestamptz,
  rejected_by text,
  rejected_at timestamptz,
  rejection_reason text,
  returned_by text,
  returned_at timestamptz,
  return_reason text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  archived_by text,
  unique (company_id, site_id, record_number)
);

create table if not exists public.mi_pm_record_checklist_items (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  pm_record_id text not null references public.mi_pm_records(id) on delete cascade,
  plan_checklist_item_id text references public.mi_pm_plan_checklist_items(id),
  item_number text not null,
  section_title text,
  task_title text not null,
  task_instruction text,
  response_type text not null default 'Done/Not Done',
  response_value_json jsonb not null default '{}'::jsonb,
  pass_fail text,
  comment text,
  evidence_required boolean not null default false,
  evidence_document_id text,
  finding_created boolean not null default false,
  completed_by text,
  completed_at timestamptz,
  required boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
