-- Training & Competency Phase 1 - workforce/profile foundation tables.

create table if not exists public.training_workers (
  id text primary key,
  company_id text not null,
  primary_site_id text null,
  linked_user_id text null,
  first_name text null,
  last_name text null,
  display_name text not null,
  work_email text null,
  personal_email text null,
  phone text null,
  employee_id text null,
  contractor_id text null,
  badge_number text null,
  preferred_language text null,
  timezone text null,
  worker_type text not null default 'Employee',
  employer_type text not null default 'Company employee',
  contractor_company_name text null,
  vendor_company_name text null,
  department_id text null,
  department_name text null,
  job_title text null,
  employment_status text not null default 'Pending onboarding',
  start_date date null,
  end_date date null,
  contract_expiry_date date null,
  supervisor_user_id text null,
  line_manager_user_id text null,
  work_schedule_foundation text null,
  shift_team_foundation text null,
  safety_critical_role boolean not null default false,
  app_access_required boolean not null default false,
  training_status text not null default 'Not Assessed',
  certification_status text not null default 'Not Assessed',
  competency_status text not null default 'Not Assessed',
  ptw_authorization_status text not null default 'Not Assessed',
  sop_acknowledgement_status text null default 'Not Assessed',
  moc_training_status text null default 'Not Assessed',
  pssr_training_readiness_status text null default 'Not Assessed',
  review_status text not null default 'Not Reviewed',
  status text not null default 'Draft',
  notes text null,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz null,
  archived_by text null,
  archive_reason text null,
  constraint training_workers_identifier_check check (
    nullif(work_email, '') is not null or nullif(employee_id, '') is not null or nullif(contractor_id, '') is not null or nullif(badge_number, '') is not null
  )
);

create table if not exists public.training_worker_site_assignments (
  id text primary key,
  company_id text not null,
  worker_id text not null references public.training_workers(id) on delete cascade,
  site_id text not null,
  department_id text null,
  unit_id text null,
  area_id text null,
  equipment_id text null,
  primary_assignment boolean not null default false,
  assignment_status text not null default 'Active',
  assignment_start_date date null,
  assignment_end_date date null,
  assignment_reason text null,
  supervisor_user_id text null,
  notes text null,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  removed_at timestamptz null,
  removed_by text null,
  remove_reason text null
);

create table if not exists public.training_worker_role_assignments (
  id text primary key,
  company_id text not null,
  worker_id text not null references public.training_workers(id) on delete cascade,
  site_id text null,
  unit_id text null,
  area_id text null,
  job_role text not null,
  competency_profile_id text null,
  required_training_profile_id text null,
  safety_critical boolean not null default false,
  ptw_role_candidate boolean not null default false,
  operations_role boolean not null default false,
  maintenance_role boolean not null default false,
  hse_role boolean not null default false,
  engineering_role boolean not null default false,
  contractor_role boolean not null default false,
  ptw_role_candidates_json jsonb not null default '[]'::jsonb,
  role_status text not null default 'Active',
  effective_date date null,
  expiry_date date null,
  notes text null,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  removed_at timestamptz null,
  removed_by text null,
  remove_reason text null
);

create table if not exists public.training_worker_account_links (
  id text primary key,
  company_id text not null,
  worker_id text not null references public.training_workers(id) on delete cascade,
  user_id text null,
  link_status text not null default 'Linked',
  linked_email text not null,
  app_access_required boolean not null default false,
  linked_by text null,
  linked_at timestamptz not null default now(),
  unlinked_by text null,
  unlinked_at timestamptz null,
  unlink_reason text null
);

create table if not exists public.training_worker_documents (
  id text primary key,
  company_id text not null,
  worker_id text not null references public.training_workers(id) on delete cascade,
  site_id text null,
  document_id text not null,
  document_type text not null,
  relationship_type text not null default 'Evidence',
  restricted_visibility boolean not null default false,
  linked_by text null,
  linked_at timestamptz not null default now(),
  removed_by text null,
  removed_at timestamptz null,
  remove_reason text null
);

create table if not exists public.training_worker_status_snapshots (
  id text primary key,
  company_id text not null,
  worker_id text not null references public.training_workers(id) on delete cascade,
  site_id text null,
  unit_id text null,
  snapshot_type text not null,
  training_status text not null,
  certification_status text not null,
  competency_status text not null,
  ptw_authorization_status text not null,
  sop_acknowledgement_status text null,
  moc_training_status text null,
  pssr_training_readiness_status text null,
  safety_critical_gap_count integer not null default 0,
  overdue_training_count integer not null default 0,
  expiring_certification_count integer not null default 0,
  blocked_reason text null,
  calculated_by_system boolean not null default true,
  calculated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.training_worker_history_events (
  id text primary key,
  company_id text not null,
  site_id text null,
  unit_id text null,
  area_id text null,
  worker_id text null references public.training_workers(id) on delete set null,
  event_type text not null,
  event_title text not null,
  event_description text null,
  before_value_json jsonb null,
  after_value_json jsonb null,
  actor_user_id text null,
  source_module text not null default 'Training & Competency',
  source_record_id text null,
  created_at timestamptz not null default now()
);

create table if not exists public.training_settings (
  id text primary key,
  company_id text not null,
  site_id text null,
  default_training_expiry_warning_days integer not null default 30,
  default_certification_expiry_warning_days integer not null default 60,
  require_site_assignment_for_active_worker boolean not null default true,
  require_role_assignment_for_active_worker boolean not null default true,
  allow_worker_without_user_account boolean not null default true,
  contractor_access_requires_site_assignment boolean not null default true,
  safety_critical_worker_requires_review boolean not null default true,
  settings_json jsonb null,
  updated_by text null,
  updated_at timestamptz not null default now()
);
