create table if not exists public.mi_relief_device_basis (
  id text primary key default gen_random_uuid()::text,
  company_id text not null,
  site_id text not null,
  relief_device_id text not null references public.mi_relief_devices(id) on delete cascade,
  scenario_type text,
  governing_scenario text,
  scenario_description text,
  relief_basis_document_id text,
  calculation_reference text,
  required_relieving_rate numeric,
  selected_capacity numeric,
  capacity_margin numeric,
  fire_case boolean not null default false,
  blocked_outlet boolean not null default false,
  cooling_water_failure boolean not null default false,
  power_failure boolean not null default false,
  control_valve_failure boolean not null default false,
  thermal_expansion boolean not null default false,
  tube_rupture boolean not null default false,
  runaway_reaction boolean not null default false,
  two_phase_relief boolean not null default false,
  disposal_destination text,
  relief_header text,
  last_review_date date,
  next_review_due date,
  basis_json jsonb not null default '{}'::jsonb,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
