import { Eye, ShieldCheck, XCircle } from 'lucide-react';
import type { PermitConflictRecord } from '../../services/ptw-conflict.service';

export function ConflictListTable({ conflicts, onView, onOverride, onResolve, onFalsePositive }: { conflicts?: PermitConflictRecord[] | undefined; onView: (row: PermitConflictRecord) => void; onOverride: (row: PermitConflictRecord) => void; onResolve: (row: PermitConflictRecord) => void; onFalsePositive: (row: PermitConflictRecord) => void }) {
  return (
    <section className="psm-card p-5">
      <h3 className="mb-4 text-sm font-semibold uppercase tracking-wide">Conflict List</h3>
      {conflicts?.length ? <div className="overflow-auto"><table className="psm-table w-full min-w-[1100px] text-left text-sm"><thead><tr>{['Type','Severity','Current Permit','Conflicting Permit','Area / Unit','Equipment','Description','Status','Detected','Override','Actions'].map((head) => <th key={head} className="px-3 py-2 text-xs uppercase text-[var(--psm-muted)]">{head}</th>)}</tr></thead><tbody>{conflicts.map((row) => <tr key={row.id} className="border-t border-[var(--psm-line)]"><td className="px-3 py-2 font-semibold">{row.conflict_type}</td><td className={`px-3 py-2 font-semibold ${row.severity === 'Critical' ? 'text-danger' : row.severity === 'High' ? 'text-warning' : 'text-primary'}`}>{row.severity}</td><td className="px-3 py-2">Current</td><td className="px-3 py-2">{row.conflicting_permit?.permit_number ?? row.conflicting_permit_id ?? '-'}</td><td className="px-3 py-2">{row.conflicting_permit?.job_area ?? '-'}</td><td className="px-3 py-2">{row.conflicting_permit?.equipment_tag ?? row.conflicting_equipment_id ?? '-'}</td><td className="px-3 py-2">{row.description}</td><td className="px-3 py-2">{row.status}</td><td className="px-3 py-2">{row.detected_at ? new Date(row.detected_at).toLocaleString() : '-'}</td><td className="px-3 py-2">{row.override_status ?? 'Not Requested'}</td><td className="px-3 py-2"><div className="flex gap-2"><button className="psm-button psm-button-secondary min-h-8 px-2" onClick={() => onView(row)}><Eye size={14} /></button><button className="psm-button psm-button-secondary min-h-8 px-2" onClick={() => onOverride(row)}><ShieldCheck size={14} /></button><button className="psm-button psm-button-primary min-h-8 px-2" onClick={() => onResolve(row)}>Resolve</button><button className="psm-button psm-button-danger min-h-8 px-2" onClick={() => onFalsePositive(row)}><XCircle size={14} /></button></div></td></tr>)}</tbody></table></div> : <div className="rounded-lg border border-dashed border-[var(--psm-line)] p-8 text-center text-sm text-[var(--psm-muted)]">No conflicts detected. Run a conflict check to verify SIMOPS status.</div>}
    </section>
  );
}
