import type { AuditLookups, AuditProgram } from '../../types/audit.types';
import { Field, inputClass } from '../../shared/AuditUi';

export function ProgramIdentitySection({ form, update, lookups }: { form: Partial<AuditProgram>; update: (patch: Partial<AuditProgram>) => void; lookups?: AuditLookups | undefined }) {
  return <div className="grid gap-4 md:grid-cols-2"><Field label="Program title"><input className={inputClass()} value={form.program_title ?? ''} onChange={(e) => update({ program_title: e.target.value })} /></Field><Field label="Program code"><input className={inputClass()} value={form.program_code ?? ''} onChange={(e) => update({ program_code: e.target.value })} /></Field><Select label="Audit type" value={form.audit_type} options={lookups?.auditTypes} onChange={(audit_type) => update({ audit_type })} /><Select label="Program category" value={form.program_category} options={lookups?.programCategories} onChange={(program_category) => update({ program_category })} /><Select label="Criticality" value={form.criticality} options={lookups?.criticalityLevels} onChange={(criticality) => update({ criticality })} /><Select label="Program status" value={form.program_status} options={lookups?.programStatuses} onChange={(program_status) => update({ program_status })} /><Field label="Effective date"><input className={inputClass()} type="date" value={form.effective_date ?? ''} onChange={(e) => update({ effective_date: e.target.value })} /></Field><Field label="Program objective"><input className={inputClass()} value={form.program_objective ?? ''} onChange={(e) => update({ program_objective: e.target.value })} /></Field><Field label="Program description"><textarea className={inputClass()} value={form.description ?? ''} onChange={(e) => update({ description: e.target.value })} /></Field><Field label="Notes"><textarea className={inputClass()} value={form.notes ?? ''} onChange={(e) => update({ notes: e.target.value })} /></Field></div>;
}

function Select({ label, value, options = [], onChange }: { label: string; value?: string | null | undefined; options?: string[] | undefined; onChange: (value: string) => void }) {
  return <Field label={label}><select className={inputClass()} value={value ?? ''} onChange={(e) => onChange(e.target.value)}><option value="">Select</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></Field>;
}
