import type { AuditContext, AuditProgram } from '../../types/audit.types';
import { Field, inputClass } from '../../shared/AuditUi';

export function ProgramOwnershipSection({ form, update, context }: { form: Partial<AuditProgram>; update: (patch: Partial<AuditProgram>) => void; context?: AuditContext | undefined }) {
  const users = context?.users ?? [];
  return <div className="grid gap-4 md:grid-cols-2"><UserSelect label="Program owner" value={form.owner_user_id} users={users} onChange={(owner_user_id) => update({ owner_user_id })} /><UserSelect label="Program reviewer" value={form.reviewer_user_id} users={users} onChange={(reviewer_user_id) => update({ reviewer_user_id })} /><UserSelect label="Approval owner foundation" value={form.approval_owner_user_id} users={users} onChange={(approval_owner_user_id) => update({ approval_owner_user_id })} /><Field label="Audit lead role"><input className={inputClass()} value={form.audit_lead_role ?? ''} onChange={(e) => update({ audit_lead_role: e.target.value })} /></Field><Field label="Audit team role foundation"><input className={inputClass()} value={(form as any).audit_team_role ?? ''} onChange={(e) => update({ ...(form as any), audit_team_role: e.target.value })} /></Field><Field label="Responsible department"><select className={inputClass()} value={form.responsible_department_id ?? ''} onChange={(e) => update({ responsible_department_id: e.target.value || null })}><option value="">Select</option>{context?.departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select></Field><UserSelect label="Escalation owner foundation" value={form.escalation_owner_user_id} users={users} onChange={(escalation_owner_user_id) => update({ escalation_owner_user_id })} /><Field label="Governance notes"><textarea className={inputClass()} value={(form as any).governance_notes ?? ''} onChange={(e) => update({ ...(form as any), governance_notes: e.target.value })} /></Field></div>;
}

function UserSelect({ label, value, users, onChange }: { label: string; value?: string | null | undefined; users: Array<{ id: string; displayName?: string | null | undefined; email?: string | null | undefined; status?: string | null | undefined }>; onChange: (value: string | null) => void }) {
  return <Field label={label}><select className={inputClass()} value={value ?? ''} onChange={(e) => onChange(e.target.value || null)}><option value="">Select user</option>{users.map((user) => <option key={user.id} value={user.id}>{user.displayName ?? user.email ?? user.id} - {user.email ?? 'No email'} ({user.status ?? 'Unknown'})</option>)}</select></Field>;
}
