'use client';
import { TrainingErrorState, TrainingLoadingState } from '../shared/TrainingUi';
import { useTrainingReportView, useTrainingScopedReports, useTrainingWorkerReports } from '../hooks/useTrainingReports';
import { generatedColumns, TrainingReportDetailPanel, TrainingReportsLayout, TrainingReportsTable } from './shared';

export function TrainingReportViewPage({ reportType }: { reportType: string }) {
  const query = useTrainingReportView(reportType);
  if (query.isLoading) return <TrainingLoadingState rows={5} />;
  if (query.isError) return <TrainingErrorState message={query.error} onRetry={() => query.refetch()} />;
  return <TrainingReportsLayout title={`${reportType} Report`} subtitle="Report-specific preview generated by the backend from real Training & Competency records."><TrainingReportDetailPanel data={query.data} /></TrainingReportsLayout>;
}

export function TrainingWorkerReportsPage({ workerId }: { workerId: string }) {
  const query = useTrainingWorkerReports(workerId);
  if (query.isLoading) return <TrainingLoadingState rows={5} />;
  if (query.isError) return <TrainingErrorState message={query.error} onRetry={() => query.refetch()} />;
  return <TrainingReportsLayout title="Worker Training Reports" subtitle="Worker-specific generated reports and evidence exports."><TrainingReportsTable title="Worker Reports" data={query.data} columns={generatedColumns} /></TrainingReportsLayout>;
}

export function TrainingScopedReportsPage({ scope, id }: { scope: 'sites' | 'units' | 'areas'; id: string }) {
  const query = useTrainingScopedReports(scope, id);
  if (query.isLoading) return <TrainingLoadingState rows={5} />;
  if (query.isError) return <TrainingErrorState message={query.error} onRetry={() => query.refetch()} />;
  return <TrainingReportsLayout title={`${scope.slice(0, -1)} Training Reports`} subtitle="Scoped generated reports using backend company/site/unit/area filters."><TrainingReportsTable title="Scoped Reports" data={query.data} columns={generatedColumns} /></TrainingReportsLayout>;
}
